/* state.svelte.js generated by Svelte v5.57.1 */
import * as $ from 'svelte/internal/client';

let s = $.state(0);

let d = $.derived(() => {
	count += 1;

	return $.get(s) * 2;
});

export let count = 0;

export function reset() {
	count = 0;
	$.set(s, 0);
}

export function increment() {
	$.set(s, $.get(s) + 1);
}

export function get() {
	return $.get(d);
}