/* input.svelte.js generated by Svelte v5.57.1 */
import * as $ from 'svelte/internal/client';

const state = 0;
const derived = $.derived(() => state + 2);
let effect = {};
let inspect = {};

$.effect_root(() => {
	;;

	$.user_effect(() => {
		console.log(state);
	});
});