//! Scope management for the analyzer.
//!
//! Tracks variable bindings, declarations, and references across scopes.

use std::collections::HashMap;

/// The root scope container for a component.
#[derive(Debug, Default)]
pub struct ScopeRoot {
    /// All unique bindings in the component
    pub bindings: Vec<Binding>,
    /// The root scope
    pub scope: Scope,
}

impl ScopeRoot {
    /// Create a new scope root.
    pub fn new() -> Self {
        Self {
            bindings: Vec::new(),
            scope: Scope::new(None),
        }
    }
}

/// A lexical scope containing variable bindings.
#[derive(Debug, Default)]
pub struct Scope {
    /// Parent scope index (None for root)
    pub parent: Option<usize>,
    /// Bindings declared in this scope (name -> binding index)
    pub declarations: HashMap<String, usize>,
    /// References to bindings in this scope
    pub references: Vec<Reference>,
    /// Child scopes
    pub children: Vec<usize>,
}

impl Scope {
    /// Create a new scope.
    pub fn new(parent: Option<usize>) -> Self {
        Self {
            parent,
            declarations: HashMap::new(),
            references: Vec::new(),
            children: Vec::new(),
        }
    }

    /// Declare a binding in this scope.
    pub fn declare(&mut self, name: String, binding_index: usize) {
        self.declarations.insert(name, binding_index);
    }

    /// Check if a name is declared in this scope.
    pub fn is_declared(&self, name: &str) -> bool {
        self.declarations.contains_key(name)
    }
}

/// The kind of declaration (var, let, const, function, etc.)
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DeclarationKind {
    /// var declaration (hoisted, function-scoped)
    Var,
    /// let declaration (block-scoped)
    Let,
    /// const declaration (block-scoped, immutable)
    Const,
    /// using declaration
    Using,
    /// await using declaration
    AwaitUsing,
    /// Function declaration
    Function,
    /// Import declaration
    Import,
    /// Function/method parameter
    Param,
    /// Rest parameter (...args)
    RestParam,
    /// Synthetic (generated by compiler)
    Synthetic,
}

/// A mutation (assignment, update expression, etc.)
#[derive(Debug, Clone)]
pub struct Mutation {
    /// Start position in source
    pub start: u32,
    /// End position in source
    pub end: u32,
    /// Kind of mutation
    pub kind: MutationKind,
}

/// The kind of mutation
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MutationKind {
    /// Assignment (=)
    Assignment,
    /// Update expression (++, --)
    Update,
    /// Compound assignment (+=, -=, etc.)
    CompoundAssign,
    /// Property mutation (obj.prop = value)
    PropertyMutation,
}

/// A variable binding.
#[derive(Debug, Clone)]
pub struct Binding {
    /// The binding kind (Normal, State, Prop, etc.)
    pub kind: BindingKind,
    /// The name of the binding
    pub name: String,
    /// How the binding was declared (let, const, var, etc.)
    pub declaration_kind: DeclarationKind,
    /// Whether the binding has been reassigned
    pub reassigned: bool,
    /// Whether the binding has been mutated (property change)
    pub mutated: bool,
    /// The scope index where this binding is declared
    pub scope_index: usize,
    /// Initial value expression (if any)
    pub initial: Option<String>,
    /// All references to this binding
    pub references: Vec<BindingReference>,
    /// All mutations to this binding
    pub mutations: Vec<Mutation>,
    /// Prop alias (for exported props with different names)
    pub prop_alias: Option<String>,
}

/// A reference to a binding from within the code
#[derive(Debug, Clone)]
pub struct BindingReference {
    /// Start position in source
    pub start: u32,
    /// End position in source
    pub end: u32,
}

impl Binding {
    /// Create a new binding.
    pub fn new(name: String, kind: BindingKind, scope_index: usize) -> Self {
        Self {
            kind,
            name,
            declaration_kind: DeclarationKind::Let,
            reassigned: false,
            mutated: false,
            scope_index,
            initial: None,
            references: Vec::new(),
            mutations: Vec::new(),
            prop_alias: None,
        }
    }

    /// Create a new binding with declaration kind.
    pub fn with_declaration_kind(
        name: String,
        kind: BindingKind,
        declaration_kind: DeclarationKind,
        scope_index: usize,
    ) -> Self {
        Self {
            kind,
            name,
            declaration_kind,
            reassigned: false,
            mutated: false,
            scope_index,
            initial: None,
            references: Vec::new(),
            mutations: Vec::new(),
            prop_alias: None,
        }
    }

    /// Returns true if this binding has been updated (reassigned or mutated)
    pub fn is_updated(&self) -> bool {
        self.reassigned || self.mutated
    }

    /// Returns true if this binding is reactive (needs runtime tracking)
    pub fn is_reactive(&self) -> bool {
        self.kind.is_reactive()
    }

    /// Returns true if this binding is a rune ($state, $derived, etc.)
    pub fn is_rune(&self) -> bool {
        self.kind.is_rune()
    }

    /// Add a reference to this binding
    pub fn add_reference(&mut self, start: u32, end: u32) {
        self.references.push(BindingReference { start, end });
    }

    /// Add a mutation to this binding
    pub fn add_mutation(&mut self, start: u32, end: u32, kind: MutationKind) {
        self.mutations.push(Mutation { start, end, kind });
        match kind {
            MutationKind::Assignment | MutationKind::Update | MutationKind::CompoundAssign => {
                self.reassigned = true;
            }
            MutationKind::PropertyMutation => {
                self.mutated = true;
            }
        }
    }
}

/// The kind of binding.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BindingKind {
    /// A normal variable binding (let, const, var)
    Normal,
    /// A component prop (possibly reassigned or mutated)
    Prop,
    /// A bindable prop (can be used with bind:)
    BindableProp,
    /// A rest prop ($$restProps)
    RestProp,
    /// A $state() reactive variable
    State,
    /// A $state.raw() reactive variable
    RawState,
    /// A $derived() computed variable
    Derived,
    /// An each block item
    EachItem,
    /// An each block index (known to be static/immutable)
    EachIndex,
    /// An await block value (then value)
    AwaitThen,
    /// An await block error (catch error)
    AwaitCatch,
    /// A snippet parameter
    SnippetParam,
    /// A let directive binding
    Let,
    /// A store subscription ($store)
    Store,
    /// A $store subscription (automatically subscribed)
    StoreSub,
    /// A legacy reactive statement ($:)
    LegacyReactive,
    /// A template-local binding (e.g., let directive in template)
    Template,
    /// A binding whose value is known to be static at compile time
    Static,
}

impl BindingKind {
    /// Returns true if this binding kind is reactive (needs runtime tracking)
    pub fn is_reactive(&self) -> bool {
        matches!(
            self,
            BindingKind::State
                | BindingKind::RawState
                | BindingKind::Derived
                | BindingKind::Prop
                | BindingKind::BindableProp
                | BindingKind::Store
                | BindingKind::StoreSub
        )
    }

    /// Returns true if this binding is a rune-based binding ($state, $derived, etc.)
    pub fn is_rune(&self) -> bool {
        matches!(
            self,
            BindingKind::State | BindingKind::RawState | BindingKind::Derived
        )
    }
}

/// A reference to a binding.
#[derive(Debug, Clone)]
pub struct Reference {
    /// The name being referenced
    pub name: String,
    /// The binding index (if resolved)
    pub binding_index: Option<usize>,
    /// Start position in source
    pub start: usize,
    /// End position in source
    pub end: usize,
}

impl Reference {
    /// Create a new reference.
    pub fn new(name: String, start: usize, end: usize) -> Self {
        Self {
            name,
            binding_index: None,
            start,
            end,
        }
    }
}
