//! Scope management for the analyzer.
//!
//! Tracks variable bindings, declarations, and references across scopes.

use rustc_hash::FxHashMap;
use smallvec::SmallVec;

/// The root scope container for a component.
#[derive(Debug, Default)]
pub struct ScopeRoot {
    /// All unique bindings in the component
    pub bindings: Vec<Binding>,
    /// The root scope (scope at index 0)
    pub scope: Scope,
    /// All scopes in the component (index 0 is the root scope)
    /// Used for scope chain lookup when validating assignments
    pub all_scopes: Vec<Scope>,
}

impl ScopeRoot {
    /// Create a new scope root.
    pub fn new() -> Self {
        Self {
            bindings: Vec::new(),
            scope: Scope::new(None),
            all_scopes: Vec::new(),
        }
    }

    /// Look up a binding by name starting from a specific scope and walking up the parent chain.
    /// This is the proper way to look up bindings, respecting lexical scoping.
    ///
    /// # Arguments
    /// * `name` - The name of the binding to look up
    /// * `scope_idx` - The scope index to start the search from
    ///
    /// # Returns
    /// The binding index if found, or None if not found in any scope in the chain.
    pub fn get_binding(&self, name: &str, scope_idx: usize) -> Option<usize> {
        let mut current_scope_idx = Some(scope_idx);

        while let Some(idx) = current_scope_idx {
            // Try to get the scope from all_scopes
            if let Some(scope) = self.all_scopes.get(idx) {
                // Check if the binding is declared in this scope
                if let Some(&binding_idx) = scope.declarations.get(name) {
                    return Some(binding_idx);
                }
                // Move to parent scope
                current_scope_idx = scope.parent;
            } else if idx == 0 {
                // Fallback to the root scope if all_scopes is empty (backward compatibility)
                if let Some(&binding_idx) = self.scope.declarations.get(name) {
                    return Some(binding_idx);
                }
                break;
            } else {
                break;
            }
        }

        None
    }

    /// Look up a binding by name, searching all scopes.
    /// This is a fallback method when we don't know the current scope.
    /// It searches all scopes and returns the first match found.
    /// Note: This may return bindings from any scope, not respecting lexical scoping.
    /// Use `get_binding` when you know the current scope for proper scoping.
    ///
    /// # Arguments
    /// * `name` - The name of the binding to look up
    ///
    /// # Returns
    /// The binding index if found in any scope, or None if not found.
    pub fn find_binding_any_scope(&self, name: &str) -> Option<usize> {
        // First check the root scope
        if let Some(&binding_idx) = self.scope.declarations.get(name) {
            return Some(binding_idx);
        }

        // Then search all other scopes
        for scope in &self.all_scopes {
            if let Some(&binding_idx) = scope.declarations.get(name) {
                return Some(binding_idx);
            }
        }

        None
    }
}

/// A lexical scope containing variable bindings.
#[derive(Debug, Default, Clone)]
pub struct Scope {
    /// Parent scope index (None for root)
    pub parent: Option<usize>,
    /// Bindings declared in this scope (name -> binding index)
    /// Using FxHashMap for 5-10x faster lookups than std HashMap
    pub declarations: FxHashMap<String, usize>,
    /// References to bindings in this scope
    pub references: Vec<Reference>,
    /// Child scopes
    pub children: Vec<usize>,
}

impl Scope {
    /// Create a new scope.
    pub fn new(parent: Option<usize>) -> Self {
        Self {
            parent,
            declarations: FxHashMap::default(),
            references: Vec::new(),
            children: Vec::new(),
        }
    }

    /// Declare a binding in this scope.
    pub fn declare(&mut self, name: String, binding_index: usize) {
        self.declarations.insert(name, binding_index);
    }

    /// Check if a name is declared in this scope.
    pub fn is_declared(&self, name: &str) -> bool {
        self.declarations.contains_key(name)
    }
}

/// The kind of declaration (var, let, const, function, etc.)
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DeclarationKind {
    /// var declaration (hoisted, function-scoped)
    Var,
    /// let declaration (block-scoped)
    Let,
    /// const declaration (block-scoped, immutable)
    Const,
    /// using declaration
    Using,
    /// await using declaration
    AwaitUsing,
    /// Function declaration
    Function,
    /// Import declaration
    Import,
    /// Function/method parameter
    Param,
    /// Rest parameter (...args)
    RestParam,
    /// Synthetic (generated by compiler)
    Synthetic,
}

/// A mutation (assignment, update expression, etc.)
#[derive(Debug, Clone)]
pub struct Mutation {
    /// Start position in source
    pub start: u32,
    /// End position in source
    pub end: u32,
    /// Kind of mutation
    pub kind: MutationKind,
}

/// The kind of mutation
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MutationKind {
    /// Assignment (=)
    Assignment,
    /// Update expression (++, --)
    Update,
    /// Compound assignment (+=, -=, etc.)
    CompoundAssign,
    /// Property mutation (obj.prop = value)
    PropertyMutation,
}

/// A variable binding.
#[derive(Debug, Clone)]
pub struct Binding {
    /// The binding kind (Normal, State, Prop, etc.)
    pub kind: BindingKind,
    /// The name of the binding
    pub name: String,
    /// How the binding was declared (let, const, var, etc.)
    pub declaration_kind: DeclarationKind,
    /// Whether the binding has been reassigned
    pub reassigned: bool,
    /// Whether the binding has been mutated (property change)
    pub mutated: bool,
    /// The scope index where this binding is declared
    pub scope_index: usize,
    /// Initial value expression (if any)
    pub initial: Option<String>,
    /// Whether the initial value is known to be defined (not null/undefined).
    pub initial_is_defined: bool,
    /// All references to this binding (SmallVec avoids heap allocation for ≤4 refs)
    pub references: SmallVec<[BindingReference; 4]>,
    /// All mutations to this binding (SmallVec avoids heap allocation for ≤2 mutations)
    pub mutations: SmallVec<[Mutation; 2]>,
    /// Prop alias (for exported props with different names)
    pub prop_alias: Option<String>,
    /// Whether the initial value is a function (ArrowFunctionExpression, FunctionExpression,
    /// or FunctionDeclaration). This is used by `is_function()` to match the official Svelte
    /// compiler's behavior where snippet blocks (declared with DeclarationKind::Function) are
    /// NOT considered functions since their initial type is SnippetBlock.
    pub initial_is_function: bool,
    /// Instance-level declarations may follow (or contain) a top-level `await`. In these cases,
    /// any reads that occur in the template must wait for the corresponding promise to resolve
    /// otherwise the initial value will not have been assigned.
    /// It is a member expression of the form `$$promises[n]`.
    /// Corresponds to `blocker` field in Svelte's Binding class (scope.js).
    pub blocker: Option<BlockerExpression>,
}

/// A blocker expression representing `$$promises[n]`.
/// Used to track async dependencies in instance-level declarations.
#[derive(Debug, Clone)]
pub struct BlockerExpression {
    /// The index in the $$promises array
    pub index: usize,
}

/// A reference to a binding from within the code
#[derive(Debug, Clone)]
pub struct BindingReference {
    /// Start position in source
    pub start: u32,
    /// End position in source
    pub end: u32,
    /// Whether this reference is in the template (Fragment)
    /// Used for legacy mode state promotion
    pub is_template_reference: bool,
}

impl Binding {
    /// Create a new binding.
    pub fn new(name: String, kind: BindingKind, scope_index: usize) -> Self {
        Self {
            kind,
            name,
            declaration_kind: DeclarationKind::Let,
            reassigned: false,
            mutated: false,
            scope_index,
            initial: None,
            initial_is_defined: false,
            initial_is_function: false,
            references: SmallVec::new(),
            mutations: SmallVec::new(),
            prop_alias: None,
            blocker: None,
        }
    }

    /// Create a new binding with declaration kind.
    pub fn with_declaration_kind(
        name: String,
        kind: BindingKind,
        declaration_kind: DeclarationKind,
        scope_index: usize,
    ) -> Self {
        Self {
            kind,
            name,
            declaration_kind,
            reassigned: false,
            mutated: false,
            scope_index,
            initial: None,
            initial_is_defined: false,
            initial_is_function: false,
            references: SmallVec::new(),
            mutations: SmallVec::new(),
            prop_alias: None,
            blocker: None,
        }
    }

    /// Returns true if this binding has been updated (reassigned or mutated)
    pub fn is_updated(&self) -> bool {
        self.reassigned || self.mutated
    }

    /// Returns true if this binding is reactive (needs runtime tracking)
    pub fn is_reactive(&self) -> bool {
        self.kind.is_reactive()
    }

    /// Returns true if this binding is a rune ($state, $derived, etc.)
    pub fn is_rune(&self) -> bool {
        self.kind.is_rune()
    }

    /// Add a reference to this binding
    pub fn add_reference(&mut self, start: u32, end: u32, is_template_reference: bool) {
        self.references.push(BindingReference {
            start,
            end,
            is_template_reference,
        });
    }

    /// Add a mutation to this binding
    pub fn add_mutation(&mut self, start: u32, end: u32, kind: MutationKind) {
        self.mutations.push(Mutation { start, end, kind });
        match kind {
            MutationKind::Assignment | MutationKind::Update | MutationKind::CompoundAssign => {
                self.reassigned = true;
            }
            MutationKind::PropertyMutation => {
                self.mutated = true;
            }
        }
    }

    /// Check if this binding represents a function.
    ///
    /// Corresponds to `is_function()` in Svelte's scope.js Binding class.
    /// Returns true only if:
    /// - The binding has not been updated (reassigned or mutated)
    /// - The initial value is a JS function type (ArrowFunctionExpression, FunctionExpression,
    ///   or FunctionDeclaration)
    ///
    /// Notably, snippet blocks are declared with DeclarationKind::Function but their initial
    /// value is a SnippetBlock, so is_function() correctly returns false for them.
    pub fn is_function(&self) -> bool {
        // If the binding has been updated (reassigned or mutated), it's not a function
        // even if it was initially declared as one.
        if self.is_updated() {
            return false;
        }

        // Check if the initial value is a function type
        self.initial_is_function
    }
}

/// The kind of binding.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BindingKind {
    /// A normal variable binding (let, const, var)
    Normal,
    /// A component prop (possibly reassigned or mutated)
    Prop,
    /// A bindable prop (can be used with bind:)
    BindableProp,
    /// A rest prop ($$restProps)
    RestProp,
    /// A $state() reactive variable
    State,
    /// A $state.raw() reactive variable
    RawState,
    /// A $derived() computed variable
    Derived,
    /// An each block item
    EachItem,
    /// An each block index (known to be static/immutable)
    EachIndex,
    /// An await block value (then value)
    AwaitThen,
    /// An await block error (catch error)
    AwaitCatch,
    /// A snippet parameter
    SnippetParam,
    /// A let directive binding
    Let,
    /// A store subscription ($store)
    Store,
    /// A $store subscription (automatically subscribed)
    StoreSub,
    /// A legacy reactive statement ($:)
    LegacyReactive,
    /// A template-local binding (e.g., let directive in template)
    Template,
    /// A binding whose value is known to be static at compile time
    Static,
}

impl BindingKind {
    /// Returns true if this binding kind is reactive (needs runtime tracking)
    pub fn is_reactive(&self) -> bool {
        matches!(
            self,
            BindingKind::State
                | BindingKind::RawState
                | BindingKind::Derived
                | BindingKind::Prop
                | BindingKind::BindableProp
                | BindingKind::Store
                | BindingKind::StoreSub
                | BindingKind::EachItem // Each block items are reactive since they can change
                | BindingKind::SnippetParam // Snippet parameters are reactive (called as functions)
        )
    }

    /// Returns true if this binding is a rune-based binding ($state, $derived, etc.)
    pub fn is_rune(&self) -> bool {
        matches!(
            self,
            BindingKind::State | BindingKind::RawState | BindingKind::Derived
        )
    }
}

/// A reference to a binding.
#[derive(Debug, Clone)]
pub struct Reference {
    /// The name being referenced
    pub name: String,
    /// The binding index (if resolved)
    pub binding_index: Option<usize>,
    /// Start position in source
    pub start: usize,
    /// End position in source
    pub end: usize,
}

impl Reference {
    /// Create a new reference.
    pub fn new(name: String, start: usize, end: usize) -> Self {
        Self {
            name,
            binding_index: None,
            start,
            end,
        }
    }
}
