/* runes01-input.svelte.js generated by Svelte v5.57.1 */
import * as $ from 'svelte/internal/client';

export class Test {
	#a = $.state(0);

	get a() {
		return $.get(this.#a);
	}

	set a(value) {
		$.set(this.#a, value, true);
	}

	#b = $.derived(() => this.a * 2);

	get b() {
		return $.get(this.#b);
	}

	set b(value) {
		$.set(this.#b, value);
	}

	output() {
		console.log(this.a, this.b);
	}
}