//! Svelte's additions to the HTML data, generated — do not edit.
//!
//! Source: `packages/language-server/src/plugins/html/dataProvider.ts` of
//! language-tools, read out of its build (MIT).
//!
//!   sha256 d065c264889493856a0b289e9e8563515f57c20e68acf0daa368b52110c6a01c (the TypeScript source)
//!   sha256 bfe5651d24d9f92c2445caa58764484caf9c6ce0635bfceb13452799d9ab627e (the build read)
//!
//! Only what `svelteHtmlDataProvider` adds to [`super::web`] is here; the
//! merge is ported in [`super::provider`], and the generator refuses to write
//! this file unless replaying that port reproduces the provider exactly.
//!
//! Regenerate with `node scripts/dev/generate-html-data.mjs`.

use super::web::{Attribute, Reference, Tag};

pub const SVELTE_TAGS: &[Tag] = &[
    Tag {
        name: "svelte:self",
        description: Some(
            "Allows a component to include itself, recursively.\n\nIt cannot appear at the top level of your markup; it must be inside an if or each block to prevent an infinite loop.",
        ),
        void_element: false,
        attributes: &[],
        references: &[],
        browsers: &[],
        status: None,
    },
    Tag {
        name: "svelte:component",
        description: Some(
            "Renders a component dynamically, using the component constructor specified as the this property. When the property changes, the component is destroyed and recreated.\n\nIf this is falsy, no component is rendered.",
        ),
        void_element: false,
        attributes: &[Attribute {
            name: "this",
            description: Some(
                "Component to render.\n\nWhen this property changes, the component is destroyed and recreated.\nIf this is falsy, no component is rendered.",
            ),
            value_set: None,
            references: &[],
            browsers: &[],
            status: None,
        }],
        references: &[],
        browsers: &[],
        status: None,
    },
    Tag {
        name: "svelte:element",
        description: Some(
            "Renders a DOM element dynamically, using the string as the this property. When the property changes, the element is destroyed and recreated.\n\nIf this is falsy, no element is rendered.",
        ),
        void_element: false,
        attributes: &[Attribute {
            name: "this",
            description: Some(
                "DOM element to render.\n\nWhen this property changes, the element is destroyed and recreated.\nIf this is falsy, no element is rendered.",
            ),
            value_set: None,
            references: &[],
            browsers: &[],
            status: None,
        }],
        references: &[],
        browsers: &[],
        status: None,
    },
    Tag {
        name: "svelte:window",
        description: Some(
            "Allows you to add event listeners to the window object without worrying about removing them when the component is destroyed, or checking for the existence of window when server-side rendering.",
        ),
        void_element: false,
        attributes: &[
            Attribute {
                name: "bind:innerWidth",
                description: Some("Bind to the inner width of the window. (read-only)"),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:innerHeight",
                description: Some("Bind to the inner height of the window. (read-only)"),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:outerWidth",
                description: Some("Bind to the outer width of the window. (read-only)"),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:outerHeight",
                description: Some("Bind to the outer height of the window. (read-only)"),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:scrollX",
                description: Some("Bind to the scroll x position of the window."),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:scrollY",
                description: Some("Bind to the scroll y position of the window."),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:online",
                description: Some("An alias for window.navigator.onLine"),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
        ],
        references: &[],
        browsers: &[],
        status: None,
    },
    Tag {
        name: "svelte:document",
        description: Some(
            "As with <svelte:window>, this element allows you to add listeners to events on document, such as visibilitychange, which don't fire on window.",
        ),
        void_element: false,
        attributes: &[
            Attribute {
                name: "bind:fullscreenElement",
                description: Some(
                    "Bind to the element that is being in full screen mode in this document. (read-only)",
                ),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:visibilityState",
                description: Some("Bind to visibility of the document. (read-only)"),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
        ],
        references: &[],
        browsers: &[],
        status: None,
    },
    Tag {
        name: "svelte:body",
        description: Some(
            "As with <svelte:window>, this element allows you to add listeners to events on document.body, such as mouseenter and mouseleave which don't fire on window.",
        ),
        void_element: false,
        attributes: &[],
        references: &[],
        browsers: &[],
        status: None,
    },
    Tag {
        name: "svelte:head",
        description: Some(
            "This element makes it possible to insert elements into document.head. During server-side rendering, head content exposed separately to the main html content.",
        ),
        void_element: false,
        attributes: &[],
        references: &[],
        browsers: &[],
        status: None,
    },
    Tag {
        name: "svelte:options",
        description: Some("Provides a place to specify per-component compiler options"),
        void_element: false,
        attributes: &[
            Attribute {
                name: "immutable",
                description: Some(
                    "If true, tells the compiler that you promise not to mutate any objects. This allows it to be less conservative about checking whether values have changed.",
                ),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "accessors",
                description: Some(
                    "If true, getters and setters will be created for the component's props. If false, they will only be created for readonly exported values (i.e. those declared with const, class and function). If compiling with customElement: true this option defaults to true.",
                ),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "namespace",
                description: Some(
                    "The namespace where this component will be used, most commonly \"svg\"",
                ),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "tag",
                description: Some(
                    "The name to use when compiling this component as a custom element",
                ),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
        ],
        references: &[],
        browsers: &[],
        status: None,
    },
    Tag {
        name: "svelte:fragment",
        description: Some(
            "This element is useful if you want to assign a component to a named slot without creating a wrapper DOM element.",
        ),
        void_element: false,
        attributes: &[Attribute {
            name: "slot",
            description: Some("The name of the named slot that should be targeted."),
            value_set: None,
            references: &[],
            browsers: &[],
            status: None,
        }],
        references: &[],
        browsers: &[],
        status: None,
    },
    Tag {
        name: "slot",
        description: Some(
            "Components can have child content, in the same way that elements can.\n\nThe content is exposed in the child component using the <slot> element, which can contain fallback content that is rendered if no children are provided.",
        ),
        void_element: false,
        attributes: &[Attribute {
            name: "name",
            description: Some(
                "Named slots allow consumers to target specific areas. They can also have fallback content.",
            ),
            value_set: None,
            references: &[],
            browsers: &[],
            status: None,
        }],
        references: &[],
        browsers: &[],
        status: None,
    },
    Tag {
        name: "svelte:boundary",
        description: Some(
            "Represents a boundary in the application. Can catch errors and show fallback UI",
        ),
        void_element: false,
        attributes: &[Attribute {
            name: "onerror",
            description: Some("Called when an error occurred within the boundary"),
            value_set: None,
            references: &[],
            browsers: &[],
            status: None,
        }],
        references: &[],
        browsers: &[],
        status: None,
    },
];

pub const GLOBAL_ADDITIONS: &[Attribute] = &[
    Attribute {
        name: "use:",
        description: Some("Actions are functions that are called when an element is mounted."),
        value_set: None,
        references: &[Reference {
            name: "Svelte.dev Reference",
            url: "https://svelte.dev/docs/svelte/use",
        }],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "transition:",
        description: Some(
            "A transition is triggered by an element entering or leaving the DOM as a result of a state change.",
        ),
        value_set: None,
        references: &[Reference {
            name: "Svelte.dev Reference",
            url: "https://svelte.dev/docs/svelte/transition",
        }],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "in:",
        description: Some(
            "The in: and out: directives are identical to transition:, except that the resulting transitions are not bidirectional.",
        ),
        value_set: None,
        references: &[Reference {
            name: "Svelte.dev Reference",
            url: "https://svelte.dev/docs/svelte/in-and-out",
        }],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "out:",
        description: Some(
            "The in: and out: directives are identical to transition:, except that the resulting transitions are not bidirectional.",
        ),
        value_set: None,
        references: &[Reference {
            name: "Svelte.dev Reference",
            url: "https://svelte.dev/docs/svelte/in-and-out",
        }],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "animate:",
        description: Some(
            "An animation is triggered when the contents of a keyed each block are re-ordered.",
        ),
        value_set: None,
        references: &[Reference {
            name: "Svelte.dev Reference",
            url: "https://svelte.dev/docs/svelte/animate",
        }],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "style:",
        description: Some(
            "The style: directive provides a shorthand for setting multiple styles on an element.",
        ),
        value_set: None,
        references: &[Reference {
            name: "Svelte.dev Reference",
            url: "https://svelte.dev/docs/svelte/style",
        }],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:abort",
        description: Some("The loading of a resource has been aborted."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:blur",
        description: Some("An element has lost focus (does not bubble)."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:canplay",
        description: Some(
            "The user agent can play the media, but estimates that not enough data has been loaded to play the media up to its end without having to stop for further buffering of content.",
        ),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:canplaythrough",
        description: Some(
            "The user agent can play the media up to its end without having to stop for further buffering of content.",
        ),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:change",
        description: Some(
            "The change event is fired for <input>, <select>, and <textarea> elements when a change to the element's value is committed by the user.",
        ),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:click",
        description: Some("A pointing device button has been pressed and released on an element."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:contextmenu",
        description: Some(
            "The right button of the mouse is clicked (before the context menu is displayed).",
        ),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:dblclick",
        description: Some("A pointing device button is clicked twice on an element."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:drag",
        description: Some("An element or text selection is being dragged (every 350ms)."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:dragend",
        description: Some(
            "A drag operation is being ended (by releasing a mouse button or hitting the escape key).",
        ),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:dragenter",
        description: Some("A dragged element or text selection enters a valid drop target."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:dragleave",
        description: Some("A dragged element or text selection leaves a valid drop target."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:dragover",
        description: Some(
            "An element or text selection is being dragged over a valid drop target (every 350ms).",
        ),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:dragstart",
        description: Some("The user starts dragging an element or text selection."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:drop",
        description: Some("An element is dropped on a valid drop target."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:durationchange",
        description: Some("The duration attribute has been updated."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:emptied",
        description: Some(
            "The media has become empty; for example, this event is sent if the media has already been loaded (or partially loaded), and the load() method is called to reload it.",
        ),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:ended",
        description: Some("Playback has stopped because the end of the media was reached."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:error",
        description: Some("A resource failed to load."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:focus",
        description: Some("An element has received focus (does not bubble)."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:formchange",
        description: None,
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:forminput",
        description: None,
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:input",
        description: Some(
            "The value of an element changes or the content of an element with the attribute contenteditable is modified.",
        ),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:invalid",
        description: Some(
            "A submittable element has been checked and doesn't satisfy its constraints.",
        ),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:keydown",
        description: Some("A key is pressed down."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:keypress",
        description: Some(
            "A key is pressed down and that key normally produces a character value (use input instead).",
        ),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:keyup",
        description: Some("A key is released."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:load",
        description: Some("A resource and its dependent resources have finished loading."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:loadeddata",
        description: Some("The first frame of the media has finished loading."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:loadedmetadata",
        description: Some("The metadata has been loaded."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:loadstart",
        description: Some("Progress has begun."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:mousedown",
        description: Some("A pointing device button (usually a mouse) is pressed on an element."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:mousemove",
        description: Some("A pointing device is moved over an element."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:mouseout",
        description: Some(
            "A pointing device is moved off the element that has the listener attached or off one of its children.",
        ),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:mouseover",
        description: Some(
            "A pointing device is moved onto the element that has the listener attached or onto one of its children.",
        ),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:mouseup",
        description: Some("A pointing device button is released over an element."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:mousewheel",
        description: None,
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:mouseenter",
        description: Some(
            "A pointing device is moved onto the element that has the listener attached.",
        ),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:mouseleave",
        description: Some(
            "A pointing device is moved off the element that has the listener attached.",
        ),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:pause",
        description: Some("Playback has been paused."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:play",
        description: Some("Playback has begun."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:playing",
        description: Some(
            "Playback is ready to start after having been paused or delayed due to lack of data.",
        ),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:progress",
        description: Some("In progress."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:ratechange",
        description: Some("The playback rate has changed."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:reset",
        description: Some("A form is reset."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:resize",
        description: Some("The document view has been resized."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:readystatechange",
        description: Some("The readyState attribute of a document has changed."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:scroll",
        description: Some("The document view or an element has been scrolled."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:seeked",
        description: Some("A seek operation completed."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:seeking",
        description: Some("A seek operation began."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:select",
        description: Some("Some text is being selected."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:show",
        description: Some(
            "A contextmenu event was fired on/bubbled to an element that has a contextmenu attribute",
        ),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:stalled",
        description: Some(
            "The user agent is trying to fetch media data, but data is unexpectedly not forthcoming.",
        ),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:submit",
        description: Some("A form is submitted."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:suspend",
        description: Some("Media data loading has been suspended."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:timeupdate",
        description: Some("The time indicated by the currentTime attribute has been updated."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:volumechange",
        description: Some("The volume has changed."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:waiting",
        description: Some("Playback has stopped because of a temporary lack of data."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:pointercancel",
        description: Some("The pointer is unlikely to produce any more events."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:pointerdown",
        description: Some("The pointer enters the active buttons state."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:pointerenter",
        description: Some("Pointing device is moved inside the hit-testing boundary."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:pointerleave",
        description: Some("Pointing device is moved out of the hit-testing boundary."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:pointerlockchange",
        description: Some("The pointer was locked or released."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:pointerlockerror",
        description: Some(
            "It was impossible to lock the pointer for technical reasons or because the permission was denied.",
        ),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:pointermove",
        description: Some("The pointer changed coordinates."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:pointerout",
        description: Some(
            "The pointing device moved out of hit-testing boundary or leaves detectable hover range.",
        ),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:pointerover",
        description: Some("The pointing device is moved into the hit-testing boundary."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:pointerup",
        description: Some("The pointer leaves the active buttons state."),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:introstart",
        description: Some("Available when element has transition"),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:introend",
        description: Some("Available when element has transition"),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:outrostart",
        description: Some("Available when element has transition"),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:outroend",
        description: Some("Available when element has transition"),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:pointercancel",
        description: None,
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:pointerdown",
        description: None,
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:pointerenter",
        description: None,
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:pointerleave",
        description: None,
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:pointermove",
        description: None,
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:pointerout",
        description: None,
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:pointerover",
        description: None,
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:pointerup",
        description: None,
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:mouseenter",
        description: None,
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:mouseleave",
        description: None,
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:hashchange",
        description: None,
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "on:visibilitychange",
        description: None,
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "bind:innerHTML",
        description: Some("Available when contenteditable=true"),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "bind:textContent",
        description: Some("Available when contenteditable=true"),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "bind:innerText",
        description: Some("Available when contenteditable=true"),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "bind:clientWidth",
        description: Some("Available for block level elements. (read-only)"),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "bind:clientHeight",
        description: Some("Available for block level elements. (read-only)"),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "bind:offsetWidth",
        description: Some("Available for block level elements. (read-only)"),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "bind:offsetHeight",
        description: Some("Available for block level elements. (read-only)"),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "bind:contentRect",
        description: Some("Available for all elements. (read-only)"),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "bind:contentBoxSize",
        description: Some("Available for all elements. (read-only)"),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "bind:borderBoxSize",
        description: Some("Available for all elements. (read-only)"),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "bind:devicePixelContentBoxSize",
        description: Some("Available for all elements. (read-only)"),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "bind:this",
        description: Some(
            "To get a reference to a DOM node, use bind:this. If used on a component, gets a reference to that component instance.",
        ),
        value_set: None,
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "data-sveltekit-keepfocus",
        description: Some(
            "SvelteKit-specific attribute. Currently focused element will retain focus after navigation. Otherwise, focus will be reset to the body.",
        ),
        value_set: Some("v"),
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "data-sveltekit-noscroll",
        description: Some(
            "SvelteKit-specific attribute. Will prevent scrolling after the link is clicked.",
        ),
        value_set: Some("v"),
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "data-sveltekit-preload-code",
        description: Some(
            "SvelteKit-specific attribute. Will cause SvelteKit to run the page's load function as soon as the user hovers over the link (on a desktop) or touches it (on mobile), rather than waiting for the click event to trigger navigation.",
        ),
        value_set: Some("v"),
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "data-sveltekit-preload-data",
        description: Some(
            "SvelteKit-specific attribute. Will cause SvelteKit to run the page's load function as soon as the user hovers over the link (on a desktop) or touches it (on mobile), rather than waiting for the click event to trigger navigation.",
        ),
        value_set: Some("v"),
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "data-sveltekit-reload",
        description: Some(
            "SvelteKit-specific attribute. Will cause SvelteKit to do a normal browser navigation which results in a full page reload.",
        ),
        value_set: Some("v"),
        references: &[],
        browsers: &[],
        status: None,
    },
    Attribute {
        name: "data-sveltekit-replacestate",
        description: Some(
            "SvelteKit-specific attribute. Will replace the current `history` entry rather than creating a new one with `pushState` when the link is clicked.",
        ),
        value_set: Some("v"),
        references: &[],
        browsers: &[],
        status: None,
    },
];

/// Appended to the named tag's own attributes, after the `on:` rename.
pub const TAG_ADDITIONS: &[(&str, &[Attribute])] = &[
    (
        "img",
        &[
            Attribute {
                name: "bind:naturalWidth",
                description: None,
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:naturalHeight",
                description: None,
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
        ],
    ),
    (
        "video",
        &[
            Attribute {
                name: "bind:duration",
                description: Some("The total duration of the video, in seconds. (readonly)"),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:buffered",
                description: Some("An array of {start, end} objects. (readonly)"),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:seekable",
                description: Some("An array of {start, end} objects. (readonly)"),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:played",
                description: Some("An array of {start, end} objects. (readonly)"),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:seeking",
                description: Some("boolean. (readonly)"),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:ended",
                description: Some("boolean. (readonly)"),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:currentTime",
                description: Some("The current point in the video, in seconds."),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:playbackRate",
                description: Some("how fast or slow to play the video, where 1 is 'normal'"),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:paused",
                description: None,
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:volume",
                description: Some("A value between 0 and 1"),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:muted",
                description: None,
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:readyState",
                description: None,
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:videoWidth",
                description: Some("readonly"),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:videoHeight",
                description: Some("readonly"),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
        ],
    ),
    (
        "audio",
        &[
            Attribute {
                name: "bind:duration",
                description: Some("The total duration of the video, in seconds. (readonly)"),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:buffered",
                description: Some("An array of {start, end} objects. (readonly)"),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:seekable",
                description: Some("An array of {start, end} objects. (readonly)"),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:played",
                description: Some("An array of {start, end} objects. (readonly)"),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:seeking",
                description: Some("boolean. (readonly)"),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:ended",
                description: Some("boolean. (readonly)"),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:currentTime",
                description: Some("The current point in the video, in seconds."),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:playbackRate",
                description: Some("how fast or slow to play the video, where 1 is 'normal'"),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:paused",
                description: None,
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:volume",
                description: Some("A value between 0 and 1"),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:muted",
                description: None,
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:readyState",
                description: None,
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
        ],
    ),
    (
        "input",
        &[
            Attribute {
                name: "bind:value",
                description: None,
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:group",
                description: Some("Available for type=\"radio\" and type=\"checkbox\""),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:checked",
                description: Some("Available for type=\"checkbox\""),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:files",
                description: Some("Available for type=\"file\" (readonly)"),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "indeterminate",
                description: Some("Available for type=\"checkbox\""),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
            Attribute {
                name: "bind:indeterminate",
                description: Some("Available for type=\"checkbox\""),
                value_set: None,
                references: &[],
                browsers: &[],
                status: None,
            },
        ],
    ),
    (
        "select",
        &[Attribute {
            name: "bind:value",
            description: None,
            value_set: None,
            references: &[],
            browsers: &[],
            status: None,
        }],
    ),
    (
        "textarea",
        &[Attribute {
            name: "bind:value",
            description: None,
            value_set: None,
            references: &[],
            browsers: &[],
            status: None,
        }],
    ),
    (
        "details",
        &[Attribute {
            name: "bind:open",
            description: None,
            value_set: None,
            references: &[],
            browsers: &[],
            status: None,
        }],
    ),
    (
        "script",
        &[Attribute {
            name: "generics",
            description: Some(
                "Generics used within the components. Only available when using TypeScript.",
            ),
            value_set: None,
            references: &[],
            browsers: &[],
            status: None,
        }],
    ),
];

/// These two are served their own attributes and no globals.
pub const OWN_ATTRIBUTES_ONLY: &[&str] = &["svelte:boundary", "svelte:options"];
