//! A broken content-level mustache was rebuilt at the column budget of its
//! continuation lines only, so its first line was laid out as if it started
//! at the indent and its last line as if nothing followed it (#4310). prettier
//! measures every JS group of a mustache in place: the first group against
//! the column the `{` sits at — after the prose before it on the same line —
//! and the last against the `}` and any text glued to it, up to the next
//! break opportunity. The printer now rebuilds the broken form with both
//! charges, so `Best happened at {categoryData.record_holders` breaks after
//! the member that still fits at column 49 rather than after the one that fits
//! at the indent.
//!
//! Every expectation here was generated by running the input through the
//! oxfmt(`svelte: true`) oracle. `carrier`, `shallow` and `glued` move under
//! the fix (`shallow` in the other direction: with room on the first line the
//! break comes later, not earlier); `paren_exact` pins that a `)` glued after
//! the `}` is charged to the last line only (the first line ends exactly at the
//! width) and `call_arg_exact` that the `{` before a call is charged to the
//! first line only (the argument line ends exactly at the width); `call` and
//! `flat` must not move.

use rsvelte_formatter::{
    FormatOptions, IndentStyle, IndentWidth, JsFormatOptions, LineWidth, format,
};

fn fmt(src: &str) -> String {
    let js = JsFormatOptions {
        indent_style: IndentStyle::Space,
        indent_width: IndentWidth::try_from(2u8).unwrap(),
        line_width: LineWidth::try_from(80u16).unwrap(),
        ..JsFormatOptions::default()
    };
    let options = FormatOptions {
        js,
        typescript: false,
        ..FormatOptions::new()
    };
    format(src, &options).expect("format ok")
}

/// (name, input, oracle output)
#[rustfmt::skip]
const CELLS: &[(&str, &str, &str)] = &[
    ("carrier", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <div>\n              <div>\n                <div>\n                  <div>\n                    <div>\n                      <div>\n                        <div>\n                          <div>\n                            <div>\n                              <div>\n                                <p>Best happened at {categoryData.record_holders.max_distance.location_name || \"this location\"}</p>\n                              </div>\n                            </div>\n                          </div>\n                        </div>\n                      </div>\n                    </div>\n                  </div>\n                </div>\n              </div>\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <div>\n              <div>\n                <div>\n                  <div>\n                    <div>\n                      <div>\n                        <div>\n                          <div>\n                            <div>\n                              <div>\n                                <p>\n                                  Best happened at {categoryData.record_holders\n                                    .max_distance.location_name ||\n                                    \"this location\"}\n                                </p>\n                              </div>\n                            </div>\n                          </div>\n                        </div>\n                      </div>\n                    </div>\n                  </div>\n                </div>\n              </div>\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n"),
    ("shallow", "<div>\n  <div>\n    <div>\n      <div>\n        <p>Best happened at {categoryData.record_holders.max_distance.location_name || \"this location\"} and more words follow here</p>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div>\n  <div>\n    <div>\n      <div>\n        <p>\n          Best happened at {categoryData.record_holders.max_distance\n            .location_name || \"this location\"} and more words follow here\n        </p>\n      </div>\n    </div>\n  </div>\n</div>\n"),
    ("glued", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <div>\n              <div>\n                <div>\n                  <div>\n                    <div>\n                      <div>\n                        <div>\n                          <div>\n                            <p>Best happened at {categoryData.record_holders.max_distance.location_name}.</p>\n                          </div>\n                        </div>\n                      </div>\n                    </div>\n                  </div>\n                </div>\n              </div>\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <div>\n              <div>\n                <div>\n                  <div>\n                    <div>\n                      <div>\n                        <div>\n                          <div>\n                            <p>\n                              Best happened at {categoryData.record_holders\n                                .max_distance.location_name}.\n                            </p>\n                          </div>\n                        </div>\n                      </div>\n                    </div>\n                  </div>\n                </div>\n              </div>\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n"),
    ("paren_exact", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <div>\n              <div>\n                <div>\n                  <div>\n                    <div>\n                      <div>\n                        <p>{$t(\"adventures.saved_activities\")} ({visit.activities.length})</p>\n                      </div>\n                    </div>\n                  </div>\n                </div>\n              </div>\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <div>\n              <div>\n                <div>\n                  <div>\n                    <div>\n                      <div>\n                        <p>\n                          {$t(\"adventures.saved_activities\")} ({visit.activities\n                            .length})\n                        </p>\n                      </div>\n                    </div>\n                  </div>\n                </div>\n              </div>\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n"),
    ("paren_over", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <div>\n              <div>\n                <div>\n                  <div>\n                    <div>\n                      <div>\n                        <p>{$t(\"adventures.saved_activitiess\")} ({visit.activities.length})</p>\n                      </div>\n                    </div>\n                  </div>\n                </div>\n              </div>\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <div>\n              <div>\n                <div>\n                  <div>\n                    <div>\n                      <div>\n                        <p>\n                          {$t(\"adventures.saved_activitiess\")} ({visit\n                            .activities.length})\n                        </p>\n                      </div>\n                    </div>\n                  </div>\n                </div>\n              </div>\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n"),
    ("call_arg_exact", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <div>\n              <span class=\"breakdown-value\">{formatNumber(result.summary.totalPoolSpace - result.summary.allocatedSpace)} addresses</span>\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <div>\n              <span class=\"breakdown-value\"\n                >{formatNumber(\n                  result.summary.totalPoolSpace - result.summary.allocatedSpace,\n                )} addresses</span\n              >\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n"),
    ("call", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <div>\n              <div>\n                <div>\n                  <div>\n                    <div>\n                      <div>\n                        <div>\n                          <div>\n                            <div>\n                              <span>Total {formatDistance(categoryData.record_holders.max_distance.value, units)} km</span>\n                            </div>\n                          </div>\n                        </div>\n                      </div>\n                    </div>\n                  </div>\n                </div>\n              </div>\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <div>\n              <div>\n                <div>\n                  <div>\n                    <div>\n                      <div>\n                        <div>\n                          <div>\n                            <div>\n                              <span\n                                >Total {formatDistance(\n                                  categoryData.record_holders.max_distance\n                                    .value,\n                                  units,\n                                )} km</span\n                              >\n                            </div>\n                          </div>\n                        </div>\n                      </div>\n                    </div>\n                  </div>\n                </div>\n              </div>\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n"),
    ("flat", "<div>\n  <div>\n    <div>\n      <div>\n        <p>Best happened at {categoryData.location_name || \"here\"}</p>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div>\n  <div>\n    <div>\n      <div>\n        <p>Best happened at {categoryData.location_name || \"here\"}</p>\n      </div>\n    </div>\n  </div>\n</div>\n"),
];

#[test]
fn every_cell_formats_to_the_oracle_output() {
    let mut wrong = Vec::new();
    for (name, input, expected) in CELLS {
        let got = fmt(input);
        if got != *expected {
            wrong.push(format!("{name}: got {got:?}, want {expected:?}"));
        }
    }
    assert!(wrong.is_empty(), "{}", wrong.join("\n"));
}

/// Liveness: a table whose every cell already fits flat measures nothing about
/// the rebuild, so the cells have to carry a mustache broken across lines in
/// both charge directions — one whose first line is shorter than its
/// continuation budget (the prose before `{`), and one whose last line ends in
/// text glued to `}`.
#[test]
fn the_table_carries_both_charges() {
    let first_line_charged = CELLS.iter().filter(|(_, _, want)| {
        want.lines()
            .any(|l| l.trim_end().ends_with("{categoryData.record_holders"))
    });
    let last_line_charged = CELLS
        .iter()
        .filter(|(_, _, want)| want.lines().any(|l| l.ends_with("}.")));
    let untouched = CELLS.iter().filter(|(_, input, want)| input == want);
    assert!(
        first_line_charged.count() >= 2,
        "no cell breaks after the member that fits the first line"
    );
    assert!(
        last_line_charged.count() >= 1,
        "no cell has text glued to its closing brace"
    );
    assert!(untouched.count() >= 1, "no cell is left untouched");
}

#[test]
fn the_oracle_output_is_a_fixed_point() {
    for (name, _, expected) in CELLS {
        assert_eq!(fmt(expected), *expected, "{name}");
    }
}
