//! A directive value's `name={` prefix belongs to its first line only. Once the
//! open tag has wrapped, prettier measures each group of the value against the
//! column it starts at, so a continuation line has the whole width minus its
//! own indent. This port charged the prefix to the whole value by narrowing the
//! print width, which re-broke continuation lines that fit (#4119) — and the
//! per-shape discounts that had been bolted on to soften that (an arrow's body,
//! an object literal) under-charged the first line instead, leaving an object
//! flat past the print width where the oracle expands it.
//!
//! Every expectation here was generated by running the input through the
//! oxfmt(`svelte: true`) oracle. `name15_control` sits one column inside the
//! old threshold and must not move; `chain_fits_flat` never wraps at all.

use rsvelte_formatter::{
    FormatOptions, IndentStyle, IndentWidth, JsFormatOptions, LineWidth, format,
};

fn fmt(src: &str) -> String {
    let js = JsFormatOptions {
        indent_style: IndentStyle::Space,
        indent_width: IndentWidth::try_from(2u8).unwrap(),
        line_width: LineWidth::try_from(80u16).unwrap(),
        ..JsFormatOptions::default()
    };
    let options = FormatOptions {
        js,
        typescript: false,
        ..FormatOptions::new()
    };
    format(src, &options).expect("format ok")
}

/// (name, input, oracle output)
#[rustfmt::skip]
const CELLS: &[(&str, &str, &str)] = &[
    ("name15_control", "<div class=\"a\">\n  <div class=\"b\">\n    <div class=\"c\">\n      <div class=\"d\">\n        <div class=\"e\">\n          <div class=\"f\">\n            <div class=\"g\">\n              {#each list as category}\n                <button\n                  class:nnnnnnnnnnnnnnn={selected_category && selected_category.id === category.id}\n                >x</button>\n              {/each}\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div class=\"a\">\n  <div class=\"b\">\n    <div class=\"c\">\n      <div class=\"d\">\n        <div class=\"e\">\n          <div class=\"f\">\n            <div class=\"g\">\n              {#each list as category}\n                <button\n                  class:nnnnnnnnnnnnnnn={selected_category &&\n                    selected_category.id === category.id}>x</button\n                >\n              {/each}\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n"),
    ("name16_breaks_once", "<div class=\"a\">\n  <div class=\"b\">\n    <div class=\"c\">\n      <div class=\"d\">\n        <div class=\"e\">\n          <div class=\"f\">\n            <div class=\"g\">\n              {#each list as category}\n                <button\n                  class:nnnnnnnnnnnnnnnn={selected_category && selected_category.id === category.id}\n                >x</button>\n              {/each}\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div class=\"a\">\n  <div class=\"b\">\n    <div class=\"c\">\n      <div class=\"d\">\n        <div class=\"e\">\n          <div class=\"f\">\n            <div class=\"g\">\n              {#each list as category}\n                <button\n                  class:nnnnnnnnnnnnnnnn={selected_category &&\n                    selected_category.id === category.id}>x</button\n                >\n              {/each}\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n"),
    ("name24_breaks_once", "<div class=\"a\">\n  <div class=\"b\">\n    <div class=\"c\">\n      <div class=\"d\">\n        <div class=\"e\">\n          <div class=\"f\">\n            <div class=\"g\">\n              {#each list as category}\n                <button\n                  class:nnnnnnnnnnnnnnnnnnnnnnnn={selected_category && selected_category.id === category.id}\n                >x</button>\n              {/each}\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div class=\"a\">\n  <div class=\"b\">\n    <div class=\"c\">\n      <div class=\"d\">\n        <div class=\"e\">\n          <div class=\"f\">\n            <div class=\"g\">\n              {#each list as category}\n                <button\n                  class:nnnnnnnnnnnnnnnnnnnnnnnn={selected_category &&\n                    selected_category.id === category.id}>x</button\n                >\n              {/each}\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n"),
    ("expr_arrow_body", "<div class=\"a\">\n  <div class=\"b\">\n    <div class=\"c\">\n      <div class=\"d\">\n        <div class=\"e\">\n          <div class=\"f\">\n            <div class=\"g\">\n              {#each list as category}\n                <button\n                  on:click={(event) => selectCategory(event, category.id, category.name)}\n                >x</button>\n              {/each}\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div class=\"a\">\n  <div class=\"b\">\n    <div class=\"c\">\n      <div class=\"d\">\n        <div class=\"e\">\n          <div class=\"f\">\n            <div class=\"g\">\n              {#each list as category}\n                <button\n                  on:click={(event) =>\n                    selectCategory(event, category.id, category.name)}>x</button\n                >\n              {/each}\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n"),
    ("call_args_break", "<div class=\"a\">\n  <div class=\"b\">\n    <div class=\"c\">\n      <div class=\"d\">\n        <div class=\"e\">\n          <div class=\"f\">\n            <div class=\"g\">\n              {#each list as category}\n                <button\n                  use:tooltip={makeTooltip(category.description, category.label, placement)}\n                >x</button>\n              {/each}\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div class=\"a\">\n  <div class=\"b\">\n    <div class=\"c\">\n      <div class=\"d\">\n        <div class=\"e\">\n          <div class=\"f\">\n            <div class=\"g\">\n              {#each list as category}\n                <button\n                  use:tooltip={makeTooltip(\n                    category.description,\n                    category.label,\n                    placement,\n                  )}>x</button\n                >\n              {/each}\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n"),
    ("chain_fits_flat", "<div class=\"a\">\n  <div class=\"b\">\n    <div class=\"c\">\n      <div class=\"d\">\n        <div class=\"e\">\n          <div class=\"f\">\n            <div class=\"g\">\n              {#each list as category}\n                <button\n                  class:active={category.id === selected.id}\n                >x</button>\n              {/each}\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div class=\"a\">\n  <div class=\"b\">\n    <div class=\"c\">\n      <div class=\"d\">\n        <div class=\"e\">\n          <div class=\"f\">\n            <div class=\"g\">\n              {#each list as category}\n                <button class:active={category.id === selected.id}>x</button>\n              {/each}\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n"),
    ("object_value_expands", "<div>\n  <div>\n    <div\n      out:fly|local={{ y: \"100vh\", duration: 600, easing: cubicOut, opacity: 1 }}\n      class=\"menu\"\n    >\n      x\n    </div>\n  </div>\n</div>\n", "<div>\n  <div>\n    <div\n      out:fly|local={{\n        y: \"100vh\",\n        duration: 600,\n        easing: cubicOut,\n        opacity: 1,\n      }}\n      class=\"menu\"\n    >\n      x\n    </div>\n  </div>\n</div>\n"),
    ("array_of_objects_inner_flat", "<svelte:document use:shortcuts={[{ shortcut: { ctrl: true, key: 'k' }, onShortcut: () => input?.select() }]} />\n", "<svelte:document\n  use:shortcuts={[\n    { shortcut: { ctrl: true, key: \"k\" }, onShortcut: () => input?.select() },\n  ]}\n/>\n"),
];

#[test]
fn every_cell_formats_to_the_oracle_output() {
    let mut wrong = Vec::new();
    for (name, input, expected) in CELLS {
        let got = fmt(input);
        if got != *expected {
            wrong.push(format!("{name}: got {got:?}, want {expected:?}"));
        }
    }
    assert!(wrong.is_empty(), "{}", wrong.join("\n"));
}

/// Liveness: the table has to carry a value that breaks exactly once at its top
/// operator, one whose literal expands, and one that stays flat, or it measures
/// one direction of the budget.
#[test]
fn the_table_carries_every_direction() {
    let once = CELLS
        .iter()
        .filter(|(_, _, want)| want.contains("&&\n") && !want.contains("===\n"))
        .count();
    let expands = CELLS
        .iter()
        .filter(|(_, _, want)| want.contains("={{\n"))
        .count();
    let flat = CELLS
        .iter()
        .filter(|(_, _, want)| {
            want.lines()
                .any(|l| l.find("={").is_some_and(|i| l[i..].contains('}')))
        })
        .count();
    assert!(once > 0, "no cell breaks once at its top-level operator");
    assert!(expands > 0, "no cell expands an object literal");
    assert!(flat > 0, "no cell keeps its value flat");
}

/// Formatting the oracle's own output has to be a fixed point: the wrapped
/// form is the one a user's file holds after the first run.
#[test]
fn the_oracle_output_is_a_fixed_point() {
    let mut wrong = Vec::new();
    for (name, _, expected) in CELLS {
        let got = fmt(expected);
        if got != *expected {
            wrong.push(format!("{name}: {got:?}"));
        }
    }
    assert!(wrong.is_empty(), "{}", wrong.join("\n"));
}
