//! `fits` charged a breakable mustache it read in break mode by the head of
//! its outermost group (`{record.holders` for a member chain), where prettier
//! stops at the first `line` of *any* group it reads in break mode — the
//! expression's first break opportunity, `{record` (#4309). An inline element
//! glued to such a mustache was therefore measured a member too long, and
//! `<span class="label">Label text</span>{record` broke the span's hug where
//! the oracle keeps it and breaks inside the mustache.
//!
//! Every expectation here was generated by running the input through the
//! oxfmt(`svelte: true`) oracle. `glued_60` is the cell that moves: the span
//! plus `{record` ends at column 79. `glued_62` and `glued_64` are the same
//! shape two and four columns wider, where `{record` itself no longer fits and
//! the span breaks under both charges; a call and a ternary share their first
//! opportunity with the outermost head (`{formatDistance(`, `{record.holders`)
//! and must not move.

use rsvelte_formatter::{
    FormatOptions, IndentStyle, IndentWidth, JsFormatOptions, LineWidth, format,
};

fn fmt(src: &str) -> String {
    let js = JsFormatOptions {
        indent_style: IndentStyle::Space,
        indent_width: IndentWidth::try_from(2u8).unwrap(),
        line_width: LineWidth::try_from(80u16).unwrap(),
        ..JsFormatOptions::default()
    };
    let options = FormatOptions {
        js,
        typescript: false,
        ..FormatOptions::new()
    };
    format(src, &options).expect("format ok")
}

/// (name, input, oracle output)
#[rustfmt::skip]
const CELLS: &[(&str, &str, &str)] = &[
    ("glued_60", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <p>xxxxxxxxxxxxxxxxxxxx <span class=\"label\">Label text</span>{record.holders.location_name}</p>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <p>\n              xxxxxxxxxxxxxxxxxxxx <span class=\"label\">Label text</span>{record\n                .holders.location_name}\n            </p>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n"),
    ("glued_62", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <p>xxxxxxxxxxxxxxxxxxxxxx <span class=\"label\">Label text</span>{record.holders.location_name}</p>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <p>\n              xxxxxxxxxxxxxxxxxxxxxx <span class=\"label\">Label text</span\n              >{record.holders.location_name}\n            </p>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n"),
    ("glued_64", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <p>xxxxxxxxxxxxxxxxxxxxxxxx <span class=\"label\">Label text</span>{record.holders.location_name}</p>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <p>\n              xxxxxxxxxxxxxxxxxxxxxxxx <span class=\"label\">Label text</span\n              >{record.holders.location_name}\n            </p>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n"),
    ("glued_call_60", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <p>xxxxxxxxxxxxxxxxxxxx <span class=\"label\">Label text</span>{formatDistance(record.holders, units)}</p>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <p>\n              xxxxxxxxxxxxxxxxxxxx <span class=\"label\">Label text</span\n              >{formatDistance(record.holders, units)}\n            </p>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n"),
    ("glued_ternary_60", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <p>xxxxxxxxxxxxxxxxxxxx <span class=\"label\">Label text</span>{record.holders ? record.name : \"none\"}</p>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <p>\n              xxxxxxxxxxxxxxxxxxxx <span class=\"label\">Label text</span\n              >{record.holders ? record.name : \"none\"}\n            </p>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n"),
    ("glued_70", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <p>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx <span class=\"label\">Label text</span>{record.holders.location_name}</p>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <p>\n              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx <span class=\"label\"\n                >Label text</span\n              >{record.holders.location_name}\n            </p>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n"),
];

#[test]
fn every_cell_formats_to_the_oracle_output() {
    let mut wrong = Vec::new();
    for (name, input, expected) in CELLS {
        let got = fmt(input);
        if got != *expected {
            wrong.push(format!("{name}: got {got:?}, want {expected:?}"));
        }
    }
    assert!(wrong.is_empty(), "{}", wrong.join("\n"));
}

/// Liveness: the table has to hold a cell whose span stays hugged with the
/// mustache breaking behind it, and one where the span itself breaks.
#[test]
fn the_table_carries_both_verdicts() {
    let span_kept = CELLS
        .iter()
        .filter(|(_, _, want)| want.contains("</span>{record\n"));
    let span_broken = CELLS
        .iter()
        .filter(|(_, _, want)| want.contains("</span\n"));
    assert!(span_kept.count() >= 1, "no cell keeps the span's hug");
    assert!(span_broken.count() >= 2, "no cell breaks the span");
}

#[test]
fn the_oracle_output_is_a_fixed_point() {
    for (name, _, expected) in CELLS {
        assert_eq!(fmt(expected), *expected, "{name}");
    }
}
