//! A `{@keyword …}` tag is measured against the whole output line, so a run of
//! siblings glued in front of it moves its break threshold. This port charged
//! only the tag's own `{@render ` prefix, so a glued run left the tag measured
//! from column 0 and lines over `printWidth` were left unbroken (#4085).
//!
//! Every expectation here was generated by running the input through the
//! oxfmt(`svelte: true`) oracle. The negative rows carry the boundaries the
//! scan must respect: a block-display sibling is itself a break opportunity, an
//! enclosing element's open tag wraps and restarts the line at the element
//! indent, and the line's own indentation is already charged by the caller's
//! depth — the double-charge `glued_tag_prefix_width` already warns about for
//! the sibling mustache rule.

use rsvelte_formatter::{
    FormatOptions, IndentStyle, IndentWidth, JsFormatOptions, LineWidth, format,
};

fn fmt(src: &str) -> String {
    let js = JsFormatOptions {
        indent_style: IndentStyle::Space,
        indent_width: IndentWidth::try_from(2u8).unwrap(),
        line_width: LineWidth::try_from(80u16).unwrap(),
        ..JsFormatOptions::default()
    };
    let options = FormatOptions {
        js,
        typescript: false,
        ..FormatOptions::new()
    };
    format(src, &options).expect("format ok")
}

/// (name, input, oracle output)
#[rustfmt::skip]
const CELLS: &[(&str, &str, &str)] = &[
    // a `{#snippet}…{/snippet}` and text glued in front
    ("snippet_glued", "{#snippet s(p)}<p>{p}</p>{/snippet}xxxxxxxxxxxxxxxxxxxxxx{@render s(alphaAlpha, betaBeta, gammaGamma)}\n", "{#snippet s(p)}<p>{p}</p>{/snippet}xxxxxxxxxxxxxxxxxxxxxx{@render s(\n  alphaAlpha,\n  betaBeta,\n  gammaGamma,\n)}\n"),
    // a bare text run glued in front
    ("text_glued", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx{@render s(alphaAlpha, betaBeta, gammaGamma)}\n", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx{@render s(\n  alphaAlpha,\n  betaBeta,\n  gammaGamma,\n)}\n"),
    // an inline `<span>…</span>` glued in front
    ("inline_element_glued", "<span>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</span>{@render s(alphaAlpha, betaBeta, gammaGamma)}\n", "<span>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</span>{@render s(\n  alphaAlpha,\n  betaBeta,\n  gammaGamma,\n)}\n"),
    // a `{#if}…{/if}` glued in front
    ("if_block_glued", "{#if a}<b>{a}</b>{/if}xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx{@render s(alphaAlpha, betaBeta, gammaGamma)}\n", "{#if a}<b>{a}</b>{/if}xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx{@render s(\n  alphaAlpha,\n  betaBeta,\n  gammaGamma,\n)}\n"),
    // an inline element with an attribute glued in front
    ("attributed_inline_glued", "<span a=\"1\">xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</span>{@render s(alphaAlpha, betaBeta, gammaGamma)}\n", "<span a=\"1\">xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</span>{@render s(\n  alphaAlpha,\n  betaBeta,\n  gammaGamma,\n)}\n"),
    // a block-display sibling is itself a break opportunity
    ("block_display_sibling_is_a_break", "<p>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</p>{@render s(alphaAlpha, betaBeta, gammaGamma)}\n", "<p>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</p>\n{@render s(alphaAlpha, betaBeta, gammaGamma)}\n"),
    // the same for a div
    ("block_display_div_sibling", "<div>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</div>{@render s(alphaAlpha, betaBeta, gammaGamma)}\n", "<div>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</div>\n{@render s(alphaAlpha, betaBeta, gammaGamma)}\n"),
    // the enclosing open tag wraps, so the line restarts at the element indent
    ("enclosing_open_tag_is_not_charged", "<div class=\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\">{@render s(alphaAlpha, betaBeta, gammaGamma)}</div>\n", "<div class=\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\">\n  {@render s(alphaAlpha, betaBeta, gammaGamma)}\n</div>\n"),
    // leading whitespace is already charged by the caller depth
    ("indentation_alone_is_not_charged", "\t\t\t\t<div><span>{@render child({ props: finalProps, ...contentState.snip })}</span></div>\n", "<div>\n  <span>{@render child({ props: finalProps, ...contentState.snip })}</span>\n</div>\n"),
    // no prefix at all
    ("nothing_precedes_the_tag", "{@render s(alphaAlpha, betaBeta, gammaGamma)}\n", "{@render s(alphaAlpha, betaBeta, gammaGamma)}\n"),
];

#[test]
fn every_cell_formats_to_the_oracle_output() {
    let mut wrong = Vec::new();
    for (name, input, expected) in CELLS {
        let got = fmt(input);
        if got != *expected {
            wrong.push(format!("{name}: got {got:?}, want {expected:?}"));
        }
    }
    assert!(wrong.is_empty(), "{}", wrong.join("\n"));
}

/// Liveness. A cell whose expected output breaks the argument list is one the
/// prefix width decides; a cell that keeps it flat is a boundary the scan has to
/// stop at. Both kinds must be present or this file measures one rule.
#[test]
fn the_table_carries_both_directions() {
    let breaks = CELLS
        .iter()
        .filter(|(_, _, want)| want.contains("s(\n"))
        .count();
    let flat = CELLS
        .iter()
        .filter(|(_, _, want)| !want.contains("s(\n"))
        .count();
    assert!(breaks > 0, "no cell exercises a prefix that forces a break");
    assert!(
        flat > 0,
        "no cell exercises a boundary that must not be charged"
    );
}

/// Formatting the oracle's own output is where charging the SOURCE column rather
/// than the output column shows up, and that arm is invisible from the
/// unformatted inputs above.
#[test]
fn the_oracle_output_is_a_fixed_point() {
    let mut wrong = Vec::new();
    for (name, _, expected) in CELLS {
        let got = fmt(expected);
        if got != *expected {
            wrong.push(format!("{name}: {got:?}"));
        }
    }
    assert!(wrong.is_empty(), "{}", wrong.join("\n"));
}
