//! A `<pre>` whose one-line form overflows wrapped its attributes where the
//! oracle keeps them flat and breaks inside the content (#4174). prettier lays
//! the attribute group out flat when everything up to the first line-break
//! opportunity fits — its `fits` runs past `>` into the content, where
//! `printPre` offers a break at a text newline, at a mustache's first breakable
//! JS group, or at a child tag's own attribute / hug break — and only a content
//! with none of those charges the close tag too. The mustaches on the content
//! line are then laid out left to right, each charged what precedes it on its
//! first line and what follows it on its last.
//!
//! Every expectation here was generated by running the input through the
//! oxfmt(`svelte: true`) oracle. Both directions are in the table: `prism`,
//! `ident_no_break` and `text_newline_overflow` overflow before any opportunity
//! and wrap their attributes; `text_newline_fits` and `prism_plain` must not
//! move at all.

use rsvelte_formatter::{
    FormatOptions, IndentStyle, IndentWidth, JsFormatOptions, LineWidth, format,
};

fn fmt(src: &str) -> String {
    let js = JsFormatOptions {
        indent_style: IndentStyle::Space,
        indent_width: IndentWidth::try_from(2u8).unwrap(),
        line_width: LineWidth::try_from(80u16).unwrap(),
        ..JsFormatOptions::default()
    };
    let options = FormatOptions {
        js,
        typescript: false,
        ..FormatOptions::new()
    };
    format(src, &options).expect("format ok")
}

/// (name, input, oracle output)
#[rustfmt::skip]
const CELLS: &[(&str, &str, &str)] = &[
    ("tag_pre", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <pre class=\"output-value code-block\">{result.examples.iscDhcpd}</pre>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <pre class=\"output-value code-block\">{result.examples\n                .iscDhcpd}</pre>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n"),
    ("html_call", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <pre class=\"banner-content\">{@html formatBanner(diagnosticState.results.banner)}</pre>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <pre class=\"banner-content\">{@html formatBanner(\n                diagnosticState.results.banner,\n              )}</pre>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n"),
    ("kit_json", "<h2>Nested Object Value</h2>\n<pre id=\"object-value\">{JSON.stringify(values.fields.object.value(), null, 2)}</pre>\n", "<h2>Nested Object Value</h2>\n<pre id=\"object-value\">{JSON.stringify(\n    values.fields.object.value(),\n    null,\n    2,\n  )}</pre>\n"),
    ("first_line_overflows", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <pre class=\"output-value code-block long-class-name-here\">{resultExamplesIscDhcpdVeryLongName.examples.iscDhcpd}</pre>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <pre\n              class=\"output-value code-block long-class-name-here\">{resultExamplesIscDhcpdVeryLongName\n                .examples.iscDhcpd}</pre>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n"),
    ("smui_mixed", "<pre class=\"status\">Selected: {selected.map((option) => option.name).join(\", \")}</pre>\n", "<pre class=\"status\">Selected: {selected\n    .map((option) => option.name)\n    .join(\", \")}</pre>\n"),
    ("smui_and", "<pre class=\"status\">Caught Event Detail: {event && JSON.stringify(event.detail)}</pre>\n", "<pre class=\"status\">Caught Event Detail: {event &&\n    JSON.stringify(event.detail)}</pre>\n"),
    ("smui_two_ternaries", "<div>\n  <div>\n    <pre class=\"status\">Selected: {valueA ? valueA.label : \"None\"}, Price: {valueA ? valueA.price : \"-\"}¢</pre>\n  </div>\n</div>\n", "<div>\n  <div>\n    <pre class=\"status\">Selected: {valueA\n        ? valueA.label\n        : \"None\"}, Price: {valueA ? valueA.price : \"-\"}¢</pre>\n  </div>\n</div>\n"),
    ("smui_three", "<pre class=\"status\">Aligned: {align.name}, Format: {format.length ? format.map((f) => f.name).join(\" & \") : \"None\"}, {actions.map(({ name, count }) => `${name}s: ${count}`).join(\", \")}</pre>\n", "<pre class=\"status\">Aligned: {align.name}, Format: {format.length\n    ? format.map((f) => f.name).join(\" & \")\n    : \"None\"}, {actions\n    .map(({ name, count }) => `${name}s: ${count}`)\n    .join(\", \")}</pre>\n"),
    ("kit_enhance", "<pre class=\"data1\">prop: {data.enhance_counter}, state: {page.data.enhance_counter}</pre>\n", "<pre class=\"data1\">prop: {data.enhance_counter}, state: {page.data\n    .enhance_counter}</pre>\n"),
    ("rz", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <h4>Zone File:</h4>\n          <pre><code>{reverseZonesContent.zoneCreation.ipv4Example.zoneFile}</code></pre>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <h4>Zone File:</h4>\n          <pre><code\n              >{reverseZonesContent.zoneCreation.ipv4Example.zoneFile}</code\n            ></pre>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n"),
    ("text_then_code", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <pre class=\"code-block\"><code>docker run -v $(pwd)/custom-styles.css:/app/static/custom-styles.css:ro ...</code></pre>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <pre class=\"code-block\"><code\n                >docker run -v $(pwd)/custom-styles.css:/app/static/custom-styles.css:ro ...</code\n              ></pre>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n"),
    ("component_child", "<div>\n  <div>\n    <div>\n      <pre class=\"value string multi\" title={value}><Highlight {value} fields={[\"value\"]} /></pre>\n    </div>\n  </div>\n</div>\n", "<div>\n  <div>\n    <div>\n      <pre class=\"value string multi\" title={value}><Highlight\n          {value}\n          fields={[\"value\"]}\n        /></pre>\n    </div>\n  </div>\n</div>\n"),
    ("prism", "<div>\n  <!-- eslint-disable-next-line svelte/no-at-html-tags -->\n  <pre class={lineNumbers ? \"line-numbers\" : \"\"} data-line={highlightLines}><code class={prismClasses}>{@html prettyCode}</code></pre>\n</div>\n", "<div>\n  <!-- eslint-disable-next-line svelte/no-at-html-tags -->\n  <pre\n    class={lineNumbers ? \"line-numbers\" : \"\"}\n    data-line={highlightLines}><code class={prismClasses}\n      >{@html prettyCode}</code\n    ></pre>\n</div>\n"),
    ("prism_ignore", "<div>\n  <!-- prettier-ignore -->\n  <!-- eslint-disable-next-line svelte/no-at-html-tags -->\n  <pre class={lineNumbers ? \"line-numbers\" : \"\"} data-line={highlightLines}><code class={prismClasses}>{@html prettyCode}</code></pre>\n</div>\n", "<div>\n  <!-- prettier-ignore -->\n  <!-- eslint-disable-next-line svelte/no-at-html-tags -->\n  <pre\n    class={lineNumbers ? \"line-numbers\" : \"\"}\n    data-line={highlightLines}><code class={prismClasses}\n      >{@html prettyCode}</code\n    ></pre>\n</div>\n"),
    ("ident_no_break", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <pre class=\"output-value code-block\">{resultExamplesIscDhcpdX}</pre>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <pre class=\"output-value code-block\">{resultExamplesIscDhcpdX}</pre>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n"),
    ("text_newline_overflow", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <pre class=\"output-value code-block\">hello world text hello world text hello world\nworld</pre>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <pre\n              class=\"output-value code-block\">hello world text hello world text hello world\nworld</pre>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n"),
    ("text_newline_fits", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <pre class=\"output-value code-block\">hello world text hello\nworld</pre>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <pre class=\"output-value code-block\">hello world text hello\nworld</pre>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n"),
    ("prism_plain", "<div>\n  <pre class=\"line-numbers-and-some-more-classes-here\" data-line={highlightLines}><code class={prismClasses}>{@html prettyCode}</code></pre>\n</div>\n", "<div>\n  <pre\n    class=\"line-numbers-and-some-more-classes-here\"\n    data-line={highlightLines}><code class={prismClasses}\n      >{@html prettyCode}</code\n    ></pre>\n</div>\n"),
];

#[test]
fn every_cell_formats_to_the_oracle_output() {
    let mut wrong = Vec::new();
    for (name, input, expected) in CELLS {
        let got = fmt(input);
        if got != *expected {
            wrong.push(format!("{name}: got {got:?}, want {expected:?}"));
        }
    }
    assert!(wrong.is_empty(), "{}", wrong.join("\n"));
}

fn pre_open_line(text: &str) -> &str {
    text.lines()
        .find(|l| l.trim_start().starts_with("<pre"))
        .expect("a <pre> line")
}

/// Liveness: the table has to carry a `<pre>` whose attributes stay flat while
/// its content breaks, one whose attributes wrap, and one the formatter leaves
/// untouched, or it measures one direction of the rule.
#[test]
fn the_table_carries_every_direction() {
    let flat_content_breaks = CELLS.iter().filter(|(_, input, want)| {
        let open = pre_open_line(want);
        open.contains('>') && want.lines().count() > input.lines().count()
    });
    let attrs_wrap = CELLS
        .iter()
        .filter(|(_, _, want)| pre_open_line(want).trim() == "<pre");
    let untouched = CELLS.iter().filter(|(_, input, want)| input == want);
    assert!(
        flat_content_breaks.count() >= 3,
        "no cell keeps its attributes flat and breaks its content"
    );
    assert!(attrs_wrap.count() >= 3, "no cell wraps its attributes");
    assert!(untouched.count() >= 2, "no cell is left untouched");
}

#[test]
fn the_oracle_output_is_a_fixed_point() {
    for (name, _, expected) in CELLS {
        assert_eq!(fmt(expected), *expected, "{name}: the oracle form moved");
    }
}
