//! The whole-value attribute model built each interpolation's broken form at
//! doc-build time, on a budget derived from the builder's running column —
//! the first line's room — and nothing re-checked it against the indent the
//! continuation lines print at (#4311). A continuation line that had the whole
//! width was broken again (`parentRowId ===` / `row.id`), and a member chain
//! split at every `?.`. The interpolations now carry their source, so the
//! printer rebuilds them at the attribute's real indent, `fits` charges them
//! up to their first break opportunity, and the closing `"` is charged the way
//! prettier charges it — by a measurement that reaches the value's end — rather
//! than as a column reserved on every line.
//!
//! Every expectation here was generated by running the input through the
//! oxfmt(`svelte: true`) oracle. The first three cells are the shapes of the
//! issue's carriers (a `class` with seven interpolations, a `message` whose
//! chain spans the wrap, a `title` with two `||` chains) and diverge without
//! the fix; `flat_control` must not move.

use rsvelte_formatter::{
    FormatOptions, IndentStyle, IndentWidth, JsFormatOptions, LineWidth, format,
};

fn fmt(src: &str) -> String {
    let js = JsFormatOptions {
        indent_style: IndentStyle::Space,
        indent_width: IndentWidth::try_from(2u8).unwrap(),
        line_width: LineWidth::try_from(80u16).unwrap(),
        ..JsFormatOptions::default()
    };
    let options = FormatOptions {
        js,
        typescript: false,
        ..FormatOptions::new()
    };
    format(src, &options).expect("format ok")
}

/// (name, input, oracle output)
#[rustfmt::skip]
const CELLS: &[(&str, &str, &str)] = &[
    ("class_many", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <TableRow data-row={row.id} data-parent-row={expandable ? true : undefined} class=\"{isSelected ? 'bx--data-table--selected' : ''} {isExpanded ? 'bx--expandable-row' : ''} {expandable ? 'bx--parent-row' : ''} {expandable && parentRowId === row.id ? 'bx--expandable-row--hover' : ''} {isHighlighted ? 'bx--data-table--highlighted-row' : ''} {expandable && isSelectionEnabled ? 'bx--expandable-row--with-selection' : ''} {rowClassValue ?? ''}\" />\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <TableRow\n              data-row={row.id}\n              data-parent-row={expandable ? true : undefined}\n              class=\"{isSelected ? 'bx--data-table--selected' : ''} {isExpanded\n                ? 'bx--expandable-row'\n                : ''} {expandable ? 'bx--parent-row' : ''} {expandable &&\n              parentRowId === row.id\n                ? 'bx--expandable-row--hover'\n                : ''} {isHighlighted\n                ? 'bx--data-table--highlighted-row'\n                : ''} {expandable && isSelectionEnabled\n                ? 'bx--expandable-row--with-selection'\n                : ''} {rowClassValue ?? ''}\"\n            />\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n"),
    ("message_chain", "<SettingsModule title=\"Delete Account\" editable={true} dangerous={true} message=\"Deleting your account can not be undone. You are currently logged in as '{session?.user?.email}'\" saveButtonTitle=\"Delete Account\" />\n", "<SettingsModule\n  title=\"Delete Account\"\n  editable={true}\n  dangerous={true}\n  message=\"Deleting your account can not be undone. You are currently logged in as '{session\n    ?.user?.email}'\"\n  saveButtonTitle=\"Delete Account\"\n/>\n"),
    ("title_two_chains", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <div>\n              <div>\n                <div>\n                  <a href={x} title=\"{$t('search_for')} {asset.exifInfo.make || ''} {asset.exifInfo.model || ''}\" class=\"hover:text-primary\">x</a>\n                </div>\n              </div>\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n", "<div>\n  <div>\n    <div>\n      <div>\n        <div>\n          <div>\n            <div>\n              <div>\n                <div>\n                  <a\n                    href={x}\n                    title=\"{$t('search_for')} {asset.exifInfo.make || ''} {asset\n                      .exifInfo.model || ''}\"\n                    class=\"hover:text-primary\">x</a\n                  >\n                </div>\n              </div>\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>\n"),
    ("flat_control", "<div>\n  <div>\n    <div class=\"card {selected ? 'active' : ''}\" data-id={id}></div>\n  </div>\n</div>\n", "<div>\n  <div>\n    <div class=\"card {selected ? 'active' : ''}\" data-id={id}></div>\n  </div>\n</div>\n"),
];

#[test]
fn every_cell_formats_to_the_oracle_output() {
    let mut wrong = Vec::new();
    for (name, input, expected) in CELLS {
        let got = fmt(input);
        if got != *expected {
            wrong.push(format!("{name}: got {got:?}, want {expected:?}"));
        }
    }
    assert!(wrong.is_empty(), "{}", wrong.join("\n"));
}

/// Liveness: a continuation line has to carry a binary that the old budget
/// split (`parentRowId === row.id` whole on its line) and a chain has to cross
/// the wrap without splitting at every `?.`.
#[test]
fn the_table_carries_the_rebuilt_continuations() {
    let whole_binary = CELLS
        .iter()
        .filter(|(_, _, want)| want.lines().any(|l| l.trim() == "parentRowId === row.id"));
    let chain_whole = CELLS
        .iter()
        .filter(|(_, _, want)| want.contains("\n    ?.user?.email}'\""));
    let untouched = CELLS.iter().filter(|(_, input, want)| input == want);
    assert!(
        whole_binary.count() >= 1,
        "no cell keeps a binary whole on its continuation line"
    );
    assert!(
        chain_whole.count() >= 1,
        "no cell carries a chain across the wrap"
    );
    assert!(untouched.count() >= 1, "no cell is left untouched");
}

#[test]
fn the_oracle_output_is_a_fixed_point() {
    for (name, _, expected) in CELLS {
        assert_eq!(fmt(expected), *expected, "{name}");
    }
}
