//! Server-side code generation.
//!
//! Generates JavaScript code for server-side rendering (SSR).
//!
//! This module is organized to match the Svelte compiler structure.

/// Pure-AST server codegen (Phase-3 rewrite). This is the ONLY server component
/// pipeline — the legacy text `ServerCodeGenerator` / `build` / `bridge` /
/// `visitors` modules were deleted after the switchover.
pub mod ast;
pub(crate) mod await_save_ast;
pub(crate) mod derived_reads_ast;
pub(crate) mod evaluate;
pub mod helpers;
pub(crate) mod rune_call_ast;
pub(crate) mod strip_export_ast;
pub mod transform_legacy;
pub mod transform_script;
pub mod transform_store;
pub mod types;
pub(crate) mod unthunk_derived_ast;

use super::TransformError;
use crate::ast::template::Root;
use crate::compiler::CompileOptions;
use crate::compiler::phases::phase2_analyze::ComponentAnalysis;
use memchr::memmem;

/// Transform a component analysis into server-side JavaScript.
///
/// # Arguments
///
/// * `analysis` - The component analysis from Phase 2
/// * `ast` - The parsed AST from Phase 1 (to avoid re-parsing)
/// * `_source` - The original source code (for backward compatibility)
/// * `_options` - Compile options
pub fn transform_server(
    analysis: &ComponentAnalysis,
    ast: &Root,
    _source: &str,
    options: &CompileOptions,
) -> Result<String, TransformError> {
    // Pure-AST SSR pipeline (`server/ast/`): builds a real oxc AST and prints it
    // once with `rsvelte_esrap` — zero text post-processing. This replaced the
    // legacy text `ServerCodeGenerator` (deleted) after reaching byte-parity
    // across the curated runtime / `compiler_fixtures` / `ssr` suites and a net
    // corpus improvement. The pipeline never returns `None` for a parseable
    // component; a `None` (only on an internal assembly failure) surfaces as an
    // error rather than silently falling back.
    let allocator = oxc_allocator::Allocator::default();
    match ast::server_component_ast(analysis, ast, _source, options, &allocator) {
        Some(code) => Ok(code),
        None => Err(TransformError::CodeGen(
            "server AST pipeline produced no output".to_string(),
        )),
    }
}

/// Transform a module (.svelte.js/.svelte.ts) into server-side JavaScript.
///
/// Unlike `transform_server`, this does NOT generate a component function.
/// It only transforms the module source (rune replacements) and prepends
/// the `import * as $ from 'svelte/internal/server'` import.
///
/// Corresponds to `server_module()` in the official Svelte compiler.
pub fn transform_server_module(
    analysis: &ComponentAnalysis,
    source: &str,
    _options: &CompileOptions,
) -> Result<String, TransformError> {
    // For server modules, perform the same rune transformations as client modules
    // but use 'svelte/internal/server' import instead.
    let basename = _options
        .filename
        .as_ref()
        .and_then(|f| f.rsplit('/').next().or_else(|| f.rsplit('\\').next()))
        .unwrap_or("input.svelte.js");

    let mut parts: Vec<String> = Vec::new();

    // Leading comment
    parts.push(format!(
        "/* {} generated by Svelte v{} */",
        basename,
        option_env!("SVELTE_VERSION").unwrap_or("VERSION")
    ));

    // Import
    parts.push("import * as $ from 'svelte/internal/server';".to_string());

    // For server modules, strip $effect and $effect.root blocks from the source
    // before applying transforms, since effects don't run on the server.
    let source_without_effects = strip_effects_from_source(source);

    // Lower `$state` / `$derived` CLASS fields with the SERVER transform FIRST.
    // The client module transform (below) privatizes a public `$state` field
    // into `#field` + get/set accessors — correct for the client, but on the
    // server a public `$state` field is just a plain public value
    // (`active = false`). Running `transform_class_fields_server` first replaces
    // `$state(v)` → `v` in the class body, so the subsequent client transform
    // finds no rune in the class and leaves the (now server-shaped) fields
    // alone. Mirrors how the component server path lowers class fields.
    let source_without_effects =
        transform_script::transform_class_fields_server(&source_without_effects);
    // `$effect.tracking()` has no effect tracking on the server → `false`
    // (mirrors the instance-script path + upstream server CallExpression visitor).
    let source_without_effects = source_without_effects.replace("$effect.tracking()", "false");

    // Transform rune calls using the same infrastructure as client modules.
    let transformed =
        super::client::transform_module_source_for_module(&source_without_effects, analysis, false);

    // Post-process: replace client-specific runtime calls with server equivalents
    // $.get(x) -> x() for server (derived signals are callable on server)
    // $.set(x, v) -> x(v)
    // $.proxy(x) -> x (no proxying on server)
    // $.state(x) -> x (no signals on server)
    // $.effect_root(...) and $.user_effect(...) -> noop (should already be stripped)
    let transformed = post_process_for_server(&transformed);

    // After the server lowering turns `$.get(x)` → `x()` for derived reads,
    // a `$derived(<bare derived>)` initializer reads as
    // `$.derived(() => source())`. Collapse it back to `$.derived(source)`,
    // mirroring the component instance-script path (the server runtime treats
    // a derived passed directly as a re-callable dependency). Modules went
    // through the CLIENT module transform, so this server-only pass wasn't
    // applied there.
    let transformed = transform_script::unthunk_bare_derived_arg(&transformed);

    // Collapse `const NAME = $.snapshot(x)` → `const NAME = x` on the module path.
    // The client module transform lowered `$state.snapshot(x)` → `$.snapshot(x)`;
    // upstream `compileModule` server keeps `$.snapshot` everywhere EXCEPT a plain
    // variable-declarator init, where it is redundant and strips to the bare arg
    // (e.g. melt-ui Popover / selection-state `const prev = $state.snapshot(this.x)`).
    let transformed = transform_script::strip_snapshot_declarator_init_module(&transformed);

    // Split imports from body
    let (script_imports, script_rest) = super::client::extract_imports_str(&transformed);

    for import_line in &script_imports {
        let trimmed = import_line.trim();
        if memmem::find(trimmed.as_bytes(), b"svelte/internal/").is_none() {
            // Ensure import statements end with semicolons, matching esrap behavior.
            if !trimmed.ends_with(';') {
                let mut with_semi = String::with_capacity(trimmed.len() + 1);
                with_semi.push_str(trimmed);
                with_semi.push(';');
                parts.push(with_semi);
            } else {
                parts.push(trimmed.to_string());
            };
        }
    }

    if let Some(rest) = script_rest {
        let rest_trimmed = rest.trim();
        if !rest_trimmed.is_empty() {
            parts.push(String::new()); // blank line
            parts.push(rest_trimmed.to_string());
        }
    }

    Ok(parts.join("\n"))
}

/// Safety cap on the fixed-point iteration for the server-module call rewrites
/// ([`strip_effects_from_source`] / [`post_process_for_server`]). Every
/// replacement strictly shrinks or unwraps its match, so real inputs settle in
/// one or two passes; the cap only guards against pathological nesting.
const REWRITE_MAX_ITERS: usize = 16;

/// Collect the byte offset of every occurrence of `needle` in `haystack` that
/// lies in JS code — skipping string / template literals and `//` / `/*`
/// comments — in a single left-to-right scan. The lexical-aware analogue of
/// [`memmem::Finder::find_iter`].
///
/// Without this guard a rune-call-shaped substring inside a string or comment
/// such as `const a = "$effect.root()"` would be matched and rewritten,
/// corrupting the literal (issue #447, H-029).
fn code_match_positions(haystack: &str, needle: &[u8]) -> Vec<usize> {
    let bytes = haystack.as_bytes();
    let n = bytes.len();
    let mut out = Vec::new();
    if needle.is_empty() {
        return out;
    }
    let mut i = 0usize;
    while i < n {
        match bytes[i] {
            b'\'' | b'"' | b'`' => {
                // Skip the whole string / template (incl. ${} interpolations).
                i = skip_string_literal(bytes, i);
                continue;
            }
            b'/' if i + 1 < n && bytes[i + 1] == b'/' => {
                i += 2;
                while i < n && bytes[i] != b'\n' {
                    i += 1;
                }
                continue;
            }
            b'/' if i + 1 < n && bytes[i + 1] == b'*' => {
                i += 2;
                while i + 1 < n && !(bytes[i] == b'*' && bytes[i + 1] == b'/') {
                    i += 1;
                }
                i = (i + 2).min(n);
                continue;
            }
            _ => {}
        }
        if i + needle.len() <= n && &bytes[i..i + needle.len()] == needle {
            out.push(i);
        }
        i += 1;
    }
    out
}

/// One collect-and-splice pass over `source` for a paren-call rewrite. For every
/// match start in `positions` (ascending) not already inside a consumed span,
/// [`build`] returns `(end, replacement)` — where `end` is the byte offset just
/// past the region to replace — or `None` to stop scanning (mirroring the
/// original loops' `break` on an unbalanced paren). The resulting non-overlapping
/// edits are applied right-to-left in a single rebuild. Returns `None` when
/// nothing matched.
fn rewrite_calls_once<F>(source: &str, positions: &[usize], build: &F) -> Option<String>
where
    F: Fn(&str, usize) -> Option<(usize, String)>,
{
    let mut edits: Vec<(usize, usize, String)> = Vec::new();
    let mut cursor = 0usize;
    for &pos in positions {
        if pos < cursor {
            continue;
        }
        match build(source, pos) {
            Some((end, replacement)) => {
                edits.push((pos, end, replacement));
                cursor = end;
            }
            None => break,
        }
    }
    if edits.is_empty() {
        return None;
    }
    // Edits are ascending and non-overlapping by construction, so applying them
    // in reverse keeps every earlier offset valid without a sort.
    let mut out = source.to_string();
    for (start, end, replacement) in edits.iter().rev() {
        out.replace_range(*start..*end, replacement);
    }
    Some(out)
}

/// Drive [`rewrite_calls_once`] to a fixed point. Positions are recomputed each
/// pass so an outer call exposed by unwrapping an inner one (e.g.
/// `$.proxy($.proxy(x))`) is picked up on the next iteration. `lexical` selects
/// the string/comment-aware [`code_match_positions`] scanner (rune-level source)
/// versus the raw [`memmem::Finder`] (already-transformed `$.` runtime calls).
fn rewrite_calls<F>(source: &str, needle: &[u8], lexical: bool, build: F) -> String
where
    F: Fn(&str, usize) -> Option<(usize, String)>,
{
    let mut current = source.to_string();
    for _ in 0..REWRITE_MAX_ITERS {
        let positions = if lexical {
            code_match_positions(&current, needle)
        } else {
            memmem::Finder::new(needle)
                .find_iter(current.as_bytes())
                .collect::<Vec<_>>()
        };
        if positions.is_empty() {
            break;
        }
        match rewrite_calls_once(&current, &positions, &build) {
            Some(next) => current = next,
            None => break,
        }
    }
    current
}

/// Strip $effect and $effect.root blocks from source code.
/// In SSR, effects don't run, so they should be removed or replaced with no-ops.
/// - `$effect.root(() => { ... })` -> `() => {}` (returns a no-op cleanup function)
/// - `$effect(() => { ... })` -> removed entirely (statement-level only)
/// - `$effect.pre(() => { ... })` -> removed entirely (statement-level only)
///
/// Matching is JS-lexical-aware via [`code_match_positions`], so effect-call-shaped
/// text inside string literals or comments is left untouched (issue #447, H-029).
fn strip_effects_from_source(source: &str) -> String {
    use super::client::find_matching_paren;

    // Consume the trailing whitespace + optional `;` after a removed statement so
    // no stray fragment remains.
    let consume_statement_tail = |s: &str, expr_end: usize| -> usize {
        let bytes = s.as_bytes();
        let mut end = expr_end;
        while end < s.len() && bytes[end].is_ascii_whitespace() {
            end += 1;
        }
        if end < s.len() && bytes[end] == b';' {
            end += 1;
        }
        end
    };

    // `$effect.root(...)` has two upstream lowerings:
    //   - statement position  → removed entirely (ExpressionStatement.js → b.empty)
    //   - expression position  → `() => {}` no-op cleanup fn (CallExpression.js)
    let result = rewrite_calls(source, b"$effect.root(", true, |s, pos| {
        let call_start = pos + 13; // after "$effect.root("
        let content_end = find_matching_paren(&s[call_start..])?;
        let expr_end = call_start + content_end + 1; // after closing paren
        // Statement position when everything from the line start to `pos` is
        // whitespace (e.g. a bare `$effect.root(...)` in a constructor body).
        let line_start = s[..pos].rfind('\n').map(|n| n + 1).unwrap_or(0);
        let is_statement = s[line_start..pos].chars().all(|c| c.is_whitespace());
        if is_statement {
            Some((consume_statement_tail(s, expr_end), String::new()))
        } else {
            Some((expr_end, "() => {}".to_string()))
        }
    });

    // Strip $effect.pre(() => { ... }) blocks
    let result = rewrite_calls(&result, b"$effect.pre(", true, |s, pos| {
        let call_start = pos + 12;
        let content_end = find_matching_paren(&s[call_start..])?;
        let expr_end = call_start + content_end + 1;
        Some((consume_statement_tail(s, expr_end), String::new()))
    });

    // Strip $effect(() => { ... }) blocks ($effect.root/$effect.pre are already
    // handled; the `(` in the needle can never precede a `.`, so those forms
    // never match here).
    rewrite_calls(&result, b"$effect(", true, |s, pos| {
        let call_start = pos + 8; // after "$effect("
        let content_end = find_matching_paren(&s[call_start..])?;
        let expr_end = call_start + content_end + 1;
        Some((consume_statement_tail(s, expr_end), String::new()))
    })
}

/// Recompact a state setter value back into a compound assignment.
///
/// The shared client module transform lowers `s += 1` (a `$state` compound
/// assignment) to `$.set(s, $.get(s) + 1)`. On the server, state is a plain
/// mutable binding, so the upstream `AssignmentExpression` visitor keeps the
/// original compound operator. By the time `post_process_for_server` reaches
/// the `$.set` rewrite, the inner `$.get(s)` read has already collapsed to a
/// bare `s`, so `value` reads `s + 1`. When `value` is exactly
/// `<signal> <binop> <single-operand>`, fold it back to `s += 1`.
///
/// Conservative on purpose: only arithmetic / bitwise operators (logical
/// `&&`/`||`/`??` are skipped), and the right-hand side must be a single
/// operand (no top-level binary operator) so there is never a precedence
/// ambiguity between `s += a + b` and `s = (s + a) + b`.
fn recompact_compound_set(signal: &str, value: &str) -> Option<String> {
    if signal.is_empty() || !value.starts_with(signal) {
        return None;
    }
    let after = &value[signal.len()..];
    // `signal` must be the whole left operand — the next char cannot continue
    // the identifier (`s.foo`, `state2`) or start a member access (`s.x += 1`
    // is a member assignment, handled elsewhere).
    match after.chars().next() {
        Some(c) if c.is_alphanumeric() || c == '_' || c == '$' || c == '.' => return None,
        None => return None,
        _ => {}
    }
    let after = after.trim_start();
    // longest-first so `**`/`<<`/`>>>`/`>>` win over their prefixes
    const OPS: &[(&str, &str)] = &[
        (">>>", ">>>="),
        ("**", "**="),
        ("<<", "<<="),
        (">>", ">>="),
        ("+", "+="),
        ("-", "-="),
        ("*", "*="),
        ("/", "/="),
        ("%", "%="),
        ("&", "&="),
        ("|", "|="),
        ("^", "^="),
    ];
    for (bin, comp) in OPS {
        let Some(rest) = after.strip_prefix(bin) else {
            continue;
        };
        // Guard against logical / longer operators that share a prefix:
        // `&&`, `||`, and a stray `>` after `>>` (i.e. `>>>`, already matched).
        if (*bin == "&" && rest.starts_with('&'))
            || (*bin == "|" && rest.starts_with('|'))
            || (*bin == "*" && rest.starts_with('*'))
            || (*bin == ">>" && rest.starts_with('>'))
        {
            continue;
        }
        let rhs = rest.trim();
        if rhs.is_empty() || has_top_level_binary_operator(rhs) {
            return None;
        }
        return Some(format!("{signal} {comp} {rhs}"));
    }
    None
}

/// True if `expr` contains a binary/logical operator at paren/bracket/brace
/// depth 0 (after skipping leading unary `+`/`-`/`!`/`~`). Used to keep
/// [`recompact_compound_set`] from folding a multi-operand right-hand side
/// where operator precedence would make `s += a + b` mean something other than
/// the original `s = s + a + b`.
fn has_top_level_binary_operator(expr: &str) -> bool {
    let bytes = expr.as_bytes();
    let len = bytes.len();
    let mut i = 0;
    // Skip a run of leading unary operators (`-x`, `!flag`, `~mask`, `+n`).
    while i < len && matches!(bytes[i], b'-' | b'+' | b'!' | b'~') {
        i += 1;
        while i < len && bytes[i] == b' ' {
            i += 1;
        }
    }
    let mut depth: i32 = 0;
    while i < len {
        match bytes[i] {
            b'(' | b'[' | b'{' => depth += 1,
            b')' | b']' | b'}' => depth -= 1,
            b'"' | b'\'' | b'`' => {
                let quote = bytes[i];
                i += 1;
                while i < len {
                    if bytes[i] == b'\\' && i + 1 < len {
                        i += 2;
                        continue;
                    }
                    if bytes[i] == quote {
                        break;
                    }
                    i += 1;
                }
            }
            b'+' | b'-' | b'*' | b'/' | b'%' | b'<' | b'>' | b'&' | b'|' | b'^' | b'=' | b'?'
                if depth == 0 =>
            {
                return true;
            }
            _ => {}
        }
        i += 1;
    }
    false
}

/// Post-process client module transform output for server context.
/// Replaces client-specific runtime calls with server equivalents.
fn post_process_for_server(source: &str) -> String {
    use super::client::find_matching_paren;
    let result = source.to_string();

    // Collect names declared as `let|const|var X = $.derived(...)` /
    // `$.derived_safe_equal(...)`. On the server, `$.derived(fn)` returns a
    // *callable* (upstream svelte `src/internal/server/index.js#derived`),
    // so reads via `$.get(X)` must rewrite to `X()` for derived names and to
    // `X` for plain state names. Without this distinction, derived values
    // become stale snapshots and downstream code (`get isValid()` etc.)
    // breaks when the underlying state mutates between calls.
    let derived_names = collect_derived_names(&result);
    // Private class fields backed by `$.derived(...)` are *callable* on the
    // server (read via `this.#x()`); `$state` fields are plain values (read via
    // `this.#x`, set via `this.#x = v`). Collect the derived ones so the
    // `$.get`/`$.set` member rewrites below pick the right form per field
    // instead of blindly treating every `this.#x` as callable (issue #907).
    let derived_private_fields = collect_derived_private_fields(&result);

    // Replace $.effect_root(...) with () => {} (no-op cleanup)
    let mut result = rewrite_calls(&result, b"$.effect_root(", false, |s, pos| {
        let call_start = pos + 14;
        let content_end = find_matching_paren(&s[call_start..])?;
        Some((call_start + content_end + 1, "() => {}".to_string()))
    });

    // Remove $.user_effect(...) calls
    result = rewrite_calls(&result, b"$.user_effect(", false, |s, pos| {
        let call_start = pos + 14;
        let content_end = find_matching_paren(&s[call_start..])?;
        let expr_end = call_start + content_end + 1;
        let bytes = s.as_bytes();
        let mut end = expr_end;
        while end < s.len() && bytes[end].is_ascii_whitespace() {
            end += 1;
        }
        if end < s.len() && bytes[end] == b';' {
            end += 1;
        }
        Some((end, String::new()))
    });

    // Replace $.proxy(x) with just x (no proxying on server)
    result = rewrite_calls(&result, b"$.proxy(", false, |s, pos| {
        let call_start = pos + 8;
        let content_end = find_matching_paren(&s[call_start..])?;
        let content = s[call_start..call_start + content_end].to_string();
        Some((call_start + content_end + 1, content))
    });

    // Replace $.get(x) for server modules:
    // - Simple identifiers naming a derived: $.get(x) -> x() (callable signal)
    // - Simple identifiers naming state:     $.get(x) -> x
    // - Member expressions (this.#x):        $.get(this.#x) -> this.#x() (callable in class)
    result = rewrite_calls(&result, b"$.get(", false, |s, pos| {
        let call_start = pos + 6;
        let content_end = find_matching_paren(&s[call_start..])?;
        let content = s[call_start..call_start + content_end].trim().to_string();
        // Check if it's a member expression (contains '.')
        let replacement = if memchr::memchr(b'.', content.as_bytes()).is_some() {
            // A private `$state` class field is a plain value on the server
            // (`this.#x`); only derived fields (and other member exprs) read
            // as a call (`this.#x()`).
            let plain_state_field = private_field_name(&content)
                .is_some_and(|name| !derived_private_fields.contains(name));
            if plain_state_field {
                content
            } else {
                format!("{content}()")
            }
        } else if derived_names.contains(content.as_str()) {
            // Derived simple ident: callable on the server
            format!("{content}()")
        } else {
            // Simple identifier (state): just the variable name
            content
        };
        Some((call_start + content_end + 1, replacement))
    });

    // Replace $.set(x, v[, flag]) for server modules:
    // - Simple identifiers: $.set(x, v) -> x = v
    // - Member expressions: $.set(this.#x, v) -> this.#x(v)
    result = rewrite_calls(&result, b"$.set(", false, |s, pos| {
        let call_start = pos + 6;
        let content_end = find_matching_paren(&s[call_start..])?;
        let content = s[call_start..call_start + content_end].to_string();
        let comma_pos = find_first_comma(&content)?;
        let signal = content[..comma_pos].trim();
        let rest = content[comma_pos + 1..].trim();
        // Rest might be "value, flag" - take only the value (up to second comma)
        let value = if let Some(comma2_pos) = find_first_comma(rest) {
            rest[..comma2_pos].trim()
        } else {
            rest
        };
        let replacement = if memchr::memchr(b'.', signal.as_bytes()).is_some() {
            // A private `$state` class field is a plain value on the server, so
            // its assignment stays `this.#x = v`; only derived fields (and other
            // member exprs) use the setter-call form `this.#x(v)`.
            let plain_state_field = private_field_name(signal)
                .is_some_and(|name| !derived_private_fields.contains(name));
            if plain_state_field {
                format!("{signal} = {value}")
            } else {
                format!("{signal}({value})")
            }
        } else if derived_names.contains(signal) {
            // Assignment to a derived binding becomes a setter call on the
            // server: `$.set(value, v)` → `value(v)` (the server runtime exposes
            // a writable derived as a callable).
            format!("{signal}({value})")
        } else if let Some(compound) = recompact_compound_set(signal, value) {
            // Compound assignment recompaction. The shared client transform
            // lowered a state compound assignment `s += 1` to
            // `$.set(s, $.get(s) + 1)`; by this point the inner `$.get(s)` read
            // already collapsed to `s`, so the value reads `s + 1`. The upstream
            // server `AssignmentExpression` visitor keeps the original compound
            // operator for a plain (server-flat) state binding, so fold it back
            // to `s += 1`.
            compound
        } else {
            // Simple identifier: assignment form
            format!("{signal} = {value}")
        };
        Some((call_start + content_end + 1, replacement))
    });

    // Replace $.update_pre(x) with ++x for server modules.
    // IMPORTANT: Process $.update_pre BEFORE $.update to avoid prefix matching issues.
    // A second argument (`$.update_pre(x, -1)`) is the decrement form (`--x`); any
    // other delta `d` maps to `x += d` (H-031 — previously the raw `x, -1` content
    // was prefixed with `++`, producing invalid `++x, -1`).
    result = rewrite_calls(&result, b"$.update_pre(", false, |s, pos| {
        let call_start = pos + 13;
        let content_end = find_matching_paren(&s[call_start..])?;
        let content = s[call_start..call_start + content_end].trim();
        Some((
            call_start + content_end + 1,
            build_update_replacement(content, true),
        ))
    });

    // Replace $.update(x) with x++ for server modules (and $.update(x, -1) with x--).
    result = rewrite_calls(&result, b"$.update(", false, |s, pos| {
        let call_start = pos + 9;
        let content_end = find_matching_paren(&s[call_start..])?;
        let content = s[call_start..call_start + content_end].trim();
        Some((
            call_start + content_end + 1,
            build_update_replacement(content, false),
        ))
    });

    // NOTE: We intentionally do NOT strip `$.derived(...)` on the server.
    // Upstream svelte's server runtime exposes `$.derived(fn)` as a callable
    // that re-evaluates on each call (memoized only inside an SSR render
    // context), and `$.get(x)` reads above translate to `x()` for derived
    // names. Stripping the wrapper here would turn the derived into an
    // eagerly-evaluated snapshot, which silently freezes computed values
    // when their underlying state mutates — e.g. `isValid` in a form model
    // stays `false` even after the form is filled in.

    // Replace $.state(x) with just x (no signals on server)
    result = rewrite_calls(&result, b"$.state(", false, |s, pos| {
        let call_start = pos + 8;
        let content_end = find_matching_paren(&s[call_start..])?;
        let content = s[call_start..call_start + content_end].to_string();
        let trimmed = content.trim();
        let value = if trimmed.is_empty() {
            "void 0".to_string()
        } else {
            trimmed.to_string()
        };
        Some((call_start + content_end + 1, value))
    });

    result
}

/// Scan a client-style module body and return the set of variable names
/// declared as `let|const|var X = $.derived(...)` / `$.derived_safe_equal(...)`.
///
/// Used by `post_process_for_server` so reads via `$.get(X)` can be lowered
/// to `X()` (the server runtime treats a derived as a callable) while plain
/// state reads stay as `X`.
fn collect_derived_names(source: &str) -> rustc_hash::FxHashSet<String> {
    use rustc_hash::FxHashSet;
    let mut names: FxHashSet<String> = FxHashSet::default();
    let patterns: &[&[u8]] = &[b"$.derived(", b"$.derived_safe_equal("];
    let bytes = source.as_bytes();
    for pat in patterns {
        let finder = memmem::Finder::new(*pat);
        for pos in finder.find_iter(bytes) {
            // Walk left from `pos` to find a `let|const|var <name> = ` shape.
            // We accept an optional `$.tag(` wrap directly before the
            // `$.derived(` — in dev-mode-disabled SSR rsvelte never emits
            // `$.tag`, but be permissive in case future builds do.
            let mut left = pos;
            // Skip back through `$.tag(` if present.
            // (Not currently emitted in SSR; left in for future-proofing.)
            const TAG: &[u8] = b"$.tag(";
            if left >= TAG.len() && &bytes[left - TAG.len()..left] == TAG {
                left -= TAG.len();
            }
            // Skip whitespace + `=`.
            while left > 0 && bytes[left - 1].is_ascii_whitespace() {
                left -= 1;
            }
            if left == 0 || bytes[left - 1] != b'=' {
                continue;
            }
            left -= 1;
            while left > 0 && bytes[left - 1].is_ascii_whitespace() {
                left -= 1;
            }
            // Read identifier backwards.
            let id_end = left;
            while left > 0 {
                let b = bytes[left - 1];
                if b.is_ascii_alphanumeric() || b == b'_' || b == b'$' {
                    left -= 1;
                } else {
                    break;
                }
            }
            if left == id_end {
                continue;
            }
            // Require a preceding `let`, `const`, or `var` keyword (with
            // whitespace separator). Otherwise this is a reassignment or
            // a class field, which we don't track here.
            let mut kw_end = left;
            while kw_end > 0 && bytes[kw_end - 1].is_ascii_whitespace() {
                kw_end -= 1;
            }
            let is_decl = (kw_end >= 3
                && (&bytes[kw_end - 3..kw_end] == b"let" || &bytes[kw_end - 3..kw_end] == b"var"))
                || (kw_end >= 5 && &bytes[kw_end - 5..kw_end] == b"const");
            if !is_decl {
                continue;
            }
            // Word-boundary check on the left side of the keyword.
            let kw_len =
                if &bytes[kw_end - 3..kw_end] == b"let" || &bytes[kw_end - 3..kw_end] == b"var" {
                    3
                } else {
                    5
                };
            let kw_start = kw_end - kw_len;
            if kw_start > 0 {
                let prev = bytes[kw_start - 1];
                if prev.is_ascii_alphanumeric() || prev == b'_' || prev == b'$' {
                    continue;
                }
            }
            if let Ok(name) = std::str::from_utf8(&bytes[left..id_end]) {
                names.insert(name.to_string());
            }
        }
    }
    names
}

/// Scan a client-style class body and return the set of *private* field names
/// (without the leading `#`) declared as `#name = $.derived(...)` /
/// `$.derived_by(...)` / `$.derived_safe_equal(...)`.
///
/// On the server a private `$derived` field is callable (`this.#name()`), while
/// a `$state` field is a plain value (`this.#name` / `this.#name = v`). The
/// `$.get`/`$.set` member rewrites in [`post_process_for_server`] use this set
/// to pick the right form per field — previously every `this.#x` was treated as
/// callable, which turned plain `$state` field assignments into the broken
/// `this.#x(value)` call form (issue #907).
fn collect_derived_private_fields(source: &str) -> rustc_hash::FxHashSet<String> {
    let mut names = rustc_hash::FxHashSet::default();
    for line in source.lines() {
        let trimmed = line.trim_start();
        let Some(rest) = trimmed.strip_prefix('#') else {
            continue;
        };
        let Some(eq) = rest.find('=') else {
            continue;
        };
        let name = rest[..eq].trim();
        if name.is_empty()
            || !name
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$')
        {
            continue;
        }
        let value = rest[eq + 1..].trim_start();
        if value.starts_with("$.derived(")
            || value.starts_with("$.derived_by(")
            || value.starts_with("$.derived_safe_equal(")
        {
            names.insert(name.to_string());
        }
    }
    names
}

/// Extract the private-field name (without `#`) from a member expression like
/// `this.#current` → `current`. Returns `None` when the expression is not a
/// direct private-field access (e.g. `obj.prop`, or `this.#x.y` which accesses
/// a property *of* the field rather than the field itself).
fn private_field_name(member_expr: &str) -> Option<&str> {
    let hash = member_expr.rfind(".#")?;
    let rest = &member_expr[hash + 2..];
    let end = rest
        .find(|c: char| !(c.is_ascii_alphanumeric() || c == '_' || c == '$'))
        .unwrap_or(rest.len());
    if end == 0 || end != rest.len() {
        // Empty name, or trailing access (`this.#x.y`) — not a bare field read.
        None
    } else {
        Some(&rest[..end])
    }
}

/// Find the byte position of the first comma at bracket-depth 0, skipping
/// commas inside string / template literals and `//` / `/*` comments (H-032).
/// Without this, `$.set(name, 'Ada, Lovelace')` splits the value at the comma
/// inside the string literal.
fn find_first_comma(s: &str) -> Option<usize> {
    let bytes = s.as_bytes();
    let mut depth = 0i32;
    let mut i = 0;
    while i < bytes.len() {
        match bytes[i] {
            b'\'' | b'"' | b'`' => {
                i = skip_string_literal(bytes, i);
                continue;
            }
            b'/' if bytes.get(i + 1) == Some(&b'/') => {
                while i < bytes.len() && bytes[i] != b'\n' {
                    i += 1;
                }
                continue;
            }
            b'/' if bytes.get(i + 1) == Some(&b'*') => {
                i += 2;
                while i + 1 < bytes.len() && !(bytes[i] == b'*' && bytes[i + 1] == b'/') {
                    i += 1;
                }
                i = (i + 2).min(bytes.len());
                continue;
            }
            b'(' | b'[' | b'{' => depth += 1,
            b')' | b']' | b'}' => depth -= 1,
            b',' if depth == 0 => return Some(i),
            _ => {}
        }
        i += 1;
    }
    None
}

/// Build the server replacement for a `$.update(...)` / `$.update_pre(...)` call
/// body. `prefix` selects `++x`/`--x` (update_pre) vs `x++`/`x--` (update).
///
/// - `signal`            -> `signal++` / `++signal`
/// - `signal, -1`        -> `signal--` / `--signal`
/// - `signal, d`         -> `signal += d` (return value is unused in SSR)
///
/// The args are split on a string/comment-aware comma so the signal expression
/// is never truncated (H-031).
fn build_update_replacement(content: &str, prefix: bool) -> String {
    let (signal, delta) = match find_first_comma(content) {
        Some(comma) => (content[..comma].trim(), Some(content[comma + 1..].trim())),
        None => (content, None),
    };
    match delta {
        None => {
            if prefix {
                format!("++{signal}")
            } else {
                format!("{signal}++")
            }
        }
        Some("-1") => {
            if prefix {
                format!("--{signal}")
            } else {
                format!("{signal}--")
            }
        }
        Some(d) => format!("{signal} += {d}"),
    }
}

/// Skip a string / template literal whose opening quote byte is at
/// `bytes[start]`. Returns the index just past the closing quote, handling
/// backslash escapes and (for template literals) balanced `${ … }`
/// interpolations.
fn skip_string_literal(bytes: &[u8], start: usize) -> usize {
    let quote = bytes[start];
    let mut i = start + 1;
    while i < bytes.len() {
        let c = bytes[i];
        if c == b'\\' {
            i += 2;
            continue;
        }
        if quote == b'`' && c == b'$' && bytes.get(i + 1) == Some(&b'{') {
            i += 2;
            let mut brace_depth = 1u32;
            while i < bytes.len() && brace_depth > 0 {
                match bytes[i] {
                    b'{' => brace_depth += 1,
                    b'}' => brace_depth -= 1,
                    _ => {}
                }
                i += 1;
            }
            continue;
        }
        i += 1;
        if c == quote {
            break;
        }
    }
    i
}
