/* client.svelte.js generated by Svelte v5.57.1 */
import * as $ from 'svelte/internal/client';
import { DEV } from 'esm-env';
import { assets } from '#app/paths';
import { version } from '$app/env';

export const internal_page = new (class Page {
	#data = $.state({});

	get data() {
		return $.get(this.#data);
	}

	set data(value) {
		$.set(this.#data, value);
	}

	#form = $.state(null);

	get form() {
		return $.get(this.#form);
	}

	set form(value) {
		$.set(this.#form, value);
	}

	#error = $.state(null);

	get error() {
		return $.get(this.#error);
	}

	set error(value) {
		$.set(this.#error, value);
	}

	#params = $.state({});

	get params() {
		return $.get(this.#params);
	}

	set params(value) {
		$.set(this.#params, value);
	}

	#route = $.state({ id: null });

	get route() {
		return $.get(this.#route);
	}

	set route(value) {
		$.set(this.#route, value);
	}

	#shallow = $.state(null);

	get shallow() {
		return $.get(this.#shallow);
	}

	set shallow(value) {
		$.set(this.#shallow, value);
	}

	#state = $.state({});

	get state() {
		return $.get(this.#state);
	}

	set state(value) {
		$.set(this.#state, value);
	}

	#status = $.state(-1);

	get status() {
		return $.get(this.#status);
	}

	set status(value) {
		$.set(this.#status, value);
	}

	#url = $.state(new URL('a:'));

	get url() {
		return $.get(this.#url);
	}

	set url(value) {
		$.set(this.#url, value);
	}
})();

export function update_page(new_page) {
	Object.assign(internal_page, new_page);
}

/**
 * A read-only reactive object with information about the current page, serving several use cases:
 * - retrieving the combined `data` of all pages/layouts anywhere in your component tree (also see [loading data](https://svelte.dev/docs/kit/load))
 * - retrieving the current value of the `form` prop anywhere in your component tree (also see [form actions](https://svelte.dev/docs/kit/form-actions))
 * - retrieving the page state that was set through `goto` (also see [goto](https://svelte.dev/docs/kit/$app-navigation#goto) and [shallow routing](https://svelte.dev/docs/kit/shallow-routing))
 * - retrieving metadata such as the URL you're on, the current route and its parameters, the target of a shallow navigation, and whether or not there was an error
 *
 * ```svelte
 * <!--- file: +layout.svelte --->
 * <script>
 * 	import { page } from '$app/state';
 * </script>
 *
 * <p>Currently at {page.url.pathname}</p>
 *
 * {#if page.error}
 * 	<span class="red">Problem detected</span>
 * {:else}
 * 	<span class="small">All systems operational</span>
 * {/if}
 * ```
 *
 * Changes to `page` are available exclusively with runes. (The legacy reactivity syntax will not reflect any changes)
 *
 * ```svelte
 * <!--- file: +page.svelte --->
 * <script>
 * 	import { page } from '$app/state';
 * 	const id = $derived(page.params.id); // This will correctly update id for usage on this page
 * 	$: badId = page.params.id; // Do not use; will never update after initial load
 * </script>
 * ```
 *
 * On the server, values can only be read during rendering (in other words _not_ in e.g. `load` functions). In the browser, the values can be read at any time.
 *
 * @type {Page}
 */
export const page = {
	get data() {
		return internal_page.data;
	},

	get error() {
		return internal_page.error;
	},

	get form() {
		return internal_page.form;
	},

	get params() {
		return internal_page.params;
	},

	get route() {
		return internal_page.route;
	},

	get shallow() {
		return internal_page.shallow;
	},

	get state() {
		return internal_page.state;
	},

	get status() {
		return internal_page.status;
	},

	get url() {
		return internal_page.url;
	}
};

/** @type {Navigation | null} */
let navigation = $.state(null);

/**
 * @param {Navigation | null} value
 */
export function set_navigation(value) {
	$.set(navigation, value);
}

/**
 * A read-only object representing an in-progress navigation, with `from`, `to`, `type` and (if `type === 'popstate'`) `delta` properties.
 * Values are `null` when no navigation is occurring, or during server rendering.
 * @type {Navigation | { from: null, to: null, type: null, willUnload: null, delta: null, complete: null }}
 */
export const navigating = {
	get from() {
		return $.get(navigation) ? $.get(navigation).from : null;
	},

	get to() {
		return $.get(navigation) ? $.get(navigation).to : null;
	},

	get type() {
		return $.get(navigation) ? $.get(navigation).type : null;
	},

	get willUnload() {
		return $.get(navigation) ? $.get(navigation).willUnload : null;
	},

	// @ts-expect-error TODO not entirely sure what's going on here
	get delta() {
		return $.get(navigation)?.type === 'popstate' ? $.get(navigation).delta : null;
	},

	get complete() {
		return $.get(navigation) ? $.get(navigation).complete : null;
	}
};

const interval = __SVELTEKIT_APP_VERSION_POLL_INTERVAL__;

/** @type {number | undefined} */
let timeout;

/** @type {Promise<boolean> | undefined} */
let checking;

let _updated = $.state(false);

/**
 * A read-only reactive value that's initially `false`. SvelteKit checks for new versions on data, remote, and form action responses (via the `x-sveltekit-version` header), when the tab regains focus or becomes visible, and on a poll interval (see [`version.pollInterval`](https://svelte.dev/docs/kit/configuration#version)). `updated.current` is set to `true` when a new version is detected. `updated.check()` will force an immediate check, regardless of polling.
 * @type {{ get current(): boolean; check(): Promise<boolean>; }}
 */
export const updated = {
	get current() {
		return $.get(_updated);
	},

	async check() {
		if (DEV) return false;

		window.clearTimeout(timeout);

		if ($.get(_updated)) {
			return Promise.resolve(true);
		}

		return checking ??= (async () => {
			try {
				const res = await fetch(`${assets}/${__SVELTEKIT_APP_VERSION_FILE__}`, { headers: { 'cache-control': 'no-cache' } });

				if (!res.ok) {
					return false;
				}

				const data = await res.json();

				return $.set(_updated, $.get(_updated) || data.version !== version);
			} catch {
				return false;
			} finally {
				checking = undefined;

				if (interval && !$.get(_updated)) timeout = window.setTimeout(updated.check, interval);
			}
		})();
	}
};

if (!DEV && interval) {
	timeout = window.setTimeout(updated.check, interval);
}

/**
 * Mark `updated.current` as `true` if the given version differs from the one
 * the app was hydrated with. Called from the server response header path.
 * Does NOT reset the poll timer — unlike `check()`, this is a passive observation
 * from a single server instance's response, not an explicit version check. The
 * poll timer continues on its original schedule as a backstop. This is important
 * for platforms that implement skew protection, where `x-sveltekit-version`
 * may be out of date — in this case we still need to poll for `version.json`.
 * @param {string | null} new_version
 */
export function notify_version(new_version) {
	if (__SVELTEKIT_APP_VERSION_CHECKS_ENABLED__ && new_version) {
		$.set(_updated, $.get(_updated) || new_version !== version);
	}
}

/**
 * Used for testing
 */
export function reset_updated() {
	$.set(_updated, false);
}