//! Producing text: an output buffer that records where each piece came from, source map v3
//! encoding, reverse lookup (generated → original, for mapping diagnostics of a generated file back),
//! and a minimal edit list for tasks that patch the original text instead of reprinting it.

use crate::source::{LineIndex, Loc, Span};

/// `len > 0`: `len` bytes copied verbatim from `src`, so offsets inside map 1:1.
/// `len == 0`: a point mapping (the generated position corresponds to `src`).
#[derive(Clone, Copy, Debug)]
pub struct Mapping {
    pub generated: u32,
    pub src: u32,
    pub len: u32,
}

#[derive(Default)]
pub struct Emitter {
    pub out: String,
    pub mappings: Vec<Mapping>,
}

impl Emitter {
    pub fn new() -> Emitter {
        Emitter::default()
    }

    #[inline]
    pub fn push(&mut self, s: &str) {
        self.out.push_str(s);
    }

    #[inline]
    pub fn push_char(&mut self, c: char) {
        self.out.push(c);
    }

    /// Marks the current output position as corresponding to source offset `src`.
    #[inline]
    pub fn mark(&mut self, src: u32) {
        self.mappings.push(Mapping {
            generated: self.out.len() as u32,
            src,
            len: 0,
        });
    }

    /// Copies `span` of `source` verbatim, with a 1:1 mapping.
    pub fn copy(&mut self, source: &str, span: Span) {
        self.mappings.push(Mapping {
            generated: self.out.len() as u32,
            src: span.lo,
            len: span.len(),
        });
        self.out.push_str(span.text(source));
    }

    /// Pushes text that stands for `span` (e.g. a renamed identifier), mapped to its start.
    pub fn push_for(&mut self, s: &str, loc: Loc) {
        if let Some(span) = loc.span() {
            self.mark(span.lo);
        }
        self.out.push_str(s);
    }

    /// Generated byte offset → original byte offset.
    pub fn lookup(&self, pos: u32) -> Option<u32> {
        let i = self.mappings.partition_point(|m| m.generated <= pos);
        let m = self.mappings.get(i.checked_sub(1)?)?;
        Some(if pos < m.generated + m.len {
            m.src + (pos - m.generated)
        } else {
            m.src
        })
    }

    /// Encodes the mappings as a source map v3 JSON document.
    pub fn source_map(&self, source: &str, source_name: &str) -> String {
        let src_index = LineIndex::new(source);
        let gen_index = LineIndex::new(&self.out);
        let mut mappings = String::new();
        let (mut prev_gen_line, mut prev_gen_col, mut prev_src_line, mut prev_src_col) =
            (1u32, 0i64, 0i64, 0i64);
        let mut first_in_line = true;
        let mut sorted = self.mappings.clone();
        sorted.sort_by_key(|m| m.generated);
        for m in &sorted {
            let g = gen_index.line_col(&self.out, m.generated);
            let s = src_index.line_col(source, m.src);
            while prev_gen_line < g.line {
                mappings.push(';');
                prev_gen_line += 1;
                prev_gen_col = 0;
                first_in_line = true;
            }
            if !first_in_line {
                mappings.push(',');
            }
            first_in_line = false;
            vlq(&mut mappings, g.column as i64 - prev_gen_col);
            vlq(&mut mappings, 0);
            vlq(&mut mappings, (s.line as i64 - 1) - prev_src_line);
            vlq(&mut mappings, s.column as i64 - prev_src_col);
            prev_gen_col = g.column as i64;
            prev_src_line = s.line as i64 - 1;
            prev_src_col = s.column as i64;
        }
        let mut json = String::from("{\"version\":3,\"sources\":[");
        crate::json::write_str(&mut json, source_name);
        json.push_str("],\"names\":[],\"mappings\":");
        crate::json::write_str(&mut json, &mappings);
        json.push('}');
        json
    }
}

fn vlq(out: &mut String, value: i64) {
    const B64: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut v = if value < 0 {
        ((-value) << 1) | 1
    } else {
        value << 1
    } as u64;
    loop {
        let mut digit = (v & 31) as u8;
        v >>= 5;
        if v > 0 {
            digit |= 32;
        }
        out.push(B64[digit as usize] as char);
        if v == 0 {
            break;
        }
    }
}

/// Insertions and deletions against an original text, applied in one pass.
#[derive(Default)]
pub struct Edits {
    items: Vec<(u32, u32, String)>,
}

impl Edits {
    pub fn insert(&mut self, at: u32, text: impl Into<String>) {
        self.items.push((at, at, text.into()));
    }

    pub fn replace(&mut self, span: Span, text: impl Into<String>) {
        self.items.push((span.lo, span.hi, text.into()));
    }

    pub fn apply(mut self, src: &str) -> String {
        self.items.sort_by_key(|&(lo, hi, _)| (lo, hi));
        let mut out =
            String::with_capacity(src.len() + self.items.iter().map(|i| i.2.len()).sum::<usize>());
        let mut pos = 0usize;
        for (lo, hi, text) in self.items {
            out.push_str(&src[pos..lo as usize]);
            out.push_str(&text);
            pos = hi as usize;
        }
        out.push_str(&src[pos..]);
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn vlq_matches_the_spec_examples() {
        let mut s = String::new();
        for v in [0, 1, -1, 16, 1000] {
            vlq(&mut s, v);
            s.push(' ');
        }
        assert_eq!(s, "A C D gB w+B ");
    }

    #[test]
    fn lookup_maps_inside_copied_chunks() {
        let src = "let answer = 42;";
        let mut e = Emitter::new();
        e.push("// header\n");
        e.copy(src, Span::new(4, 10));
        assert_eq!(e.lookup(10), Some(4));
        assert_eq!(e.lookup(13), Some(7));
    }

    #[test]
    fn edits_apply_in_order() {
        let mut e = Edits::default();
        e.insert(4, ".h");
        e.replace(Span::new(0, 1), "X");
        assert_eq!(e.apply(".big {}"), "Xbig.h {}");
    }
}
