import 'svelte/internal/disclose-version';
import * as $ from 'svelte/internal/client';
import { tooltip } from '$lib/actions/tooltip.js';
import Icon from '$lib/components/global/Icon.svelte';
import { useClipboard } from '$lib/composables';
import { generatePTRName, generateCIDRPTRs } from '$lib/utils/reverse-dns.js';

var root = $.from_html(`<button><div class="example-header svelte-2ka88l"><div class="example-label svelte-2ka88l"> </div> <div> </div></div> <code class="example-input svelte-2ka88l"> </code> <div class="example-description svelte-2ka88l"> </div></button>`);
var root_1 = $.from_html(`<div class="stat-item svelte-2ka88l"><span class="stat-value svelte-2ka88l"> </span> <span class="stat-label svelte-2ka88l">IPv4</span></div>`);
var root_2 = $.from_html(`<div class="stat-item svelte-2ka88l"><span class="stat-value svelte-2ka88l"> </span> <span class="stat-label svelte-2ka88l">IPv6</span></div>`);
var root_3 = $.from_html(`<code class="svelte-2ka88l"> </code>`);
var root_4 = $.from_html(`<div class="table-row svelte-2ka88l"><div class="col-ip"><code> </code></div> <div class="col-ptr svelte-2ka88l"><code class="svelte-2ka88l"> </code> <button><!></button></div> <div class="col-zone-line svelte-2ka88l"><!> <button><!></button></div> <div class="col-type"><span> </span></div></div>`);
var root_5 = $.from_html(`<div class="table-truncated svelte-2ka88l"> </div>`);
var root_6 = $.from_html(`<div class="results-header svelte-2ka88l"><h3 class="svelte-2ka88l">PTR Records Generated</h3> <div class="summary-stats svelte-2ka88l"><div class="stat-item svelte-2ka88l"><span class="stat-value svelte-2ka88l"> </span> <span class="stat-label svelte-2ka88l">Total PTRs</span></div> <!> <!> <div class="stat-item svelte-2ka88l"><span class="stat-value svelte-2ka88l"> </span> <span class="stat-label svelte-2ka88l">Zones</span></div></div></div> <div class="ptr-records svelte-2ka88l"><h4 class="svelte-2ka88l"><!> PTR Records & Zone Lines</h4> <div class="records-table svelte-2ka88l"><div class="table-header svelte-2ka88l"><div class="col-ip">IP Address</div> <div class="col-ptr svelte-2ka88l">PTR Record Name</div> <div class="col-zone-line svelte-2ka88l">Zone File Line</div> <div class="col-type">Type</div></div> <!> <!></div></div>`, 1);
var root_7 = $.from_html(`<div class="error-result svelte-2ka88l"><!> <h4 class="svelte-2ka88l">Generation Error</h4> <p class="svelte-2ka88l"> </p> <div class="error-help svelte-2ka88l"><strong>Valid formats:</strong> <ul class="svelte-2ka88l"><li class="svelte-2ka88l">Single IPv4: 192.168.1.100</li> <li class="svelte-2ka88l">Single IPv6: 2001:db8::1</li> <li class="svelte-2ka88l">IPv4 CIDR: 192.168.1.0/24 (max /16)</li> <li class="svelte-2ka88l">IPv6 CIDR: 2001:db8::/64 (max /64)</li></ul></div></div>`);
var root_8 = $.from_html(`<div class="card results-card svelte-2ka88l"><!></div>`);

var root_9 = $.from_html(`<div class="card"><header class="card-header"><h1>Reverse PTR Generator</h1> <p>Convert IP addresses and CIDR blocks to PTR record names and zone file examples</p></header> <div class="card info-card svelte-2ka88l"><div class="overview-content svelte-2ka88l"><div class="overview-item svelte-2ka88l"><!> <div><strong class="svelte-2ka88l">Reverse DNS:</strong> PTR records map IP addresses back to hostnames using <code class="svelte-2ka88l">in-addr.arpa</code> (IPv4) and <code class="svelte-2ka88l">ip6.arpa</code> (IPv6) zones.</div></div> <div class="overview-item svelte-2ka88l"><!> <div><strong class="svelte-2ka88l">PTR Names:</strong> Generated by reversing IP octets/nibbles and appending the appropriate arpa domain.</div></div> <div class="overview-item svelte-2ka88l"><!> <div><strong class="svelte-2ka88l">Zone Lines:</strong> Ready-to-use DNS zone file entries with proper PTR record format.</div></div></div></div> <div class="card examples-card svelte-2ka88l"><details class="examples-details svelte-2ka88l"><summary class="examples-summary svelte-2ka88l"><!> <h3 class="svelte-2ka88l">Quick Examples</h3></summary> <div class="examples-grid svelte-2ka88l"></div></details></div> <div class="card input-card svelte-2ka88l"><div class="type-section svelte-2ka88l"><h3 class="type-label svelte-2ka88l">Input Type</h3> <div class="type-options svelte-2ka88l"><label class="type-option svelte-2ka88l"><input type="radio" class="svelte-2ka88l"/> <div class="type-content svelte-2ka88l"><!> <span>Single IP</span></div></label> <label class="type-option svelte-2ka88l"><input type="radio" class="svelte-2ka88l"/> <div class="type-content svelte-2ka88l"><!> <span>CIDR Block</span></div></label></div></div> <div class="input-group svelte-2ka88l"><label for="ip-input" class="svelte-2ka88l"><!> </label> <input id="ip-input" type="text" spellcheck="false"/></div></div> <!> <div class="education-card svelte-2ka88l"><div class="education-grid svelte-2ka88l"><div class="education-item info-panel svelte-2ka88l"><h4 class="svelte-2ka88l">PTR Record Format</h4> <p class="svelte-2ka88l">PTR records use the special <code class="svelte-2ka88l">in-addr.arpa</code> (IPv4) and <code class="svelte-2ka88l">ip6.arpa</code> (IPv6) domains. IP
          addresses are reversed: <code class="svelte-2ka88l">192.168.1.100</code> becomes <code class="svelte-2ka88l">100.1.168.192.in-addr.arpa</code>.</p></div> <div class="education-item info-panel svelte-2ka88l"><h4 class="svelte-2ka88l">Zone File Usage</h4> <p class="svelte-2ka88l">The generated zone file lines can be copied directly into your reverse DNS zone files. Remember to adjust the
          hostname targets to match your actual domain structure.</p></div> <div class="education-item info-panel svelte-2ka88l"><h4 class="svelte-2ka88l">IPv6 Nibbles</h4> <p class="svelte-2ka88l">IPv6 PTR records use individual hex digits (nibbles) reversed. Each character becomes a separate label: <code class="svelte-2ka88l">2001:db8::1</code> becomes a very long <code class="svelte-2ka88l">ip6.arpa</code> name.</p></div> <div class="education-item info-panel svelte-2ka88l"><h4 class="svelte-2ka88l">Best Practices</h4> <p class="svelte-2ka88l">Ensure PTR records have corresponding A/AAAA records for proper forward-reverse DNS consistency. Use
          descriptive hostnames that include IP information for easier network management.</p></div></div></div></div>`);

export default function ReversePTRGenerator($$anchor, $$props) {
	$.push($$props, true);

	const binding_group = [];
	let inputValue = $.state('192.168.1.100');
	let inputType = $.state('single');
	let results = $.state(null);
	const clipboard = useClipboard();
	let selectedExample = $.state(null);
	let _userModified = $.state(false);

	const examples = [
		{
			label: 'Single IPv4',
			input: '192.168.1.100',
			type: 'single',
			description: 'Generate PTR for single IPv4 address'
		},

		{
			label: 'Single IPv6',
			input: '2001:db8::1',
			type: 'single',
			description: 'Generate PTR for single IPv6 address'
		},

		{
			label: 'IPv4 /28 Block',
			input: '192.168.1.16/28',
			type: 'cidr',
			description: 'Generate PTRs for /28 subnet (16 addresses)'
		},

		{
			label: 'IPv4 /24 Network',
			input: '10.0.0.0/24',
			type: 'cidr',
			description: 'Generate PTRs for entire /24 network'
		},

		{
			label: 'IPv6 /64 Network',
			input: '2001:db8:1000::/64',
			type: 'cidr',
			description: 'Generate IPv6 PTR examples for /64'
		}
	];

	function loadExample(example) {
		$.set(inputValue, example.input, true);
		$.set(inputType, example.type, true);
		$.set(selectedExample, example.label, true);
		$.set(_userModified, false);
		generatePTRs();
	}

	function generatePTRs() {
		if (!$.get(inputValue).trim()) {
			$.set(results, null);

			return;
		}

		try {
			const trimmed = $.get(inputValue).trim();
			let entries = [];

			if ($.get(inputType) === 'single') {
				// Single IP address
				const record = generatePTRName(trimmed);

				if (record) {
					entries.push(record);
				} else {
					throw new Error('Invalid IP address format');
				}
			} else {
				// CIDR notation
				entries = generateCIDRPTRs(trimmed, 1000);
			}

			// Generate summary
			const summary = {
				totalEntries: entries.length,
				ipv4Entries: entries.filter((e) => e.type === 'IPv4').length,
				ipv6Entries: entries.filter((e) => e.type === 'IPv6').length,
				uniqueZones: [...new Set(entries.map((e) => e.zone))].length
			};

			$.set(results, { success: true, entries, summary }, true);
		} catch(error) {
			$.set(
				results,
				{
					success: false,
					error: error instanceof Error ? error.message : 'Unknown error occurred',
					entries: [],
					summary: {
						totalEntries: 0,
						ipv4Entries: 0,
						ipv6Entries: 0,
						uniqueZones: 0
					}
				},
				true
			);
		}
	}

	function handleInputChange() {
		$.set(_userModified, true);
		$.set(selectedExample, null);
		generatePTRs();
	}

	function handleTypeChange() {
		$.set(_userModified, true);
		$.set(selectedExample, null);
		generatePTRs();
	}

	// Generate on component load
	generatePTRs();

	var div = root_9();
	var div_1 = $.sibling($.child(div), 2);
	var div_2 = $.child(div_1);
	var div_3 = $.child(div_2);
	var node = $.child(div_3);

	Icon(node, { name: 'rotate', size: 'sm' });
	$.next(2);
	$.reset(div_3);

	var div_4 = $.sibling(div_3, 2);
	var node_1 = $.child(div_4);

	Icon(node_1, { name: 'target', size: 'sm' });
	$.next(2);
	$.reset(div_4);

	var div_5 = $.sibling(div_4, 2);
	var node_2 = $.child(div_5);

	Icon(node_2, { name: 'file', size: 'sm' });
	$.next(2);
	$.reset(div_5);
	$.reset(div_2);
	$.reset(div_1);

	var div_6 = $.sibling(div_1, 2);
	var details = $.child(div_6);
	var summary_1 = $.child(details);
	var node_3 = $.child(summary_1);

	Icon(node_3, { name: 'chevron-right', size: 'sm' });
	$.next(2);
	$.reset(summary_1);

	var div_7 = $.sibling(summary_1, 2);

	$.each(div_7, 21, () => examples, (example) => example.label, ($$anchor, example) => {
		var button = root();
		var div_8 = $.child(button);
		var div_9 = $.child(div_8);
		var text = $.only_child(div_9, true);
		var div_10 = $.sibling(div_9, 2);
		var text_1 = $.only_child(div_10, true);

		$.reset(div_8);

		var code = $.sibling(div_8, 2);
		var text_2 = $.only_child(code, true);
		var div_11 = $.sibling(code, 2);
		var text_3 = $.only_child(div_11, true);

		$.reset(button);

		$.template_effect(() => {
			$.set_class(button, 1, `example-card ${$.get(selectedExample) === $.get(example).label ? 'active' : ''}`, 'svelte-2ka88l');
			$.set_text(text, $.get(example).label);
			$.set_class(div_10, 1, `example-type ${$.get(example).type ?? ''}`, 'svelte-2ka88l');
			$.set_text(text_1, $.get(example).type === 'single' ? 'Single IP' : 'CIDR Block');
			$.set_text(text_2, $.get(example).input);
			$.set_text(text_3, $.get(example).description);
		});

		$.delegated('click', button, () => loadExample($.get(example)));
		$.append($$anchor, button);
	});

	$.reset(div_7);
	$.reset(details);
	$.reset(div_6);

	var div_12 = $.sibling(div_6, 2);
	var div_13 = $.child(div_12);
	var div_14 = $.sibling($.child(div_13), 2);
	var label = $.child(div_14);
	var input = $.child(label);

	$.remove_input_defaults(input);
	input.value = input.__value = 'single';

	var div_15 = $.sibling(input, 2);
	var node_4 = $.child(div_15);

	Icon(node_4, { name: 'target', size: 'sm' });
	$.next(2);
	$.reset(div_15);
	$.reset(label);

	var label_1 = $.sibling(label, 2);
	var input_1 = $.child(label_1);

	$.remove_input_defaults(input_1);
	input_1.value = input_1.__value = 'cidr';

	var div_16 = $.sibling(input_1, 2);
	var node_5 = $.child(div_16);

	Icon(node_5, { name: 'network', size: 'sm' });
	$.next(2);
	$.reset(div_16);
	$.reset(label_1);
	$.reset(div_14);
	$.reset(div_13);

	var div_17 = $.sibling(div_13, 2);
	var label_2 = $.child(div_17);
	var node_6 = $.child(label_2);

	{
		let $0 = $.derived(() => $.get(inputType) === 'single' ? 'target' : 'network');

		Icon(node_6, {
			get name() {
				return $.get($0);
			},
			size: 'sm'
		});
	}

	var text_4 = $.sibling(node_6);

	$.reset(label_2);

	$.action(label_2, ($$node, $$action_arg) => tooltip?.($$node, $$action_arg), () => $.get(inputType) === 'single'
		? 'Enter a single IPv4 or IPv6 address'
		: 'Enter an IPv4 or IPv6 CIDR block (e.g., 192.168.1.0/24)');

	var input_2 = $.sibling(label_2, 2);

	$.remove_input_defaults(input_2);
	$.reset(div_17);
	$.reset(div_12);

	var node_7 = $.sibling(div_12, 2);

	{
		var consequent_4 = ($$anchor) => {
			var div_18 = root_8();
			var node_8 = $.child(div_18);

			{
				var consequent_3 = ($$anchor) => {
					var fragment = root_6();
					var div_19 = $.first_child(fragment);
					var div_20 = $.sibling($.child(div_19), 2);
					var div_21 = $.child(div_20);
					var span = $.child(div_21);
					var text_5 = $.only_child(span, true);

					$.next(2);
					$.reset(div_21);

					var node_9 = $.sibling(div_21, 2);

					{
						var consequent = ($$anchor) => {
							var div_22 = root_1();
							var span_1 = $.child(div_22);
							var text_6 = $.only_child(span_1, true);

							$.next(2);
							$.reset(div_22);
							$.template_effect(() => $.set_text(text_6, $.get(results).summary.ipv4Entries));
							$.append($$anchor, div_22);
						};

						$.if(node_9, ($$render) => {
							if ($.get(results).summary.ipv4Entries > 0) $$render(consequent);
						});
					}

					var node_10 = $.sibling(node_9, 2);

					{
						var consequent_1 = ($$anchor) => {
							var div_23 = root_2();
							var span_2 = $.child(div_23);
							var text_7 = $.only_child(span_2, true);

							$.next(2);
							$.reset(div_23);
							$.template_effect(() => $.set_text(text_7, $.get(results).summary.ipv6Entries));
							$.append($$anchor, div_23);
						};

						$.if(node_10, ($$render) => {
							if ($.get(results).summary.ipv6Entries > 0) $$render(consequent_1);
						});
					}

					var div_24 = $.sibling(node_10, 2);
					var span_3 = $.child(div_24);
					var text_8 = $.only_child(span_3, true);

					$.next(2);
					$.reset(div_24);
					$.reset(div_20);
					$.reset(div_19);

					var div_25 = $.sibling(div_19, 2);
					var h4 = $.child(div_25);
					var node_11 = $.child(h4);

					Icon(node_11, { name: 'list', size: 'sm' });
					$.next();
					$.reset(h4);

					var div_26 = $.sibling(h4, 2);
					var node_12 = $.sibling($.child(div_26), 2);

					$.each(node_12, 17, () => $.get(results).entries.slice(0, 100), (entry) => `${entry.ip}-${entry.ptrName}`, ($$anchor, entry) => {
						var div_27 = root_4();
						var div_28 = $.child(div_27);
						var code_1 = $.child(div_28);
						var text_9 = $.only_child(code_1, true);

						$.reset(div_28);

						var div_29 = $.sibling(div_28, 2);
						var code_2 = $.child(div_29);
						var text_10 = $.only_child(code_2, true);
						var button_1 = $.sibling(code_2, 2);
						var node_13 = $.child(button_1);

						{
							let $0 = $.derived(() => clipboard.isCopied(`ptr-${$.get(entry).ip}`) ? 'check' : 'copy');

							Icon(node_13, {
								get name() {
									return $.get($0);
								},
								size: 'sm'
							});
						}

						$.reset(button_1);
						$.reset(div_29);

						var div_30 = $.sibling(div_29, 2);

						{
							const zoneLine = ($$anchor) => {
								const recordName = $.derived(() => $.get(entry).ptrName.replace(`.${$.get(entry).zone}`, '').replace(/\.$/, ''));
								const hostname = $.derived(() => `host-${$.get(entry).ip.replace(/[:.]/g, '-')}.example.com.`);
								var code_3 = root_3();
								var text_11 = $.only_child(code_3);

								$.template_effect(() => $.set_text(text_11, `${$.get(recordName) ?? ''} IN PTR ${$.get(hostname) ?? ''}`));
								$.append($$anchor, code_3);
							};

							var node_14 = $.child(div_30);

							zoneLine(node_14);

							var button_2 = $.sibling(node_14, 2);
							var node_15 = $.child(button_2);

							{
								let $0 = $.derived(() => clipboard.isCopied(`zone-${$.get(entry).ip}`) ? 'check' : 'copy');

								Icon(node_15, {
									get name() {
										return $.get($0);
									},
									size: 'sm'
								});
							}

							$.reset(button_2);
							$.reset(div_30);

							$.template_effect(($0, $1) => $.set_class(button_2, 1, `copy-button ${$1 ?? ''}`, 'svelte-2ka88l'), [
								() => clipboard.isCopied(`ptr-${$.get(entry).ip}`) ? 'copied' : '',
								() => clipboard.isCopied(`zone-${$.get(entry).ip}`) ? 'copied' : ''
							]);

							$.delegated('click', button_2, () => {
								const recordName = $.get(entry).ptrName.replace(`.${$.get(entry).zone}`, '').replace(/\.$/, '');
								const hostname = `host-${$.get(entry).ip.replace(/[:.]/g, '-')}.example.com.`;

								clipboard.copy(`${recordName}    IN    PTR    ${hostname}`, `zone-${$.get(entry).ip}`);
							});
						}

						var div_31 = $.sibling(div_30, 2);
						var span_4 = $.child(div_31);
						var text_12 = $.only_child(span_4, true);

						$.reset(div_31);
						$.reset(div_27);

						$.template_effect(
							($0, $1, $2) => {
								$.set_text(text_9, $.get(entry).ip);
								$.set_text(text_10, $.get(entry).ptrName);
								$.set_class(button_1, 1, `copy-button ${$0 ?? ''}`, 'svelte-2ka88l');
								$.set_class(span_4, 1, `type-badge ${$2 ?? ''}`, 'svelte-2ka88l');
								$.set_text(text_12, $.get(entry).type);
							},
							[
								() => clipboard.isCopied(`ptr-${$.get(entry).ip}`) ? 'copied' : '',
								() => clipboard.isCopied(`zone-${$.get(entry).ip}`) ? 'copied' : '',
								() => $.get(entry).type.toLowerCase()
							]
						);

						$.delegated('click', button_1, () => clipboard.copy($.get(entry).ptrName, `ptr-${$.get(entry).ip}`));
						$.append($$anchor, div_27);
					});

					var node_16 = $.sibling(node_12, 2);

					{
						var consequent_2 = ($$anchor) => {
							var div_32 = root_5();
							var text_13 = $.only_child(div_32);

							$.template_effect(() => $.set_text(text_13, `... and ${$.get(results).entries.length - 100} more records`));
							$.append($$anchor, div_32);
						};

						$.if(node_16, ($$render) => {
							if ($.get(results).entries.length > 100) $$render(consequent_2);
						});
					}

					$.reset(div_26);
					$.reset(div_25);

					$.template_effect(() => {
						$.set_text(text_5, $.get(results).summary.totalEntries);
						$.set_text(text_8, $.get(results).summary.uniqueZones);
					});

					$.append($$anchor, fragment);
				};

				var alternate = ($$anchor) => {
					var div_33 = root_7();
					var node_17 = $.child(div_33);

					Icon(node_17, { name: 'alert-triangle', size: 'lg' });

					var p = $.sibling(node_17, 4);
					var text_14 = $.only_child(p, true);

					$.next(2);
					$.reset(div_33);
					$.template_effect(() => $.set_text(text_14, $.get(results).error));
					$.append($$anchor, div_33);
				};

				$.if(node_8, ($$render) => {
					if ($.get(results).success) $$render(consequent_3); else $$render(alternate, -1);
				});
			}

			$.reset(div_18);
			$.append($$anchor, div_18);
		};

		var d = $.derived(() => $.get(results) && $.get(inputValue).trim());

		$.if(node_7, ($$render) => {
			if ($.get(d)) $$render(consequent_4);
		});
	}

	$.next(2);
	$.reset(div);

	$.template_effect(() => {
		$.set_text(text_4, ` ${$.get(inputType) === 'single' ? 'IP Address' : 'CIDR Block'}`);

		$.set_attribute(input_2, 'placeholder', $.get(inputType) === 'single'
			? '192.168.1.100 or 2001:db8::1'
			: '192.168.1.0/24 or 2001:db8::/64');

		$.set_class(
			input_2,
			1,
			`ip-input ${$.get(results)?.success === true
				? 'valid'
				: $.get(results)?.success === false ? 'invalid' : ''}`,
			'svelte-2ka88l'
		);
	});

	$.delegated('change', input, handleTypeChange);
	$.bind_group(binding_group, [], input, () => $.get(inputType), ($$value) => $.set(inputType, $$value));
	$.delegated('change', input_1, handleTypeChange);
	$.bind_group(binding_group, [], input_1, () => $.get(inputType), ($$value) => $.set(inputType, $$value));
	$.delegated('input', input_2, handleInputChange);
	$.bind_value(input_2, () => $.get(inputValue), ($$value) => $.set(inputValue, $$value));
	$.append($$anchor, div);
	$.pop();
}

$.delegate(['click', 'change', 'input']);