//! Stable, in-process building blocks for Svelte-aware toolchains.
//!
//! The facade owns no filesystem, cache, scheduler, or thread pool. Embedders
//! keep those policies and cache the returned immutable DTOs themselves.

use std::ops::Range;

use crate::{
    CompileError, CompileOptions, CompileResult, GenerateMode,
    ast::{AttributeValue, AttributeValuePart, Root, ScriptContext},
    compiler::{
        ComponentAnalysis,
        phases::{phase2_analyze::BindingKind, phase3_transform::transform_component},
    },
    svelte2tsx::{Svelte2TsxError, Svelte2TsxOptions, svelte2tsx},
};

/// Version of the public toolchain facade.
pub const TOOLCHAIN_ABI_VERSION: u32 = 1;
/// Version of the reusable runtime preparation contract.
pub const RUNTIME_ABI_VERSION: u32 = 1;
/// Version of the IDE projection artifact contract.
pub const PROJECTION_ABI_VERSION: u32 = 1;
/// Version of the normalized facts contract.
pub const FACTS_ABI_VERSION: u32 = 2;

const SVELTE_VERSION: &str = match option_env!("SVELTE_VERSION") {
    Some(version) => version,
    None => "unknown",
};

/// Versions that participate in an embedder's cache namespace.
///
/// This does not fingerprint source or options. In particular, function-valued
/// compile options require caller-owned stable identities to be cacheable.
#[non_exhaustive]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct EngineFingerprint {
    /// rsvelte crate version.
    pub rsvelte_version: &'static str,
    /// Svelte reference version compiled into rsvelte.
    pub svelte_version: &'static str,
    /// Public facade ABI version.
    pub toolchain_abi: u32,
    /// Runtime preparation and generation ABI version.
    pub runtime_abi: u32,
    /// IDE projection ABI version.
    pub projection_abi: u32,
    /// Normalized facts ABI version.
    pub facts_abi: u32,
}

/// A half-open UTF-8 byte range in the original or generated source.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash)]
pub struct ByteRange {
    pub start: u32,
    pub end: u32,
}

impl ByteRange {
    #[must_use]
    pub const fn new(start: u32, end: u32) -> Self {
        Self { start, end }
    }

    #[must_use]
    pub const fn len(self) -> u32 {
        self.end.saturating_sub(self.start)
    }

    #[must_use]
    pub const fn is_empty(self) -> bool {
        self.start >= self.end
    }

    #[must_use]
    pub const fn contains(self, offset: u32) -> bool {
        offset >= self.start && offset < self.end
    }

    #[must_use]
    pub const fn contains_range(self, range: Self) -> bool {
        range.start >= self.start && range.end <= self.end && range.start <= range.end
    }

    #[must_use]
    pub const fn as_usize_range(self) -> Range<usize> {
        self.start as usize..self.end as usize
    }
}

/// One byte-exact, length-preserving mapping segment.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ExactMapping {
    pub source: ByteRange,
    pub generated: ByteRange,
}

/// Byte-exact mappings for verbatim source chunks in an IDE projection.
///
/// Synthesized or rewritten output has no segment. Source ranges can have
/// multiple generated candidates when a chunk is moved or duplicated.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ProjectionMap {
    segments: Vec<ExactMapping>,
}

impl ProjectionMap {
    #[must_use]
    pub fn new(segments: Vec<ExactMapping>) -> Self {
        debug_assert!(
            segments
                .iter()
                .all(|segment| segment.source.len() == segment.generated.len())
        );
        Self { segments }
    }

    #[must_use]
    pub fn segments(&self) -> &[ExactMapping] {
        &self.segments
    }

    /// Map one original byte offset to every exact generated candidate.
    #[must_use]
    pub fn source_to_generated(&self, offset: u32) -> Vec<u32> {
        self.segments
            .iter()
            .filter(|segment| segment.source.contains(offset))
            .map(|segment| segment.generated.start + offset - segment.source.start)
            .collect()
    }

    /// Map one generated byte offset back to its exact original offset.
    #[must_use]
    pub fn generated_to_source(&self, offset: u32) -> Option<u32> {
        self.segments
            .iter()
            .find(|segment| segment.generated.contains(offset))
            .map(|segment| segment.source.start + offset - segment.generated.start)
    }

    /// Map an original range to every segment that contains it completely.
    #[must_use]
    pub fn source_range_to_generated(&self, range: ByteRange) -> Vec<ByteRange> {
        self.segments
            .iter()
            .filter(|segment| segment.source.contains_range(range))
            .map(|segment| {
                let start = segment.generated.start + range.start - segment.source.start;
                ByteRange::new(start, start + range.len())
            })
            .collect()
    }

    /// Map a generated range when one exact segment contains it completely.
    #[must_use]
    pub fn generated_range_to_source(&self, range: ByteRange) -> Option<ByteRange> {
        self.segments
            .iter()
            .find(|segment| segment.generated.contains_range(range))
            .map(|segment| {
                let start = segment.source.start + range.start - segment.generated.start;
                ByteRange::new(start, start + range.len())
            })
    }
}

/// Runtime output target for a prepared component.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum RuntimeTarget {
    Client,
    Server,
}

impl From<RuntimeTarget> for GenerateMode {
    fn from(target: RuntimeTarget) -> Self {
        match target {
            RuntimeTarget::Client => Self::Client,
            RuntimeTarget::Server => Self::Server,
        }
    }
}

/// The role of a component script block.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ScriptKind {
    Instance,
    Module,
}

/// Source regions and dialect for one script block.
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ScriptRegion {
    pub kind: ScriptKind,
    pub tag: ByteRange,
    pub content: ByteRange,
    pub typescript: bool,
}

/// Source regions for the component style block.
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StyleRegion {
    pub tag: ByteRange,
    pub content: ByteRange,
}

/// A syntactically declared component prop.
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ComponentProp {
    pub name: String,
    pub local_name: String,
    pub declaration: Option<ByteRange>,
    pub bindable: bool,
}

/// A component export discovered during analysis.
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ComponentExport {
    pub name: String,
    pub local_name: String,
}

/// Immutable, cross-file-resolution-free facts from compiler analysis.
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ComponentFacts {
    pub runes: bool,
    /// Scope class frozen by component analysis, when a style block exists.
    pub css_scope_hash: Option<String>,
    /// Whether legacy `$$props` is referenced.
    pub uses_legacy_props: bool,
    /// Whether legacy `$$restProps` is referenced.
    pub uses_legacy_rest_props: bool,
    /// Whether legacy `$$slots` is referenced.
    pub uses_legacy_slots: bool,
    pub uses_render_tags: bool,
    pub uses_component_bindings: bool,
    pub scripts: Vec<ScriptRegion>,
    pub style: Option<StyleRegion>,
    pub props: Vec<ComponentProp>,
    pub exports: Vec<ComponentExport>,
}

impl ComponentFacts {
    fn collect(source: &str, ast: &Root<'_>, analysis: &ComponentAnalysis, runes: bool) -> Self {
        let mut scripts = [ast.instance.as_deref(), ast.module.as_deref()]
            .into_iter()
            .flatten()
            .map(|script| ScriptRegion {
                kind: match script.context {
                    ScriptContext::Default => ScriptKind::Instance,
                    ScriptContext::Module => ScriptKind::Module,
                },
                tag: ByteRange::new(script.start, script.end),
                content: ByteRange::new(
                    script.content_offset,
                    source[script.content_offset as usize..script.end as usize]
                        .rfind("</script")
                        .map_or(script.end, |offset| script.content_offset + offset as u32),
                ),
                typescript: script.attributes.iter().any(|attribute| {
                    attribute.name == "lang"
                        && matches!(
                            &attribute.value,
                            AttributeValue::Sequence(parts)
                                if matches!(
                                    parts.first(),
                                    Some(AttributeValuePart::Text(text))
                                        if text.data == "ts" || text.data == "typescript"
                                )
                        )
                }),
            })
            .collect::<Vec<_>>();
        scripts.sort_by_key(|script| script.tag.start);

        let style = ast.css.as_ref().map(|style| StyleRegion {
            tag: ByteRange::new(style.start, style.end),
            content: ByteRange::new(style.content.start, style.content.end),
        });

        let mut props = analysis
            .root
            .bindings
            .iter()
            .filter(|binding| matches!(binding.kind, BindingKind::Prop | BindingKind::BindableProp))
            .map(|binding| ComponentProp {
                name: binding
                    .prop_alias
                    .clone()
                    .unwrap_or_else(|| binding.name.clone()),
                local_name: binding.name.clone(),
                declaration: binding.declaration_start.map(|start| {
                    ByteRange::new(start, start.saturating_add(binding.name.len() as u32))
                }),
                bindable: binding.kind == BindingKind::BindableProp,
            })
            .collect::<Vec<_>>();
        props.sort_by_key(|prop| prop.declaration.map_or(u32::MAX, |range| range.start));

        Self {
            runes,
            css_scope_hash: style.as_ref().map(|_| analysis.css.hash.clone()),
            uses_legacy_props: analysis.uses_props,
            uses_legacy_rest_props: analysis.uses_rest_props,
            uses_legacy_slots: analysis.uses_slots,
            uses_render_tags: analysis.uses_render_tags,
            uses_component_bindings: analysis.uses_component_bindings,
            scripts,
            style,
            props,
            exports: analysis
                .exports
                .iter()
                .map(|export| ComponentExport {
                    name: export.alias.clone().unwrap_or_else(|| export.name.clone()),
                    local_name: export.name.clone(),
                })
                .collect(),
        }
    }
}

/// A normalized prop fact from the IDE projection pass.
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProjectionProp {
    pub name: String,
    pub local_name: String,
    pub optional: bool,
    pub bindable: bool,
    pub type_annotation: Option<String>,
}

/// A normalized named export fact from the IDE projection pass.
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProjectionExport {
    pub name: String,
    pub local_name: String,
    pub type_annotation: Option<String>,
}

/// Immutable syntactic facts collected while producing the IDE projection.
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProjectionFacts {
    pub runes: bool,
    pub props: Vec<ProjectionProp>,
    pub exports: Vec<ProjectionExport>,
    pub events: Vec<String>,
}

/// Generated IDE code, its standard source map, exact mappings, and facts.
#[non_exhaustive]
#[derive(Debug, Clone)]
pub struct ProjectionArtifact {
    pub code: String,
    pub source_map: Option<String>,
    /// Exact mappings are unavailable when a configured post-pass rewrites
    /// generated text after the projection chunk graph is finalized.
    pub exact_mappings: Option<ProjectionMap>,
    pub facts: ProjectionFacts,
}

/// A parsed and analyzed component whose runtime options are frozen.
///
/// The component borrows its source, is movable between workers, and is
/// intentionally not `Sync`. Emission requires `&mut self`, while the AST and
/// analysis remain private. Client and server output can be generated in any
/// order without repeating parse or analysis.
pub struct PreparedComponent<'source> {
    source: &'source str,
    ast: Box<Root<'source>>,
    analysis: Box<ComponentAnalysis>,
    options: CompileOptions,
    runes_mode: bool,
    facts: ComponentFacts,
}

impl std::fmt::Debug for PreparedComponent<'_> {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("PreparedComponent")
            .field("source_len", &self.source.len())
            .field("options", &self.options)
            .field("runes_mode", &self.runes_mode)
            .field("facts", &self.facts)
            .finish_non_exhaustive()
    }
}

impl<'source> PreparedComponent<'source> {
    pub(crate) fn new(source: &'source str, options: CompileOptions) -> Result<Self, CompileError> {
        let mut ast = Box::new(crate::compiler::parse_component(source)?);
        let (options, analysis, runes_mode, facts) = {
            // SAFETY: the guard is dropped before `ast` moves into the result.
            let _arena_guard =
                unsafe { crate::ast::arena::SerializeArenaGuard::new(&ast.arena as *const _) };
            let (options, analysis, runes_mode) =
                crate::compiler::prepare_and_analyze(&mut ast, source, options)?;
            let facts = ComponentFacts::collect(source, &ast, &analysis, runes_mode);
            (options, Box::new(analysis), runes_mode, facts)
        };

        Ok(Self {
            source,
            ast,
            analysis,
            options,
            runes_mode,
            facts,
        })
    }

    #[must_use]
    pub fn facts(&self) -> &ComponentFacts {
        &self.facts
    }

    pub fn compile(&mut self, target: RuntimeTarget) -> Result<CompileResult, CompileError> {
        self.compile_mode(target.into())
    }

    pub fn compile_both(&mut self) -> Result<(CompileResult, CompileResult), CompileError> {
        let client = self.compile(RuntimeTarget::Client)?;
        let server = self.compile(RuntimeTarget::Server)?;
        Ok((client, server))
    }

    pub(crate) fn compile_mode(
        &mut self,
        generate: GenerateMode,
    ) -> Result<CompileResult, CompileError> {
        // SAFETY: `self.ast` cannot move for the duration of this mutable borrow.
        let _arena_guard =
            unsafe { crate::ast::arena::SerializeArenaGuard::new(&self.ast.arena as *const _) };
        let mut options = self.options.clone();
        options.generate = generate;
        let transform_result =
            transform_component(&self.analysis, &self.ast, self.source, &options)
                .map_err(CompileError::from)?;
        Ok(crate::compiler::finalize_compile_result(
            transform_result,
            &self.analysis,
            self.source,
            &options,
            self.runes_mode,
        ))
    }
}

/// Stateless entry point for compiler and IDE products.
#[derive(Debug, Default, Clone, Copy)]
pub struct Toolchain;

impl Toolchain {
    #[must_use]
    pub const fn new() -> Self {
        Self
    }

    #[must_use]
    pub const fn fingerprint(self) -> EngineFingerprint {
        EngineFingerprint {
            rsvelte_version: env!("CARGO_PKG_VERSION"),
            svelte_version: SVELTE_VERSION,
            toolchain_abi: TOOLCHAIN_ABI_VERSION,
            runtime_abi: RUNTIME_ABI_VERSION,
            projection_abi: PROJECTION_ABI_VERSION,
            facts_abi: FACTS_ABI_VERSION,
        }
    }

    pub fn prepare<'source>(
        self,
        source: &'source str,
        options: CompileOptions,
    ) -> Result<PreparedComponent<'source>, CompileError> {
        PreparedComponent::new(source, options)
    }

    pub fn project(
        self,
        source: &str,
        options: Svelte2TsxOptions,
    ) -> Result<ProjectionArtifact, Svelte2TsxError> {
        let has_postprocess = options.rewrite_external_imports.is_some();
        let result = svelte2tsx(source, options)?;
        let bindable_props = &result.exported_names.bindable_props;
        let mut props = Vec::new();
        let mut exports = Vec::new();
        for name in result.exported_names.get_all_names() {
            let Some(info) = result.exported_names.get(name) else {
                continue;
            };
            if info.is_prop {
                props.push(ProjectionProp {
                    name: name.to_string(),
                    local_name: info.local_name.clone(),
                    optional: info.has_default,
                    bindable: bindable_props.iter().any(|bindable| bindable == name),
                    type_annotation: info.type_annotation.clone(),
                });
            }
            if (!info.is_prop || info.is_named_export)
                && (!info.is_let || (result.exported_names.is_runes_mode() && info.is_named_export))
            {
                exports.push(ProjectionExport {
                    name: name.to_string(),
                    local_name: info.local_name.clone(),
                    type_annotation: info.type_annotation.clone(),
                });
            }
        }
        let facts = ProjectionFacts {
            runes: result.exported_names.is_runes_mode(),
            props,
            exports,
            events: result
                .events
                .get_event_names()
                .into_iter()
                .map(str::to_string)
                .collect(),
        };
        let exact_mappings = (!has_postprocess).then(|| {
            ProjectionMap::new(
                result
                    .forward_map
                    .iter()
                    .map(
                        |&(source_start, source_end, generated_start)| ExactMapping {
                            source: ByteRange::new(source_start, source_end),
                            generated: ByteRange::new(
                                generated_start,
                                generated_start + source_end - source_start,
                            ),
                        },
                    )
                    .collect(),
            )
        });

        Ok(ProjectionArtifact {
            code: result.code,
            source_map: result.map,
            exact_mappings,
            facts,
        })
    }
}
