[package]
name = "rsvelte_bench"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
rsvelte_core = { path = "../rsvelte_core" }
rsvelte_esrap = { path = "../rsvelte_esrap" }

[dev-dependencies]
criterion = { version = "5.0.0", features = ["html_reports"], package = "codspeed-criterion-compat" }
oxc_allocator = "0.145"
oxc_ast = "0.145"
oxc_codegen = "0.145"
oxc_parser = "0.145"
oxc_span = "0.145"

[[bench]]
name = "ci"
harness = false

[lints]
workspace = true
