import { bilingual } from '$lib/i18n';

export const pipelineTasks = [
	{ identifier: 'format', label: bilingual('フォーマット', 'Format'), input: bilingual('ソースAST・トークン', 'the source AST and tokens'), output: bilingual('整形したSvelte', 'Formatted Svelte'), nodes: ['format'] },
	{ identifier: 'lint', label: bilingual('Lint', 'Lint'), input: bilingual('ソースAST・HIR・参照情報', 'the source AST, HIR, and references'), output: bilingual('未使用変数の診断', 'Unused variable diagnostic'), nodes: ['lint'] },
	{ identifier: 'compile', label: bilingual('コンパイル', 'Compile'), input: bilingual('HIR・スコープ・参照情報', 'HIR, scopes, and references'), output: bilingual('JavaScript・スタイル', 'JavaScript and styles'), nodes: ['analyze', 'lower', 'emit'] },
	{ identifier: 'check', label: bilingual('型検査', 'Type check'), input: bilingual('元のソースAST', 'the original source AST'), output: bilingual('Svelte上の型エラー', 'Type errors in Svelte'), nodes: ['projection', 'typescript', 'mapping'] }
];

const input = { language: 'svelte', source: '<script lang="ts">\nlet name: string = $state("Ada");\nconst unused = 1;\n</script>\n<p class="greeting">{name.toFixed(2)}</p>\n<style>.greeting {color: navy;}</style>' };
const format = { language: 'svelte', source: '<script lang="ts">\n  let name: string = $state("Ada");\n  const unused = 1;\n</script>\n\n<p class="greeting">{name.toFixed(2)}</p>\n\n<style>\n  .greeting {\n    color: navy;\n  }\n</style>' };

export const pipelineExamples = bilingual({
	input,
	parsed: { language: 'text', source: 'ソースAST: Component\nGreeting.svelte\n├─ script: TypeScript\n│  ├─ name: string = $state("Ada")\n│  └─ unused = 1\n├─ template: <p>\n│  └─ expression: name.toFixed(2)\n└─ style: .greeting { color: navy; }' },
	format,
	normalized: { language: 'text', source: 'テンプレートHIR: CompilerSyntaxTree\nElement: p\n  Attribute: class="greeting"\n  Expression:\n    Call: name.toFixed(2)\n式は元のJavaScript/TypeScript ASTのノードを参照する。' },
	resolved: { language: 'text', source: '1. スコープと宣言を登録\n   ルートスコープ: name, unused\n2. 識別子の参照先と読み書きを記録\n   name（テンプレート）→ scriptのname\n   name: 読み取り1件、宣言後の書き込み0件\n   unused: 読み取り0件\n3. Svelte固有の宣言種別を分類\n   name: $state、unused: 通常の変数\n保存: スコープ表・宣言表・参照表\n制御フローグラフと型の判定は含まない。' },
	lint: { language: 'text', source: 'Greeting.svelte:3\nconst unused = 1;\n      ^^^^^^\n未使用の変数 unused を報告する。\nname はテンプレートで参照されている。' },
	analyze: { language: 'text', source: 'コード生成に必要な解析\nname: $stateで作るリアクティブな状態\nテンプレート: nameに依存する式\nスタイル: .greetingの対応を解析\n型検査の結果は入力に含まれない。' },
	lower: { language: 'text', source: '入力: テンプレートHIR + JavaScript/TypeScript AST\n      + 解析結果 + RenderPlan\n出力: LoweredModule\n      クライアント向けJavaScript AST\n元のソースASTとHIRは変更しない。' },
	emit: { language: 'javascript', source: '// Greeting.jsのテキスト更新部分を抜粋\n$.template_effect(\n  ($0) => $.set_text(text, $0),\n  [() => name.toFixed(2)]\n);' },
	projection: { language: 'typescript', source: '// 型検査用TypeScriptの説明用の抜粋\nlet name: string = $state("Ada");\nconst unused = 1;\n\n// 元のテンプレートの式を検査する\nname.toFixed(2);' },
	typescript: { language: 'text', source: '検査用TypeScript + 他ファイル + 型宣言\n  → プロジェクト全体でtscを1回起動\nname: string\ntoFixed: stringには存在しない\n診断位置は、まだ検査用TypeScript上。' },
	mapping: { language: 'svelte', source: '<p class="greeting">{name.toFixed(2)}</p>\n<!-- stringにtoFixedは存在しない。\n     診断を元のSvelteの式に対応付ける。 -->' }
}, {
	input,
	parsed: { language: 'text', source: 'Source AST: Component\nGreeting.svelte\n├─ script: TypeScript\n│  ├─ name: string = $state("Ada")\n│  └─ unused = 1\n├─ template: <p>\n│  └─ expression: name.toFixed(2)\n└─ style: .greeting { color: navy; }' },
	format,
	normalized: { language: 'text', source: 'Template HIR: CompilerSyntaxTree\nElement: p\n  Attribute: class="greeting"\n  Expression:\n    Call: name.toFixed(2)\nExpressions point to nodes in the original JavaScript/TypeScript AST.' },
	resolved: { language: 'text', source: '1. Register scopes and declarations\n   Root scope: name, unused\n2. Record each identifier\'s target, reads, and writes\n   name (template) → name in script\n   name: 1 read, 0 writes after the declaration\n   unused: 0 reads\n3. Classify Svelte declaration kinds\n   name: $state, unused: plain variable\nStored: scope, declaration, and reference tables\nNo control flow graph and no type decisions.' },
	lint: { language: 'text', source: 'Greeting.svelte:3\nconst unused = 1;\n      ^^^^^^\nReports the unused variable unused.\nThe template refers to name.' },
	analyze: { language: 'text', source: 'Analysis for code generation\nname: reactive state made by $state\ntemplate: an expression that depends on name\nstyle: finds what .greeting matches\nType check results are not an input.' },
	lower: { language: 'text', source: 'Input:  template HIR + JavaScript/TypeScript AST\n        + analysis results + RenderPlan\nOutput: LoweredModule\n        client JavaScript AST\nThe source AST and HIR do not change.' },
	emit: { language: 'javascript', source: '// Excerpt: the text update in Greeting.js\n$.template_effect(\n  ($0) => $.set_text(text, $0),\n  [() => name.toFixed(2)]\n);' },
	projection: { language: 'typescript', source: '// Short excerpt of the type check TypeScript, for illustration\nlet name: string = $state("Ada");\nconst unused = 1;\n\n// Checks the expression from the original template\nname.toFixed(2);' },
	typescript: { language: 'text', source: 'Type check TypeScript + other files + type declarations\n  → one tsc run for the whole project\nname: string\ntoFixed: does not exist on string\nThe diagnostic is still at a position in the type check TypeScript.' },
	mapping: { language: 'svelte', source: '<p class="greeting">{name.toFixed(2)}</p>\n<!-- toFixed does not exist on string.\n     The diagnostic maps to the original Svelte expression. -->' }
});

export const pipelineStages = [
	{ identifier: 'input', structure: bilingual('ソーステキスト', 'Source text'), label: bilingual('Svelteファイル', 'Svelte file'), description: bilingual('同じGreeting.svelteのスナップショットに、4種類の処理を実行します。nameはstringですが、テンプレートでは数値向けのtoFixedを呼んでいます。', 'The 4 tasks run on the same snapshot of Greeting.svelte. name is a string, but the template calls toFixed, a number method.'), reads: [] },
	{ identifier: 'parsed', structure: bilingual('Component・SyntaxTree・トークン', 'Component, SyntaxTree, and tokens'), label: bilingual('ソースASTを生成', 'Build the source AST'), description: bilingual('ソースASTとトークンを保存します。Componentがテンプレート、JavaScript/TypeScript AST、スタイルの構文木を保持します。スクリプトとテンプレートのJavaScript式は、同じSyntaxTreeに入ります。このSvelteソースの構文解析は、同じ実行コンテキスト内で1回です。', 'Stores the source AST and the tokens. Component holds the template, the JavaScript/TypeScript AST, and the style tree. The script and the JavaScript expressions in the template go into the same SyntaxTree. Within one run context, this Svelte source is parsed once.'), reads: ['input'] },
	{ identifier: 'format', structure: bilingual('整形したSvelteテキスト', 'Formatted Svelte text'), label: bilingual('フォーマット', 'Format'), description: bilingual('保存した構文木と元のソースから、字下げや空白を整えたSvelteを出力します。名前解決や型検査は要求しません。整形結果を後続タスクの入力に差し替えることもありません。', 'Prints Svelte with fixed indentation and spacing, from the stored tree and the original source. It does not request name resolution or a type check. Later tasks do not get the formatted text as their input.'), reads: ['parsed'] },
	{ identifier: 'normalized', structure: bilingual('CompilerSyntaxTree', 'CompilerSyntaxTree'), label: bilingual('テンプレートHIRを生成', 'Build the template HIR'), description: bilingual('ソースASTのテンプレートをHIRに変換します。CompilerSyntaxTreeが分岐や属性をコンパイラ向けに整理します。JavaScript式は元のJavaScript/TypeScript ASTのノードを参照し、HIRのノードには元のテンプレートとの対応を保持します。', 'Converts the template in the source AST to HIR. CompilerSyntaxTree arranges branches and attributes for the compiler. JavaScript expressions point to nodes in the original JavaScript/TypeScript AST, and each HIR node keeps its link to the original template.'), reads: ['parsed'] },
	{ identifier: 'resolved', structure: bilingual('Resolution・Semanticのサイドテーブル', 'Resolution and Semantic side tables'), label: bilingual('スコープ構築・参照解析', 'Build scopes and resolve references'), description: bilingual('第1パスでスコープの親子関係と宣言を登録します。第2パスで参照先を解決し、読み取り・書き込みを記録します。Svelteの宣言をrunesなどの種別に分類し、スコープ・宣言・参照の表を共有します。制御フローグラフは生成していません。', 'Pass 1 registers the scopes, their parents, and the declarations. Pass 2 resolves each reference and records reads and writes. Svelte declarations are sorted into kinds such as runes, and the scope, declaration, and reference tables are shared. No control flow graph is built.'), reads: ['parsed', 'normalized'] },
	{ identifier: 'lint', structure: bilingual('ルールの診断', 'Rule diagnostics'), label: bilingual('Lintの診断', 'Lint diagnostics'), description: bilingual('保存済みの木とスコープ・参照情報を使ってルールを評価します。unusedには参照がありません。nameにはテンプレートからの参照があるため、未使用変数にはなりません。', 'Rules run on the stored trees and the scope and reference data. unused has no references. The template refers to name, so name is not an unused variable.'), reads: ['parsed', 'normalized', 'resolved'] },
	{ identifier: 'analyze', structure: bilingual('Analysis・RenderPlan', 'Analysis and RenderPlan'), label: bilingual('コンパイル用の解析', 'Analysis for compiling'), description: bilingual('保存済みのスコープ・参照情報とコンパイラ用の木を再利用します。Analysisにリアクティビティやスタイルなどの解析結果を保存します。RenderPlanにはHIRから生成した描画計画を保持します。', 'Reuses the stored scope and reference data and the compiler tree. Analysis stores results such as reactivity and styles. RenderPlan holds the render plan built from the HIR.'), reads: ['parsed', 'normalized', 'resolved'] },
	{ identifier: 'lower', structure: bilingual('LoweredModule・SyntaxTree', 'LoweredModule and SyntaxTree'), label: bilingual('出力JavaScript ASTを生成', 'Build the output JavaScript AST'), description: bilingual('テンプレートHIR、JavaScript/TypeScript AST、解析結果、描画計画から、出力用のJavaScript ASTを新しく作ります。LoweredModuleがこのASTを保持します。この例ではクライアント向けを選びます。', 'Builds a new JavaScript AST for the output from the template HIR, the JavaScript/TypeScript AST, the analysis results, and the render plan. LoweredModule holds this AST. This example targets the client.'), reads: ['analyze', 'normalized', 'resolved'] },
	{ identifier: 'emit', structure: bilingual('JavaScript・スタイルテキスト', 'JavaScript and style text'), label: bilingual('JavaScript・スタイルを出力', 'Print JavaScript and styles'), description: bilingual('生成したJavaScriptの木を文字列にし、スコープ付きのスタイルと合わせて返します。コード欄は生成されたテキスト更新処理の抜粋です。toFixedの呼び出しも出力され、型の妥当性は後の型検査で判定されます。', 'Prints the generated JavaScript tree as text and returns it with the scoped styles. The code panel shows an excerpt of the generated text update. The toFixed call is printed too; the type check decides later whether the types are valid.'), reads: ['lower'] },
	{ identifier: 'projection', structure: bilingual('TypeScriptテキスト・位置対応表', 'TypeScript text and position table'), label: bilingual('検査用TypeScriptを生成', 'Build the type check TypeScript'), description: bilingual('元のソースASTから、テンプレートの式も検査できるTypeScriptテキストと位置の対応表を作ります。コンパイル済みJavaScriptは使いません。コード欄は仕組みを示す抜粋で、実際の生成コード全文ではありません。', 'From the original source AST, builds TypeScript text in which template expressions can also be checked, and a table that maps its positions to the source. It does not use the compiled JavaScript. The code panel is an excerpt that shows the idea, not the full generated code.'), reads: ['parsed'] },
	{ identifier: 'typescript', structure: bilingual('TypeScript上の診断', 'Diagnostics in TypeScript'), label: bilingual('プロジェクト全体を型検査', 'Type check the whole project'), description: bilingual('全ファイルの検査用TypeScriptがそろった後、型宣言と設定を合わせてtscを1回起動します。tscは生成したTypeScriptを別途解析し、stringにtoFixedがないことを検出します。', 'When the type check TypeScript of every file is ready, tsc runs once with the type declarations and the settings. tsc parses the generated TypeScript on its own and finds that string has no toFixed.'), reads: ['projection'] },
	{ identifier: 'mapping', structure: bilingual('Svelte上の診断', 'Diagnostics in Svelte'), label: bilingual('診断位置をSvelteに戻す', 'Map positions back to Svelte'), description: bilingual('生成時の位置の対応表で、TypeScript上の診断をGreeting.svelteのname.toFixed(2)に戻します。利用者には元のSvelteファイルの位置を返します。', 'The position table from the projection step maps the TypeScript diagnostic back to name.toFixed(2) in Greeting.svelte. You get positions in the original Svelte file.'), reads: ['typescript', 'projection'] }
];

export function selectedPipeline(selected: string[]) {
	const needsSemantic = selected.includes('lint') || selected.includes('compile');
	const requested = new Set(['input', 'parsed', ...(needsSemantic ? ['normalized', 'resolved'] : []),
		...pipelineTasks.filter(task => selected.includes(task.identifier)).flatMap(task => task.nodes)]);
	return selected.length ? pipelineStages.filter(stage => requested.has(stage.identifier)) : [];
}
