/* instance.svelte.js generated by Svelte v5.57.1 */
import * as $ from 'svelte/internal/client';
import { query_responses, handle_error } from '../../client.js';
import { HandledHttpError } from '@sveltejs/kit/internal';
import { QUERY_OVERRIDE_KEY } from '../shared.svelte.js';
import { noop } from '../../../../utils/functions.js';
import { with_resolvers } from '../../../../utils/promise.js';
import { tick, untrack } from 'svelte';

export class Query {
	/** @type {string} */
	#key;

	/** @type {() => Promise<T>} */
	#fn;

	#loading = $.state(true);

	/** @type {Array<(value: undefined) => void>} */
	#latest = [];

	/** @type {boolean} */
	#ready = $.state(false);

	/** @type {T | undefined} */
	#raw = $.state();

	/** @type {Promise<void> | null} */
	#promise = $.state(null);

	/** @type {Array<(old: T) => T>} */
	#overrides = $.state($.proxy([]));

	/** @type {T | undefined} */
	#current = $.derived(() => {
		// don't reduce undefined value
		if (!$.get(this.#ready)) return undefined;

		return $.get(this.#overrides /** @type {T} */).reduce((v, r) => r(v), $.get(this.#raw));
	});

	/** @type {App.Error | undefined} */
	#error = $.state(undefined);

	/** @type {Promise<T>['then']} */
	// @ts-expect-error TS doesn't understand that the promise returns something
	#then = $.derived(() => {
		const p = this.#get_promise();

		$.get(this.#overrides).length;

		return (resolve, reject) => {
			const result = p.then(tick).then(() => $.get(/** @type {T} */ (this.#current)));

			if (resolve || reject) {
				return result.then(resolve, reject);
			}

			return result;
		};
	});

	/**
	 * @param {string} key
	 * @param {() => Promise<T>} fn
	 */
	constructor(key, fn) {
		this.#key = key;
		this.#fn = fn;

		if (Object.hasOwn(query_responses, key)) {
			const node = query_responses[key];

			delete query_responses[key];

			if (node.e) {
				this.fail(new HandledHttpError(node.e));
			} else {
				this.set(/** @type {T} */ (node.v));
			}
		}
	}

	#get_promise() {
		void untrack(() => $.get(this.#promise) ?? $.set(this.#promise, this.#run()));

		return $.get(/** @type {Promise<T>} */ (this.#promise));
	}

	start() {
		// there is a really weird bug with untrack and writes and initializations
		// every time you see this comment, try removing the `tick.then` here and see
		// if all the tests still pass with the latest svelte version
		// if they do, congrats, you can remove tick.then
		void tick().then(() => this.#get_promise()).catch(noop);
	}

	#clear_pending() {
		this.#latest.forEach((r) => r(undefined));
		this.#latest.length = 0;
	}

	#run() {
		$.set(this.#loading, true);

		const { promise, resolve, reject } = with_resolvers();

		// the rejection is surfaced via `.error` / the `then` getter for awaiting
		// consumers — a purely reactive consumer (`.current`) attaches no handler,
		// so make sure the stored promise can never become an unhandled rejection
		promise.catch(noop);

		this.#latest.push(resolve);

		Promise.resolve(this.#fn()).then((value) => {
			// Skip the response if resource was refreshed with a later promise while we were waiting for this one to resolve
			const idx = this.#latest.indexOf(resolve);

			if (idx === -1) return;

			// Untrack this to not trigger mutation validation errors which can occur if you do e.g. $derived({ a: await queryA(), b: await queryB() })
			untrack(() => {
				this.#latest.splice(0, idx).forEach((r) => r(undefined));
				$.set(this.#ready, true);
				$.set(this.#loading, false);
				$.set(this.#raw, value);
				$.set(this.#error, undefined);
			});

			resolve(undefined);
		}).catch(async (e) => {
			// TODO: Our behavior here could be better:
			// - We should not reject on redirects, but should hook into the router
			//   to ensure the query is properly refreshed before the navigation completes
			// - Instead of failing on transport-level errors, we should probably do what
			//   LiveQuery does and preserve the last known good value and retry the connection
			if (this.#latest.indexOf(resolve) === -1) return;

			const error = await handle_error(e, { params: {}, route: { id: null }, url: new URL(location.href) });

			// Re-check after the async `handle_error` gap: a later request may have
			// resolved/rejected while we were awaiting and superseded this one, so
			// recompute the index and bail out if this request is no longer current
			const idx = this.#latest.indexOf(resolve);

			if (idx === -1) return;

			untrack(() => {
				this.#latest.splice(0, idx).forEach((r) => r(undefined));
				$.set(this.#error, error);
				$.set(this.#loading, false);
			});

			reject(new HandledHttpError(error));
		});

		return promise;
	}

	get then() {
		// TODO this should be unnecessary but due to the bug described
		// in #start, we need to do this in some circumstances
		this.start();

		return $.get(this.#then);
	}

	get catch() {
		this.start();
		$.get(this.#then);

		return (/** @type {any} */ reject) => {
			return $.get(this.#then)(undefined, reject);
		};
	}

	get finally() {
		this.start();
		$.get(this.#then);

		return (/** @type {any} */ fn) => {
			return $.get(this.#then)(
				(value) => {
					fn();

					return value;
				},
				(error) => {
					fn();

					throw error;
				}
			);
		};
	}

	get current() {
		this.start();

		return $.get(this.#current);
	}

	get error() {
		this.start();

		return $.get(this.#error);
	}

	/**
	 * Returns true if the resource is loading or reloading.
	 */
	get loading() {
		this.start();

		return $.get(this.#loading);
	}

	/**
	 * Returns true once the resource has been loaded for the first time.
	 */
	get ready() {
		this.start();

		return $.get(this.#ready);
	}

	/**
	 * @returns {Promise<void>}
	 */
	refresh() {
		delete query_responses[this.#key];

		return $.set(this.#promise, this.#run());
	}

	/**
	 * @param {T} value
	 */
	set(value) {
		// normally consumed in the constructor, but make sure a leftover
		// SSR record can never shadow the newly-set value
		delete query_responses[this.#key];

		this.#clear_pending();
		$.set(this.#ready, true);
		$.set(this.#loading, false);
		$.set(this.#error, undefined);
		$.set(this.#raw, value);
		$.set(this.#promise, Promise.resolve());
	}

	/** @param {HttpError} error */
	fail(error) {
		// normally consumed in the constructor, but make sure a leftover
		// SSR record can never shadow the newly-set error
		delete query_responses[this.#key];

		this.#clear_pending();
		$.set(this.#loading, false);
		$.set(this.#error, error.body);

		const promise = Promise.reject(error);

		promise.catch(noop);
		$.set(this.#promise, promise);
	}

	/**
	 * @param {(old: T) => T} fn
	 * @returns {(() => void) & { [QUERY_OVERRIDE_KEY]: string }}
	 */
	withOverride(fn) {
		$.get(this.#overrides).push(fn);

		const release = /** @type {(() => void) & { [QUERY_OVERRIDE_KEY]: string }} */ (
		() => {
			const i = $.get(this.#overrides).indexOf(fn);

			if (i !== -1) {
				$.get(this.#overrides).splice(i, 1);
			}
		});

		Object.defineProperty(release, QUERY_OVERRIDE_KEY, { value: this.#key });

		return release;
	}

	/**
	 * Reset ahead of a navigation that invalidates all, to force newly
	 * rendered queries to get fresh data
	 */
	reset() {
		$.set(this.#promise, null);
		delete query_responses[this.#key];
	}

	get [Symbol.toStringTag]() {
		return 'Query';
	}
}