/* root.svelte.js generated by Svelte v5.57.1 */
import * as $ from 'svelte/internal/client';

export function with_root(get_x) {
	const cleanup = $.effect_root(() => {
		$.user_effect(() => {
			console.log(get_x());
		});

		const nested_cleanup = $.effect_root(() => {
			return () => {
				console.log('cleanup 2');
			};
		});

		return () => {
			console.log('cleanup 1');
			nested_cleanup();
		};
	});

	return cleanup;
}