/* rsvelte C ABI - generated by cbindgen. DO NOT EDIT. */

#ifndef RSVELTE_H
#define RSVELTE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>

/**
 * Owned byte buffer crossing the FFI boundary.
 *
 * Layout-stable on every platform we care about (pointer + length).
 * The caller MUST release every non-null buffer returned by this
 * library with [`rsvelte_free`].
 */
typedef struct RsvelteBuf {
  /**
   * Pointer to UTF-8 bytes. May be null when `len == 0`.
   */
  uint8_t *data;
  /**
   * Length in bytes (does NOT include any trailing NUL).
   */
  uintptr_t len;
  /**
   * Allocated capacity in bytes. Reserved for [`rsvelte_free`]; do
   * not interpret in caller code.
   */
  uintptr_t cap;
} RsvelteBuf;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Library version (matches the `rsvelte_core` crate version).
 *
 * Returns a static, NUL-terminated UTF-8 string. The caller MUST NOT
 * free the returned pointer.
 */
const char *rsvelte_version(void);

/**
 * Release a buffer previously returned by this library.
 *
 * Safe to call with a zero-initialised buffer (data=NULL, len=0,
 * cap=0); does nothing in that case. Calling twice on the same
 * non-empty buffer is undefined behaviour.
 *
 * # Safety
 * `buf` must be a value previously returned by an `rsvelte_*` call.
 */
void rsvelte_free(struct RsvelteBuf buf);

/**
 * Decomposed-argument variant of [`rsvelte_free`] for hosts whose
 * FFI can't pass structs by value (Ruby Fiddle, some PHP setups).
 *
 * # Safety
 * `(data, len, cap)` must be the three fields of a `RsvelteBuf`
 * previously returned by an `rsvelte_*` call.
 */
void rsvelte_free_raw(uint8_t *data, uintptr_t len, uintptr_t cap);

/**
 * Compile a Svelte component.
 *
 * Both inputs are borrowed for the duration of the call. The result
 * is a JSON envelope ({"ok":true,"result":...} or
 * {"ok":false,"error":...}). Returns an empty buffer on argument
 * errors *too severe to encode* (e.g. invalid source pointer) — every
 * recoverable error is reported inside the JSON envelope instead.
 *
 * # Safety
 * - `source` must point to `source_len` valid UTF-8 bytes (or be NULL when len==0).
 * - `options_json` must point to `options_len` valid UTF-8 bytes (or be NULL when len==0).
 *   When `options_len == 0` the compiler defaults are used.
 */
struct RsvelteBuf rsvelte_compile(const uint8_t *source,
                                  uintptr_t source_len,
                                  const uint8_t *options_json,
                                  uintptr_t options_len);

/**
 * Compile a Svelte `.svelte.js` / `.svelte.ts` module.
 *
 * Same calling convention as [`rsvelte_compile`].
 *
 * # Safety
 * See [`rsvelte_compile`].
 */
struct RsvelteBuf rsvelte_compile_module(const uint8_t *source,
                                         uintptr_t source_len,
                                         const uint8_t *options_json,
                                         uintptr_t options_len);

/**
 * Out-parameter variant of [`rsvelte_compile`] for hosts whose FFI
 * can't return structs by value (e.g. Ruby Fiddle, older PHP, some
 * Java JNI setups). The result is written through `out`. The caller
 * still owns the bytes and must release them with [`rsvelte_free`].
 *
 * # Safety
 * `out` must be a non-null pointer to a writable `RsvelteBuf`.
 * Source/options pointers follow the same rules as [`rsvelte_compile`].
 */
void rsvelte_compile_into(const uint8_t *source,
                          uintptr_t source_len,
                          const uint8_t *options_json,
                          uintptr_t options_len,
                          struct RsvelteBuf *out);

/**
 * Out-parameter variant of [`rsvelte_compile_module`]. See
 * [`rsvelte_compile_into`] for the rationale.
 *
 * # Safety
 * See [`rsvelte_compile_into`].
 */
void rsvelte_compile_module_into(const uint8_t *source,
                                 uintptr_t source_len,
                                 const uint8_t *options_json,
                                 uintptr_t options_len,
                                 struct RsvelteBuf *out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RSVELTE_H */
