/* rsvelte C ABI - generated by cbindgen. DO NOT EDIT. */

#ifndef RSVELTE_H
#define RSVELTE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>

/**
 * Owned byte buffer crossing the FFI boundary.
 *
 * Layout-stable on every platform we care about (pointer + length).
 * The caller MUST release every non-null buffer returned by this
 * library with [`rsvelte_free`].
 */
typedef struct RsvelteBuf {
  /**
   * Pointer to UTF-8 bytes. May be null when `len == 0`.
   */
  uint8_t *data;
  /**
   * Length in bytes (does NOT include any trailing NUL).
   */
  uintptr_t len;
  /**
   * Allocated capacity in bytes. Reserved for [`rsvelte_free`]; do
   * not interpret in caller code.
   */
  uintptr_t cap;
} RsvelteBuf;

/**
 * Borrowed UTF-8 string view returned by a callback into this library.
 *
 * Unlike [`RsvelteBuf`], the library does NOT take ownership of these
 * bytes and never frees them. The pointer must stay valid only for the
 * duration of the callback invocation that returned it (this library
 * copies the bytes synchronously before the callback returns control
 * upstream). A `{ data: NULL, len: 0 }` value means "no value — fall
 * back to the compiler default".
 */
typedef struct RsvelteStr {
  /**
   * Pointer to borrowed UTF-8 bytes. NULL means "no value".
   */
  const uint8_t *data;
  /**
   * Length in bytes (does NOT include any trailing NUL).
   */
  uintptr_t len;
} RsvelteStr;

/**
 * Input handed to a [`RsvelteCssHashFn`] callback.
 *
 * Every field is a borrowed `(pointer, length)` UTF-8 slice, valid only
 * for the duration of the callback. `hash` is the raw digest (WITHOUT the
 * `svelte-` prefix) that the compiler's *default* `cssHash` produces —
 * upstream digests the rootDir-relative `filename` when known, else `css`
 * — so prepending `svelte-` reproduces the default class name exactly.
 */
typedef struct RsvelteCssHashInput {
  /**
   * The component's CSS source.
   */
  const uint8_t *css;
  /**
   * Length of `css` in bytes.
   */
  uintptr_t css_len;
  /**
   * The rootDir-relative (or absolute) filename, or `(unknown)`.
   */
  const uint8_t *filename;
  /**
   * Length of `filename` in bytes.
   */
  uintptr_t filename_len;
  /**
   * The derived component name.
   */
  const uint8_t *name;
  /**
   * Length of `name` in bytes.
   */
  uintptr_t name_len;
  /**
   * The raw digest the default `cssHash` produces — the filename when
   * known, else the css (no `svelte-` prefix).
   */
  const uint8_t *hash;
  /**
   * Length of `hash` in bytes.
   */
  uintptr_t hash_len;
} RsvelteCssHashInput;

/**
 * Optional compile callbacks (issue #1680).
 *
 * Passed by pointer to the `*_with_callbacks` entry points. A NULL
 * function-pointer field disables that callback. Each `*_userdata`
 * pointer is passed back verbatim to its callback and is otherwise
 * opaque to this library — use it to carry closure state. When a
 * constant `cssHashOverride` is also set in the options JSON, that
 * constant wins and `css_hash` is not invoked (mirrors the wasm/NAPI
 * precedence).
 */
typedef struct RsvelteCallbacks {
  /**
   * CSS hash callback (a [`RsvelteCssHashFn`]), or NULL. Inlined rather
   * than referenced via the alias so cbindgen emits a nullable function
   * pointer instead of an opaque `Option_*` struct.
   */
  struct RsvelteStr (*css_hash)(void *userdata, const struct RsvelteCssHashInput *input);
  /**
   * Opaque state pointer passed to `css_hash`.
   */
  void *css_hash_userdata;
  /**
   * Warning filter callback (a [`RsvelteWarningFilterFn`]), or NULL.
   */
  bool (*warning_filter)(void *userdata, const uint8_t *warning_json, uintptr_t warning_json_len);
  /**
   * Opaque state pointer passed to `warning_filter`.
   */
  void *warning_filter_userdata;
} RsvelteCallbacks;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Library version (matches the `rsvelte_core` crate version).
 *
 * Returns a static, NUL-terminated UTF-8 string. The caller MUST NOT
 * free the returned pointer.
 */
const char *rsvelte_version(void);

/**
 * Release a buffer previously returned by this library.
 *
 * Safe to call with a zero-initialised buffer (data=NULL, len=0,
 * cap=0); does nothing in that case. Calling twice on the same
 * non-empty buffer is undefined behaviour.
 *
 * # Safety
 * `buf` must be a value previously returned by an `rsvelte_*` call.
 */
void rsvelte_free(struct RsvelteBuf buf);

/**
 * Decomposed-argument variant of [`rsvelte_free`] for hosts whose
 * FFI can't pass structs by value (Ruby Fiddle, some PHP setups).
 *
 * # Safety
 * `(data, len, cap)` must be the three fields of a `RsvelteBuf`
 * previously returned by an `rsvelte_*` call.
 */
void rsvelte_free_raw(uint8_t *data, uintptr_t len, uintptr_t cap);

/**
 * Compile a Svelte component.
 *
 * Both inputs are borrowed for the duration of the call. The result
 * is a JSON envelope ({"ok":true,"result":...} or
 * {"ok":false,"error":...}). Returns an empty buffer on argument
 * errors *too severe to encode* (e.g. invalid source pointer) — every
 * recoverable error is reported inside the JSON envelope instead.
 *
 * # Safety
 * - `source` must point to `source_len` valid UTF-8 bytes (or be NULL when len==0).
 * - `options_json` must point to `options_len` valid UTF-8 bytes (or be NULL when len==0).
 *   When `options_len == 0` the compiler defaults are used.
 */
struct RsvelteBuf rsvelte_compile(const uint8_t *source,
                                  uintptr_t source_len,
                                  const uint8_t *options_json,
                                  uintptr_t options_len);

/**
 * Compile a Svelte `.svelte.js` / `.svelte.ts` module.
 *
 * Same calling convention as [`rsvelte_compile`].
 *
 * # Safety
 * See [`rsvelte_compile`].
 */
struct RsvelteBuf rsvelte_compile_module(const uint8_t *source,
                                         uintptr_t source_len,
                                         const uint8_t *options_json,
                                         uintptr_t options_len);

/**
 * Compile a Svelte component with optional `cssHash` / `warningFilter`
 * callbacks (issue #1680).
 *
 * Identical to [`rsvelte_compile`] but also resolves the two callback
 * compile options that can't cross the JSON boundary. `callbacks` may
 * be NULL (equivalent to [`rsvelte_compile`]); individual callback
 * fields may be NULL too. The callbacks are input-only and are never
 * retained past this call.
 *
 * # Safety
 * - Source/options pointers follow [`rsvelte_compile`]'s rules.
 * - `callbacks` must be NULL or point to a valid [`RsvelteCallbacks`];
 *   each non-NULL function pointer must be callable with the documented
 *   signature and its paired `*_userdata` value.
 */
struct RsvelteBuf rsvelte_compile_with_callbacks(const uint8_t *source,
                                                 uintptr_t source_len,
                                                 const uint8_t *options_json,
                                                 uintptr_t options_len,
                                                 const struct RsvelteCallbacks *callbacks);

/**
 * Compile a Svelte `.svelte.js` / `.svelte.ts` module with an optional
 * `warningFilter` callback (issue #1680). Modules have no CSS, so the
 * `css_hash` field of `callbacks` is ignored.
 *
 * # Safety
 * See [`rsvelte_compile_with_callbacks`].
 */
struct RsvelteBuf rsvelte_compile_module_with_callbacks(const uint8_t *source,
                                                        uintptr_t source_len,
                                                        const uint8_t *options_json,
                                                        uintptr_t options_len,
                                                        const struct RsvelteCallbacks *callbacks);

/**
 * Out-parameter variant of [`rsvelte_compile`] for hosts whose FFI
 * can't return structs by value (e.g. Ruby Fiddle, older PHP, some
 * Java JNI setups). The result is written through `out`. The caller
 * still owns the bytes and must release them with [`rsvelte_free`].
 *
 * # Safety
 * `out` must be a non-null pointer to a writable `RsvelteBuf`.
 * Source/options pointers follow the same rules as [`rsvelte_compile`].
 */
void rsvelte_compile_into(const uint8_t *source,
                          uintptr_t source_len,
                          const uint8_t *options_json,
                          uintptr_t options_len,
                          struct RsvelteBuf *out);

/**
 * Out-parameter variant of [`rsvelte_compile_module`]. See
 * [`rsvelte_compile_into`] for the rationale.
 *
 * # Safety
 * See [`rsvelte_compile_into`].
 */
void rsvelte_compile_module_into(const uint8_t *source,
                                 uintptr_t source_len,
                                 const uint8_t *options_json,
                                 uintptr_t options_len,
                                 struct RsvelteBuf *out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RSVELTE_H */
