/* state.svelte.js generated by Svelte v5.57.1 */
import * as $ from 'svelte/internal/server';

let s = 0;

let d = $.derived(() => {
	count += 1;

	return s * 2;
});

export let count = 0;

export function reset() {
	count = 0;
	s = 0;
}

export function increment() {
	s += 1;
}

export function get() {
	return d();
}