//! Server-side code generation.
//!
//! Generates JavaScript code for server-side rendering (SSR).
//!
//! This module is organized to match the Svelte compiler structure.

pub mod build;
pub mod helpers;
pub mod transform_legacy;
pub mod transform_script;
pub mod transform_store;
pub mod types;
pub mod visitors;

use super::TransformError;
use super::css::render_stylesheet_minified;
use crate::ast::template::{Fragment, Root, Script, TemplateNode};
use crate::compiler::CompileOptions;
use crate::compiler::phases::phase2_analyze::ComponentAnalysis;
use crate::compiler::phases::phase2_analyze::scope::BindingKind;
use crate::compiler::phases::phase3_transform::utils::is_svelte_whitespace_only;
use helpers::*;
use memchr::memmem;
use types::{OutputPart, SnippetDef};

use rustc_hash::FxHashMap;

/// Transform a component analysis into server-side JavaScript.
///
/// # Arguments
///
/// * `analysis` - The component analysis from Phase 2
/// * `ast` - The parsed AST from Phase 1 (to avoid re-parsing)
/// * `_source` - The original source code (for backward compatibility)
/// * `_options` - Compile options
pub fn transform_server(
    analysis: &ComponentAnalysis,
    ast: &Root,
    _source: &str,
    options: &CompileOptions,
) -> Result<String, TransformError> {
    let component_name = &analysis.name;

    // Use the AST's instance script directly (no re-parsing needed)
    let instance_script = ast.instance.as_ref().map(|s| s.as_ref());
    // Use the AST's module script (context="module")
    let module_script = ast.module.as_ref().map(|s| s.as_ref());

    let mut generator = ServerCodeGenerator::new(
        component_name.clone(),
        analysis.source.clone(),
        instance_script,
        module_script,
        Some(analysis),
        options.experimental.r#async,
    );
    generator.preserve_whitespace = options.preserve_whitespace;
    generator.preserve_comments = options.preserve_comments;
    generator.dev = options.dev;
    generator.component_api_v4 = matches!(
        options.compatibility.component_api,
        crate::compiler::ComponentApi::V4
    );
    // Make filename relative to rootDir if specified (matches official Svelte compiler behavior)
    generator.filename = options.filename.as_ref().map(|fname| {
        let fname = fname.replace('\\', "/");
        if let Some(ref root_dir) = options.root_dir {
            let rd = root_dir.replace('\\', "/");
            let rd = rd.trim_end_matches('/');
            if let Some(stripped) = fname.strip_prefix(rd) {
                stripped.trim_start_matches('/').to_string()
            } else {
                fname
            }
        } else {
            fname
        }
    });

    // Handle CSS injection for options.css === 'injected'
    // Reference: transform-server.js line 303: options.css === 'injected' && !options.customElement
    // Note: analysis.inject_styles is also true for custom elements, but custom elements
    // handle styles client-side (in shadow DOM), so we check the compile option directly.
    if options.css == crate::compiler::CssMode::Injected
        && analysis.css.has_css
        && !analysis.css.hash.is_empty()
        && !options.custom_element
    {
        // Render the CSS stylesheet with scoping and minification for SSR
        if let Ok(css_output) = render_stylesheet_minified(analysis, &analysis.source, options)
            && !css_output.code.is_empty()
        {
            generator.set_injected_css(analysis.css.hash.clone(), css_output.code);
        }
    }

    // Use the AST fragment directly (no re-parsing needed)
    generator.generate_component(&ast.fragment)?;

    let output = generator.build();
    let output = strip_empty_statements(&output);
    Ok(add_esrap_blank_lines(&output))
}

/// Transform a module (.svelte.js/.svelte.ts) into server-side JavaScript.
///
/// Unlike `transform_server`, this does NOT generate a component function.
/// It only transforms the module source (rune replacements) and prepends
/// the `import * as $ from 'svelte/internal/server'` import.
///
/// Corresponds to `server_module()` in the official Svelte compiler.
pub fn transform_server_module(
    analysis: &ComponentAnalysis,
    source: &str,
    _options: &CompileOptions,
) -> Result<String, TransformError> {
    // For server modules, perform the same rune transformations as client modules
    // but use 'svelte/internal/server' import instead.
    let basename = _options
        .filename
        .as_ref()
        .and_then(|f| f.rsplit('/').next().or_else(|| f.rsplit('\\').next()))
        .unwrap_or("input.svelte.js");

    let mut parts: Vec<String> = Vec::new();

    // Leading comment
    parts.push(format!(
        "/* {} generated by Svelte v{} */",
        basename,
        option_env!("SVELTE_VERSION").unwrap_or("VERSION")
    ));

    // Import
    parts.push("import * as $ from 'svelte/internal/server';".to_string());

    // For server modules, strip $effect and $effect.root blocks from the source
    // before applying transforms, since effects don't run on the server.
    let source_without_effects = strip_effects_from_source(source);

    // Transform rune calls using the same infrastructure as client modules.
    // The client transform handles class fields ($state, $derived in classes).
    let transformed =
        super::client::transform_module_source_for_module(&source_without_effects, analysis, false);

    // Post-process: replace client-specific runtime calls with server equivalents
    // $.get(x) -> x() for server (derived signals are callable on server)
    // $.set(x, v) -> x(v)
    // $.proxy(x) -> x (no proxying on server)
    // $.state(x) -> x (no signals on server)
    // $.effect_root(...) and $.user_effect(...) -> noop (should already be stripped)
    let transformed = post_process_for_server(&transformed);

    // Split imports from body
    let (script_imports, script_rest) = super::client::extract_imports_str(&transformed);

    for import_line in &script_imports {
        let trimmed = import_line.trim();
        if memmem::find(trimmed.as_bytes(), b"svelte/internal/").is_none() {
            // Ensure import statements end with semicolons, matching esrap behavior.
            if !trimmed.ends_with(';') {
                let mut with_semi = String::with_capacity(trimmed.len() + 1);
                with_semi.push_str(trimmed);
                with_semi.push(';');
                parts.push(with_semi);
            } else {
                parts.push(trimmed.to_string());
            };
        }
    }

    if let Some(rest) = script_rest {
        let rest_trimmed = rest.trim();
        if !rest_trimmed.is_empty() {
            parts.push(String::new()); // blank line
            parts.push(rest_trimmed.to_string());
        }
    }

    Ok(parts.join("\n"))
}

/// Add esrap-style blank lines between statements of different types.
/// Strip standalone empty statements (`;` on its own line) from server code.
///
/// The server code generator sometimes emits standalone semicolons that the
/// official Svelte compiler doesn't produce. This removes lines that consist
/// only of whitespace followed by `;`.
fn strip_empty_statements(code: &str) -> String {
    let lines: Vec<&str> = code.lines().collect();
    let mut result: Vec<String> = Vec::with_capacity(lines.len());
    for line in lines {
        let trimmed = line.trim();
        if trimmed == ";" {
            continue;
        }
        // Clean stray semicolons at start of block: `{;` -> `{`
        if trimmed.ends_with("{;") {
            let indent = &line[..line.len() - trimmed.len()];
            result.push(format!("{}{}", indent, &trimmed[..trimmed.len() - 1]));
        } else {
            result.push(line.to_string());
        }
    }
    result.join("\n")
}

/// In the official Svelte compiler, esrap adds a blank line when:
/// - The AST node type changes between consecutive statements, OR
/// - Either statement is multiline
///
/// This function post-processes the generated server code to match that behavior.
fn add_esrap_blank_lines(code: &str) -> String {
    // Pre-process: split lines where `}\tstatement` or `}\t\t...});` appears
    // The server build sometimes concatenates closing braces with the next statement.
    let code = split_concatenated_braces(code);
    let lines: Vec<&str> = code.lines().collect();
    let mut result = Vec::with_capacity(lines.len() + 20);

    // Track the previous statement type at each indentation level
    let mut prev_type_at_indent: rustc_hash::FxHashMap<usize, &str> =
        rustc_hash::FxHashMap::default();
    let mut prev_multiline_at_indent: rustc_hash::FxHashMap<usize, bool> =
        rustc_hash::FxHashMap::default();

    // Track whether each indent level is a "statement context" (function body, if-block, etc.)
    // or a "property context" (object literal properties). esrap only adds blank lines between
    // statements, not between object properties.
    // true = statement context (add blank lines), false = property context (no blank lines)
    let mut is_statement_context: rustc_hash::FxHashMap<usize, bool> =
        rustc_hash::FxHashMap::default();
    // The top level and any function body are statement contexts
    is_statement_context.insert(0, true);
    // Track indent levels that have a pending leading comment for the next statement
    let mut comment_at_indent: rustc_hash::FxHashSet<usize> = rustc_hash::FxHashSet::default();

    // Track whether we're inside a template literal (backtick string).
    // Lines inside template literals must not be modified.
    let mut in_template_literal = false;

    let mut i = 0;
    while i < lines.len() {
        let line = lines[i];

        // Track template literal state across lines using proper parsing
        // that handles string literals, ${} expressions, and nested template literals.
        if in_template_literal {
            result.push(line);
            // Check if this line closes the template literal
            in_template_literal = line_ends_in_template_literal(line, true);
            i += 1;
            continue;
        }

        // Check if this line starts a template literal that doesn't close on the same line
        let ends_in_tl = line_ends_in_template_literal(line, false);
        if ends_in_tl {
            // Template literal started but not closed on this line
            // Process this line normally (it's a statement start) but mark subsequent
            // lines as inside the template literal
            in_template_literal = true;
        }

        // Handle blank lines based on context:
        // In statement contexts: strip blank lines and reconstruct based on esrap rules
        // In property contexts (object literals): preserve blank lines from source
        if line.trim().is_empty() {
            // Look at the next non-empty line to determine which context this blank line belongs to
            let next_indent = lines[(i + 1)..]
                .iter()
                .find(|l| !l.trim().is_empty())
                .map(|l| l.bytes().take_while(|&b| b == b'\t').count());
            let in_prop_context = next_indent
                .and_then(|indent| is_statement_context.get(&indent))
                .map(|&is_stmt| !is_stmt)
                .unwrap_or(false);
            if in_prop_context {
                result.push(line);
            }
            // In statement context: skip the blank line (we'll add our own)
            i += 1;
            continue;
        }

        // Determine indent level (count leading tabs)
        let indent_level = line.bytes().take_while(|&b| b == b'\t').count();
        let trimmed = line.trim_start_matches('\t');

        // Lines that are just closing braces/brackets end a multiline statement
        // at this indent level. Mark the previous statement as multiline so
        // the next statement at this level gets a blank line.
        if trimmed.starts_with('}') || trimmed.starts_with(']') || trimmed.starts_with(')') {
            // Mark that the previous statement at this indent was multiline
            prev_multiline_at_indent.insert(indent_level, true);
            // If this line opens a new block (e.g., `} else {`, `} catch {`),
            // reset tracking for the inner indent level so statements inside
            // the new block don't inherit multiline/type state from the previous block.
            if trimmed.ends_with('{') {
                prev_type_at_indent.remove(&(indent_level + 1));
                prev_multiline_at_indent.remove(&(indent_level + 1));
            }
            result.push(line);
            i += 1;
            continue;
        }

        // When a line opens a block with `{`, determine if the inner content is
        // statement context or property context.
        if trimmed.ends_with('{') {
            prev_type_at_indent.remove(&(indent_level + 1));
            prev_multiline_at_indent.remove(&(indent_level + 1));

            // Detect if this opens an object literal (property context) or a statement block.
            // Object literals are opened by patterns like:
            //   `Foo(args, {`  or  `identifier({`  or  `= {`  or  `return {`
            // Statement blocks are opened by:
            //   `function ...() {`  `if (...) {`  `for (...) {`  `=> {`  `else {`
            let opens_object = is_object_literal_opening(trimmed);
            is_statement_context.insert(indent_level + 1, !opens_object);
        }

        // When a line ends with `(` or `[`, the elements inside are NOT in a statement context.
        // e.g., `$$renderer.option(` followed by args at indent_level+1
        //        `$$renderer.run([` followed by thunks at indent_level+1
        if trimmed.ends_with('(') || trimmed.ends_with('[') {
            prev_type_at_indent.remove(&(indent_level + 1));
            prev_multiline_at_indent.remove(&(indent_level + 1));
            is_statement_context.insert(indent_level + 1, false);
        }

        // Check if this indent level is in a statement context
        let in_stmt_context = is_statement_context
            .get(&indent_level)
            .copied()
            .unwrap_or(true);

        // Determine the statement type
        let stmt_type = classify_server_line(trimmed);

        // Comments are "transparent" - they attach to the following node (as leading
        // comments in esrap). They don't trigger blank lines or update type tracking.
        // However, they make the following statement multiline.
        if stmt_type == "Comment" {
            comment_at_indent.insert(indent_level);
            result.push(line);
            i += 1;
            continue;
        }

        // Check if this statement is multiline (spans multiple lines)
        // A leading comment makes the statement multiline
        let has_leading_comment = comment_at_indent.remove(&indent_level);
        let is_multiline = has_leading_comment || is_server_stmt_multiline(&lines, i, indent_level);

        // Only add blank lines in statement contexts (not inside object literals)
        if in_stmt_context {
            // Check if we need a blank line before this statement
            if let Some(prev_type) = prev_type_at_indent.get(&indent_level) {
                let prev_ml = prev_multiline_at_indent
                    .get(&indent_level)
                    .copied()
                    .unwrap_or(false);
                if stmt_type != *prev_type || is_multiline || prev_ml {
                    // Add blank line if the last line in result isn't already blank
                    if !result.is_empty() && result.last() != Some(&"") {
                        result.push("");
                    }
                }
            }
        }

        prev_type_at_indent.insert(indent_level, stmt_type);
        prev_multiline_at_indent.insert(indent_level, is_multiline);
        result.push(line);
        i += 1;
    }

    // Remove trailing empty lines
    while result.last() == Some(&"") {
        result.pop();
    }

    result.join("\n")
}

/// Determine if a line ending with `{` opens an object literal (property context)
/// rather than a statement block.
fn is_object_literal_opening(trimmed: &str) -> bool {
    // Lines ending with `=> {` open a function body (arrow function)
    if trimmed.ends_with("=> {") {
        return false;
    }

    // Lines starting with block keywords open statement blocks
    if trimmed.starts_with("function ")
        || trimmed.starts_with("async function ")
        || trimmed.starts_with("if ")
        || trimmed.starts_with("if(")
        || trimmed.starts_with("} else if ")
        || trimmed.starts_with("} else {")
        || trimmed.starts_with("else {")
        || trimmed.starts_with("for ")
        || trimmed.starts_with("for(")
        || trimmed.starts_with("while ")
        || trimmed.starts_with("while(")
        || trimmed.starts_with("do {")
        || trimmed.starts_with("do{")
        || trimmed.starts_with("try {")
        || trimmed.starts_with("} catch")
        || trimmed.starts_with("} finally")
        || trimmed.starts_with("class ")
        || trimmed.starts_with("switch ")
        || trimmed.starts_with("switch(")
        || trimmed.starts_with("export default function")
        || trimmed.starts_with("export function")
    {
        return false;
    }

    // If line ends with `) {` after a function-like pattern, it's a statement block
    // e.g., `constructor(...) {`, `get name() {`, `set name(val) {`
    if trimmed.ends_with(") {") {
        // Check for method/constructor patterns
        if trimmed.starts_with("constructor(")
            || trimmed.starts_with("constructor (")
            || trimmed.starts_with("get ")
            || trimmed.starts_with("set ")
            || trimmed.starts_with("async ")
        {
            return false;
        }
        // Generic function call followed by `{` - e.g., named methods
        // If it has `(` and `) {` it's likely a function/method definition
        if let Some(paren_pos) = trimmed.find('(') {
            let before_paren = &trimmed[..paren_pos];
            // If the part before `(` is a simple identifier, it's a method definition
            if before_paren
                .chars()
                .all(|c| c.is_alphanumeric() || c == '_' || c == '$')
            {
                return false;
            }
        }
    }

    // Otherwise, `{` at the end typically opens an object literal
    // e.g., `Foo(args, {`, `return {`, `const x = {`, `key: {`
    true
}

/// Classify a line of server-generated code by its statement type.
fn classify_server_line(trimmed: &str) -> &'static str {
    if trimmed.starts_with("import ") {
        "ImportDeclaration"
    } else if trimmed.starts_with("export default function") {
        "ExportDefaultDeclaration"
    } else if trimmed.starts_with("export ") {
        "ExportNamedDeclaration"
    } else if trimmed.starts_with("var ")
        || trimmed.starts_with("let ")
        || trimmed.starts_with("const ")
    {
        "VariableDeclaration"
    } else if trimmed.starts_with("function ") || trimmed.starts_with("async function ") {
        "FunctionDeclaration"
    } else if trimmed.starts_with("return ")
        || trimmed.starts_with("return;")
        || trimmed == "return"
    {
        "ReturnStatement"
    } else if trimmed.starts_with("if ") || trimmed.starts_with("if(") {
        "IfStatement"
    } else if trimmed.starts_with("for ") || trimmed.starts_with("for(") {
        "ForStatement"
    } else if trimmed.starts_with("while ") || trimmed.starts_with("while(") {
        "WhileStatement"
    } else if trimmed.starts_with("class ") {
        "ClassDeclaration"
    } else if trimmed.starts_with("do ") || trimmed.starts_with("do{") {
        "DoWhileStatement"
    } else if trimmed.starts_with("/*") || trimmed.starts_with("//") {
        "Comment"
    } else {
        "ExpressionStatement"
    }
}

/// Check if a statement starting at line index `start` spans multiple lines.
fn is_server_stmt_multiline(lines: &[&str], start: usize, indent_level: usize) -> bool {
    // A statement is multiline if the next line at the same or deeper indent level
    // is a continuation (not a new statement at the same indent)
    if start + 1 >= lines.len() {
        return false;
    }

    // For opening braces like `for (...) {` or `function ... {`, the body is multiline
    let trimmed = lines[start].trim_start_matches('\t');
    if trimmed.ends_with('{') || trimmed.ends_with("=> {") {
        return true;
    }

    // Check if the immediate next non-empty line is at a deeper indent (continuation)
    for next in &lines[(start + 1)..] {
        let next = *next;
        if next.trim().is_empty() {
            continue;
        }
        let next_indent = next.bytes().take_while(|&b| b == b'\t').count();
        // If next line is deeper, this is multiline
        if next_indent > indent_level {
            return true;
        }
        break;
    }

    false
}

/// Split lines where a closing brace `}` is concatenated with a following statement.
/// For example, `\t\t}\t$$renderer.push(...)` becomes two lines:
/// `\t\t}` and `\t$$renderer.push(...)`.
/// This handles cases where the server build concatenates parts on the same line.
fn split_concatenated_braces(code: &str) -> String {
    let mut result = String::with_capacity(code.len() + 100);
    for line in code.lines() {
        let trimmed = line.trim();
        // Check if line starts with `}` followed by more content (not just `}` or `});` etc.)
        // Pattern: `}\t...` or `} ...` where ... is not empty and not just closing chars
        if let Some(rest_start) = trimmed.strip_prefix('}') {
            let rest = rest_start.trim_start();
            // If rest is non-empty and doesn't start with closing chars or comma,
            // and the rest looks like a new statement (not a continuation like `)` or `]`)
            if !rest.is_empty()
                && !rest.starts_with(')')
                && !rest.starts_with('(')
                && !rest.starts_with(']')
                && !rest.starts_with(',')
                && !rest.starts_with(';')
                && !rest.starts_with("else")
                && !rest.starts_with("while")
                && !rest.starts_with("catch")
                && !rest.starts_with("finally")
                && !rest.starts_with("from ")
                && !rest.starts_with("from\t")
                && rest != "}"
            {
                // Determine indentation of the original line
                let indent: String = line.chars().take_while(|c| c.is_whitespace()).collect();
                // The closing brace keeps the original indentation
                result.push_str(&indent);
                result.push('}');
                result.push('\n');
                // The following statement is at the same level as the closing brace
                // (it's a sibling statement after the block)
                result.push_str(&indent);
                result.push_str(rest);
                result.push('\n');
                continue;
            }
        }
        result.push_str(line);
        result.push('\n');
    }
    // Remove the extra trailing newline we added
    if result.ends_with('\n') {
        result.pop();
    }
    result
}

/// Determine whether a line ends inside a template literal, given the starting state.
///
/// This properly handles:
/// - Escaped characters (`\``, `\\`, etc.)
/// - String literals inside template expressions (`'...'`, `"..."`)
/// - Nested template literals inside `${...}` expressions
/// - `${...}` expression nesting depth
///
/// Returns `true` if we're inside a template literal at the end of the line.
fn line_ends_in_template_literal(line: &str, in_template_literal_at_start: bool) -> bool {
    let bytes = line.as_bytes();
    let len = bytes.len();
    let mut i = 0;

    // Stack tracks nesting: each entry is true if we're in a template literal,
    // false if we're in a ${} expression context.
    // When the stack is empty, we're at the top level (outside template literals).
    let mut in_tl = in_template_literal_at_start;
    // Track ${} nesting depth when inside a template literal.
    // When depth > 0, we're inside a ${} expression.
    let mut expr_depth: u32 = 0;
    // Track brace depth inside ${} expressions (for nested objects, functions, etc.)
    let mut brace_depth: u32 = 0;

    while i < len {
        let ch = bytes[i];

        if in_tl && expr_depth == 0 {
            // Inside a template literal (not inside a ${} expression)
            if ch == b'\\' {
                i += 2; // skip escaped character
                continue;
            }
            if ch == b'`' {
                // Closing backtick - exit template literal
                in_tl = false;
                i += 1;
                continue;
            }
            if ch == b'$' && i + 1 < len && bytes[i + 1] == b'{' {
                // Enter ${} expression
                expr_depth = 1;
                brace_depth = 0;
                i += 2;
                continue;
            }
            i += 1;
        } else if in_tl && expr_depth > 0 {
            // Inside a ${} expression within a template literal
            if ch == b'\\' {
                i += 2;
                continue;
            }
            if ch == b'\'' || ch == b'"' {
                // Skip string literal inside expression
                let quote = ch;
                i += 1;
                while i < len && bytes[i] != quote {
                    if bytes[i] == b'\\' {
                        i += 2;
                    } else {
                        i += 1;
                    }
                }
                if i < len {
                    i += 1; // skip closing quote
                }
                continue;
            }
            if ch == b'`' {
                // Nested template literal inside expression
                // We push into a "nested template literal" context.
                // For simplicity, recursively process from this point.
                // Actually, since we track state with a simple model,
                // handle this by incrementing expr_depth would be wrong.
                // Instead, recursively scan the nested template literal.
                let remaining = &line[i..];
                let consumed = skip_template_literal_from_start(remaining);
                i += consumed;
                continue;
            }
            if ch == b'{' {
                brace_depth += 1;
                i += 1;
                continue;
            }
            if ch == b'}' {
                if brace_depth > 0 {
                    brace_depth -= 1;
                } else {
                    // Close the ${} expression, back to template literal content
                    expr_depth = 0;
                }
                i += 1;
                continue;
            }
            i += 1;
        } else {
            // Outside template literal (top level or after closing a template literal)
            if ch == b'\\' {
                i += 2;
                continue;
            }
            if ch == b'\'' || ch == b'"' {
                // Skip string literal at top level
                let quote = ch;
                i += 1;
                while i < len && bytes[i] != quote {
                    if bytes[i] == b'\\' {
                        i += 2;
                    } else {
                        i += 1;
                    }
                }
                if i < len {
                    i += 1; // skip closing quote
                }
                continue;
            }
            if ch == b'`' {
                // Opening backtick - enter template literal
                in_tl = true;
                expr_depth = 0;
                brace_depth = 0;
                i += 1;
                continue;
            }
            i += 1;
        }
    }

    in_tl
}

/// Skip a complete template literal starting at position 0 (which must be a backtick).
/// Returns the number of bytes consumed (including the opening and closing backticks).
/// If the template literal is not closed on this line, returns the length of the input.
fn skip_template_literal_from_start(s: &str) -> usize {
    let bytes = s.as_bytes();
    let len = bytes.len();
    debug_assert!(bytes[0] == b'`');
    let mut i = 1; // skip opening backtick
    let mut brace_depth: u32 = 0;
    let mut in_expr = false;

    while i < len {
        let ch = bytes[i];

        if !in_expr {
            // Inside template literal content
            if ch == b'\\' {
                i += 2;
                continue;
            }
            if ch == b'`' {
                return i + 1; // closing backtick
            }
            if ch == b'$' && i + 1 < len && bytes[i + 1] == b'{' {
                in_expr = true;
                brace_depth = 0;
                i += 2;
                continue;
            }
            i += 1;
        } else {
            // Inside ${} expression
            if ch == b'\\' {
                i += 2;
                continue;
            }
            if ch == b'\'' || ch == b'"' {
                let quote = ch;
                i += 1;
                while i < len && bytes[i] != quote {
                    if bytes[i] == b'\\' {
                        i += 2;
                    } else {
                        i += 1;
                    }
                }
                if i < len {
                    i += 1;
                }
                continue;
            }
            if ch == b'`' {
                // Nested template literal
                let consumed = skip_template_literal_from_start(&s[i..]);
                i += consumed;
                continue;
            }
            if ch == b'{' {
                brace_depth += 1;
                i += 1;
                continue;
            }
            if ch == b'}' {
                if brace_depth > 0 {
                    brace_depth -= 1;
                } else {
                    in_expr = false;
                }
                i += 1;
                continue;
            }
            i += 1;
        }
    }

    len // template literal not closed on this line
}

/// Strip $effect and $effect.root blocks from source code.
/// In SSR, effects don't run, so they should be removed or replaced with no-ops.
/// - `$effect.root(() => { ... })` -> `() => {}` (returns a no-op cleanup function)
/// - `$effect(() => { ... })` -> removed entirely (statement-level only)
/// - `$effect.pre(() => { ... })` -> removed entirely (statement-level only)
fn strip_effects_from_source(source: &str) -> String {
    use super::client::find_matching_paren;
    let mut result = source.to_string();

    let finder_root = memmem::Finder::new(b"$effect.root(");
    let finder_pre = memmem::Finder::new(b"$effect.pre(");
    let finder_effect = memmem::Finder::new(b"$effect(");

    // Replace $effect.root(() => { ... }) with () => {} (a no-op cleanup function)
    // $effect.root returns a cleanup function, so we need to provide one.
    while let Some(pos) = finder_root.find(result.as_bytes()) {
        let call_start = pos + 13; // after "$effect.root("
        if let Some(content_end) = find_matching_paren(&result[call_start..]) {
            let expr_end = call_start + content_end + 1; // after closing paren
            let mut new_result = String::with_capacity(pos + 7 + result.len() - expr_end);
            new_result.push_str(&result[..pos]);
            new_result.push_str("() => {}");
            new_result.push_str(&result[expr_end..]);
            result = new_result;
        } else {
            break;
        }
    }

    // Strip $effect.pre(() => { ... }) blocks
    while let Some(pos) = finder_pre.find(result.as_bytes()) {
        let call_start = pos + 12;
        if let Some(content_end) = find_matching_paren(&result[call_start..]) {
            let expr_end = call_start + content_end + 1;
            let mut end = expr_end;
            while end < result.len() && result.as_bytes()[end].is_ascii_whitespace() {
                end += 1;
            }
            if end < result.len() && result.as_bytes()[end] == b';' {
                end += 1;
            }
            let mut new_result = String::with_capacity(pos + result.len() - end);
            new_result.push_str(&result[..pos]);
            new_result.push_str(&result[end..]);
            result = new_result;
        } else {
            break;
        }
    }

    // Strip $effect(() => { ... }) blocks (but not $effect.root/$effect.pre which were already handled)
    while let Some(pos) = finder_effect.find(result.as_bytes()) {
        // Make sure this is not $effect.something (should already be handled above)
        if pos + 8 < result.len() && result.as_bytes()[pos + 7] == b'.' {
            break; // shouldn't happen since $effect.root and $effect.pre are already handled
        }
        let call_start = pos + 8; // after "$effect("
        if let Some(content_end) = find_matching_paren(&result[call_start..]) {
            let expr_end = call_start + content_end + 1;
            let mut end = expr_end;
            while end < result.len() && result.as_bytes()[end].is_ascii_whitespace() {
                end += 1;
            }
            if end < result.len() && result.as_bytes()[end] == b';' {
                end += 1;
            }
            let mut new_result = String::with_capacity(pos + result.len() - end);
            new_result.push_str(&result[..pos]);
            new_result.push_str(&result[end..]);
            result = new_result;
        } else {
            break;
        }
    }

    result
}

/// Post-process client module transform output for server context.
/// Replaces client-specific runtime calls with server equivalents.
fn post_process_for_server(source: &str) -> String {
    use super::client::find_matching_paren;
    let mut result = source.to_string();

    let finder_effect_root = memmem::Finder::new(b"$.effect_root(");
    let finder_user_effect = memmem::Finder::new(b"$.user_effect(");
    let finder_proxy = memmem::Finder::new(b"$.proxy(");
    let finder_get = memmem::Finder::new(b"$.get(");
    let finder_set = memmem::Finder::new(b"$.set(");
    let finder_update = memmem::Finder::new(b"$.update(");
    let finder_update_pre = memmem::Finder::new(b"$.update_pre(");
    let finder_state = memmem::Finder::new(b"$.state(");

    // Helper: splice result string efficiently without format!
    macro_rules! splice {
        ($result:expr, $before_end:expr, $middle:expr, $after_start:expr) => {{
            let before = &$result[..$before_end];
            let after = &$result[$after_start..];
            let mut new = String::with_capacity(before.len() + $middle.len() + after.len());
            new.push_str(before);
            new.push_str($middle);
            new.push_str(after);
            new
        }};
    }

    // Replace $.effect_root(...) with () => {} (no-op cleanup)
    while let Some(pos) = finder_effect_root.find(result.as_bytes()) {
        let call_start = pos + 14;
        if let Some(content_end) = find_matching_paren(&result[call_start..]) {
            let expr_end = call_start + content_end + 1;
            result = splice!(result, pos, "() => {}", expr_end);
        } else {
            break;
        }
    }

    // Remove $.user_effect(...) calls
    while let Some(pos) = finder_user_effect.find(result.as_bytes()) {
        let call_start = pos + 14;
        if let Some(content_end) = find_matching_paren(&result[call_start..]) {
            let expr_end = call_start + content_end + 1;
            let mut end = expr_end;
            while end < result.len() && result.as_bytes()[end].is_ascii_whitespace() {
                end += 1;
            }
            if end < result.len() && result.as_bytes()[end] == b';' {
                end += 1;
            }
            result = splice!(result, pos, "", end);
        } else {
            break;
        }
    }

    // Replace $.proxy(x) with just x (no proxying on server)
    while let Some(pos) = finder_proxy.find(result.as_bytes()) {
        let call_start = pos + 8;
        if let Some(content_end) = find_matching_paren(&result[call_start..]) {
            let content = result[call_start..call_start + content_end].to_string();
            result = splice!(result, pos, &content, call_start + content_end + 1);
        } else {
            break;
        }
    }

    // Replace $.get(x) for server modules:
    // - Simple identifiers: $.get(x) -> x (plain variable)
    // - Member expressions (this.#x): $.get(this.#x) -> this.#x() (callable signal in class)
    while let Some(pos) = finder_get.find(result.as_bytes()) {
        let call_start = pos + 6;
        if let Some(content_end) = find_matching_paren(&result[call_start..]) {
            let content = result[call_start..call_start + content_end]
                .trim()
                .to_string();
            // Check if it's a member expression (contains '.')
            if memchr::memchr(b'.', content.as_bytes()).is_some() {
                // Member expression: keep as function call
                let mut replacement = String::with_capacity(content.len() + 2);
                replacement.push_str(&content);
                replacement.push_str("()");
                result = splice!(result, pos, &replacement, call_start + content_end + 1);
            } else {
                // Simple identifier: just the variable name
                result = splice!(result, pos, &content, call_start + content_end + 1);
            }
        } else {
            break;
        }
    }

    // Replace $.set(x, v[, flag]) for server modules:
    // - Simple identifiers: $.set(x, v) -> x = v
    // - Member expressions: $.set(this.#x, v) -> this.#x(v)
    while let Some(pos) = finder_set.find(result.as_bytes()) {
        let call_start = pos + 6;
        if let Some(content_end) = find_matching_paren(&result[call_start..]) {
            let content = result[call_start..call_start + content_end].to_string();
            if let Some(comma_pos) = find_first_comma(&content) {
                let signal = content[..comma_pos].trim();
                let rest = content[comma_pos + 1..].trim();
                // Rest might be "value, flag" - take only the value (up to second comma)
                let value = if let Some(comma2_pos) = find_first_comma(rest) {
                    rest[..comma2_pos].trim()
                } else {
                    rest
                };
                if memchr::memchr(b'.', signal.as_bytes()).is_some() {
                    // Member expression: function call form
                    let mut replacement = String::with_capacity(signal.len() + 1 + value.len() + 1);
                    replacement.push_str(signal);
                    replacement.push('(');
                    replacement.push_str(value);
                    replacement.push(')');
                    result = splice!(result, pos, &replacement, call_start + content_end + 1);
                } else {
                    // Simple identifier: assignment form
                    let mut replacement = String::with_capacity(signal.len() + 3 + value.len());
                    replacement.push_str(signal);
                    replacement.push_str(" = ");
                    replacement.push_str(value);
                    result = splice!(result, pos, &replacement, call_start + content_end + 1);
                }
            } else {
                break;
            }
        } else {
            break;
        }
    }

    // Replace $.update_pre(x) with ++x for server modules
    // IMPORTANT: Process $.update_pre BEFORE $.update to avoid prefix matching issues
    while let Some(pos) = finder_update_pre.find(result.as_bytes()) {
        let call_start = pos + 13;
        if let Some(content_end) = find_matching_paren(&result[call_start..]) {
            let content = result[call_start..call_start + content_end].trim();
            let mut replacement = String::with_capacity(content.len() + 2);
            replacement.push_str("++");
            replacement.push_str(content);
            result = splice!(result, pos, &replacement, call_start + content_end + 1);
        } else {
            break;
        }
    }

    // Replace $.update(x) with x++ for server modules
    while let Some(pos) = finder_update.find(result.as_bytes()) {
        let call_start = pos + 9;
        if let Some(content_end) = find_matching_paren(&result[call_start..]) {
            let content = result[call_start..call_start + content_end].trim();
            let mut replacement = String::with_capacity(content.len() + 2);
            replacement.push_str(content);
            replacement.push_str("++");
            result = splice!(result, pos, &replacement, call_start + content_end + 1);
        } else {
            break;
        }
    }

    // Replace $.derived(() => expr) with just expr for module-level (non-class) derived
    // In class contexts, $.derived is kept as-is (server runtime has $.derived for classes)
    let derived_patterns: &[(&[u8], usize)] = &[
        (b"$.derived(" as &[u8], 10),
        (b"$.derived_safe_equal(" as &[u8], 21),
    ];
    for &(pattern_bytes, pattern_len) in derived_patterns {
        let finder = memmem::Finder::new(pattern_bytes);
        while let Some(pos) = finder.find(result.as_bytes()) {
            // Check if this is inside a class body by looking for preceding class-like context
            // If it's a class field assignment (e.g., #field = $.derived(...)), skip it
            let before = &result[..pos];
            let trimmed_before = before.trim_end();
            let is_class_field = trimmed_before.ends_with('=') && {
                // Check if the line starts with # or this. (class field/constructor)
                let line_start = before.rfind('\n').map(|p| p + 1).unwrap_or(0);
                let line = before[line_start..].trim_start();
                line.starts_with('#') || line.starts_with("this.#") || line.starts_with("this.")
            };

            if is_class_field {
                // Don't strip $.derived in class context - skip past this occurrence
                break; // Can't easily skip since positions change; just stop processing
            }

            let call_start = pos + pattern_len;
            if let Some(content_end) = find_matching_paren(&result[call_start..]) {
                let content = result[call_start..call_start + content_end]
                    .trim()
                    .to_string();
                // If content is an arrow function () => expr, extract just the expr
                let value = if content.starts_with("() =>") {
                    content.trim_start_matches("() =>").trim().to_string()
                } else {
                    content
                };
                result = splice!(result, pos, &value, call_start + content_end + 1);
            } else {
                break;
            }
        }
    }

    // Replace $.state(x) with just x (no signals on server)
    while let Some(pos) = finder_state.find(result.as_bytes()) {
        let call_start = pos + 8;
        if let Some(content_end) = find_matching_paren(&result[call_start..]) {
            let content = result[call_start..call_start + content_end].to_string();
            let trimmed = content.trim();
            let value = if trimmed.is_empty() {
                "void 0"
            } else {
                trimmed
            };
            result = splice!(result, pos, value, call_start + content_end + 1);
        } else {
            break;
        }
    }

    result
}

/// Find the position of the first comma at depth 0 in a string.
fn find_first_comma(s: &str) -> Option<usize> {
    let mut depth = 0i32;
    for (i, c) in s.char_indices() {
        match c {
            '(' | '[' | '{' => depth += 1,
            ')' | ']' | '}' => depth -= 1,
            ',' if depth == 0 => return Some(i),
            _ => {}
        }
    }
    None
}

/// Server-side code generator.
pub(crate) struct ServerCodeGenerator<'a> {
    pub(crate) component_name: String,
    pub(crate) source: String,
    pub(crate) output_parts: Vec<OutputPart>,
    pub(crate) instance_script: Option<&'a Script>,
    /// Module script (context="module") - executed at module level outside component
    pub(crate) module_script: Option<&'a Script>,
    /// Map of constant variable names to their values
    pub(crate) constant_vars: FxHashMap<String, String>,
    /// Snippet definitions to be generated at module level
    pub(crate) snippets: Vec<SnippetDef>,
    /// Component analysis from Phase 2
    pub(crate) analysis: Option<&'a ComponentAnalysis>,
    /// Whether the component uses store subscriptions (requires $$store_subs variable)
    pub(crate) uses_store_subs: bool,
    /// Whether experimental.async is enabled
    pub(crate) use_async: bool,
    /// CSS injection info (hash, code) if css="injected"
    pub(crate) injected_css: Option<(String, String)>,
    /// Whether to skip hydration boundaries (empty comment markers after RenderTags/Components)
    /// This is true when the current fragment is "standalone" (contains only a single RenderTag/Component)
    pub(crate) skip_hydration_boundaries: bool,
    /// Whether the component uses TypeScript (lang="ts")
    pub(crate) is_typescript: bool,
    /// Current namespace context (html, svg, mathml).
    /// In SVG namespace, whitespace-only text nodes between elements are entirely removed.
    pub(crate) namespace: String,
    /// Whether to preserve whitespace (from <svelte:options preserveWhitespace /> or compile option).
    pub(crate) preserve_whitespace: bool,
    /// Whether to preserve HTML comments in server output (from preserveComments option).
    pub(crate) preserve_comments: bool,
    /// Whether dev mode is enabled (for $.validate_snippet_args etc.)
    pub(crate) dev: bool,
    /// Whether compatibility.componentApi === 4 (legacy class API)
    pub(crate) component_api_v4: bool,
    /// Filename for dev mode (used for FILENAME assignment)
    pub(crate) filename: Option<String>,
    /// Whether we're inside a control-flow block body (if/each block body).
    /// When true, async expressions use plain `await expr` instead of `(await $.save(expr))()`.
    pub(crate) in_block_body: bool,
    /// Whether we're inside an if block body specifically.
    /// When true, async expressions use plain `await expr` instead of `(await $.save(expr))()`.
    /// Each block bodies still use $.save().
    pub(crate) in_if_body: bool,
    /// Counter for generating unique promise group names (promises, promises_1, promises_2, ...)
    /// Shared across nested generators via Rc<Cell> to ensure unique names across the component.
    pub(crate) const_promises_counter: std::rc::Rc<std::cell::Cell<usize>>,
    /// Mapping from variable names to their const-level blocker expressions.
    /// When a const tag declares an async variable in a `$$renderer.run()` group,
    /// the blocker (e.g., "promises[0]") is recorded here for subsequent const tags
    /// and expression tags to use for `$$renderer.async()` wrapping.
    /// Shared across nested generators via Rc<RefCell> so blockers from outer boundaries
    /// are visible in inner boundaries.
    pub(crate) const_blocker_map:
        std::rc::Rc<std::cell::RefCell<rustc_hash::FxHashMap<String, String>>>,
    /// Accumulator for async const tag grouping.
    /// When an async const tag is encountered, subsequent const tags in the same fragment
    /// are accumulated into this group. Flushed by the fragment visitor after processing all nodes.
    /// Format: (group_name, thunks, declared_variable_names_with_thunk_indices)
    pub(crate) async_consts: Option<AsyncConstsGroup>,
}

/// Accumulator for grouping multiple const tags into a single `$$renderer.run()` call.
pub(crate) struct AsyncConstsGroup {
    /// The promise group name (e.g., "promises", "promises_1")
    pub name: String,
    /// The accumulated thunks (each is a string like "async () => { ... }" or "() => { ... }")
    pub thunks: Vec<(String, bool)>, // (thunk_code, is_async)
    /// Variable names declared in this group, with their thunk index for blocker registration
    pub declared_vars: Vec<(String, usize)>,
}

impl<'a> ServerCodeGenerator<'a> {
    pub(crate) fn new(
        component_name: String,
        source: String,
        instance_script: Option<&'a Script>,
        module_script: Option<&'a Script>,
        analysis: Option<&'a ComponentAnalysis>,
        use_async: bool,
    ) -> Self {
        // Extract constant variables from script
        let mut constant_vars = FxHashMap::default();

        // Extract constants from module script first (only const declarations)
        if let Some(script) = module_script {
            let start = script.content.start().unwrap_or(0) as usize;
            let end = script.content.end().unwrap_or(0) as usize;
            if end > start && end <= source.len() {
                for (k, v) in extract_constant_vars(&source[start..end], &source) {
                    constant_vars.insert(k, v);
                }
            }
        }

        // Then from instance script (both let and const)
        if let Some(script) = instance_script {
            let start = script.content.start().unwrap_or(0) as usize;
            let end = script.content.end().unwrap_or(0) as usize;
            if end > start && end <= source.len() {
                for (k, v) in extract_constant_vars(&source[start..end], &source) {
                    constant_vars.insert(k, v);
                }
            }
        }

        // Add scope-based constants for $state variables that are not updated.
        // The text-based extraction skips $state lines, but if scope analysis shows
        // a $state binding is never reassigned/mutated, we can fold its initial value.
        if let Some(analysis) = analysis {
            for binding in &analysis.root.bindings {
                if matches!(binding.kind, BindingKind::State | BindingKind::RawState)
                    && !binding.is_updated()
                    && !constant_vars.contains_key(&binding.name)
                    && let Some(ref init) = binding.initial
                {
                    let trimmed = init.trim();
                    // Parse the initial value as a constant
                    if (trimmed.starts_with('\'') && trimmed.ends_with('\''))
                        || (trimmed.starts_with('"') && trimmed.ends_with('"'))
                    {
                        if trimmed.len() >= 2 {
                            constant_vars.insert(
                                binding.name.clone(),
                                trimmed[1..trimmed.len() - 1].to_string(),
                            );
                        }
                    } else if let Ok(n) = trimmed.parse::<i64>() {
                        constant_vars.insert(binding.name.clone(), n.to_string());
                    } else if let Ok(n) = trimmed.parse::<f64>() {
                        if n.is_finite() {
                            constant_vars.insert(binding.name.clone(), n.to_string());
                        }
                    } else {
                        match trimmed {
                            "true" | "false" | "null" | "undefined" => {
                                constant_vars.insert(binding.name.clone(), trimmed.to_string());
                            }
                            _ => {}
                        }
                    }
                }
            }
        }

        // Check if any script uses TypeScript (needed for $derived expression stripping)
        let is_ts = instance_script.is_some_and(script_is_typescript)
            || module_script.is_some_and(script_is_typescript);

        // After we have both text-based and scope-based constants, try to fold
        // $derived() expressions whose inner value can be evaluated with known constants.
        // $derived values are readonly by definition, so they're safe to fold.
        if let Some(script) = instance_script {
            let start = script.content.start().unwrap_or(0) as usize;
            let end = script.content.end().unwrap_or(0) as usize;
            if end > start && end <= source.len() {
                let script_content = &source[start..end];
                for line in script_content.lines() {
                    let trimmed = line.trim();
                    let tb = trimmed.as_bytes();
                    if memmem::find(tb, b"$derived(").is_none()
                        || memmem::find(tb, b"$derived.by(").is_some()
                    {
                        continue;
                    }
                    let decl_trimmed = if let Some(rest) = trimmed.strip_prefix("export ") {
                        rest.trim_start()
                    } else {
                        trimmed
                    };
                    let decl_start = if decl_trimmed.starts_with("const ") {
                        Some(6)
                    } else if decl_trimmed.starts_with("let ") {
                        Some(4)
                    } else {
                        None
                    };
                    if let Some(s) = decl_start {
                        let rest = &decl_trimmed[s..];
                        if let Some(eq_idx) = rest.find('=') {
                            let name = rest[..eq_idx].trim();
                            if name.contains('{')
                                || name.contains('[')
                                || constant_vars.contains_key(name)
                            {
                                continue;
                            }
                            let value = rest[eq_idx + 1..].trim().trim_end_matches(';');
                            if let Some(inner) = extract_rune_inner(value, "$derived(") {
                                // Strip TypeScript syntax (as T, !, etc.) from inner expression
                                let inner = strip_ts_from_derived_inner(&inner, is_ts);
                                if let Some(folded) =
                                    try_evaluate_with_constants(&inner, &constant_vars)
                                {
                                    constant_vars.insert(name.to_string(), folded);
                                }
                            }
                        }
                    }
                }
            }
        }

        // Remove BindableProp variables from constant_vars.
        // Variables exported via `export { x }` are props and can receive values from parents,
        // so they should NOT be treated as constants even if they have literal initial values.
        // Also remove any binding that the scope analysis marks as updated (reassigned or mutated),
        // to handle cases that the text-based reassignment check misses (e.g. destructuring
        // assignments like `({ x } = { x: 1 })`).
        if let Some(analysis) = analysis {
            for binding in &analysis.root.bindings {
                if matches!(binding.kind, BindingKind::BindableProp) || binding.is_updated() {
                    constant_vars.remove(&binding.name);
                }
            }
        }

        // When experimental.async is enabled, remove variables that are in the
        // blocker_map from constant_vars. These variables are assigned asynchronously
        // in $$promises thunks and should NOT be constant-folded, because they need to
        // be rendered via $$renderer.async() wrappers.
        if use_async && let Some(script) = instance_script {
            let start = script.content.start().unwrap_or(0) as usize;
            let end = script.content.end().unwrap_or(0) as usize;
            if end > start && end <= source.len() {
                let raw_script = &source[start..end];
                let blocker_map = crate::compiler::phases::phase3_transform::shared::async_body::compute_blocker_map(raw_script);
                for name in blocker_map.keys() {
                    constant_vars.remove(name);
                }
            }
        }

        // Check if the analysis has any StoreSub bindings
        let uses_store_subs = analysis
            .map(|a| {
                a.root
                    .bindings
                    .iter()
                    .any(|b| matches!(b.kind, BindingKind::StoreSub))
            })
            .unwrap_or(false);

        // Check if any script uses TypeScript
        let is_typescript = instance_script.is_some_and(script_is_typescript)
            || module_script.is_some_and(script_is_typescript);

        // Determine namespace from component analysis
        let namespace = if analysis.is_some_and(|a| a.component_namespace_is_svg) {
            "svg".to_string()
        } else if analysis.is_some_and(|a| a.component_namespace_is_mathml) {
            "mathml".to_string()
        } else {
            "html".to_string()
        };

        Self {
            component_name,
            source,
            // Pre-allocate capacity based on typical component sizes
            // Average component has ~50-100 output parts
            output_parts: Vec::new(),
            instance_script,
            module_script,
            constant_vars,
            // Most components have 0-5 snippets
            snippets: Vec::new(),
            analysis,
            uses_store_subs,
            use_async,
            injected_css: None,
            skip_hydration_boundaries: false,
            is_typescript,
            namespace,
            preserve_whitespace: false,
            preserve_comments: false,
            dev: false,
            component_api_v4: false,
            filename: None,
            in_block_body: false,
            in_if_body: false,
            const_promises_counter: std::rc::Rc::new(std::cell::Cell::new(0)),
            const_blocker_map: std::rc::Rc::new(std::cell::RefCell::new(
                rustc_hash::FxHashMap::default(),
            )),
            async_consts: None,
        }
    }

    /// Create a generator for a child fragment with the given skip_hydration_boundaries flag
    pub(crate) fn new_child_generator(&self, skip_hydration_boundaries: bool) -> Self {
        Self {
            component_name: self.component_name.clone(),
            source: self.source.clone(),
            output_parts: Vec::new(),
            instance_script: None,
            module_script: None,
            constant_vars: self.constant_vars.clone(),
            snippets: Vec::new(),
            analysis: self.analysis,
            uses_store_subs: self.uses_store_subs,
            use_async: self.use_async,
            injected_css: None,
            skip_hydration_boundaries,
            is_typescript: self.is_typescript,
            namespace: self.namespace.clone(),
            preserve_whitespace: self.preserve_whitespace,
            preserve_comments: self.preserve_comments,
            dev: self.dev,
            component_api_v4: self.component_api_v4,
            filename: self.filename.clone(),
            in_block_body: self.in_block_body,
            in_if_body: self.in_if_body,
            const_promises_counter: self.const_promises_counter.clone(),
            const_blocker_map: self.const_blocker_map.clone(),
            async_consts: None,
        }
    }

    /// Set the injected CSS info (for css="injected" mode)
    pub(crate) fn set_injected_css(&mut self, hash: String, code: String) {
        self.injected_css = Some((hash, code));
    }

    /// Transform store subscriptions in an expression.
    /// Converts `$store` to `$.store_get($$store_subs ??= {}, '$store', store)`.
    pub(crate) fn transform_store_refs(&self, expr: &str) -> String {
        if !self.uses_store_subs {
            return expr.to_string();
        }

        let analysis = match self.analysis {
            Some(a) => a,
            None => return expr.to_string(),
        };

        // Collect store subscription names from the analysis
        let store_sub_names: Vec<&str> = analysis
            .root
            .bindings
            .iter()
            .filter(|b| matches!(b.kind, BindingKind::StoreSub))
            .map(|b| b.name.as_str())
            .collect();

        if store_sub_names.is_empty() {
            return expr.to_string();
        }

        let mut result = expr.to_string();

        // Transform each store subscription
        for name in store_sub_names {
            // Skip if it doesn't start with $
            if !name.starts_with('$') {
                continue;
            }

            // Get the store variable name (without $)
            let store_name = &name[1..];

            // Replace $store with $.store_get($$store_subs ??= {}, '$store', store)
            // We need to be careful to only replace complete identifiers, not substrings
            result = replace_store_identifier(&result, name, store_name);
        }

        result
    }

    /// Transform special legacy variables in template expressions.
    /// In server-side legacy mode, `$$props` should be replaced with `$$sanitized_props`
    /// (as the official Svelte compiler does in its Identifier.js server visitor).
    pub(crate) fn transform_special_vars(&self, expr: &str) -> String {
        let analysis = match self.analysis {
            Some(a) => a,
            None => return expr.to_string(),
        };

        if analysis.runes {
            return expr.to_string();
        }

        // Replace $$props with $$sanitized_props if uses_props is set
        if analysis.uses_props && memmem::find(expr.as_bytes(), b"$$props").is_some() {
            return replace_identifier_in_expr(expr, "$$props", "$$sanitized_props");
        }

        expr.to_string()
    }

    /// Transform rune calls in template expressions for server-side rendering.
    /// Handles: $state.eager(x) -> x, $state.snapshot(x) -> $.snapshot(x),
    ///          $effect.tracking() -> false, $effect.pending() -> false
    pub(crate) fn transform_rune_in_template_expr(expr: &str) -> String {
        use crate::compiler::phases::phase3_transform::server::transform_script::remove_effect_blocks;

        let result_bytes = expr.as_bytes();
        let mut result = expr.to_string();
        // $state.eager(x) -> x (unwrap the rune call)
        if memmem::find(result_bytes, b"$state.eager(").is_some() {
            result = transform_rune_call_simple(&result, "$state.eager(");
        }
        // $state.snapshot(x) -> $.snapshot(x)
        if memmem::find(result.as_bytes(), b"$state.snapshot(").is_some() {
            result = result.replace("$state.snapshot(", "$.snapshot(");
        }
        // $effect.tracking() -> false
        if memmem::find(result.as_bytes(), b"$effect.tracking()").is_some() {
            result = result.replace("$effect.tracking()", "false");
        }
        // $effect.pending() -> 0 (number, matching official compiler)
        if memmem::find(result.as_bytes(), b"$effect.pending()").is_some() {
            result = result.replace("$effect.pending()", "0");
        }
        // Remove $effect(), $effect.pre(), $effect.root(), $inspect(), $inspect.trace() blocks
        // These are client-side only and should be stripped in SSR template expressions too
        if memmem::find(result.as_bytes(), b"$effect(").is_some()
            || memmem::find(result.as_bytes(), b"$effect.pre(").is_some()
            || memmem::find(result.as_bytes(), b"$effect.root(").is_some()
            || memmem::find(result.as_bytes(), b"$inspect(").is_some()
            || memmem::find(result.as_bytes(), b"$inspect.trace(").is_some()
        {
            result = remove_effect_blocks(&result, false, false);
        }
        result
    }

    /// Strip TypeScript syntax from a template expression string.
    ///
    /// This wraps the expression in a parseable JavaScript statement (`var _ = EXPR;`),
    /// runs `strip_typescript()` to remove TS-specific syntax (like non-null assertions `!`,
    /// type assertions `as T`, etc.), then extracts the cleaned expression back.
    pub(crate) fn strip_ts_from_expr(&self, expr: &str) -> String {
        if !self.is_typescript {
            return expr.to_string();
        }
        use crate::compiler::phases::phase2_analyze::types::strip_typescript;
        let wrapper = format!("var _ = {};", expr);
        let stripped = strip_typescript(&wrapper);
        // Extract the expression back: "var _ = EXPR;"
        if let Some(rest) = stripped.strip_prefix("var _ = ") {
            let result = rest.trim_end_matches(';').trim();
            result.to_string()
        } else {
            // Fallback if stripping changed the structure
            expr.to_string()
        }
    }

    /// Strip TypeScript from a component prop string (e.g., `key: (arg: Type) => expr`).
    pub(crate) fn strip_ts_from_prop(&self, prop: &str) -> String {
        if !self.is_typescript {
            return prop.to_string();
        }
        use crate::compiler::phases::phase2_analyze::types::strip_typescript;
        let wrapper = format!("var _ = {{ {} }};", prop);
        let stripped = strip_typescript(&wrapper);
        // Extract back: "var _ = { PROP };"
        if let Some(rest) = stripped.strip_prefix("var _ = {") {
            let rest = rest.trim();
            if let Some(inner) = rest.strip_suffix("};") {
                let result = inner.trim();
                return result.to_string();
            }
        }
        prop.to_string()
    }

    /// Transform store subscriptions in script content.
    /// This is used for the instance script where store references like `$page`
    /// need to be transformed to `$.store_get($$store_subs ??= {}, '$page', page)`.
    pub(crate) fn transform_store_refs_in_script(&self, script: &str) -> String {
        if !self.uses_store_subs {
            return script.to_string();
        }

        let analysis = match self.analysis {
            Some(a) => a,
            None => return script.to_string(),
        };

        // Collect store subscription names from the analysis
        let store_sub_names: Vec<&str> = analysis
            .root
            .bindings
            .iter()
            .filter(|b| matches!(b.kind, BindingKind::StoreSub))
            .map(|b| b.name.as_str())
            .collect();

        if store_sub_names.is_empty() {
            return script.to_string();
        }

        let mut result = script.to_string();

        // Transform each store subscription
        for name in store_sub_names {
            // Skip if it doesn't start with $
            if !name.starts_with('$') {
                continue;
            }

            // Get the store variable name (without $)
            let store_name = &name[1..];

            // Replace $store with $.store_get($$store_subs ??= {}, '$store', store)
            // We need to be careful to only replace complete identifiers, not substrings
            // Also need to skip store assignments which are handled separately
            result = replace_store_identifier_in_script(&result, name, store_name);
        }

        result
    }

    /// Collect store subscription names from the analysis.
    /// Returns a list of (store_ref, store_name) pairs like ("$a", "a").
    pub(crate) fn get_store_sub_names(&self) -> Vec<(String, String)> {
        if !self.uses_store_subs {
            return Vec::new();
        }

        let analysis = match self.analysis {
            Some(a) => a,
            None => return Vec::new(),
        };

        analysis
            .root
            .bindings
            .iter()
            .filter(|b| matches!(b.kind, BindingKind::StoreSub))
            .filter(|b| b.name.starts_with('$'))
            .map(|b| (b.name.clone(), b.name[1..].to_string()))
            .collect()
    }

    /// Check if a fragment is "standalone" (contains only a single RenderTag or Component).
    /// When standalone, hydration boundaries can be skipped because the parent's anchors are sufficient.
    pub(crate) fn is_standalone_fragment(nodes: &[TemplateNode]) -> bool {
        // Filter out whitespace-only text, comments, and hoisted nodes
        // (matching clean_nodes behavior in the official compiler)
        let meaningful_nodes: Vec<_> = nodes
            .iter()
            .filter(|n| match n {
                TemplateNode::Text(text) => !is_svelte_whitespace_only(&text.data),
                TemplateNode::Comment(_) => false,
                // These node types are hoisted out by clean_nodes in the official compiler
                TemplateNode::SnippetBlock(_) => false,
                TemplateNode::ConstTag(_) => false,
                TemplateNode::SvelteBody(_) => false,
                TemplateNode::SvelteWindow(_) => false,
                TemplateNode::SvelteDocument(_) => false,
                TemplateNode::SvelteHead(_) => false,
                TemplateNode::TitleElement(_) => false,
                _ => true,
            })
            .collect();

        // Standalone if there's exactly one node and it's a non-dynamic RenderTag or Component
        // (matching official compiler's clean_nodes logic)
        if meaningful_nodes.len() != 1 {
            return false;
        }
        match meaningful_nodes[0] {
            TemplateNode::RenderTag(tag) => !tag.metadata.dynamic,
            TemplateNode::Component(comp) => {
                !comp.metadata.dynamic
                    && !comp.attributes.iter().any(|attr| {
                        matches!(attr, crate::ast::template::Attribute::Attribute(a) if a.name.starts_with("--"))
                    })
            }
            _ => false,
        }
    }

    /// Apply the official compiler's `clean_nodes` whitespace collapsing logic.
    ///
    /// When hoisted nodes (SnippetBlock, ConstTag, etc.) are between text nodes,
    /// the whitespace should be collapsed as if the hoisted nodes don't exist.
    /// e.g., `A\n{#snippet}...{/snippet}\nB` becomes `A B` (single space).
    ///
    /// Corresponds to `clean_nodes` in `svelte/packages/svelte/src/compiler/phases/3-transform/utils.js`.
    #[allow(dead_code)]
    pub(crate) fn clean_nodes_whitespace(
        nodes: &[TemplateNode],
        can_remove_entirely: bool,
    ) -> Vec<TemplateNode> {
        fn is_hoisted(n: &TemplateNode) -> bool {
            matches!(
                n,
                TemplateNode::SnippetBlock(_)
                    | TemplateNode::ConstTag(_)
                    | TemplateNode::SvelteBody(_)
                    | TemplateNode::SvelteWindow(_)
                    | TemplateNode::SvelteDocument(_)
                    | TemplateNode::SvelteHead(_)
                    | TemplateNode::TitleElement(_)
                    | TemplateNode::Comment(_)
            )
        }

        fn starts_with_ws(s: &str) -> bool {
            s.starts_with([' ', '\t', '\r', '\n', '\x0C'])
        }

        fn ends_with_ws(s: &str) -> bool {
            s.ends_with([' ', '\t', '\r', '\n', '\x0C'])
        }

        fn replace_leading_ws(s: &str, replacement: &str) -> String {
            let trimmed = s.trim_start_matches([' ', '\t', '\r', '\n', '\x0C']);
            format!("{}{}", replacement, trimmed)
        }

        fn replace_trailing_ws(s: &str, replacement: &str) -> String {
            let trimmed = s.trim_end_matches([' ', '\t', '\r', '\n', '\x0C']);
            format!("{}{}", trimmed, replacement)
        }

        let mut result: Vec<TemplateNode> = nodes.to_vec();

        // Build list of non-hoisted node indices for adjacency analysis
        let non_hoisted_indices: Vec<usize> = result
            .iter()
            .enumerate()
            .filter(|(_, n)| !is_hoisted(n))
            .map(|(i, _)| i)
            .collect();

        // Apply whitespace collapsing for text nodes based on non-hoisted neighbors
        for (pos, &idx) in non_hoisted_indices.iter().enumerate() {
            if let TemplateNode::Text(text) = &result[idx] {
                let mut data = text.data.to_string();

                let prev = if pos > 0 {
                    Some(&result[non_hoisted_indices[pos - 1]])
                } else {
                    None
                };
                let next = if pos + 1 < non_hoisted_indices.len() {
                    Some(&result[non_hoisted_indices[pos + 1]])
                } else {
                    None
                };

                // If prev is not an ExpressionTag, collapse leading whitespace
                if !matches!(prev, Some(TemplateNode::ExpressionTag(_))) && starts_with_ws(&data) {
                    let prev_ends =
                        matches!(prev, Some(TemplateNode::Text(t)) if ends_with_ws(&t.data));
                    let replacement = if prev_ends { "" } else { " " };
                    data = replace_leading_ws(&data, replacement);
                }

                // If next is not an ExpressionTag, collapse trailing whitespace
                if !matches!(next, Some(TemplateNode::ExpressionTag(_))) && ends_with_ws(&data) {
                    data = replace_trailing_ws(&data, " ");
                }

                // Skip empty or whitespace-only text in can_remove_entirely mode
                if data.is_empty() || (data == " " && can_remove_entirely) {
                    let mut modified = text.clone();
                    modified.data = "".into();
                    result[idx] = TemplateNode::Text(modified);
                    continue;
                }

                let mut modified = text.clone();
                modified.data = data.into();
                result[idx] = TemplateNode::Text(modified);
            }
        }

        // Filter out empty text nodes created by collapsing
        result
            .into_iter()
            .filter(|n| {
                if let TemplateNode::Text(t) = n {
                    !t.data.is_empty()
                } else {
                    true
                }
            })
            .collect()
    }

    /// Infer namespace from fragment children nodes.
    /// If all RegularElement children are SVG, returns "svg".
    /// If all are MathML, returns "mathml".
    /// Otherwise returns the parent namespace.
    fn infer_namespace_from_nodes_static(
        nodes: &[&TemplateNode],
        parent_namespace: &str,
    ) -> String {
        let mut found_namespace: Option<&str> = None;

        for node in nodes {
            if let TemplateNode::RegularElement(el) = node {
                if el.metadata.svg {
                    match found_namespace {
                        None => found_namespace = Some("svg"),
                        Some("svg") => {}
                        _ => return "html".to_string(),
                    }
                } else if el.metadata.mathml {
                    match found_namespace {
                        None => found_namespace = Some("mathml"),
                        Some("mathml") => {}
                        _ => return "html".to_string(),
                    }
                } else {
                    return "html".to_string();
                }
            }
        }

        found_namespace
            .map(|s| s.to_string())
            .unwrap_or_else(|| parent_namespace.to_string())
    }

    pub(crate) fn generate_component(&mut self, fragment: &Fragment) -> Result<(), TransformError> {
        let nodes: Vec<_> = fragment.nodes.iter().collect();
        let len = nodes.len();

        // Infer namespace from fragment children for SVG whitespace stripping
        let inferred_ns = Self::infer_namespace_from_nodes_static(&nodes, &self.namespace);
        if inferred_ns != self.namespace {
            self.namespace = inferred_ns.clone();
        }
        let can_remove_whitespace_entirely = inferred_ns == "svg";

        // Helper to check if a node is "meaningful" for SSR output purposes
        // SvelteWindow, SvelteDocument, SvelteBody don't render anything in SSR
        // When preserveWhitespace is true, whitespace-only text IS meaningful
        let preserve_ws = self.preserve_whitespace;
        let preserve_cmts = self.preserve_comments;
        let is_ssr_meaningful = |n: &&TemplateNode| {
            (!matches!(n, TemplateNode::Text(t) if is_svelte_whitespace_only(&t.data))
                || preserve_ws)
                && (!matches!(n, TemplateNode::Comment(_)) || preserve_cmts)
                && !matches!(n, TemplateNode::SvelteWindow(_))
                && !matches!(n, TemplateNode::SvelteDocument(_))
                && !matches!(n, TemplateNode::SvelteBody(_))
        };

        // Find indices of first and last non-whitespace nodes (excluding SSR-invisible elements)
        let first_meaningful_idx = nodes.iter().position(is_ssr_meaningful);
        let last_meaningful_idx = nodes.iter().rposition(is_ssr_meaningful);

        // Check if the root fragment is standalone (only a single RenderTag/Component)
        // to determine if we should skip hydration boundaries
        self.skip_hydration_boundaries = Self::is_standalone_fragment(&fragment.nodes);

        // If the first meaningful node is a Text or ExpressionTag, add <!---->
        // to prevent text fusion during hydration.
        // Skip SvelteOptions nodes since they don't produce output.
        let first_visible_idx = first_meaningful_idx.and_then(|start| {
            nodes[start..].iter().position(|n| {
                !matches!(n, TemplateNode::SvelteOptions(_))
                    && (preserve_ws || !matches!(n, TemplateNode::Text(t) if is_svelte_whitespace_only(&t.data)))
            }).map(|offset| start + offset)
        });
        let first_visible_node = first_visible_idx.map(|i| &nodes[i]);
        let needs_anchor = matches!(
            first_visible_node,
            Some(TemplateNode::Text(_)) | Some(TemplateNode::ExpressionTag(_))
        );

        if needs_anchor {
            self.output_parts
                .push(OutputPart::Html("<!---->".to_string()));
        }

        // Track whether we need to trim leading whitespace from the first text node
        // When an anchor comment is added, the next text should not have a leading space
        let mut trim_leading_ws = needs_anchor;
        // Track whether the previous visible text ended with whitespace.
        // Used to collapse whitespace across hoisted nodes (SnippetBlock, ConstTag).
        // When text before a hoisted node ends with whitespace and text after starts with
        // whitespace, the leading whitespace of the text-after is trimmed to avoid double space.
        let mut prev_text_ends_with_ws = false;

        for (i, node) in nodes.iter().enumerate() {
            // Skip whitespace-only text at root level (unless preserveWhitespace is set)
            if !self.preserve_whitespace
                && let TemplateNode::Text(text) = node
                && is_svelte_whitespace_only(&text.data)
            {
                // In SVG namespace, skip whitespace-only text nodes entirely
                // (matching official compiler's can_remove_entirely in clean_nodes)
                if can_remove_whitespace_entirely {
                    continue;
                }
                // Skip if there is no meaningful content at all (e.g. component with only
                // <script> blocks and no template nodes - whitespace between/after scripts
                // should not be emitted as $$renderer.push(` `)).
                if last_meaningful_idx.is_none() {
                    continue;
                }
                // Skip if before first meaningful content
                if first_meaningful_idx.is_some() && i < first_meaningful_idx.unwrap() {
                    continue;
                }
                // Skip if after last meaningful content
                if last_meaningful_idx.is_some() && i > last_meaningful_idx.unwrap() {
                    continue;
                }
                // Skip whitespace adjacent to snippets at root level, but only
                // when the snippet is at the edge (no non-hoisted content on the other side).
                // When snippets are between content nodes, we need to preserve one space
                // (matching clean_nodes which merges text around hoisted nodes).
                //
                // Check if previous node is a snippet at the leading edge.
                // Only skip whitespace after snippet when there's no real content
                // before the snippet (i.e., snippet is at the start of the fragment).
                // When the snippet is between content nodes, the whitespace should be
                // handled by prev_text_ends_with_ws collapsing, not skipped entirely.
                if i > 0
                    && let TemplateNode::SnippetBlock(_) = nodes[i - 1]
                {
                    let has_content_before_snippet = nodes[..i - 1].iter().any(|n| {
                        !matches!(n, TemplateNode::Text(t) if is_svelte_whitespace_only(&t.data))
                            && (!matches!(n, TemplateNode::Comment(_)) || self.preserve_comments)
                            && !matches!(n, TemplateNode::SnippetBlock(_))
                            && !matches!(n, TemplateNode::ConstTag(_))
                    });
                    if !has_content_before_snippet {
                        continue;
                    }
                    // When there IS content before, let the whitespace go through
                    // normal processing with prev_text_ends_with_ws collapsing
                }
                // Check if next node is a snippet
                if i + 1 < len
                    && let TemplateNode::SnippetBlock(_) = nodes[i + 1]
                {
                    // Check if there's meaningful content after the snippet
                    // If so, keep this whitespace to produce the space between the
                    // pre-snippet content and the post-snippet content
                    let has_content_after_snippet = nodes[i + 2..].iter().any(|n| {
                        !matches!(n, TemplateNode::Text(t) if is_svelte_whitespace_only(&t.data))
                            && (!matches!(n, TemplateNode::Comment(_)) || self.preserve_comments)
                            && !matches!(n, TemplateNode::SnippetBlock(_))
                    });
                    if !has_content_after_snippet {
                        continue;
                    }
                    // Keep this whitespace - it will produce a space
                }
                // Skip whitespace after SvelteHead (head elements are hoisted in official compiler)
                if i > 0 && matches!(nodes[i - 1], TemplateNode::SvelteHead(_)) {
                    continue;
                }
                // Skip whitespace before SvelteHead
                if i + 1 < len && matches!(nodes[i + 1], TemplateNode::SvelteHead(_)) {
                    continue;
                }
                // Skip whitespace around SvelteWindow/SvelteDocument/SvelteBody
                // (these don't render in SSR). But only skip if there's no visible
                // content on the other side - if both sides have visible content,
                // ONE whitespace node should be preserved to produce a space between them.
                // We always skip whitespace AFTER non-rendering nodes, and conditionally
                // keep whitespace BEFORE non-rendering nodes (to avoid double spaces).
                {
                    let is_non_rendering = |n: &TemplateNode| {
                        matches!(n, TemplateNode::SvelteWindow(_))
                            || matches!(n, TemplateNode::SvelteDocument(_))
                            || matches!(n, TemplateNode::SvelteBody(_))
                    };
                    let prev_is_non_rendering = i > 0 && is_non_rendering(nodes[i - 1]);
                    let next_is_non_rendering = i + 1 < len && is_non_rendering(nodes[i + 1]);

                    if prev_is_non_rendering {
                        // Always skip whitespace after a non-rendering node.
                        // The whitespace before the non-rendering node (if any) provides the space.
                        continue;
                    }
                    if next_is_non_rendering {
                        // Whitespace before a non-rendering node: keep only if there's
                        // visible content on both sides of the non-rendering group.
                        let has_visible_before = nodes[..i].iter().any(|n| {
                            !matches!(n, TemplateNode::Text(t) if is_svelte_whitespace_only(&t.data))
                                && !is_non_rendering(n)
                                && !matches!(n, TemplateNode::SvelteHead(_))
                                && !matches!(n, TemplateNode::SnippetBlock(_))
                                && !matches!(n, TemplateNode::ConstTag(_))
                                && !matches!(n, TemplateNode::DebugTag(_))
                                && (!matches!(n, TemplateNode::Comment(_)) || self.preserve_comments)
                        });
                        // Look past all consecutive non-rendering nodes + whitespace for visible content
                        let has_visible_after = {
                            let mut found = false;
                            let mut j = i + 1;
                            while j < len {
                                let n = nodes[j];
                                if is_non_rendering(n)
                                    || matches!(n, TemplateNode::Text(t) if is_svelte_whitespace_only(&t.data))
                                {
                                    j += 1;
                                    continue;
                                }
                                found = true;
                                break;
                            }
                            found
                        };

                        if !has_visible_before || !has_visible_after {
                            continue;
                        }
                        // Both sides have visible content - keep this whitespace
                    }
                }
                // Skip whitespace around DebugTag ({@debug} generates JS code but no HTML)
                if i > 0 && matches!(nodes[i - 1], TemplateNode::DebugTag(_)) {
                    continue;
                }
                if i + 1 < len && matches!(nodes[i + 1], TemplateNode::DebugTag(_)) {
                    continue;
                }
                // Comments are transparent during rendering (stripped in clean_nodes).
                // Whitespace before/after comments is handled naturally by the
                // prev_text_ends_with_ws collapsing mechanism, which also handles
                // whitespace around SnippetBlocks and ConstTags.
                // Whitespace AFTER a comment doesn't need special handling because
                // the Comment node doesn't reset prev_text_ends_with_ws.
            }
            // Handle text node modifications:
            // 1. Trim leading whitespace from the first text after anchor comment
            // 2. Trim trailing whitespace from the last meaningful text node
            // 3. Collapse leading whitespace when previous text ended with whitespace
            //    (across hoisted nodes like SnippetBlock)
            // Skip these modifications when preserveWhitespace is set
            if !self.preserve_whitespace
                && let TemplateNode::Text(text) = node
            {
                let mut modified_data = text.data.to_string();
                let mut needs_modification = false;

                // Trim leading whitespace if this is the first text after an anchor comment
                if trim_leading_ws {
                    let trimmed = modified_data.trim_start().to_string();
                    if trimmed != modified_data {
                        modified_data = trimmed;
                        needs_modification = true;
                    }
                    trim_leading_ws = false;
                }

                // Collapse leading whitespace when previous visible text ended with whitespace.
                // This handles the case where a hoisted node (SnippetBlock) was between
                // two text nodes: "A\n" + SnippetBlock + "\nB" → "A B" (not "A  B")
                if prev_text_ends_with_ws {
                    let trimmed = modified_data
                        .trim_start_matches(|c: char| {
                            matches!(c, ' ' | '\t' | '\r' | '\n' | '\x0C')
                        })
                        .to_string();
                    if trimmed != modified_data {
                        modified_data = trimmed;
                        needs_modification = true;
                    }
                }

                // Trim trailing whitespace from the last meaningful text node
                if last_meaningful_idx.is_some() && i == last_meaningful_idx.unwrap() {
                    let trimmed = modified_data.trim_end().to_string();
                    if trimmed != modified_data {
                        modified_data = trimmed;
                        needs_modification = true;
                    }
                }

                // Track whether this text ends with whitespace (for collapsing across hoisted nodes)
                prev_text_ends_with_ws = modified_data.ends_with([' ', '\t', '\r', '\n']);

                // Determine whether prev/next non-hoisted sibling is an ExpressionTag.
                let prev_is_expression = {
                    let mut pi = i;
                    loop {
                        if pi == 0 {
                            break false;
                        }
                        pi -= 1;
                        let pn = &nodes[pi];
                        let pn_hoisted = matches!(pn, TemplateNode::ConstTag(_))
                            || matches!(pn, TemplateNode::SnippetBlock(_))
                            || (matches!(pn, TemplateNode::Comment(_)) && !self.preserve_comments);
                        if !pn_hoisted {
                            break matches!(pn, TemplateNode::ExpressionTag(_));
                        }
                    }
                };
                let next_is_expression = {
                    let mut ni = i + 1;
                    loop {
                        if ni >= nodes.len() {
                            break false;
                        }
                        let nn = &nodes[ni];
                        let nn_hoisted = matches!(nn, TemplateNode::ConstTag(_))
                            || matches!(nn, TemplateNode::SnippetBlock(_))
                            || (matches!(nn, TemplateNode::Comment(_)) && !self.preserve_comments);
                        if !nn_hoisted {
                            break matches!(nn, TemplateNode::ExpressionTag(_));
                        }
                        ni += 1;
                    }
                };

                // For whitespace-only text between ExpressionTags, preserve as-is
                if is_svelte_whitespace_only(&modified_data)
                    && prev_is_expression
                    && next_is_expression
                {
                    use crate::compiler::phases::phase3_transform::shared::sanitize_template_string;
                    self.output_parts
                        .push(OutputPart::Html(sanitize_template_string(&modified_data)));
                    continue;
                }

                // Use generate_text_with_expr_context for proper ExpressionTag-adjacent
                // whitespace preservation
                if needs_modification {
                    let mut modified_text = text.clone();
                    modified_text.data = modified_data.into();
                    self.generate_text_with_expr_context(
                        &modified_text,
                        prev_is_expression,
                        next_is_expression,
                    )?;
                    continue;
                } else {
                    self.generate_text_with_expr_context(
                        text,
                        prev_is_expression,
                        next_is_expression,
                    )?;
                    continue;
                }
            } else {
                // Reset trim flag when we hit a non-text, non-whitespace node
                if trim_leading_ws
                    && first_meaningful_idx.is_some()
                    && i >= first_meaningful_idx.unwrap()
                {
                    trim_leading_ws = false;
                }
                // Reset prev_text_ends_with_ws for non-hoisted/non-transparent nodes.
                // SnippetBlock, ConstTag, and Comment (when !preserveComments) are
                // transparent: they don't affect whitespace collapsing between text nodes.
                let is_transparent = matches!(node, TemplateNode::SnippetBlock(_))
                    || matches!(node, TemplateNode::ConstTag(_))
                    || (matches!(node, TemplateNode::Comment(_)) && !self.preserve_comments);
                if !is_transparent {
                    prev_text_ends_with_ws = false;
                }
            }

            self.generate_node(node, true)?;
        }
        Ok(())
    }
}
