/* singleselection.svelte.js generated by Svelte v5.57.1 */
import * as $ from 'svelte/internal/client';
import { getContext, setContext, untrack } from "svelte";

const SINGLE_SELECTION_KEY = Symbol("singleton");

export function createSingleSelectionContext(nonReactive = false) {
	if (nonReactive) return setContext(SINGLE_SELECTION_KEY, {});

	const context = $.proxy({ value: null });

	return setContext(SINGLE_SELECTION_KEY, context);
}

/**
 * @template T
 * @param {SingleSelectionContext<T>} context
 * @param {boolean} open
 * @param {T=} value
 * @returns {SingleSelectionContext<T>}
 */
function setSelected(context, open, value) {
	if (open) context.value = value ?? null; else if (context.value === value) context.value = null;

	return context;
}

/**
 * @template T
 * @param {(value: T|null) => void} callback
 * @returns {(open: boolean, v?: T) => SingleSelectionContext<T>}
 */
export function useSingleSelection(callback) {
	const context = getContext(SINGLE_SELECTION_KEY) ?? createSingleSelectionContext(false);

	if (!context.hasOwnProperty?.("value")) return () => context;

	$.user_effect(() => {
		if (context.value !== null) callback(context.value);
	});

	return (open, v) => untrack(() => setSelected(context, open, v));
}