/* util.svelte.js generated by Svelte v5.57.1 */
import * as $ from 'svelte/internal/client';

export const createAppState = (options) => {
	const source = $.derived(() => options.source());
	let value = $.derived(() => $.get(source));

	return {
		get value() {
			return $.get(value);
		},

		onChange(nextValue) {
			$.set(value, nextValue);
		}
	};
};

const result = createAppState({ source: () => 'wrong' });

result.onChange('right');

export const expect2 = result.value === 'right';