/* theme.svelte.js generated by Svelte v5.57.1 */
import * as $ from 'svelte/internal/client';
import { fromStore, writable } from 'svelte/store';

export const store = writable({ theme: 'dark' });

class ThemeState {
	#storeState = fromStore(store);
	#value = $.derived(() => this.#storeState.current);

	get value() {
		return $.get(this.#value);
	}

	set value(value) {
		$.set(this.#value, value);
	}

	constructor() {
		$.effect_root(() => {
			$.user_effect(() => {
				console.log(this.value.theme);
			});
		});
	}
}

export const themeState = new ThemeState();