/* theme.svelte.js generated by Svelte v5.57.1 */
import * as $ from 'svelte/internal/server';
import { fromStore, writable } from 'svelte/store';

export const store = writable({ theme: 'dark' });

class ThemeState {
	#storeState = fromStore(store);
	#value = $.derived(() => this.#storeState.current);

	get value() {
		return this.#value();
	}

	set value($$value) {
		return this.#value($$value);
	}

	constructor() {}
}

export const themeState = new ThemeState();