/* event.svelte.js generated by Svelte v5.57.1 */
import * as $ from 'svelte/internal/server';

export const log_a = () => {
	console.log('a');
};

export const log_b = () => {
	console.log('b');
};

let handle = log_a;

export const handler = {
	get value() {
		return handle;
	},

	set value(v) {
		handle = v;
	}
};