/* event.svelte.js generated by Svelte v5.57.1 */
import * as $ from 'svelte/internal/client';

export const log_a = () => {
	console.log('a');
};

export const log_b = () => {
	console.log('b');
};

let handle = $.state(log_a);

export const handler = {
	get value() {
		return $.get(handle);
	},

	set value(v) {
		$.set(handle, v, true);
	}
};