/* runes01-input.svelte.js generated by Svelte v5.57.1 */
import * as $ from 'svelte/internal/server';

export class Test {
	a = 0;
	#b = $.derived(() => this.a * 2);

	get b() {
		return this.#b();
	}

	set b($$value) {
		return this.#b($$value);
	}

	output() {
		console.log(this.a, this.b);
	}
}