/* translations.svelte.js generated by Svelte v5.57.1 */
import * as $ from 'svelte/internal/client';

let greeting = $.state('Hello');

export function get_translation() {
	return $.get(greeting);
}

export function set_translation(value) {
	$.set(greeting, value, true);
}