/* translations.svelte.js generated by Svelte v5.57.1 */
import * as $ from 'svelte/internal/server';

let greeting = 'Hello';

export function get_translation() {
	return greeting;
}

export function set_translation(value) {
	greeting = value;
}