[package]
name = "rsvelte_svelte_typecheck"
description = "Svelte type checking"
edition.workspace = true
version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
rsvelte_svelte_parser.workspace = true
rsvelte_kernel.workspace = true
rsvelte_typescript_check.workspace = true
rsvelte_typescript_content_mapper.workspace = true
rsvelte_svelte_typescript_projection.workspace = true

[dev-dependencies]
rsvelte_fixture_test.workspace = true

[[test]]
name = "fixtures"
harness = false

[lints]
workspace = true
