#!/usr/bin/env node

/**
 * Script to generate Rust code for HTML named character references.
 * Fetches the official WHATWG entities.json and generates a Rust match statement.
 *
 * Usage: node scripts/generate_entities.mjs > src/compiler/phases/1_parse/utils/entities_data.rs
 */

const response = await fetch('https://html.spec.whatwg.org/entities.json');
const entities = await response.json();

// Process entities - remove & prefix and ; suffix, keep only those ending with ;
const processed = [];
for (const [name, data] of Object.entries(entities)) {
    // Only include entities that end with semicolon (standard form)
    if (!name.endsWith(';')) continue;

    // Remove & prefix and ; suffix
    const cleanName = name.slice(1, -1);
    const codepoints = data.codepoints;

    processed.push({ name: cleanName, codepoints });
}

// Sort for binary search - use byte-wise comparison (same as Rust's Ord for &str)
processed.sort((a, b) => {
    if (a.name < b.name) return -1;
    if (a.name > b.name) return 1;
    return 0;
});

console.log(`//! Auto-generated HTML entity data from WHATWG HTML specification.
//! Source: https://html.spec.whatwg.org/entities.json
//!
//! This file is generated by scripts/generate_entities.mjs
//! DO NOT EDIT MANUALLY

/// Total number of HTML named character references
pub const ENTITY_COUNT: usize = ${processed.length};

/// HTML entity entry: (name, codepoints)
/// Names are sorted alphabetically for binary search
pub static ENTITIES: &[(&str, &[u32])] = &[`);

for (const { name, codepoints } of processed) {
    // Escape the name for Rust string literal
    const escapedName = name.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
    const codepointStr = codepoints.join(', ');
    console.log(`    ("${escapedName}", &[${codepointStr}]),`);
}

console.log(`];

/// Decode a named HTML entity (without & prefix and ; suffix)
/// Returns the decoded character(s) as a String, or None if not found
pub fn decode_named_entity(name: &str) -> Option<String> {
    // Binary search for the entity
    match ENTITIES.binary_search_by(|(n, _)| (*n).cmp(name)) {
        Ok(idx) => {
            let (_, codepoints) = &ENTITIES[idx];
            let mut result = String::with_capacity(codepoints.len() * 4);
            for &cp in *codepoints {
                if let Some(c) = char::from_u32(cp) {
                    result.push(c);
                }
            }
            Some(result)
        }
        Err(_) => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_basic_entities() {
        assert_eq!(decode_named_entity("amp"), Some("&".to_string()));
        assert_eq!(decode_named_entity("lt"), Some("<".to_string()));
        assert_eq!(decode_named_entity("gt"), Some(">".to_string()));
        assert_eq!(decode_named_entity("quot"), Some("\\"".to_string()));
        assert_eq!(decode_named_entity("apos"), Some("'".to_string()));
        assert_eq!(decode_named_entity("nbsp"), Some("\\u{00A0}".to_string()));
    }

    #[test]
    fn test_extended_entities() {
        assert_eq!(decode_named_entity("copy"), Some("\\u{00A9}".to_string()));
        assert_eq!(decode_named_entity("reg"), Some("\\u{00AE}".to_string()));
        assert_eq!(decode_named_entity("trade"), Some("\\u{2122}".to_string()));
        assert_eq!(decode_named_entity("euro"), Some("\\u{20AC}".to_string()));
    }

    #[test]
    fn test_multi_codepoint_entities() {
        // Some entities decode to multiple characters
        // e.g., &nGt; -> ≫⃒ (U+226B, U+20D2)
        let result = decode_named_entity("nGt");
        assert!(result.is_some());
        let s = result.unwrap();
        assert!(s.len() > 1);
    }

    #[test]
    fn test_unknown_entity() {
        assert_eq!(decode_named_entity("notanentity"), None);
    }
}
`);
