import * as $ from 'svelte/internal/server';
import { tooltip } from '$lib/actions/tooltip.js';
import Icon from '$lib/components/global/Icon.svelte';
import { useClipboard } from '$lib/composables';
import { generatePTRName, generateCIDRPTRs } from '$lib/utils/reverse-dns.js';

export default function ReversePTRGenerator($$renderer, $$props) {
	$$renderer.component(($$renderer) => {
		let inputValue = '192.168.1.100';
		let inputType = 'single';
		let results = null;
		const clipboard = useClipboard();
		let selectedExample = null;
		let _userModified = false;

		const examples = [
			{
				label: 'Single IPv4',
				input: '192.168.1.100',
				type: 'single',
				description: 'Generate PTR for single IPv4 address'
			},

			{
				label: 'Single IPv6',
				input: '2001:db8::1',
				type: 'single',
				description: 'Generate PTR for single IPv6 address'
			},

			{
				label: 'IPv4 /28 Block',
				input: '192.168.1.16/28',
				type: 'cidr',
				description: 'Generate PTRs for /28 subnet (16 addresses)'
			},

			{
				label: 'IPv4 /24 Network',
				input: '10.0.0.0/24',
				type: 'cidr',
				description: 'Generate PTRs for entire /24 network'
			},

			{
				label: 'IPv6 /64 Network',
				input: '2001:db8:1000::/64',
				type: 'cidr',
				description: 'Generate IPv6 PTR examples for /64'
			}
		];

		function loadExample(example) {
			inputValue = example.input;
			inputType = example.type;
			selectedExample = example.label;
			_userModified = false;
			generatePTRs();
		}

		function generatePTRs() {
			if (!inputValue.trim()) {
				results = null;

				return;
			}

			try {
				const trimmed = inputValue.trim();
				let entries = [];

				if (inputType === 'single') {
					// Single IP address
					const record = generatePTRName(trimmed);

					if (record) {
						entries.push(record);
					} else {
						throw new Error('Invalid IP address format');
					}
				} else {
					// CIDR notation
					entries = generateCIDRPTRs(trimmed, 1000);
				}

				// Generate summary
				const summary = {
					totalEntries: entries.length,
					ipv4Entries: entries.filter((e) => e.type === 'IPv4').length,
					ipv6Entries: entries.filter((e) => e.type === 'IPv6').length,
					uniqueZones: [...new Set(entries.map((e) => e.zone))].length
				};

				results = { success: true, entries, summary };
			} catch(error) {
				results = {
					success: false,
					error: error instanceof Error ? error.message : 'Unknown error occurred',
					entries: [],
					summary: {
						totalEntries: 0,
						ipv4Entries: 0,
						ipv6Entries: 0,
						uniqueZones: 0
					}
				};
			}
		}

		function handleInputChange() {
			_userModified = true;
			selectedExample = null;
			generatePTRs();
		}

		function handleTypeChange() {
			_userModified = true;
			selectedExample = null;
			generatePTRs();
		}

		// Generate on component load
		generatePTRs();

		$$renderer.push(`<div class="card"><header class="card-header"><h1>Reverse PTR Generator</h1> <p>Convert IP addresses and CIDR blocks to PTR record names and zone file examples</p></header> <div class="card info-card svelte-2ka88l"><div class="overview-content svelte-2ka88l"><div class="overview-item svelte-2ka88l">`);
		Icon($$renderer, { name: 'rotate', size: 'sm' });
		$$renderer.push(`<!----> <div><strong class="svelte-2ka88l">Reverse DNS:</strong> PTR records map IP addresses back to hostnames using <code class="svelte-2ka88l">in-addr.arpa</code> (IPv4) and <code class="svelte-2ka88l">ip6.arpa</code> (IPv6) zones.</div></div> <div class="overview-item svelte-2ka88l">`);
		Icon($$renderer, { name: 'target', size: 'sm' });
		$$renderer.push(`<!----> <div><strong class="svelte-2ka88l">PTR Names:</strong> Generated by reversing IP octets/nibbles and appending the appropriate arpa domain.</div></div> <div class="overview-item svelte-2ka88l">`);
		Icon($$renderer, { name: 'file', size: 'sm' });
		$$renderer.push(`<!----> <div><strong class="svelte-2ka88l">Zone Lines:</strong> Ready-to-use DNS zone file entries with proper PTR record format.</div></div></div></div> <div class="card examples-card svelte-2ka88l"><details class="examples-details svelte-2ka88l"><summary class="examples-summary svelte-2ka88l">`);
		Icon($$renderer, { name: 'chevron-right', size: 'sm' });
		$$renderer.push(`<!----> <h3 class="svelte-2ka88l">Quick Examples</h3></summary> <div class="examples-grid svelte-2ka88l"><!--[-->`);

		const each_array = $.ensure_array_like(examples);

		for (let $$index = 0, $$length = each_array.length; $$index < $$length; $$index++) {
			let example = each_array[$$index];

			$$renderer.push(`<button${$.attr_class(`example-card ${selectedExample === example.label ? 'active' : ''}`, 'svelte-2ka88l')}><div class="example-header svelte-2ka88l"><div class="example-label svelte-2ka88l">${$.escape(example.label)}</div> <div${$.attr_class(`example-type ${$.stringify(example.type)}`, 'svelte-2ka88l')}>${$.escape(example.type === 'single' ? 'Single IP' : 'CIDR Block')}</div></div> <code class="example-input svelte-2ka88l">${$.escape(example.input)}</code> <div class="example-description svelte-2ka88l">${$.escape(example.description)}</div></button>`);
		}

		$$renderer.push(`<!--]--></div></details></div> <div class="card input-card svelte-2ka88l"><div class="type-section svelte-2ka88l"><h3 class="type-label svelte-2ka88l">Input Type</h3> <div class="type-options svelte-2ka88l"><label class="type-option svelte-2ka88l"><input type="radio"${$.attr('checked', inputType === 'single', true)} value="single" class="svelte-2ka88l"/> <div class="type-content svelte-2ka88l">`);
		Icon($$renderer, { name: 'target', size: 'sm' });
		$$renderer.push(`<!----> <span>Single IP</span></div></label> <label class="type-option svelte-2ka88l"><input type="radio"${$.attr('checked', inputType === 'cidr', true)} value="cidr" class="svelte-2ka88l"/> <div class="type-content svelte-2ka88l">`);
		Icon($$renderer, { name: 'network', size: 'sm' });
		$$renderer.push(`<!----> <span>CIDR Block</span></div></label></div></div> <div class="input-group svelte-2ka88l"><label for="ip-input" class="svelte-2ka88l">`);

		Icon($$renderer, {
			name: inputType === 'single' ? 'target' : 'network',
			size: 'sm'
		});

		$$renderer.push(`<!----> ${$.escape(inputType === 'single' ? 'IP Address' : 'CIDR Block')}</label> <input id="ip-input" type="text"${$.attr('value', inputValue)}${$.attr('placeholder', inputType === 'single'
			? '192.168.1.100 or 2001:db8::1'
			: '192.168.1.0/24 or 2001:db8::/64')}${$.attr_class(`ip-input ${results?.success === true ? 'valid' : results?.success === false ? 'invalid' : ''}`, 'svelte-2ka88l')} spellcheck="false"/></div></div> `);

		if (results && inputValue.trim()) {
			$$renderer.push(`<!--[0--><div class="card results-card svelte-2ka88l">`);

			if (results.success) {
				$$renderer.push(`<!--[0--><div class="results-header svelte-2ka88l"><h3 class="svelte-2ka88l">PTR Records Generated</h3> <div class="summary-stats svelte-2ka88l"><div class="stat-item svelte-2ka88l"><span class="stat-value svelte-2ka88l">${$.escape(results.summary.totalEntries)}</span> <span class="stat-label svelte-2ka88l">Total PTRs</span></div> `);

				if (results.summary.ipv4Entries > 0) {
					$$renderer.push(`<!--[0--><div class="stat-item svelte-2ka88l"><span class="stat-value svelte-2ka88l">${$.escape(results.summary.ipv4Entries)}</span> <span class="stat-label svelte-2ka88l">IPv4</span></div>`);
				} else {
					$$renderer.push('<!--[-1-->');
				}

				$$renderer.push(`<!--]--> `);

				if (results.summary.ipv6Entries > 0) {
					$$renderer.push(`<!--[0--><div class="stat-item svelte-2ka88l"><span class="stat-value svelte-2ka88l">${$.escape(results.summary.ipv6Entries)}</span> <span class="stat-label svelte-2ka88l">IPv6</span></div>`);
				} else {
					$$renderer.push('<!--[-1-->');
				}

				$$renderer.push(`<!--]--> <div class="stat-item svelte-2ka88l"><span class="stat-value svelte-2ka88l">${$.escape(results.summary.uniqueZones)}</span> <span class="stat-label svelte-2ka88l">Zones</span></div></div></div> <div class="ptr-records svelte-2ka88l"><h4 class="svelte-2ka88l">`);
				Icon($$renderer, { name: 'list', size: 'sm' });
				$$renderer.push(`<!----> PTR Records &amp; Zone Lines</h4> <div class="records-table svelte-2ka88l"><div class="table-header svelte-2ka88l"><div class="col-ip">IP Address</div> <div class="col-ptr svelte-2ka88l">PTR Record Name</div> <div class="col-zone-line svelte-2ka88l">Zone File Line</div> <div class="col-type">Type</div></div> <!--[-->`);

				const each_array_1 = $.ensure_array_like(results.entries.slice(0, 100));

				for (let $$index_1 = 0, $$length = each_array_1.length; $$index_1 < $$length; $$index_1++) {
					let entry = each_array_1[$$index_1];

					function zoneLine($$renderer) {
						const recordName = entry.ptrName.replace(`.${entry.zone}`, '').replace(/\.$/, '');
						const hostname = `host-${entry.ip.replace(/[:.]/g, '-')}.example.com.`;

						$$renderer.push(`<code class="svelte-2ka88l">${$.escape(recordName)} IN PTR ${$.escape(hostname)}</code>`);
					}

					$$renderer.push(`<div class="table-row svelte-2ka88l"><div class="col-ip"><code>${$.escape(entry.ip)}</code></div> <div class="col-ptr svelte-2ka88l"><code class="svelte-2ka88l">${$.escape(entry.ptrName)}</code> <button${$.attr_class(`copy-button ${clipboard.isCopied(`ptr-${entry.ip}`) ? 'copied' : ''}`, 'svelte-2ka88l')}>`);

					Icon($$renderer, {
						name: clipboard.isCopied(`ptr-${entry.ip}`) ? 'check' : 'copy',
						size: 'sm'
					});

					$$renderer.push(`<!----></button></div> <div class="col-zone-line svelte-2ka88l">`);
					zoneLine($$renderer);
					$$renderer.push(`<!----> <button${$.attr_class(`copy-button ${clipboard.isCopied(`zone-${entry.ip}`) ? 'copied' : ''}`, 'svelte-2ka88l')}>`);

					Icon($$renderer, {
						name: clipboard.isCopied(`zone-${entry.ip}`) ? 'check' : 'copy',
						size: 'sm'
					});

					$$renderer.push(`<!----></button></div> <div class="col-type"><span${$.attr_class(`type-badge ${$.stringify(entry.type.toLowerCase())}`, 'svelte-2ka88l')}>${$.escape(entry.type)}</span></div></div>`);
				}

				$$renderer.push(`<!--]--> `);

				if (results.entries.length > 100) {
					$$renderer.push(`<!--[0--><div class="table-truncated svelte-2ka88l">... and ${$.escape(results.entries.length - 100)} more records</div>`);
				} else {
					$$renderer.push('<!--[-1-->');
				}

				$$renderer.push(`<!--]--></div></div>`);
			} else {
				$$renderer.push(`<!--[-1--><div class="error-result svelte-2ka88l">`);
				Icon($$renderer, { name: 'alert-triangle', size: 'lg' });
				$$renderer.push(`<!----> <h4 class="svelte-2ka88l">Generation Error</h4> <p class="svelte-2ka88l">${$.escape(results.error)}</p> <div class="error-help svelte-2ka88l"><strong>Valid formats:</strong> <ul class="svelte-2ka88l"><li class="svelte-2ka88l">Single IPv4: 192.168.1.100</li> <li class="svelte-2ka88l">Single IPv6: 2001:db8::1</li> <li class="svelte-2ka88l">IPv4 CIDR: 192.168.1.0/24 (max /16)</li> <li class="svelte-2ka88l">IPv6 CIDR: 2001:db8::/64 (max /64)</li></ul></div></div>`);
			}

			$$renderer.push(`<!--]--></div>`);
		} else {
			$$renderer.push('<!--[-1-->');
		}

		$$renderer.push(`<!--]--> <div class="education-card svelte-2ka88l"><div class="education-grid svelte-2ka88l"><div class="education-item info-panel svelte-2ka88l"><h4 class="svelte-2ka88l">PTR Record Format</h4> <p class="svelte-2ka88l">PTR records use the special <code class="svelte-2ka88l">in-addr.arpa</code> (IPv4) and <code class="svelte-2ka88l">ip6.arpa</code> (IPv6) domains. IP
          addresses are reversed: <code class="svelte-2ka88l">192.168.1.100</code> becomes <code class="svelte-2ka88l">100.1.168.192.in-addr.arpa</code>.</p></div> <div class="education-item info-panel svelte-2ka88l"><h4 class="svelte-2ka88l">Zone File Usage</h4> <p class="svelte-2ka88l">The generated zone file lines can be copied directly into your reverse DNS zone files. Remember to adjust the
          hostname targets to match your actual domain structure.</p></div> <div class="education-item info-panel svelte-2ka88l"><h4 class="svelte-2ka88l">IPv6 Nibbles</h4> <p class="svelte-2ka88l">IPv6 PTR records use individual hex digits (nibbles) reversed. Each character becomes a separate label: <code class="svelte-2ka88l">2001:db8::1</code> becomes a very long <code class="svelte-2ka88l">ip6.arpa</code> name.</p></div> <div class="education-item info-panel svelte-2ka88l"><h4 class="svelte-2ka88l">Best Practices</h4> <p class="svelte-2ka88l">Ensure PTR records have corresponding A/AAAA records for proper forward-reverse DNS consistency. Use
          descriptive hostnames that include IP information for easier network management.</p></div></div></div></div>`);
	});
}