//! Option-axis parity for `svelte2tsx`.
//!
//! Every other svelte2tsx gate in this repo runs with `mode: 'ts'`,
//! `namespace: 'html'`, `version: '5'` and a supplied `filename`, so the option
//! object is a constant no gate varies. The fixture here is **generated by the
//! official `svelte2tsx`** (see `data/svelte2tsx_option_axis.json`): each
//! case carries the JS option object, the source, and upstream's exact output.
//!
//! Regenerate with the official tool rather than editing the expectations by
//! hand — a hand-written expectation is somebody's idea of the behaviour, not
//! the behaviour.

use rsvelte_projection::svelte2tsx::{Svelte2TsxOptions, svelte2tsx};

#[test]
fn option_axis_matches_official_svelte2tsx() {
    let fixture: serde_json::Value =
        serde_json::from_str(include_str!("data/svelte2tsx_option_axis.json"))
            .expect("fixture parses");
    let cases = fixture["cases"].as_array().expect("cases array");
    // A truncated fixture would pass vacuously, so state what the axis has to
    // contain rather than only that it is non-empty.
    for key in [
        "mode",
        "typingsNamespace",
        "emitJsDoc",
        "noSvelteComponentTyped",
        "version",
    ] {
        assert!(
            cases
                .iter()
                .any(|case| case["options"].get(key).is_some_and(|v| !v.is_null())),
            "fixture exercises no case with `{key}` set"
        );
    }
    assert!(
        cases
            .iter()
            .any(|case| case["options"].get("filename").is_none()),
        "fixture exercises no case without `filename`"
    );

    let mut failures = Vec::new();
    for case in cases {
        let id = case["id"].as_str().expect("id");
        let source = case["source"].as_str().expect("source");
        let expected = case["expected"].as_str().expect("expected");
        let options = Svelte2TsxOptions::from_json(&case["options"]);
        match svelte2tsx(source, options) {
            Ok(result) if result.code == expected => {}
            Ok(result) => failures.push(format!(
                "{id}\n--- expected ---\n{expected}\n--- actual ---\n{}\n",
                result.code
            )),
            Err(error) => failures.push(format!("{id}: projection failed: {error}")),
        }
    }

    assert!(
        failures.is_empty(),
        "{} of {} option-axis cases diverge from official svelte2tsx:\n\n{}",
        failures.len(),
        cases.len(),
        failures.join("\n")
    );
}
