//! `+error.svelte` types its `error` prop as `App.Error`.
//!
//! Upstream reaches that through an `else if (isKitErrorFile(this.basename))`
//! arm that sits *after* the route-file arm, and `isKitErrorFile` strips only
//! the extension — it has no `@anchor` handling, unlike `isKitRouteFile`. So the
//! filename axis is the discriminating one: `+error@foo.svelte` and
//! `+error.other.svelte` are ordinary components, and every prop but `error`
//! is dropped from `+error.svelte` exactly as a route file's non-kit props are.
//! Expectations are generated by running the official `svelte2tsx`, never
//! hand-written.

use rsvelte_projection::svelte2tsx::{Svelte2TsxOptions, svelte2tsx};

struct Case {
    name: String,
    filename: String,
    source: String,
    expected: String,
}

fn cases() -> Vec<Case> {
    let raw: serde_json::Value =
        serde_json::from_str(include_str!("data/svelte2tsx_kit_error_props.json")).unwrap();
    raw.as_array()
        .unwrap()
        .iter()
        .map(|c| {
            let get = |k: &str| c[k].as_str().unwrap().to_string();
            Case {
                name: get("name"),
                filename: get("filename"),
                source: get("source"),
                expected: get("expected"),
            }
        })
        .collect()
}

#[test]
fn kit_error_props_match_official_svelte2tsx() {
    let cases = cases();
    // A fixture-driven test scores "0 compared" as a pass, so the population is
    // asserted before the comparison.
    assert_eq!(cases.len(), 24, "the generated grid changed size");

    let mut failures = Vec::new();
    for case in &cases {
        let options = Svelte2TsxOptions {
            filename: case.filename.clone(),
            is_ts_file: true,
            ..Default::default()
        };
        match svelte2tsx(&case.source, options) {
            Ok(actual) if actual.code == case.expected => {}
            Ok(actual) => failures.push(format!(
                "{}\n  expected: {}\n  actual  : {}",
                case.name,
                first_props_line(&case.expected),
                first_props_line(&actual.code)
            )),
            Err(error) => failures.push(format!("{}: threw {error:?}", case.name)),
        }
    }
    assert!(
        failures.is_empty(),
        "{} of {} cases differ:\n{}",
        failures.len(),
        cases.len(),
        failures.join("\n")
    );
}

fn first_props_line(code: &str) -> String {
    code.lines()
        .find(|line| line.contains("$$ComponentProps ="))
        .unwrap_or("(no $$ComponentProps)")
        .trim()
        .to_string()
}
