//! Runes-vs-legacy mode is decided by one scan over a class body and one over a
//! function's parameters. Every entry point — a `class` statement, an
//! `export class`, a class *expression*, a nested class, a superclass
//! expression — must answer identically, so this fixture crosses the member kind
//! with the host the class sits in and compares the whole emitted component to
//! the official `svelte2tsx`. Expectations are generated by running the official
//! tool, never hand-written.

use std::collections::HashSet;

use rsvelte_projection::svelte2tsx::{Svelte2TsxOptions, svelte2tsx};

struct Case {
    name: String,
    filename: String,
    source: String,
    expected: String,
    group: String,
}

fn cases() -> Vec<Case> {
    let raw: serde_json::Value =
        serde_json::from_str(include_str!("data/svelte2tsx_class_rune_scan.json")).unwrap();
    raw.as_array()
        .unwrap()
        .iter()
        .map(|c| {
            let get = |k: &str| c[k].as_str().unwrap().to_string();
            Case {
                name: get("name"),
                filename: get("filename"),
                source: get("source"),
                expected: get("expected"),
                group: get("group"),
            }
        })
        .collect()
}

/// A fixture-driven test scores "0 compared" as a pass, so assert the population
/// actually holds the shapes the scan is about before trusting the comparison.
#[test]
fn the_population_is_not_degenerate() {
    let cases = cases();
    assert!(cases.len() >= 80, "population shrank to {}", cases.len());

    let names: HashSet<&str> = cases.iter().map(|c| c.name.as_str()).collect();
    for required in [
        // the two former copies, same member, one keyword apart
        "decl-top__static-block",
        "expr-const__static-block",
        "decl-top__method-param-shadow",
        "expr-const__method-param-shadow",
        // member kinds neither copy had an arm for
        "decl-top__accessor-prop",
        "decl-top__computed-key",
        "decl-top__method-param-def",
        // the superclass expression is part of the class
        "expr-extends__prop-init",
        // the same parameter rule outside a class body
        "arrow-expr-body-rune",
        "fn-decl-param-default",
        "fn-decl-param-shadow",
    ] {
        assert!(names.contains(required), "missing case {required}");
    }

    let groups: HashSet<&str> = cases.iter().map(|c| c.group.as_str()).collect();
    assert!(groups.contains("class-body") && groups.contains("function-params"));

    // Both verdicts must be present, or the fixture only tests one direction.
    let runes = cases
        .iter()
        .filter(|c| c.expected.contains("__sveltets_2_fn_component"))
        .count();
    assert!(runes > 0 && runes < cases.len(), "one-sided population");
}

#[test]
fn matches_official_svelte2tsx() {
    let mut failures = Vec::new();
    for case in cases() {
        let options = Svelte2TsxOptions {
            filename: case.filename.clone(),
            ..Svelte2TsxOptions::default()
        };
        match svelte2tsx(&case.source, options) {
            Ok(result) if result.code == case.expected => {}
            Ok(result) => failures.push(format!(
                "{}\n  source:   {}\n  expected: {}\n  actual:   {}",
                case.name,
                case.source.replace('\n', " "),
                mode_line(&case.expected),
                mode_line(&result.code),
            )),
            Err(e) => failures.push(format!("{}: error {e:?}", case.name)),
        }
    }
    assert!(
        failures.is_empty(),
        "{} of the cases diverge from official:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

/// The whole file is compared, but every divergence in this population is the
/// runes-vs-legacy component shape, so report that line rather than a 40-line dump.
fn mode_line(code: &str) -> &str {
    code.lines()
        .find(|l| {
            l.contains("__sveltets_2_fn_component")
                || l.contains("__sveltets_2_isomorphic_component")
        })
        .unwrap_or("<no component line>")
}
