[package]
name = "rsvelte_typescript_lint"
description = "TypeScript lint"
edition.workspace = true
version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
rsvelte_lint.workspace = true
rsvelte_kernel.workspace = true
rsvelte_typescript.workspace = true

[lints]
workspace = true
