import * as $ from 'svelte/internal/server';
import { onMount } from 'svelte';
import { s } from '$lib/client/localization.svelte';
import { themeSettings } from '$lib/data/settings.svelte.js';

export default function SplashScreen($$renderer, $$props) {
	$$renderer.component(($$renderer) => {
		// Props
		let {
			showProgress = false,
			progress = 0,
			stage = '',
			hasError = false,
			errorMessage = ''
		} = $$props;

		// Smooth animated progress counter
		let displayProgress = 0;

		let animationFrame;

		// Animation loop that runs continuously
		onMount(() => {
			const animate = () => {
				const diff = progress - displayProgress;

				// If we're close enough, just set it directly
				if (Math.abs(diff) < 0.1) {
					displayProgress = progress;
				} else {
					// Otherwise, animate towards the target
					// Use a smaller step for smoother animation
					displayProgress += diff * 0.08;
				}

				// Keep animating
				animationFrame = requestAnimationFrame(animate);
			};

			// Start animation
			animate();

			// Cleanup
			return () => {
				if (animationFrame) {
					cancelAnimationFrame(animationFrame);
				}
			};
		});

		$$renderer.push(`<div class="fixed inset-0 z-50 flex items-center justify-center bg-white dark:bg-dark-bg"><div class="text-center"><div class="relative mx-auto mb-4 h-40 w-40"><img src="/svg/spin_body.svg" alt=""${$.attr_class('absolute inset-0 h-full w-full animate-spin-slow', void 0, {
			'brightness-75': hasError,
			'sepia': hasError,
			'hue-rotate-[320deg]': hasError,
			'saturate-150': hasError
		})}/> <img${$.attr('src', themeSettings.isDark
			? "/svg/spin_circle_dark.svg"
			: "/svg/spin_circle_light.svg")} alt=""${$.attr_class('absolute inset-0 h-full w-full animate-spin-reverse', void 0, {
			'brightness-75': hasError,
			'sepia': hasError,
			'hue-rotate-[320deg]': hasError,
			'saturate-150': hasError
		})}/></div> <h1 class="mb-2 flex items-center justify-center text-2xl font-bold text-gray-800 dark:text-dark-text"><span>${$.escape(s("app.title") || "Kite")}</span> <span class="mt-0.5 ms-2 rounded-lg bg-yellow-200 px-2 py-0.5 text-xs font-medium text-black">${$.escape(s("app.beta") || "BETA")}</span></h1> <p class="text-xl text-gray-600 dark:text-gray-400">${$.escape(s("app.motto") || "News. Elevated.")}</p> `);

		if (hasError) {
			$$renderer.push(`<!--[0--><div class="mt-4 text-center"><p class="text-red-500 dark:text-red-400 font-medium">${$.escape(errorMessage || "An error occurred")}</p> <p class="text-sm text-gray-500 dark:text-gray-400 mt-1">${$.escape(s("loading.errorFallback") || "Continuing with limited functionality...")}</p></div>`);
		} else if (showProgress) {
			$$renderer.push(`<!--[1--><div class="mt-4 text-center"><p class="text-xl text-gray-600 dark:text-gray-400">${$.escape(Math.round(displayProgress))}%</p> <p class="min-h-[1.5rem] text-sm text-gray-500 dark:text-gray-400 mt-1">${$.escape(stage || "")}</p></div>`);
		} else {
			$$renderer.push('<!--[-1-->');
		}

		$$renderer.push(`<!--]--> <div class="mt-6 text-center text-xs text-gray-500 dark:text-gray-400"><p>${$.escape(s("app.disclaimerAutoGenerated") || "Summaries are auto-generated and Kite can make mistakes.")}</p> <p>${$.escape(s("app.disclaimerVerify") || "Please verify important information.")}</p></div></div></div>`);
	});
}