//! svelte.dev markdown end-to-end CLI parity (Stage 3).
//!
//! Runs the real `rsvelte-fmt` CLI on every markdown file from the
//! `submodules/svelte.dev` corpus and asserts the output matches an oracle
//! produced by `oxfmt` directly. rsvelte-fmt delegates non-`.svelte` files to
//! oxfmt, forwarding the resolved config — so this guards that the delegation
//! and config forwarding (`-c`, `svelte: true` for embedded code blocks) keep
//! the CLI a faithful pass-through for `.md`.
//!
//! Oracle fixtures live in `fixtures/fmt-corpus/<svelte.dev-sha>/markdown/`,
//! generated by `pnpm run generate-fmt-corpus`. Requirements mirror the
//! formatter corpus test: the corpus must exist and a runnable `oxfmt` is
//! located via `FMT_CORPUS_OXFMT` / `OXFMT_BIN` / `node_modules/.bin/oxfmt`.
//! Missing corpus or oxfmt → the test no-ops with a notice. Hard gate: every
//! markdown file must match the oxfmt oracle byte-for-byte.

use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::sync::Mutex;
use std::sync::atomic::{AtomicUsize, Ordering};

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .canonicalize()
        .expect("canonicalize repo root")
}

fn svelte_dev_short_sha(root: &Path) -> Option<String> {
    let out = Command::new("git")
        .arg("-C")
        .arg(root.join("submodules/svelte.dev"))
        .args(["rev-parse", "HEAD"])
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    let sha = String::from_utf8(out.stdout).ok()?;
    let sha = sha.trim();
    (sha.len() >= 12).then(|| sha[..12].to_string())
}

fn oxfmt_bin() -> PathBuf {
    if let Ok(p) = std::env::var("FMT_CORPUS_OXFMT") {
        return PathBuf::from(p);
    }
    if let Ok(p) = std::env::var("OXFMT_BIN") {
        return PathBuf::from(p);
    }
    repo_root().join("node_modules/.bin/oxfmt")
}

fn oxfmt_runnable(oxfmt: &Path) -> bool {
    Command::new(oxfmt)
        .arg("--version")
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

struct Sample {
    id: String,
    dir: PathBuf,
    md_name: String,
}

fn collect_markdown_samples(markdown_root: &Path, sha_root: &Path) -> Vec<Sample> {
    let mut out = Vec::new();
    fn walk(dir: &Path, sha_root: &Path, out: &mut Vec<Sample>) {
        let Ok(entries) = std::fs::read_dir(dir) else {
            return;
        };
        for e in entries.flatten() {
            let p = e.path();
            if !p.is_dir() {
                continue;
            }
            if p.join("input.md").is_file() && p.join("expected.md").is_file() {
                let id = p
                    .strip_prefix(sha_root)
                    .unwrap()
                    .to_string_lossy()
                    .replace('\\', "/");
                // The sample dir is named after the source file (…/index.md/).
                let md_name = p
                    .file_name()
                    .map(|s| s.to_string_lossy().into_owned())
                    .unwrap_or_else(|| "doc.md".to_string());
                out.push(Sample {
                    id,
                    dir: p,
                    md_name,
                });
            } else {
                walk(&p, sha_root, out);
            }
        }
    }
    walk(markdown_root, sha_root, &mut out);
    out.sort_by(|a, b| a.id.cmp(&b.id));
    out
}

#[test]
fn svelte_dev_markdown_cli_parity() {
    let root = repo_root();

    let Some(short_sha) = svelte_dev_short_sha(&root) else {
        eprintln!("[fmt-corpus-md] svelte.dev submodule not checked out; skipping.");
        return;
    };
    let fixtures = root.join("fixtures/fmt-corpus").join(&short_sha);
    let markdown_root = fixtures.join("markdown");
    if !markdown_root.is_dir() {
        eprintln!(
            "[fmt-corpus-md] no markdown fixtures at fixtures/fmt-corpus/{short_sha}; skipping. \
             Run: pnpm run generate-fmt-corpus"
        );
        return;
    }

    let oxfmt = oxfmt_bin();
    if !oxfmt_runnable(&oxfmt) {
        eprintln!(
            "[fmt-corpus-md] oxfmt not runnable at {} (set FMT_CORPUS_OXFMT); skipping.",
            oxfmt.display()
        );
        return;
    }
    let config = root.join("scripts/fixtures/fmt-corpus.oxfmtrc.json");
    let bin = PathBuf::from(env!("CARGO_BIN_EXE_rsvelte-fmt"));

    let samples = collect_markdown_samples(&markdown_root, &fixtures);
    assert!(
        !samples.is_empty(),
        "no markdown samples under {markdown_root:?}"
    );

    let failures: Mutex<Vec<(String, String)>> = Mutex::new(Vec::new());
    let next = AtomicUsize::new(0);
    // Each worker spends almost all of its wall-time *blocked* in
    // `child.wait_with_output()`: every sample spawns the `rsvelte-fmt` CLI,
    // which in turn spawns `oxfmt` (a Node launcher), so the loop is dominated
    // by two chained process-startup latencies, not CPU. With one worker per
    // core (`available_parallelism`) the cores sit idle waiting on those
    // subprocesses, and on a 4-core CI runner this single `#[test]` was the
    // suite's long pole (~200s for ~640 markdown samples). Oversubscribe so
    // many startups are in flight at once; the cap bounds peak concurrent
    // Node processes (memory) while keeping the CPUs saturated.
    let n_threads = std::thread::available_parallelism()
        .map(|n| n.get())
        .unwrap_or(4)
        .saturating_mul(4)
        .clamp(8, 32);

    std::thread::scope(|scope| {
        for _ in 0..n_threads {
            let (next, failures, samples) = (&next, &failures, &samples);
            let (bin, config, oxfmt) = (&bin, &config, &oxfmt);
            scope.spawn(move || {
                loop {
                    let i = next.fetch_add(1, Ordering::Relaxed);
                    if i >= samples.len() {
                        break;
                    }
                    let s = &samples[i];
                    let input = std::fs::read(s.dir.join("input.md")).unwrap();
                    let expected = std::fs::read_to_string(s.dir.join("expected.md")).unwrap();

                    let mut child = Command::new(bin)
                        .args(["--stdin", "--stdin-filepath"])
                        .arg(&s.md_name)
                        .arg("-c")
                        .arg(config)
                        .arg("--oxfmt-bin")
                        .arg(oxfmt)
                        .stdin(Stdio::piped())
                        .stdout(Stdio::piped())
                        .stderr(Stdio::piped())
                        .spawn()
                        .expect("spawn rsvelte-fmt");
                    child.stdin.take().unwrap().write_all(&input).unwrap();
                    let out = child.wait_with_output().unwrap();

                    let detail = if !out.status.success() {
                        format!(
                            "rsvelte-fmt exited {:?}: {}",
                            out.status.code(),
                            String::from_utf8_lossy(&out.stderr).trim()
                        )
                    } else {
                        match String::from_utf8(out.stdout) {
                            Ok(got) if got == expected => continue,
                            Ok(got) => first_diff(&expected, &got),
                            Err(_) => "non-utf8 output".to_string(),
                        }
                    };
                    failures.lock().unwrap().push((s.id.clone(), detail));
                }
            });
        }
    });

    let mut failures = failures.into_inner().unwrap();
    failures.sort_by(|a, b| a.0.cmp(&b.0));

    let total = samples.len();
    let passing = total - failures.len();
    println!(
        "[fmt-corpus-md] svelte.dev@{short_sha}: {passing}/{total} pass, {} fail",
        failures.len()
    );

    if !failures.is_empty() {
        // Hard gate: rsvelte-fmt's .md delegation must match the oxfmt oracle.
        const SHOW: usize = 60;
        let mut msg = format!(
            "\n{} markdown CLI parity failure(s) vs the oxfmt oracle ({passing}/{total} pass):\n",
            failures.len(),
        );
        use std::fmt::Write as _;
        for (id, detail) in failures.iter().take(SHOW) {
            let _ = write!(msg, "\n  ✗ {id}\n      {detail}\n");
        }
        if failures.len() > SHOW {
            let _ = write!(msg, "\n  … and {} more.\n", failures.len() - SHOW);
        }
        panic!("{msg}");
    }
}

fn first_diff(expected: &str, got: &str) -> String {
    for (i, (e, g)) in expected.lines().zip(got.lines()).enumerate() {
        if e != g {
            return format!("line {}: expected {:?} got {:?}", i + 1, trunc(e), trunc(g));
        }
    }
    let (el, gl) = (expected.lines().count(), got.lines().count());
    if el != gl {
        format!("line count differs: expected {el} got {gl}")
    } else {
        "outputs differ (trailing whitespace/newline)".to_string()
    }
}

fn trunc(s: &str) -> String {
    if s.len() > 80 {
        format!("{}…", &s[..80])
    } else {
        s.to_string()
    }
}
