//! The client text aligner walks the source against the generated text and
//! resyncs on a common run. Two shapes defeat a one-sided skip: the first
//! fragment, whose opening byte can sit further from the source than a token's
//! worth of skew, and a rewrite that both deletes and inserts (`count++` ->
//! `$.update(count)`), which resyncs on neither side alone.
//!
//! Every expected pair below was generated by compiling the same source with
//! the official compiler (`submodules/svelte/packages/svelte/src/compiler/index.js`)
//! and reading its client map; none was read back out of rsvelte.

use rsvelte_core::{CompileOptions, GenerateMode, compile};
use std::collections::BTreeSet;

/// `(generated line:column, source line:column)` for every four-field segment.
fn source_pairs(source: &str) -> BTreeSet<((i64, i64), (i64, i64))> {
    let map = compile(
        source,
        CompileOptions {
            filename: Some("M.svelte".to_string()),
            generate: GenerateMode::Client,
            dev: false,
            ..Default::default()
        },
    )
    .expect("compile")
    .js
    .map
    .expect("the client map is on by default");

    let mappings = map
        .split("\"mappings\":")
        .nth(1)
        .and_then(|rest| rest.split('"').nth(1))
        .expect("mappings field")
        .to_string();

    let mut out = BTreeSet::new();
    let mut state = [0i64; 4];
    for (generated_line, line) in mappings.split(';').enumerate() {
        state[0] = 0;
        for segment in line.split(',') {
            if segment.is_empty() {
                continue;
            }
            let mut fields = Vec::new();
            let mut value = 0i64;
            let mut shift = 0u32;
            for byte in segment.bytes() {
                let digit = match byte {
                    b'A'..=b'Z' => i64::from(byte - b'A'),
                    b'a'..=b'z' => i64::from(byte - b'a') + 26,
                    b'0'..=b'9' => i64::from(byte - b'0') + 52,
                    b'+' => 62,
                    b'/' => 63,
                    _ => panic!("not a base64 VLQ digit: {byte}"),
                };
                value += (digit & 31) << shift;
                shift += 5;
                if digit & 32 == 0 {
                    let negative = value & 1 == 1;
                    value >>= 1;
                    fields.push(if negative { -value } else { value });
                    value = 0;
                    shift = 0;
                }
            }
            state[0] += fields[0];
            if fields.len() < 4 {
                continue;
            }
            state[1] += fields[1];
            state[2] += fields[2];
            state[3] += fields[3];
            out.insert((
                (i64::try_from(generated_line).expect("line fits"), state[0]),
                (state[2], state[3]),
            ));
        }
    }
    out
}

fn pairs(spelled: &str) -> BTreeSet<((i64, i64), (i64, i64))> {
    spelled
        .split_whitespace()
        .map(|pair| {
            let (generated, source) = pair.split_once("->").expect("generated->source");
            let split = |text: &str| {
                let (line, column) = text.split_once(':').expect("line:column");
                (line.parse().expect("line"), column.parse().expect("column"))
            };
            (split(generated), split(source))
        })
        .collect()
}

/// The oracle's pairs must all be present. rsvelte emits segments upstream does
/// not, so equality is the wrong assertion; a dropped or mis-anchored one is
/// what this catches.
fn assert_covers_oracle(source: &str, oracle: &str) {
    let ours = source_pairs(source);
    let missing: Vec<_> = pairs(oracle).difference(&ours).copied().collect();
    assert!(
        missing.is_empty(),
        "official pairs rsvelte does not reproduce: {missing:?}\nours: {ours:?}"
    );
}

/// `count++` inside an arrow becomes `$.update(count)` — a rewrite that deletes
/// `++` and inserts a call, so neither a source-only nor a generated-only skip
/// finds the next common run.
#[test]
fn cell_update_expression_in_an_arrow() {
    assert_covers_oracle(
        "<script lang=\"ts\">\n\tlet count: number = 0;\n\tsetInterval(() => count++, 1000);\n</script>\n<div>{count}</div>\n",
        "6:36->0:0 6:37->0:1 7:1->1:1 7:5->1:5 7:10->1:18 7:30->1:21 7:31->1:22
         9:1->2:1 9:12->2:12 9:28->2:19 9:33->2:24 9:36->2:28 9:40->2:32
         11:5->4:1 11:8->4:4 12:20->4:1 12:23->4:4 14:9->4:1 14:12->4:4
         15:48->4:6 15:53->4:11 16:20->4:1 16:23->4:4 17:0->3:8 17:1->3:9",
    );
}

/// An import above the first copied fragment. `let count = $.mutable_source(0)`
/// is the first fragment, so the aligner has no earlier span to bound the
/// search: with only the near window it anchors into the import's own `;`
/// instead, and the declaration's three positions land in line 1.
#[test]
fn cell_first_fragment_after_an_import() {
    assert_covers_oracle(
        "<script lang=\"ts\">\n\timport { onMount } from 'svelte';\n\n\tlet count: number = 0;\n\n\tonMount(() => count++);\n</script>\n<div>{count}</div>\n",
        "3:0->1:1 3:7->1:8 3:9->1:10 3:16->1:17 3:24->1:25 3:32->1:33
         7:45->0:0 7:46->0:1 10:1->3:1 10:5->3:5 10:10->3:18 10:30->3:21 10:31->3:22
         12:1->5:1 12:8->5:8 12:24->5:15 12:29->5:20
         15:5->7:1 15:8->7:4 16:20->7:1 16:23->7:4 18:9->7:1 18:12->7:4
         19:48->7:6 19:53->7:11 20:20->7:1 20:23->7:4 22:0->6:8 22:1->6:9",
    );
}
