//! Upstream's dev `$.assign` wrap skips a right-hand side `scope.evaluate` calls
//! primitive, and its `Identifier` arm resolves the name through
//! `binding.initial` when the binding is neither a prop nor ever updated
//! (`scope.js:303`).
//!
//! Two properties of that guard decide the rows below. `updated` is a getter
//! over `mutated || reassigned` (`scope.js:174`), which phase 2 keeps as two
//! fields — the `mutated_*` rows fail in the OPPOSITE direction from the defect
//! and every other written row spells a REASSIGNMENT, so a port reading one
//! field passes all of them. And the guard has to be read off phase 2's view of
//! the ORIGINAL script, because the settled text has turned every write into a
//! call (`$.set` / `$.update` / `$.update_pre`) and oxc scores the name's only
//! occurrence a read.
//!
//! HOST is the axis, not the binding: an assignment in a `<script>` function
//! reaches `assign_dev_ast`, one in a template-inline arrow reaches
//! `expression_converter`, and both had the gap. Expected values are the
//! official compiler's own, generated by compiling each cell.

use rsvelte_core::{CompileOptions, GenerateMode, compile};

/// `(name, declaration, write, script-host wraps, inline-host wraps)`.
const CELLS: &[(&str, &str, &str, bool, bool)] = &[
    (
        "never_written_plain",
        r#"let g = Math.round(1.5);"#,
        r#""#,
        false,
        false,
    ),
    (
        "reassigned",
        r#"let g = Math.round(1.5);"#,
        r#"g = 2;"#,
        true,
        true,
    ),
    (
        "update",
        r#"let g = Math.round(1.5);"#,
        r#"g++;"#,
        true,
        true,
    ),
    (
        "state_never_written",
        r#"let g = $state(Math.round(1.5));"#,
        r#""#,
        false,
        false,
    ),
    (
        "state_reassigned",
        r#"let g = $state(Math.round(1.5));"#,
        r#"g = 2;"#,
        true,
        true,
    ),
    (
        "const_global_call",
        r#"const g = Math.round(1.5);"#,
        r#""#,
        false,
        false,
    ),
    ("const_literal", r#"const g = 7;"#, r#""#, false, false),
    ("const_binary", r#"const g = 1 + 2;"#, r#""#, false, false),
    (
        "const_template",
        r#"const g = `a${1}`;"#,
        r#""#,
        false,
        false,
    ),
    (
        "const_ternary",
        r#"const g = 1 ? 2 : 3;"#,
        r#""#,
        false,
        false,
    ),
    ("const_arrow", r#"const g = () => 1;"#, r#""#, false, false),
    ("const_object", r#"const g = {};"#, r#""#, true, true),
    ("const_array", r#"const g = [];"#, r#""#, true, true),
    ("const_new", r#"const g = new Date();"#, r#""#, true, true),
    ("no_initializer", r#"let g;"#, r#""#, true, true),
    (
        "chain_primitive",
        r#"const h = 1; const g = h;"#,
        r#""#,
        false,
        false,
    ),
    (
        "chain_object",
        r#"const h = {}; const g = h;"#,
        r#""#,
        true,
        true,
    ),
    (
        "mutated_member",
        r#"const g = 7;"#,
        r#"g.x = 1;"#,
        true,
        true,
    ),
    (
        "mutated_inner",
        r#"const h = 1; const g = h;"#,
        r#"h.x = 1;"#,
        true,
        true,
    ),
];

fn wraps(source: &str) -> bool {
    let options = CompileOptions {
        generate: GenerateMode::Client,
        dev: true,
        filename: Some("C.svelte".to_string()),
        ..Default::default()
    };
    compile(source, options)
        .expect("cell must compile")
        .js
        .code
        .contains("$.assign(")
}

fn script_host(decl: &str, write: &str) -> String {
    format!(
        "<script>\n\tlet o = $state({{}});\n\t{decl}\n\tfunction f() {{ {write} o.a = o.b = g; }}\n</script>\n<button onclick={{f}}>x</button>\n"
    )
}

fn inline_host(decl: &str, write: &str) -> String {
    format!(
        "<script>\n\tlet o = $state({{}});\n\t{decl}\n</script>\n<button onclick={{() => {{ {write} o.a = o.b = g; }}}}>x</button>\n"
    )
}

#[test]
fn both_hosts_agree_with_upstream_on_which_right_hand_side_is_primitive() {
    let mut wrong = Vec::new();
    for &(name, decl, write, want_script, want_inline) in CELLS {
        let got_script = wraps(&script_host(decl, write));
        if got_script != want_script {
            wrong.push(format!(
                "script/{name}: want {want_script}, got {got_script}"
            ));
        }
        let got_inline = wraps(&inline_host(decl, write));
        if got_inline != want_inline {
            wrong.push(format!(
                "inline/{name}: want {want_inline}, got {got_inline}"
            ));
        }
    }
    assert!(wrong.is_empty(), "{}", wrong.join("\n"));
}

/// A shadowed name has no scope chain in the settled fragment, so the resolver
/// refuses rather than taking the first match — which leaves the wrap in place.
/// The second cell is the direction that refusal costs: upstream resolves to the
/// inner primitive and does not wrap. Both cells are pinned so a later scope-aware
/// lookup shows up as a change here rather than as a silent one.
///
/// Neither cell is an identity probe: both pass before the fix too, because a
/// tree that never folds wraps everything. They discriminate the FIRST version
/// of this fix — a flat first-match lookup — from the corrected one.
#[test]
fn a_shadowed_name_is_refused_rather_than_guessed() {
    let outer_primitive = "<script>\n\tlet o = $state({});\n\tconst g = 7;\n\tfunction f() { const g = {}; o.a = o.b = g; }\n</script>\n<button onclick={f}>x</button>\n";
    let outer_object = "<script>\n\tlet o = $state({});\n\tconst g = {};\n\tfunction f() { const g = 7; o.a = o.b = g; }\n</script>\n<button onclick={f}>x</button>\n";
    assert!(
        wraps(outer_primitive),
        "upstream wraps: the inner `g` is an object"
    );
    assert!(
        wraps(outer_object),
        "upstream does NOT wrap here; the refusal is conservative and costs only output equality"
    );
}

/// Upstream's `scope.evaluate` is a case per node type (`scope.js:269-562`) and a
/// sequence is not among them, so both of these keep the wrap. The first was
/// already wrong before the identifier resolution existed; the second is what
/// making the predicate reachable from an initializer would have added.
#[test]
fn a_sequence_expression_is_not_a_known_primitive() {
    let direct = "<script>\n\tlet o = $state({});\n\tfunction f() { o.a = o.b = (1, 2); }\n</script>\n<button onclick={f}>x</button>\n";
    let via_initializer = "<script>\n\tlet o = $state({});\n\tconst g = (1, 2);\n\tfunction f() { o.a = o.b = g; }\n</script>\n<button onclick={f}>x</button>\n";
    assert!(wraps(direct), "a sequence right-hand side keeps the wrap");
    assert!(
        wraps(via_initializer),
        "and so does one reached through a binding"
    );
}

/// The initializer is re-parsed out of its original source range, so a TypeScript
/// annotation is inside the slice. Both spellings must still fold.
#[test]
fn a_typescript_initializer_still_folds() {
    for decl in ["const g = 1 as number;", "const g: number = 1;"] {
        let source = format!(
            "<script lang=\"ts\">\n\tlet o = $state({{}});\n\t{decl}\n\tfunction f() {{ o.a = o.b = g; }}\n</script>\n<button onclick={{f}}>x</button>\n"
        );
        assert!(!wraps(&source), "{decl} must fold");
    }
}
