//! A binding's own type annotation belongs to the binding's range upstream, so
//! esrap stamps the annotation's end where rsvelte stamped the binding's own
//! last byte. rsvelte erases the annotation from the script text before
//! re-parsing, which is why the position has to be carried separately
//! (`ScriptProjection::binding_annotation_ends`).
//!
//! Every expected position below was generated by compiling the same source with
//! the official compiler (`submodules/svelte/packages/svelte/src/compiler/index.js`)
//! and reading its client map; none was read back out of rsvelte.

use rsvelte_core::{CompileOptions, GenerateMode, compile};
use std::collections::BTreeSet;

/// The distinct `line:column` source positions the client map points at.
fn source_positions(source: &str) -> BTreeSet<(i64, i64)> {
    let map = compile(
        source,
        CompileOptions {
            filename: Some("M.svelte".to_string()),
            generate: GenerateMode::Client,
            dev: false,
            ..Default::default()
        },
    )
    .expect("compile")
    .js
    .map
    .expect("the client map is on by default");

    let mappings = map
        .split("\"mappings\":")
        .nth(1)
        .and_then(|rest| rest.split('"').nth(1))
        .expect("mappings field")
        .to_string();

    let mut out = BTreeSet::new();
    let mut state = [0i64; 4];
    for line in mappings.split(';') {
        state[0] = 0;
        for segment in line.split(',') {
            if segment.is_empty() {
                continue;
            }
            let mut fields = Vec::new();
            let mut value = 0i64;
            let mut shift = 0u32;
            for byte in segment.bytes() {
                let digit = match byte {
                    b'A'..=b'Z' => i64::from(byte - b'A'),
                    b'a'..=b'z' => i64::from(byte - b'a') + 26,
                    b'0'..=b'9' => i64::from(byte - b'0') + 52,
                    b'+' => 62,
                    b'/' => 63,
                    _ => panic!("not a base64 VLQ digit: {byte}"),
                };
                value += (digit & 31) << shift;
                shift += 5;
                if digit & 32 == 0 {
                    let negative = value & 1 == 1;
                    value >>= 1;
                    fields.push(if negative { -value } else { value });
                    value = 0;
                    shift = 0;
                }
            }
            state[0] += fields[0];
            if fields.len() < 4 {
                continue;
            }
            state[1] += fields[1];
            state[2] += fields[2];
            state[3] += fields[3];
            out.insert((state[2], state[3]));
        }
    }
    out
}

fn positions(spelled: &str) -> BTreeSet<(i64, i64)> {
    spelled
        .split_whitespace()
        .map(|pair| {
            let (line, column) = pair.split_once(':').expect("line:column");
            (line.parse().expect("line"), column.parse().expect("column"))
        })
        .collect()
}

/// no annotation anywhere - a negative control the fix must not move
#[test]
fn cell_no_annotation() {
    assert_eq!(
        source_positions("<script lang=\"ts\">\n\tlet a = 0;\n\tlet b = 1;\n</script>\n{a}{b}\n"),
        positions("0:0 0:1 1:1 1:5 1:6 1:9 1:10 2:1 2:5 2:6 2:9 2:10 3:8 3:9")
    );
}

/// `let count: number = 0` - the reported shape
#[test]
fn cell_declarator() {
    assert_eq!(
        source_positions("<script lang=\"ts\">\n\tlet count: number = 0;\n</script>\n{count}\n"),
        positions("0:0 0:1 1:1 1:5 1:18 1:21 1:22 2:8 2:9")
    );
}

/// an annotated declaration followed by an unannotated one - the cell that
/// falsifies "stripped coordinates are emitted raw": `b` is untouched
#[test]
fn cell_annotated_then_plain() {
    assert_eq!(
        source_positions(
            "<script lang=\"ts\">\n\tlet a: number = 0;\n\tlet b = 1;\n</script>\n{a}{b}\n"
        ),
        positions("0:0 0:1 1:1 1:5 1:14 1:17 1:18 2:1 2:5 2:6 2:9 2:10 3:8 3:9")
    );
}

/// a space before the colon - the cell that falsifies a touching-boundary
/// rule, because the binding does not end at the erased run boundary
#[test]
fn cell_space_before_colon() {
    assert_eq!(
        source_positions("<script lang=\"ts\">\n\tlet count : number = 0;\n</script>\n{count}\n"),
        positions("0:0 0:1 1:1 1:5 1:19 1:22 1:23 2:8 2:9")
    );
}

/// a function parameter
#[test]
fn cell_function_parameter() {
    assert_eq!(
        source_positions(
            "<script lang=\"ts\">\n\texport function f(a: number) { return a; }\n</script>\n{f(1)}\n"
        ),
        positions(
            "0:0 0:1 1:8 1:16 1:17 1:18 1:19 1:28 1:30 1:31 1:32 1:38 1:39 1:40 1:42 1:43 2:8 2:9 3:1 3:2 3:3 3:4"
        )
    );
}

/// an arrow parameter, with a return type beside it
#[test]
fn cell_arrow_parameter() {
    assert_eq!(
        source_positions(
            "<script lang=\"ts\">\n\tconst g = (a: number): number => a;\n</script>\n{g(1)}\n"
        ),
        positions("0:0 0:1 1:1 1:7 1:8 1:12 1:21 1:34 1:35 2:8 2:9 3:1 3:2 3:3 3:4")
    );
}

/// a destructuring pattern - correct before the fix and after it
#[test]
fn cell_destructuring_pattern() {
    assert_eq!(
        source_positions(
            "<script lang=\"ts\">\n\tlet { a, b }: { a: number; b: number } = { a: 1, b: 2 };\n</script>\n{a}{b}\n"
        ),
        positions(
            "0:0 0:1 1:1 1:5 1:7 1:8 1:10 1:11 1:44 1:45 1:47 1:48 1:50 1:51 1:53 1:54 2:8 2:9 3:1 3:2 3:4 3:5"
        )
    );
}

/// a rest parameter - upstream keeps the annotation on the `RestElement`
/// and stamps the inner identifier, so this cell must NOT be extended
#[test]
fn cell_rest_parameter() {
    assert_eq!(
        source_positions(
            "<script lang=\"ts\">\n\texport function h(...r: number[]) { return r.length; }\n</script>\n{h(1)}\n"
        ),
        positions(
            "0:0 0:1 1:8 1:16 1:17 1:18 1:22 1:23 1:35 1:36 1:37 1:43 1:44 1:45 1:46 1:52 1:54 1:55 2:8 2:9 3:1 3:2 3:3 3:4"
        )
    );
}

/// a catch parameter.
///
/// The only cell that also carries a SECOND, unrelated divergence: rsvelte emits
/// five source positions the oracle does not. Measured on both arms of this fix,
/// all five are present before it and after it, so they are pinned rather than
/// folded into agreement. What this fix owns here is the oracle's `2:29`, which
/// rsvelte used to spell as `2:24` — the end of `e` rather than of `e: any`.
#[test]
fn cell_catch_parameter() {
    let oracle = positions(
        "0:0 0:1 1:1 1:5 1:6 1:9 1:10 2:1 2:4 2:5 2:6 2:7 2:8 2:11 2:12 2:14 2:15 2:16 2:21 2:23 2:29 2:31 2:32 2:33 2:34 2:37 2:38 2:40 2:41 3:8 3:9 4:1 4:2",
    );
    let got = source_positions(
        "<script lang=\"ts\">\n\tlet m = 0;\n\ttry { m = 1; } catch (e: any) { m = 2; }\n</script>\n{m}\n",
    );

    let missing: Vec<_> = oracle.difference(&got).copied().collect();
    assert_eq!(
        missing,
        Vec::new(),
        "positions the oracle emits and rsvelte does not"
    );

    let extra: Vec<_> = got.difference(&oracle).copied().collect();
    assert_eq!(
        extra,
        positions("0:10 2:9 2:18 2:36 3:5")
            .into_iter()
            .collect::<Vec<_>>(),
        "pre-existing extras, unrelated to a type annotation"
    );
}

/// a parameter with both an annotation and a default
#[test]
fn cell_parameter_with_default() {
    assert_eq!(
        source_positions(
            "<script lang=\"ts\">\n\texport function g(p: number = 1) { return p; }\n</script>\n{g(2)}\n"
        ),
        positions(
            "0:0 0:1 1:8 1:16 1:17 1:18 1:19 1:28 1:31 1:32 1:34 1:35 1:36 1:42 1:43 1:44 1:46 1:47 2:8 2:9 3:1 3:2 3:3 3:4"
        )
    );
}
