//! An `import` declaration needs no whitespace after the keyword: `import"pkg";`
//! is what Bun's TypeScript transpiler prints. The client's import extractor keyed
//! on the literal prefixes `import ` / `import{`, so such a statement stayed inside
//! the component function.
//!
//! Expected values are the official compiler's output for the same source.

use rsvelte_core::{CompileOptions, GenerateMode, ModuleCompileOptions, compile, compile_module};

/// The module banner carries the pinned Svelte version, so it is read from the
/// same place the compiler reads it rather than spelled again here.
const SVELTE_VERSION: &str = match option_env!("SVELTE_VERSION") {
    Some(version) => version,
    None => "VERSION",
};

fn component(src: &str, generate: GenerateMode, dev: bool) -> String {
    compile(
        src,
        CompileOptions {
            filename: Some("T.svelte".to_string()),
            generate,
            dev,
            ..Default::default()
        },
    )
    .expect("compile")
    .js
    .code
}

fn module(src: &str, generate: GenerateMode, dev: bool) -> String {
    compile_module(
        src,
        ModuleCompileOptions {
            filename: Some("T.svelte.js".to_string()),
            generate,
            dev,
            ..Default::default()
        },
    )
    .expect("compile_module")
    .js
    .code
}

#[test]
fn side_effect_import_hoists_on_the_client() {
    let src = r#"<script>import"side-effect-pkg";
let n = $state(0);</script>
<b>{n}</b>"#;
    let expected = r#"import 'svelte/internal/disclose-version';
import * as $ from 'svelte/internal/client';
import "side-effect-pkg";

var root = $.from_html(`<b></b>`);

export default function T($$anchor) {
	let n = 0;
	var b = root();

	b.textContent = '0';
	$.append($$anchor, b);
}"#;
    assert_eq!(component(src, GenerateMode::Client, false), expected);
}

#[test]
fn side_effect_import_hoists_on_the_client_in_dev() {
    let src = r#"<script>import"side-effect-pkg";
let n = $state(0);</script>
<b>{n}</b>"#;
    let expected = r#"import 'svelte/internal/disclose-version';

T[$.FILENAME] = 'T.svelte';

import * as $ from 'svelte/internal/client';
import "side-effect-pkg";

var root = $.add_locations($.from_html(`<b></b>`), T[$.FILENAME], [[3, 0]]);

export default function T($$anchor, $$props) {
	$.check_target(new.target);
	$.push($$props, true, T);

	let n = 0;
	var $$exports = { ...$.legacy_api() };
	var b = root();

	b.textContent = '0';
	$.append($$anchor, b);

	return $.pop($$exports);
}"#;
    assert_eq!(component(src, GenerateMode::Client, true), expected);
}

#[test]
fn side_effect_import_hoists_from_a_ts_script() {
    let src = r#"<script lang="ts">import"side-effect-pkg";
let n: number = $state(0);</script>
<b>{n}</b>"#;
    let expected = r#"import 'svelte/internal/disclose-version';
import * as $ from 'svelte/internal/client';
import "side-effect-pkg";

var root = $.from_html(`<b></b>`);

export default function T($$anchor) {
	let n = 0;
	var b = root();

	b.textContent = '0';
	$.append($$anchor, b);
}"#;
    assert_eq!(component(src, GenerateMode::Client, false), expected);
}

#[test]
fn side_effect_import_hoists_from_the_module_script() {
    let src = r#"<script module>import"side-effect-pkg";
</script>
<script>let n = $state(0);</script>
<b>{n}</b>"#;
    let expected = r#"import 'svelte/internal/disclose-version';
import "side-effect-pkg";
import * as $ from 'svelte/internal/client';

var root = $.from_html(`<b></b>`);

export default function T($$anchor) {
	let n = 0;
	var b = root();

	b.textContent = '0';
	$.append($$anchor, b);
}"#;
    assert_eq!(component(src, GenerateMode::Client, false), expected);
}

#[test]
fn side_effect_import_hoists_on_the_server() {
    let src = r#"<script>import"side-effect-pkg";
let n = $state(0);</script>
<b>{n}</b>"#;
    let expected = r#"import * as $ from 'svelte/internal/server';
import "side-effect-pkg";

export default function T($$renderer) {
	let n = 0;

	$$renderer.push(`<b>0</b>`);
}"#;
    assert_eq!(component(src, GenerateMode::Server, false), expected);
}

#[test]
fn side_effect_import_stays_first_in_a_module() {
    let src = r#"import"side-effect-pkg";
export const n = $state({v:0});"#;
    let expected = format!(
        r#"/* T.svelte.js generated by Svelte v{SVELTE_VERSION} */
import * as $ from 'svelte/internal/client';
import "side-effect-pkg";

export const n = $.proxy({{ v: 0 }});"#
    );
    assert_eq!(module(src, GenerateMode::Client, false), expected);
}

#[test]
fn single_quoted_specifier() {
    let src = r#"<script>import'side-effect-pkg';
let n = $state(0);</script>
<b>{n}</b>"#;
    let expected = r#"import 'svelte/internal/disclose-version';
import * as $ from 'svelte/internal/client';
import 'side-effect-pkg';

var root = $.from_html(`<b></b>`);

export default function T($$anchor) {
	let n = 0;
	var b = root();

	b.textContent = '0';
	$.append($$anchor, b);
}"#;
    assert_eq!(component(src, GenerateMode::Client, false), expected);
}

#[test]
fn specifier_on_the_next_line() {
    let src = r#"<script>import
"side-effect-pkg";
let n = $state(0);</script>
<b>{n}</b>"#;
    let expected = r#"import 'svelte/internal/disclose-version';
import * as $ from 'svelte/internal/client';
import "side-effect-pkg";

var root = $.from_html(`<b></b>`);

export default function T($$anchor) {
	let n = 0;
	var b = root();

	b.textContent = '0';
	$.append($$anchor, b);
}"#;
    assert_eq!(component(src, GenerateMode::Client, false), expected);
}

#[test]
fn comment_between_keyword_and_specifier() {
    let src = r#"<script>import/**/"side-effect-pkg";
let n = $state(0);</script>
<b>{n}</b>"#;
    let expected = r#"import 'svelte/internal/disclose-version';
import * as $ from 'svelte/internal/client';
import "side-effect-pkg";

var root = $.from_html(`<b></b>`);

export default function T($$anchor) {
	/**/
	let n = 0;

	var b = root();

	b.textContent = '0';
	$.append($$anchor, b);
}"#;
    assert_eq!(component(src, GenerateMode::Client, false), expected);
}

#[test]
fn namespace_import() {
    let src = r#"<script>import*as ns from"side-effect-pkg";
let n = $state(0);</script>
<b>{n}</b>"#;
    let expected = r#"import 'svelte/internal/disclose-version';
import * as $ from 'svelte/internal/client';
import * as ns from "side-effect-pkg";

var root = $.from_html(`<b></b>`);

export default function T($$anchor) {
	let n = 0;
	var b = root();

	b.textContent = '0';
	$.append($$anchor, b);
}"#;
    assert_eq!(component(src, GenerateMode::Client, false), expected);
}

#[test]
fn namespace_import_ended_by_asi() {
    let src = r#"<script>import*as ns from"side-effect-pkg"
let n = $state(0);</script>
<b>{n}</b>"#;
    let expected = r#"import 'svelte/internal/disclose-version';
import * as $ from 'svelte/internal/client';
import * as ns from "side-effect-pkg";

var root = $.from_html(`<b></b>`);

export default function T($$anchor) {
	let n = 0;
	var b = root();

	b.textContent = '0';
	$.append($$anchor, b);
}"#;
    assert_eq!(component(src, GenerateMode::Client, false), expected);
}

#[test]
fn named_import_ended_by_asi() {
    let src = r#"<script>import{tick}from"svelte"
let n = $state(0);</script>
<b>{n}</b>"#;
    let expected = r#"import 'svelte/internal/disclose-version';
import * as $ from 'svelte/internal/client';
import { tick } from "svelte";

var root = $.from_html(`<b></b>`);

export default function T($$anchor) {
	let n = 0;
	var b = root();

	b.textContent = '0';
	$.append($$anchor, b);
}"#;
    assert_eq!(component(src, GenerateMode::Client, false), expected);
}

#[test]
fn default_import_ended_by_asi() {
    let src = r#"<script>import d from"side-effect-pkg"
let n = $state(0);</script>
<b>{n}</b>"#;
    let expected = r#"import 'svelte/internal/disclose-version';
import * as $ from 'svelte/internal/client';
import d from "side-effect-pkg";

var root = $.from_html(`<b></b>`);

export default function T($$anchor) {
	let n = 0;
	var b = root();

	b.textContent = '0';
	$.append($$anchor, b);
}"#;
    assert_eq!(component(src, GenerateMode::Client, false), expected);
}

#[test]
fn packed_imports_on_one_line() {
    let src = r#"<script>import"a-pkg";import{tick}from"svelte";
let n = $state(0);</script>
<b>{n}</b>"#;
    let expected = r#"import 'svelte/internal/disclose-version';
import * as $ from 'svelte/internal/client';
import "a-pkg";
import { tick } from "svelte";

var root = $.from_html(`<b></b>`);

export default function T($$anchor) {
	let n = 0;
	var b = root();

	b.textContent = '0';
	$.append($$anchor, b);
}"#;
    assert_eq!(component(src, GenerateMode::Client, false), expected);
}

#[test]
fn dynamic_import_statement_is_not_a_declaration() {
    let src = r#"<script>import ("side-effect-pkg");
let n = $state(0);</script>
<b>{n}</b>"#;
    let expected = r#"import 'svelte/internal/disclose-version';
import * as $ from 'svelte/internal/client';

var root = $.from_html(`<b></b>`);

export default function T($$anchor) {
	import("side-effect-pkg");

	let n = 0;
	var b = root();

	b.textContent = '0';
	$.append($$anchor, b);
}"#;
    assert_eq!(component(src, GenerateMode::Client, false), expected);
}

#[test]
fn import_meta_statement_is_not_a_declaration() {
    let src = r#"<script>import.meta.url;
let n = $state(0);</script>
<b>{n}</b>"#;
    let expected = r#"import 'svelte/internal/disclose-version';
import * as $ from 'svelte/internal/client';

var root = $.from_html(`<b></b>`);

export default function T($$anchor, $$props) {
	$.push($$props, true);
	import.meta.url;

	let n = 0;
	var b = root();

	b.textContent = '0';
	$.append($$anchor, b);
	$.pop();
}"#;
    assert_eq!(component(src, GenerateMode::Client, false), expected);
}

#[test]
fn import_property_key_on_its_own_line_is_not_a_declaration() {
    let src = r#"<script>
	const modules = import.meta.glob("./examples/*.svelte", {
		query: "?raw",
		import: "default",
		eager: true
	});
</script>

<b>{Object.keys(modules).length}</b>"#;
    let expected = r#"import 'svelte/internal/disclose-version';
import 'svelte/internal/flags/legacy';
import * as $ from 'svelte/internal/client';

var root = $.from_html(`<b> </b>`);

export default function T($$anchor, $$props) {
	$.push($$props, false);

	const modules = import.meta.glob("./examples/*.svelte", { query: "?raw", import: "default", eager: true });

	$.init();

	var b = root();
	var text = $.only_child(b, true);

	$.template_effect(($0) => $.set_text(text, $0), [() => Object.keys(modules).length]);
	$.append($$anchor, b);
	$.pop();
}"#;
    assert_eq!(component(src, GenerateMode::Client, false), expected);
}

#[test]
fn a_block_comment_after_the_keyword_may_close_on_a_later_line() {
    let src =
        "<script>\nimport /* a\n b */ x from \"m\";\nlet n = $state(x);\n</script>\n<b>{n}</b>";
    let expected = r#"import 'svelte/internal/disclose-version';
import * as $ from 'svelte/internal/client';
import x from "m";

var root = $.from_html(`<b> </b>`);

export default function T($$anchor) {
	/* a
	 b */
	let n = $.proxy(x);

	var b = root();
	var text = $.only_child(b, true);

	$.template_effect(() => $.set_text(text, n));
	$.append($$anchor, b);
}"#;
    assert_eq!(component(src, GenerateMode::Client, false), expected);
}
