//! `compileModule` keeps an `import` where the source put it.
//!
//! Upstream's `client_module` / `server_module` concatenate the generated `$`
//! import with the walked module body untouched, so statement order is the
//! source's. rsvelte split the transformed text into "imports" and "rest" with
//! a line scan and emitted every import first, which moves a module's side
//! effects relative to a preceding `export … from` (issue #3073).
//!
//! Every expectation is the official compiler's own output for the same source
//! (`compileModule`, `filename: 'T.svelte.js'`, `dev: false`).

use rsvelte_core::compiler::ModuleCompileOptions;
use rsvelte_core::{GenerateMode, compile_module};

fn compile(src: &str, generate: GenerateMode) -> String {
    compile_module(
        src,
        ModuleCompileOptions {
            filename: Some("T.svelte.js".to_string()),
            generate,
            dev: false,
            ..Default::default()
        },
    )
    .expect("compile")
    .js
    .code
}

fn client(src: &str) -> String {
    compile(src, GenerateMode::Client)
}

fn server(src: &str) -> String {
    compile(src, GenerateMode::Server)
}

/// The issue's repro. Upstream's esrap prints `export * ` and then ` from `,
/// so official's bytes carry a double space there; the corpus comparison
/// normalizes it away and it is not what this test is about, so only the
/// statement order is asserted for this shape.
#[test]
fn an_import_stays_below_a_preceding_export_all() {
    let src = "export * from './other.js';\nimport { thing } from './other.js';\nexport const use = () => thing;\n";
    for out in [client(src), server(src)] {
        let export_all = out.find("export *").expect("export * emitted");
        let import = out
            .find("import { thing }")
            .expect("the user import is emitted");
        assert!(
            export_all < import,
            "`import` was hoisted above `export * from`:\n{out}"
        );
    }
}

/// A side-effect import between two statements evaluates where it was written.
#[test]
fn a_side_effect_import_keeps_its_slot() {
    let src = "import './a.js';\nexport const x = 1;\nimport './b.js';\nexport const y = 2;\n";
    assert_eq!(
        client(src),
        "/* T.svelte.js generated by Svelte v5.56.9 */\nimport * as $ from 'svelte/internal/client';\nimport './a.js';\n\nexport const x = 1;\n\nimport './b.js';\n\nexport const y = 2;"
    );
    assert_eq!(
        server(src),
        "/* T.svelte.js generated by Svelte v5.56.9 */\nimport * as $ from 'svelte/internal/server';\nimport './a.js';\n\nexport const x = 1;\n\nimport './b.js';\n\nexport const y = 2;"
    );
}

/// A rune declaration below an import is still lowered, and the import does not
/// jump above the statement that precedes it.
#[test]
fn a_state_declaration_below_an_import_is_still_lowered() {
    let src = "export const a = 1;\nimport { b } from './b.js';\nlet c = $state(0);\nexport function inc() { c += b; }\n";
    assert_eq!(
        client(src),
        "/* T.svelte.js generated by Svelte v5.56.9 */\nimport * as $ from 'svelte/internal/client';\n\nexport const a = 1;\n\nimport { b } from './b.js';\n\nlet c = $.state(0);\n\nexport function inc() {\n\t$.set(c, $.get(c) + b);\n}"
    );
    assert_eq!(
        server(src),
        "/* T.svelte.js generated by Svelte v5.56.9 */\nimport * as $ from 'svelte/internal/server';\n\nexport const a = 1;\n\nimport { b } from './b.js';\n\nlet c = 0;\n\nexport function inc() {\n\tc += b;\n}"
    );
}

/// An `$effect.root` in the module routes the body through the effect-aware
/// print path; the import below `export … from` still keeps its place there.
#[test]
fn an_effect_bearing_module_keeps_import_order() {
    let src = "export { z } from './z.js';\nimport { q } from './q.js';\nlet v = $state(0);\n$effect.root(() => { v = q; });\nexport const get = () => v;\n";
    assert_eq!(
        client(src),
        "/* T.svelte.js generated by Svelte v5.56.9 */\nimport * as $ from 'svelte/internal/client';\n\nexport { z } from './z.js';\n\nimport { q } from './q.js';\n\nlet v = $.state(0);\n\n$.effect_root(() => {\n\t$.set(v, q, true);\n});\n\nexport const get = () => $.get(v);"
    );
    assert_eq!(
        server(src),
        "/* T.svelte.js generated by Svelte v5.56.9 */\nimport * as $ from 'svelte/internal/server';\n\nexport { z } from './z.js';\n\nimport { q } from './q.js';\n\nlet v = 0;\n\nexport const get = () => v;"
    );
}

/// The word `import` inside a line comment is not a statement, so nothing about
/// it may move — the old line scan is exactly the shape #2986/#2987/#2988 broke
/// on, and this pipeline no longer decides statement kind by reading text.
#[test]
fn an_import_written_in_a_comment_moves_nothing() {
    let src = "export const a = 1;\n// import { x } from './b.js';\nimport { thing } from './c.js';\nexport const use = () => thing;\n";
    assert_eq!(
        client(src),
        "/* T.svelte.js generated by Svelte v5.56.9 */\nimport * as $ from 'svelte/internal/client';\n\nexport const a = 1;\n\nimport { thing } from './c.js';\n\nexport const use = () => thing;"
    );
    assert_eq!(
        server(src),
        "/* T.svelte.js generated by Svelte v5.56.9 */\nimport * as $ from 'svelte/internal/server';\n\nexport const a = 1;\n\nimport { thing } from './c.js';\n\nexport const use = () => thing;"
    );
}

/// A block comment spanning two lines, both of which spell an import.
#[test]
fn an_import_written_in_a_block_comment_moves_nothing() {
    let src = "export const a = 1;\n/* import { x } from './b.js';\n   import { w } from './e.js'; */\nimport { thing } from './c.js';\nexport const use = () => thing;\n";
    assert_eq!(
        client(src),
        "/* T.svelte.js generated by Svelte v5.56.9 */\nimport * as $ from 'svelte/internal/client';\n\nexport const a = 1;\n\nimport { thing } from './c.js';\n\nexport const use = () => thing;"
    );
    assert_eq!(
        server(src),
        "/* T.svelte.js generated by Svelte v5.56.9 */\nimport * as $ from 'svelte/internal/server';\n\nexport const a = 1;\n\nimport { thing } from './c.js';\n\nexport const use = () => thing;"
    );
}

/// The third carrier of the #2986/#2987/#2988 family: a regex literal.
#[test]
fn an_import_written_in_a_regex_literal_moves_nothing() {
    let src = "export const re = /import { y } from '.\\/d.js';/;\nimport { thing } from './c.js';\nexport const use = () => thing;\n";
    assert_eq!(
        client(src),
        "/* T.svelte.js generated by Svelte v5.56.9 */\nimport * as $ from 'svelte/internal/client';\n\nexport const re = /import { y } from '.\\/d.js';/;\n\nimport { thing } from './c.js';\n\nexport const use = () => thing;"
    );
    assert_eq!(
        server(src),
        "/* T.svelte.js generated by Svelte v5.56.9 */\nimport * as $ from 'svelte/internal/server';\n\nexport const re = /import { y } from '.\\/d.js';/;\n\nimport { thing } from './c.js';\n\nexport const use = () => thing;"
    );
}

/// And a template literal.
#[test]
fn an_import_written_in_a_template_literal_moves_nothing() {
    let src = "export const t = `import { y } from './d.js';`;\nimport { thing } from './c.js';\nexport const use = () => thing + t;\n";
    assert_eq!(
        client(src),
        "/* T.svelte.js generated by Svelte v5.56.9 */\nimport * as $ from 'svelte/internal/client';\n\nexport const t = `import { y } from './d.js';`;\n\nimport { thing } from './c.js';\n\nexport const use = () => thing + t;"
    );
    assert_eq!(
        server(src),
        "/* T.svelte.js generated by Svelte v5.56.9 */\nimport * as $ from 'svelte/internal/server';\n\nexport const t = `import { y } from './d.js';`;\n\nimport { thing } from './c.js';\n\nexport const use = () => thing + t;"
    );
}

/// The same for a string literal that spells an import statement.
#[test]
fn an_import_written_in_a_string_moves_nothing() {
    let src = "export const s = \"import { y } from './d.js';\";\nimport { thing } from './c.js';\nexport const use = () => thing + s;\n";
    assert_eq!(
        client(src),
        "/* T.svelte.js generated by Svelte v5.56.9 */\nimport * as $ from 'svelte/internal/client';\n\nexport const s = \"import { y } from './d.js';\";\n\nimport { thing } from './c.js';\n\nexport const use = () => thing + s;"
    );
    assert_eq!(
        server(src),
        "/* T.svelte.js generated by Svelte v5.56.9 */\nimport * as $ from 'svelte/internal/server';\n\nexport const s = \"import { y } from './d.js';\";\n\nimport { thing } from './c.js';\n\nexport const use = () => thing + s;"
    );
}
