//! Top-level (Program-level) comments in the `.svelte.(js|ts)` module path.
//!
//! Upstream prints the generated program with esrap, and `client_module` /
//! `server_module` return a **synthesized** `Program` that has no `loc`.
//! esrap's `reset_comment_index` handles a body without a `loc` by parking the
//! comment cursor past the end of the comment list, so nothing is emitted at
//! Program level. Only a nested body that *does* have a `loc` (a function
//! block, a class body) rewinds the cursor — which is why comments inside a
//! function body survive, and why a top-level comment that follows such a
//! block survives too, the rewind having moved the cursor back onto it.
//!
//! `tests/module_comment_ownership.rs` covers the dropped side. What is pinned
//! *only* here is the preserved side of the same rule — `after_fn_toplevel` and
//! `inside_fn_then_two_top`, where a top-level comment following a located body
//! survives. Parking the cursor at the end of a located body passes every
//! assertion of that file and fails exactly those two, which is the shape a
//! blanket "drop every Program-level comment" fix degenerates into: measured
//! against upstream it is wrong in 112 of 192 generated slots (#2399).
//!
//! Every expectation here is the official compiler's byte-exact output. Server
//! differs from client only in its generated runtime import.

use rsvelte_core::compiler::ModuleCompileOptions;
use rsvelte_core::{GenerateMode, compile_module};

fn compile(src: &str, generate: GenerateMode, dev: bool) -> String {
    compile_module(
        src,
        ModuleCompileOptions {
            filename: Some("m.svelte.js".to_string()),
            generate,
            dev,
            ..Default::default()
        },
    )
    .expect("compile")
    .js
    .code
}

struct Case {
    name: &'static str,
    src: &'static str,
    client: &'static str,
    client_dev: &'static str,
}

/// Expectations carry the pinned Svelte version in their header comment;
/// substitute the version this crate was built against.
fn expected(template: &str) -> String {
    template.replace("__V__", option_env!("SVELTE_VERSION").unwrap_or("VERSION"))
}

fn cases() -> Vec<Case> {
    vec![
        Case {
            name: "lead_before_decl",
            src: "// lead\nexport const a = 1;\n",
            client: "/* m.svelte.js generated by Svelte v__V__ */\nimport * as $ from 'svelte/internal/client';\n\nexport const a = 1;",
            client_dev: "/* m.svelte.js generated by Svelte v__V__ */\nimport * as $ from 'svelte/internal/client';\n\nexport const a = 1;",
        },
        Case {
            name: "between_stmts",
            src: "export const a = 1;\n// between\nexport const b = 2;\n",
            client: "/* m.svelte.js generated by Svelte v__V__ */\nimport * as $ from 'svelte/internal/client';\n\nexport const a = 1;\nexport const b = 2;",
            client_dev: "/* m.svelte.js generated by Svelte v__V__ */\nimport * as $ from 'svelte/internal/client';\n\nexport const a = 1;\nexport const b = 2;",
        },
        Case {
            name: "after_import",
            src: "import { x } from './x.js';\n// after import\nexport const a = 1;\n",
            client: "/* m.svelte.js generated by Svelte v__V__ */\nimport * as $ from 'svelte/internal/client';\nimport { x } from './x.js';\n\nexport const a = 1;",
            client_dev: "/* m.svelte.js generated by Svelte v__V__ */\nimport * as $ from 'svelte/internal/client';\nimport { x } from './x.js';\n\nexport const a = 1;",
        },
        Case {
            name: "jsdoc_before_fn",
            src: "/** doc */\nexport function f() {\n\treturn 1;\n}\n",
            client: "/* m.svelte.js generated by Svelte v__V__ */\nimport * as $ from 'svelte/internal/client';\n\nexport function f() {\n\treturn 1;\n}",
            client_dev: "/* m.svelte.js generated by Svelte v__V__ */\nimport * as $ from 'svelte/internal/client';\n\nexport function f() {\n\treturn 1;\n}",
        },
        Case {
            name: "license_header",
            src: "/* license */\nimport { x } from './x.js';\nexport const a = $state(0);\n",
            client: "/* m.svelte.js generated by Svelte v__V__ */\nimport * as $ from 'svelte/internal/client';\nimport { x } from './x.js';\n\nexport const a = 0;",
            client_dev: "/* m.svelte.js generated by Svelte v__V__ */\nimport * as $ from 'svelte/internal/client';\nimport { x } from './x.js';\n\nexport const a = 0;",
        },
        Case {
            name: "inside_fn_body",
            src: "export function f() {\n\t// inside\n\treturn 1;\n}\n",
            client: "/* m.svelte.js generated by Svelte v__V__ */\nimport * as $ from 'svelte/internal/client';\n\nexport function f() {\n\t// inside\n\treturn 1;\n}",
            client_dev: "/* m.svelte.js generated by Svelte v__V__ */\nimport * as $ from 'svelte/internal/client';\n\nexport function f() {\n\t// inside\n\treturn 1;\n}",
        },
        Case {
            name: "after_fn_toplevel",
            src: "export function f() {\n\treturn 1;\n}\n// after fn\nexport const a = 1;\n",
            client: "/* m.svelte.js generated by Svelte v__V__ */\nimport * as $ from 'svelte/internal/client';\n\nexport function f() {\n\treturn 1;\n}\n\n// after fn\nexport const a = 1;",
            client_dev: "/* m.svelte.js generated by Svelte v__V__ */\nimport * as $ from 'svelte/internal/client';\n\nexport function f() {\n\treturn 1;\n}\n\n// after fn\nexport const a = 1;",
        },
        Case {
            name: "trailing_same_line",
            src: "export const a = 1; // trailing\n",
            client: "/* m.svelte.js generated by Svelte v__V__ */\nimport * as $ from 'svelte/internal/client';\n\nexport const a = 1;",
            client_dev: "/* m.svelte.js generated by Svelte v__V__ */\nimport * as $ from 'svelte/internal/client';\n\nexport const a = 1;",
        },
        Case {
            name: "end_of_file",
            src: "export const a = 1;\n// eof\n",
            client: "/* m.svelte.js generated by Svelte v__V__ */\nimport * as $ from 'svelte/internal/client';\n\nexport const a = 1;",
            client_dev: "/* m.svelte.js generated by Svelte v__V__ */\nimport * as $ from 'svelte/internal/client';\n\nexport const a = 1;",
        },
        Case {
            name: "end_of_file_after_located_body",
            src: "export function f() {\n\treturn 1;\n}\nexport const a = 1;\n// eof\n",
            client: "/* m.svelte.js generated by Svelte v__V__ */\nimport * as $ from 'svelte/internal/client';\n\nexport function f() {\n\treturn 1;\n}\n\nexport const a = 1;",
            client_dev: "/* m.svelte.js generated by Svelte v__V__ */\nimport * as $ from 'svelte/internal/client';\n\nexport function f() {\n\treturn 1;\n}\n\nexport const a = 1;",
        },
        Case {
            name: "inside_fn_then_two_top",
            src: "export function f() {\n\t// inner\n}\n// t1\nexport const a = 1;\n// t2\nexport const b = 2;\n",
            client: "/* m.svelte.js generated by Svelte v__V__ */\nimport * as $ from 'svelte/internal/client';\n\nexport function f() {\n\t// inner\n}\n\n// t1\nexport const a = 1;\n\n// t2\nexport const b = 2;",
            client_dev: "/* m.svelte.js generated by Svelte v__V__ */\nimport * as $ from 'svelte/internal/client';\n\nexport function f() {\n\t// inner\n}\n\n// t1\nexport const a = 1;\n\n// t2\nexport const b = 2;",
        },
    ]
}

#[test]
fn module_toplevel_comments_match_upstream() {
    let mut failures = Vec::new();
    for case in cases() {
        for (target, generate, dev, want) in [
            (
                "client",
                GenerateMode::Client,
                false,
                case.client.to_string(),
            ),
            (
                "client-dev",
                GenerateMode::Client,
                true,
                case.client_dev.to_string(),
            ),
            (
                "server",
                GenerateMode::Server,
                false,
                case.client
                    .replace("svelte/internal/client", "svelte/internal/server"),
            ),
        ] {
            let got = compile(case.src, generate, dev);
            let want = expected(&want);
            if got != want {
                failures.push(format!(
                    "--- {} [{target}]\n--- input\n{}\n--- expected\n{want}\n--- actual\n{got}\n",
                    case.name, case.src
                ));
            }
        }
    }
    assert!(
        failures.is_empty(),
        "{} divergence(s):\n\n{}",
        failures.len(),
        failures.join("\n")
    );
}
