//! Non-dev `$inspect` removal in a `.svelte.(js|ts)` module.
//!
//! Upstream's `CallExpression` visitor returns `b.empty` for the CALL while the
//! `ExpressionStatement` around it survives, so the statement prints as `;;`.
//! rsvelte's module pipeline deleted the statement outright — and did it with a
//! raw `memmem::find(b"$inspect(")` scan, which also rewrote the token inside a
//! string, a template literal and a comment (issue #3231).
//!
//! Every expectation here is the official compiler's byte-for-byte output for
//! the same input, recorded from `compileModule(src, { generate })`.

use rsvelte_core::{GenerateMode, compile_module, compiler::ModuleCompileOptions};

fn build(src: &str, generate: GenerateMode) -> String {
    compile_module(
        src,
        ModuleCompileOptions {
            filename: Some("m.svelte.js".into()),
            generate,
            dev: false,
            ..Default::default()
        },
    )
    .map(|r| r.js.code)
    .unwrap_or_else(|e| format!("COMPILE_ERROR: {e:?}"))
}

/// The header and the runtime import, which every expectation below shares.
fn head(generate: GenerateMode) -> String {
    let target = match generate {
        GenerateMode::Server => "server",
        _ => "client",
    };
    format!(
        "/* m.svelte.js generated by Svelte v{} */\nimport * as $ from 'svelte/internal/{target}';\n",
        env!("SVELTE_VERSION")
    )
}

fn check(src: &str, tail: &str) {
    for generate in [GenerateMode::Client, GenerateMode::Server] {
        assert_eq!(
            build(src, generate),
            format!("{}{tail}", head(generate)),
            "generate={generate:?} for {src:?}"
        );
    }
}

#[test]
fn a_removed_inspect_leaves_the_statement_slots() {
    check("let a = $state(1);\n$inspect(a);\n", "\nlet a = 1;\n\n;;");
}

/// The `;;` pair is one upstream statement, so consecutive holes are separated
/// by a plain newline while a real neighbour gets a blank line.
#[test]
fn consecutive_holes_do_not_merge() {
    check(
        "let a = $state(1);\n$inspect(a);\n$inspect(a);\n$inspect(a);\n",
        "\nlet a = 1;\n\n;;\n;;\n;;",
    );
    check(
        "let a = $state(1);\n$inspect(a);\nlet b = 2;\n$inspect(b);\nlet c = 3;\n",
        "\nlet a = 1;\n\n;;\n\nlet b = 2;\n\n;;\n\nlet c = 3;",
    );
}

#[test]
fn a_hole_is_kept_at_every_body_position() {
    check("$inspect(1);\n", "\n;;");
    check(
        "$inspect(1);\nexport const a = 1;\n",
        "\n;;\n\nexport const a = 1;",
    );
    check(
        "export function f() {\n\tlet a = $state(1);\n\t$inspect(a);\n\treturn a;\n}\n",
        "\nexport function f() {\n\tlet a = 1;\n\n\t;;\n\n\treturn a;\n}",
    );
    check(
        "export const f = () => {\n\t$inspect(1);\n};\n",
        "\nexport const f = () => {\n\t;;\n};",
    );
    check(
        "export function f() {\n\tif (true) {\n\t\t$inspect(1);\n\t}\n\treturn 1;\n}\n",
        "\nexport function f() {\n\tif (true) {\n\t\t;;\n\t}\n\n\treturn 1;\n}",
    );
}

/// Statement position is determined from code tokens, not from the final byte
/// of a leading comment. Otherwise the comment text turns the removed call into
/// an `undefined` expression on both module targets.
#[test]
fn a_leading_line_comment_does_not_turn_the_hole_into_a_value() {
    check(
        "export function f(a) {\n\t// } c\n\t$inspect(a);\n}\n",
        "\nexport function f(a) {\n\t// } c\n\t;;\n}",
    );
    check(
        "export function f(a) {\n\t// svelte-ignore a11y_no_static_element_interactions\n\t$inspect(a);\n\tconsole.log(2);\n}\n",
        "\nexport function f(a) {\n\t// svelte-ignore a11y_no_static_element_interactions\n\t;;\n\n\tconsole.log(2);\n}",
    );
}

#[test]
fn the_with_form_is_one_hole_too() {
    check(
        "let a = $state(1);\n$inspect(a).with(console.trace);\n",
        "\nlet a = 1;\n\n;;",
    );
}

/// `$inspect.trace(...)` is dropped by upstream's `ExpressionStatement` visitor
/// (`b.empty` in STATEMENT position, which esrap elides) — no `;;`.
#[test]
fn inspect_trace_leaves_nothing_behind() {
    check(
        "export function g() {\n\t$inspect.trace();\n\treturn 1;\n}\n",
        "\nexport function g() {\n\treturn 1;\n}",
    );
}

/// The removal is AST-driven, so `$inspect(` spelled inside an opaque region is
/// not code and must survive untouched.
#[test]
fn inspect_shaped_text_in_an_opaque_region_survives() {
    check(
        "export const s = '$inspect(nope);';\nexport const t = 1;\n",
        "\nexport const s = '$inspect(nope);';\nexport const t = 1;",
    );
    check(
        "export const s = `x $inspect(nope); y`;\nexport const t = 1;\n",
        "\nexport const s = `x $inspect(nope); y`;\nexport const t = 1;",
    );
    check(
        "export function h() {\n\t/* $inspect(nope); */\n\treturn 1;\n}\n",
        "\nexport function h() {\n\t/* $inspect(nope); */\n\treturn 1;\n}",
    );
}

/// The component instance script is the other port of the same lowering and
/// shares the printer's hole pairing.
#[test]
fn the_component_port_pairs_its_holes_too() {
    use rsvelte_core::{CompileOptions, compile};

    let out = compile(
        "<script>\n\tlet a = $state(1);\n\t$inspect(a);\n\t$inspect(a);\n</script>\n<p>{a}</p>\n",
        CompileOptions {
            filename: Some("A.svelte".into()),
            generate: GenerateMode::Server,
            dev: false,
            ..Default::default()
        },
    )
    .map(|r| r.js.code)
    .unwrap();
    assert_eq!(
        out,
        "import * as $ from 'svelte/internal/server';\n\nexport default function A($$renderer) {\n\tlet a = 1;\n\n\t;;\n\t;;\n\t$$renderer.push(`<p>1</p>`);\n}"
    );
}
