//! Issue #3440: a statement-level `$inspect(…)` in a `.svelte.(js|ts)` module.
//!
//! Upstream substitutes an `EmptyStatement` for the call, so the statement's own
//! `;` plus the substituted one print as `;;` where the call stood. The module
//! loop in `client/mod.rs` deleted the call and its line instead, losing both;
//! the component-instance path in `rune_transforms.rs` has always been right.
//!
//! Every expected string here is the full output of the pinned oracle
//! (`submodules/svelte`, `VERSION` 5.56.10), not written by hand.
//!
//! KNOWN RESIDUAL, deliberately not asserted here: two statement-level
//! `$inspect` calls in a row print as `;;;;` rather than `;;\n;;`. That is a
//! separate, pre-existing defect of the shared downstream printer — the
//! component-instance path reproduces it on `origin/main` with none of this
//! change applied — so it is tracked as #3562 rather than pinned here.

use rsvelte_core::{GenerateMode, ModuleCompileOptions, compile_module};

fn module(src: &str, generate: GenerateMode, dev: bool) -> String {
    compile_module(
        src,
        ModuleCompileOptions {
            filename: Some("T.svelte.js".into()),
            generate,
            dev,
            ..Default::default()
        },
    )
    .expect("compile_module")
    .js
    .code
}

fn client(src: &str) -> String {
    module(src, GenerateMode::Client, false)
}

const HEAD: &str = "/* T.svelte.js generated by Svelte v5.56.10 */\nimport * as $ from 'svelte/internal/client';\n";

#[test]
fn a_statement_level_inspect_becomes_two_empty_statements() {
    assert_eq!(
        client("let a = $state(1);\n$inspect(a);\nexport const z = 1;\n"),
        format!("{HEAD}\nlet a = 1;\n\n;;\n\nexport const z = 1;")
    );
}

/// The call needs no `;` of its own — upstream reads the statement, not the
/// punctuation, and a semicolon-free module is the `standard`-style source that
/// has broken every other scan in this pipeline.
#[test]
fn a_semicolon_free_inspect_statement_is_the_same() {
    assert_eq!(
        client("let a = $state(1);\n$inspect(a)\nexport const z = 1;\n"),
        format!("{HEAD}\nlet a = 1;\n\n;;\n\nexport const z = 1;")
    );
}

/// The substitution happens at the statement's position, so code sharing the
/// line is unaffected and keeps its own statement — in either order.
#[test]
fn code_sharing_the_line_keeps_its_own_statement() {
    assert_eq!(
        client("let a = $state(1);\n$inspect(a); export const z = 1;\n"),
        format!("{HEAD}\nlet a = 1;\n\n;;\n\nexport const z = 1;")
    );
    assert_eq!(
        client("let a = $state(1);\nexport const z = 1; $inspect(a);\n"),
        format!("{HEAD}\nlet a = 1;\n\nexport const z = 1;\n\n;;")
    );
}

/// Nesting: the old code deleted the whole line including its indentation, so a
/// nested call took its block's layout with it.
#[test]
fn a_nested_inspect_statement_keeps_its_nesting() {
    assert_eq!(
        client("export function f() {\n\tlet a = $state(1);\n\t$inspect(a);\n\treturn a;\n}\n"),
        format!("{HEAD}\nexport function f() {{\n\tlet a = 1;\n\n\t;;\n\n\treturn a;\n}}")
    );
    assert_eq!(
        client("let a = $state(1);\nif (a) {\n\t$inspect(a);\n}\nexport const z = 1;\n"),
        format!("{HEAD}\nlet a = 1;\n\nif (a) {{\n\t;;\n}}\n\nexport const z = 1;")
    );
}

#[test]
fn a_with_chain_is_removed_as_one_statement() {
    assert_eq!(
        client("let a = $state(1);\n$inspect(a).with(console.log);\nexport const z = 1;\n"),
        format!("{HEAD}\nlet a = 1;\n\n;;\n\nexport const z = 1;")
    );
}

#[test]
fn the_server_target_agrees() {
    assert_eq!(
        module(
            "let a = $state(1);\n$inspect(a);\nexport const z = 1;\n",
            GenerateMode::Server,
            false
        ),
        "/* T.svelte.js generated by Svelte v5.56.10 */\nimport * as $ from 'svelte/internal/server';\n\nlet a = 1;\n\n;;\n\nexport const z = 1;"
    );
}

/// `$inspect.trace()` is a different rune with its own loop: upstream removes it
/// outright and prints no `;;`. Without this the fix reads as "every `$inspect`
/// family call leaves `;;`", which is wrong.
#[test]
fn inspect_trace_is_still_removed_outright() {
    let out = client("export function f() {\n\t$inspect.trace();\n\treturn 1;\n}\n");
    assert_eq!(
        out,
        format!("{HEAD}\nexport function f() {{\n\treturn 1;\n}}")
    );
    assert!(!out.contains(";;"), "{out}");
}

/// Dev mode keeps the call: the whole loop is gated on `!dev`.
#[test]
fn dev_mode_keeps_the_call() {
    let out = module(
        "let a = $state(1);\n$inspect(a);\nexport const z = 1;\n",
        GenerateMode::Client,
        true,
    );
    assert!(out.contains("$.inspect("), "{out}");
    assert!(!out.contains("\n;;"), "{out}");
}

/// A value-position `$inspect` is #3213 item 3 and takes the other arm of this
/// same branch: it keeps an operand instead of becoming `;;`. Kept here so the
/// two arms cannot be collapsed into one.
#[test]
fn a_value_position_inspect_still_keeps_its_operand() {
    let decl = client("export const v = $inspect(1);\n");
    assert!(decl.contains("export const v = undefined;"), "{decl}");
    let arr = client("export const o = [$inspect(1)];\n");
    assert!(arr.contains("export const o = [undefined];"), "{arr}");
}
