//! Statement-level margins inside block bodies of a `.svelte.(js|ts)` module.
//!
//! esrap separates two statements with a blank line whenever either prints
//! across several lines or their node types differ. `rsvelte_esrap` implements
//! that predicate, but the client module path printed with the handwritten
//! text generator and so never ran it. Expectations are the official
//! compiler's output.

use rsvelte_core::compiler::ModuleCompileOptions;
use rsvelte_core::{GenerateMode, compile_module};

fn client(src: &str) -> String {
    compile_module(
        src,
        ModuleCompileOptions {
            filename: Some("store.svelte.js".to_string()),
            generate: GenerateMode::Client,
            dev: false,
            ..Default::default()
        },
    )
    .expect("compile")
    .js
    .code
}

const CLASS: &str = "export class R {\n\t#x = $state({});\n\n\tconstructor(s) {\n\t\tconst b = 2;\n\t\tthis.#x = s;\n\t}\n\n\tm(s) {\n\t\tconst a = 1;\n\t\treturn this.#x;\n\t}\n}\n";

/// The whole file, byte for byte, as the official compiler emits it.
///
/// The version in the header comes from the same `SVELTE_VERSION` the compiler
/// stamps it with, not from a literal: spelling it out here makes every
/// submodule bump fail this test for a reason that has nothing to do with block
/// margins, which is what it is actually measuring.
#[test]
fn block_statement_margins_match_upstream() {
    let version = option_env!("SVELTE_VERSION").unwrap_or("VERSION");
    let expected = format!(
        "/* store.svelte.js generated by Svelte v{version} */\nimport * as $ from 'svelte/internal/client';\n\nexport class R {{\n\t#x = $.state($.proxy({{}}));\n\n\tconstructor(s) {{\n\t\tconst b = 2;\n\n\t\t$.set(this.#x, s, true);\n\t}}\n\n\tm(s) {{\n\t\tconst a = 1;\n\n\t\treturn $.get(this.#x);\n\t}}\n}}"
    );
    assert_eq!(client(CLASS), expected);
}

/// The header is prepended to the printed program, not carried as a statement:
/// a comment-only statement parses to nothing, leaving the comment to flush at
/// the body tail.
#[test]
fn the_generated_by_header_leads_the_file() {
    let out = client(CLASS);
    assert!(
        out.starts_with("/* store.svelte.js generated by Svelte v"),
        "header must lead the file:\n{out}"
    );
    assert_eq!(
        out.matches("generated by Svelte v").count(),
        1,
        "header emitted more than once:\n{out}"
    );
}

/// Two single-line statements of the same kind stay adjacent — the predicate
/// is structural, so it removes a source blank line as readily as it adds one.
#[test]
fn same_kind_single_line_statements_get_no_margin() {
    let src = "export function f() {\n\tconst a = 1;\n\n\tconst b = 2;\n\n\treturn a + b;\n}\n";
    let out = client(src);
    assert!(
        out.contains("\tconst a = 1;\n\tconst b = 2;\n"),
        "adjacent single-line consts must not keep a margin:\n{out}"
    );
}
