//! A statement the SERVER transform removes must not take the comments around
//! and inside it with it.
//!
//! Upstream removes the statement NODE and esrap flushes the orphaned comments
//! from the enclosing (located) body. rsvelte removed a source RANGE on the
//! `compileModule` path — so the interior comment died with the range while the
//! leading one survived — and left the statement's comment region unreferenced
//! on the component path, where both died. Two mechanisms, one shape, and a
//! repro on either path alone reads as a complete fix (#2567).
//!
//! Every expectation is the official compiler's output at the pinned
//! `submodules/svelte`, byte for byte.

use rsvelte_core::{CompileOptions, GenerateMode, ModuleCompileOptions, compile, compile_module};

#[track_caller]
fn ssr(source: &str) -> String {
    compile(
        source,
        CompileOptions {
            generate: GenerateMode::Server,
            filename: Some("A.svelte".to_string()),
            ..Default::default()
        },
    )
    .expect("component should compile")
    .js
    .code
}

#[track_caller]
fn ssr_module(source: &str) -> String {
    compile_module(
        source,
        ModuleCompileOptions {
            generate: GenerateMode::Server,
            filename: Some("A.svelte.js".to_string()),
            ..Default::default()
        },
    )
    .expect("module should compile")
    .js
    .code
}

/// Compares against official's output with its `generated by Svelte vX` header
/// stripped, since the version string is not what is under test.
#[track_caller]
fn assert_body(actual: &str, expected_body: &str) {
    let body = actual
        .split_once("*/\n")
        .map_or(actual, |(_, rest)| rest)
        .trim_end();
    assert_eq!(
        body,
        expected_body.trim_end(),
        "\n--- full output ---\n{actual}"
    );
}

#[test]
fn module_effect_keeps_the_leading_and_interior_comments() {
    let out = ssr_module(
        "export function f(a) {\n\t// leading\n\t$effect(() => {\n\t\t// interior\n\t\tconsole.log(a);\n\t});\n\n\tconsole.log(2);\n}\n",
    );
    assert_body(
        &out,
        "import * as $ from 'svelte/internal/server';\nexport function f(a) {\n\t// leading\n\t// interior\n\tconsole.log(2);\n}",
    );
}

/// The issue's own repro: nothing survives after the effect, so both comments
/// land at the end of the (now empty) function body.
#[test]
fn module_effect_with_no_successor_keeps_both_comments() {
    let out = ssr_module(
        "export function f() {\n\t// keep\n\t$effect(() => {\n\t\t// gone with the effect\n\t\tconsole.log(1);\n\t});\n}\n",
    );
    assert_body(
        &out,
        "import * as $ from 'svelte/internal/server';\nexport function f() {\n\t// keep\n\t// gone with the effect\n}",
    );
}

#[test]
fn instance_effect_keeps_the_leading_and_interior_comments() {
    let out = ssr(
        "<script>\n\tlet a = $state(1);\n\n\t// leading\n\t$effect(() => {\n\t\t// interior\n\t\tconsole.log(a);\n\t});\n\n\tconsole.log(2);\n</script>\n\n<p>{a}</p>\n",
    );
    assert_body(
        &out,
        "import * as $ from 'svelte/internal/server';\nexport default function A($$renderer, $$props) {\n\t$$renderer.component(($$renderer) => {\n\t\tlet a = 1;\n\t\t// leading\n\t\t// interior\n\t\tconsole.log(2);\n\t\t$$renderer.push(`<p>1</p>`);\n\t});\n}",
    );
}

/// The control that already passed: nested one function deep, the effect is not
/// a top-level region at all, so a fix aimed at the top-level loop must leave it
/// alone.
#[test]
fn effect_nested_in_a_function_keeps_both_comments() {
    let out = ssr(
        "<script>\n\tlet a = $state(1);\n\n\tfunction f() {\n\t\t// leading\n\t\t$effect(() => {\n\t\t\t// interior\n\t\t\tconsole.log(a);\n\t\t});\n\t}\n\n\tf();\n</script>\n\n<p>{a}</p>\n",
    );
    assert_body(
        &out,
        "import * as $ from 'svelte/internal/server';\nexport default function A($$renderer, $$props) {\n\t$$renderer.component(($$renderer) => {\n\t\tlet a = 1;\n\t\tfunction f() {\n\t\t\t// leading\n\t\t\t// interior\n\t\t}\n\t\tf();\n\t\t$$renderer.push(`<p>1</p>`);\n\t});\n}",
    );
}

/// A removed `$inspect` leaves two kept `EmptyStatement` sentinels behind, and a
/// sentinel span is exactly what the comment carry-over refuses to rewrite — so
/// "it emitted something" is not the same question as "it emitted something that
/// can host a region". Exact bytes are not asserted: the `;;` the sentinels print
/// as differs from official's in whitespace alone, which every normalizer erases
/// and which this test is not about.
#[test]
fn instance_inspect_rehomes_its_leading_comment_past_the_sentinels() {
    let out = ssr(
        "<script>\n\tlet a = $state(1);\n\n\t// leading\n\t$inspect(a);\n\n\tconsole.log(2);\n</script>\n\n<p>{a}</p>\n",
    );
    assert!(out.contains("// leading"), "leading comment lost:\n{out}");
}

/// The counterweight, and it must keep FAILING to re-home: with nothing after the
/// effect there is no anchor region, and upstream flushes the comments at the end
/// of the component body instead. That is a separate defect with its own issue;
/// what this pins is that the re-home did not resurrect them somewhere arbitrary.
#[test]
fn effect_with_no_successor_still_drops_its_comments() {
    let out = ssr(
        "<script>\n\tlet a = $state(1);\n\n\t// leading\n\t$effect(() => {\n\t\t// interior\n\t\tconsole.log(a);\n\t});\n</script>\n\n<p>{a}</p>\n",
    );
    assert!(
        !out.contains("// leading") && !out.contains("// interior"),
        "unexpected comment placement — upstream puts both after the template push:\n{out}"
    );
}
