//! A statement the SERVER transform removes must not take the comments around
//! and inside it with it.
//!
//! Upstream removes the statement NODE and esrap flushes the orphaned comments
//! from the enclosing (located) body. rsvelte removed a source RANGE on the
//! `compileModule` path — so the interior comment died with the range while the
//! leading one survived — and left the statement's comment region unreferenced
//! on the component path, where both died. Two mechanisms, one shape, and a
//! repro on either path alone reads as a complete fix (#2567).
//!
//! Every expectation is the official compiler's output at the pinned
//! `submodules/svelte`, byte for byte.

use rsvelte_core::{CompileOptions, GenerateMode, ModuleCompileOptions, compile, compile_module};

#[track_caller]
fn ssr(source: &str) -> String {
    compile(
        source,
        CompileOptions {
            generate: GenerateMode::Server,
            filename: Some("A.svelte".to_string()),
            ..Default::default()
        },
    )
    .expect("component should compile")
    .js
    .code
}

#[track_caller]
fn ssr_dev(source: &str) -> String {
    compile(
        source,
        CompileOptions {
            generate: GenerateMode::Server,
            dev: true,
            filename: Some("A.svelte".to_string()),
            ..Default::default()
        },
    )
    .expect("component should compile")
    .js
    .code
}

#[track_caller]
fn ssr_module(source: &str) -> String {
    compile_module(
        source,
        ModuleCompileOptions {
            generate: GenerateMode::Server,
            filename: Some("A.svelte.js".to_string()),
            ..Default::default()
        },
    )
    .expect("module should compile")
    .js
    .code
}

/// Compares against official's output with its `generated by Svelte vX` header
/// stripped, since the version string is not what is under test.
#[track_caller]
fn assert_body(actual: &str, expected_body: &str) {
    let body = actual
        .split_once("*/\n")
        .map_or(actual, |(_, rest)| rest)
        .trim_end();
    assert_eq!(
        body,
        expected_body.trim_end(),
        "\n--- full output ---\n{actual}"
    );
}

#[test]
fn module_effect_keeps_the_leading_and_interior_comments() {
    let out = ssr_module(
        "export function f(a) {\n\t// leading\n\t$effect(() => {\n\t\t// interior\n\t\tconsole.log(a);\n\t});\n\n\tconsole.log(2);\n}\n",
    );
    assert_body(
        &out,
        "import * as $ from 'svelte/internal/server';\n\nexport function f(a) {\n\t// leading\n\t// interior\n\tconsole.log(2);\n}",
    );
}

/// The issue's own repro: nothing survives after the effect, so both comments
/// land at the end of the (now empty) function body.
#[test]
fn module_effect_with_no_successor_keeps_both_comments() {
    let out = ssr_module(
        "export function f() {\n\t// keep\n\t$effect(() => {\n\t\t// gone with the effect\n\t\tconsole.log(1);\n\t});\n}\n",
    );
    assert_body(
        &out,
        "import * as $ from 'svelte/internal/server';\n\nexport function f() {\n\t// keep\n\t// gone with the effect\n}",
    );
}

#[test]
fn instance_effect_keeps_the_leading_and_interior_comments() {
    let out = ssr(
        "<script>\n\tlet a = $state(1);\n\n\t// leading\n\t$effect(() => {\n\t\t// interior\n\t\tconsole.log(a);\n\t});\n\n\tconsole.log(2);\n</script>\n\n<p>{a}</p>\n",
    );
    assert_body(
        &out,
        "import * as $ from 'svelte/internal/server';\n\nexport default function A($$renderer, $$props) {\n\t$$renderer.component(($$renderer) => {\n\t\tlet a = 1;\n\n\t\t// leading\n\t\t// interior\n\t\tconsole.log(2);\n\n\t\t$$renderer.push(`<p>1</p>`);\n\t});\n}",
    );
}

/// The control that already passed: nested one function deep, the effect is not
/// a top-level region at all, so a fix aimed at the top-level loop must leave it
/// alone.
#[test]
fn effect_nested_in_a_function_keeps_both_comments() {
    let out = ssr(
        "<script>\n\tlet a = $state(1);\n\n\tfunction f() {\n\t\t// leading\n\t\t$effect(() => {\n\t\t\t// interior\n\t\t\tconsole.log(a);\n\t\t});\n\t}\n\n\tf();\n</script>\n\n<p>{a}</p>\n",
    );
    assert_body(
        &out,
        "import * as $ from 'svelte/internal/server';\n\nexport default function A($$renderer, $$props) {\n\t$$renderer.component(($$renderer) => {\n\t\tlet a = 1;\n\n\t\tfunction f() {\n\t\t\t// leading\n\t\t\t// interior\n\t\t}\n\n\t\tf();\n\t\t$$renderer.push(`<p>1</p>`);\n\t});\n}",
    );
}

/// A removed `$inspect` leaves two kept `EmptyStatement` sentinels behind. Their
/// end is a keep-marker, while their start is still the removed statement's
/// comment anchor and must be remapped with the surrounding source region.
#[test]
fn instance_inspect_rehomes_its_leading_comment_past_the_sentinels() {
    let out = ssr(
        "<script>\n\tlet a = $state(1);\n\n\t// leading\n\t$inspect(a);\n\n\tconsole.log(2);\n</script>\n\n<p>{a}</p>\n",
    );
    assert!(out.contains("// leading"), "leading comment lost:\n{out}");
}

#[test]
fn nested_inspect_keeps_a_leading_block_comment_on_its_own_line() {
    let out = ssr(
        "<script>\n\tlet a = 1;\n\n\tfunction f() {\n\t\t/* ) c */\n\t\t$inspect(a);\n\t\tconsole.log(2);\n\t}\n\n\tf();\n</script>\n<p>{a}</p>\n",
    );
    assert!(
        out.find("/* ) c */").is_some_and(|comment| {
            out.find("console.log(2)")
                .is_some_and(|successor| comment < successor)
        }) && !out.contains("/* ) c */ console.log(2)"),
        "leading comment collapsed onto its successor:\n{out}"
    );
}

#[test]
fn final_inspect_keeps_its_leading_and_trailing_comments_before_markup() {
    let leading =
        ssr("<script>\n\tlet a = 1;\n\n\t// leading\n\t$inspect(a);\n</script>\n<p>{a}</p>\n");
    assert!(
        leading.find("// leading").is_some_and(|comment| {
            leading
                .find("$$renderer.push")
                .is_some_and(|markup| comment < markup)
        }),
        "leading comment moved behind the rendered markup:\n{leading}"
    );

    let trailing =
        ssr("<script>\n\tlet a = 1;\n\t$inspect(a); /* trailing */\n</script>\n<p>{a}</p>\n");
    assert!(
        trailing.find("/* trailing */").is_some_and(|comment| {
            trailing
                .find("$$renderer.push")
                .is_some_and(|markup| comment < markup)
        }),
        "trailing comment moved behind the rendered markup:\n{trailing}"
    );
}

#[test]
fn dev_inspect_keeps_a_leading_comment_before_the_generated_call() {
    let out = ssr_dev(
        "<script>\n\tlet a = 1;\n\n\tfunction f() {\n\t\t/* ) c */\n\t\t$inspect(a);\n\t\tconsole.log(2);\n\t}\n\n\tf();\n</script>\n<p>{a}</p>\n",
    );
    assert!(
        out.contains("\n\t\t\t\t/* ) c */\n\t\t\t\tconsole.log('$inspect(', a, ')');"),
        "leading comment moved into an inspect argument:\n{out}"
    );
}

#[test]
fn dev_inspect_keeps_a_trailing_line_comment_on_the_argument() {
    let out = ssr_dev(
        "<script>\n\tlet a = 1;\n\t$inspect(a); // c\n\tconsole.log(2);\n</script>\n<p>{a}</p>\n",
    );
    assert!(
        out.contains("a, // c\n") && !out.contains("'); // c"),
        "trailing comment moved outside the generated inspect call:\n{out}"
    );
}

/// The counterweight: with nothing after the effect there is no anchor region,
/// so the comments stay pending and upstream flushes them at the end of the
/// component body — which here is the `$$renderer.component` callback, not the
/// exported function.
#[test]
fn effect_with_no_successor_lands_at_the_component_body_end() {
    let out = ssr(
        "<script>\n\tlet a = $state(1);\n\n\t// leading\n\t$effect(() => {\n\t\t// interior\n\t\tconsole.log(a);\n\t});\n</script>\n\n<p>{a}</p>\n",
    );
    assert_body(
        &out,
        "import * as $ from 'svelte/internal/server';\n\nexport default function A($$renderer, $$props) {\n\t$$renderer.component(($$renderer) => {\n\t\tlet a = 1;\n\n\t\t$$renderer.push(`<p>1</p>`);\n\t\t// leading\n\t\t// interior\n\t});\n}",
    );
}

/// Dev prints `$$renderer.component` as a multiline call. Its callback body is
/// three indentation levels deep, so the tail-comment fallback must find the
/// two-level callback close rather than the one-level exported-function close.
#[test]
fn dev_effect_with_no_successor_lands_inside_the_component_callback() {
    let out = ssr_dev(
        "<script>\n\tlet a = 1;\n\n\t// leading\n\t$effect(() => {\n\t\t// interior\n\t\tconsole.log(a);\n\t});\n</script>\n\n<p>{a}</p>\n",
    );
    assert!(
        out.contains("\n\t\t\t// leading\n\t\t\t// interior\n\t\t},\n\t\tA\n"),
        "comments did not land at the dev callback tail:\n{out}"
    );
}
