//! A template expression is parsed in the component's language mode: TypeScript
//! only when some `<script>` declares `lang="ts"`, exactly as upstream's
//! `parse_expression_at` reaches acorn-typescript only when `parser.ts`.
//!
//! The axes are the TypeScript-only construct, the template slot it sits in and
//! which script (if any) declares the mode. Expectations are the official
//! compiler's own verdict, generated by running it — never hand-written.
//!
//! What this comparison cannot see:
//!
//! - **The error's position.** Only the `code` is compared. Where OXC stops
//!   consuming differs from where acorn does, the span differs and this stays
//!   green; that is the `error-position` ratchet's axis.
//! - **The message text**, for the same reason.
//! - **Accepted output.** A cell scored `accept` is not compiled to bytes here,
//!   so a component that parses in the right mode and then *generates* the wrong
//!   code is invisible — the corpus output gate is what covers that.
//! - **`loose` (editor) mode**, which keeps a placeholder identifier by design.
//!   Every case runs with the compiler's default options.

use std::collections::{HashMap, HashSet};

use rsvelte_core::compiler::{CompileOptions, compile};

struct Case {
    name: String,
    source: String,
    /// The official compiler's error code, or `None` when it accepts.
    expected: Option<String>,
}

fn cases() -> Vec<Case> {
    include_str!("data/template_expression_ts_gate.json")
        .lines()
        .filter(|l| !l.trim().is_empty())
        .map(|line| {
            let v: serde_json::Value = serde_json::from_str(line).unwrap();
            Case {
                name: v["name"].as_str().unwrap().to_string(),
                source: v["source"].as_str().unwrap().to_string(),
                expected: v["expected"].as_str().map(str::to_string),
            }
        })
        .collect()
}

fn host_of(name: &str) -> &str {
    name.rsplit("__").next().unwrap_or("")
}

/// "0 compared" scores as a pass, and a population where every case is rejected
/// cannot see an under-rejection. Assert the shape of the population first.
#[test]
fn the_population_is_not_degenerate() {
    let cases = cases();
    assert!(cases.len() >= 400, "population shrank to {}", cases.len());

    let names: HashSet<&str> = cases.iter().map(|c| c.name.as_str()).collect();
    for required in [
        // the issue's own repro, and the same construct where the mode IS declared
        "as-string__mustache__no-script",
        "as-string__mustache__plain-script",
        "as-string__mustache__instance-ts",
        "as-string__mustache__module-ts-only",
        // acorn fails on the spot rather than stopping cleanly
        "angle-cast__mustache__no-script",
        // negative control on the construct axis: plain JavaScript
        "plain-js__mustache__no-script",
        // the slots that swallowed a parse failure entirely
        "as-string__await__no-script",
        "as-string__const-tag__no-script",
        "as-string__render-arg__no-script",
        // nested one level down from the slot the axis names
        "as-string__each-pattern-default__no-script",
        "as-string__const-tag-pattern-default__no-script",
        "as-string__debug-tag__no-script",
        // the block header, which is not an expression slot at all
        "header-snippet-type-param-with-arg__no-script",
        "header-snippet-plain__no-script",
        // the SAME axis in the other direction: a pattern default is an
        // expression, and it must parse as TypeScript when the component says so
        "as-string__each-pattern-default__instance-ts",
        "as-string__await-then-pattern-default__instance-ts",
    ] {
        assert!(names.contains(required), "missing case {required}");
    }

    let hosts: HashSet<&str> = cases.iter().map(|c| host_of(&c.name)).collect();
    for host in ["no-script", "plain-script", "instance-ts", "module-ts-only"] {
        assert!(hosts.contains(host), "missing host {host}");
    }

    // Both verdicts, and both error codes, or the comparison is one-sided.
    let accepted = cases.iter().filter(|c| c.expected.is_none()).count();
    assert!(
        accepted > 0 && accepted < cases.len(),
        "one-sided population"
    );
    let codes: HashSet<&str> = cases.iter().filter_map(|c| c.expected.as_deref()).collect();
    assert!(codes.contains("expected_token"), "no expected_token case");
    assert!(codes.contains("js_parse_error"), "no js_parse_error case");

    // A TypeScript host must accept what a plain host rejects, or the gate is
    // measuring "rejects TypeScript" rather than "respects the declared mode".
    let by_name: HashMap<&str, &Case> = cases.iter().map(|c| (c.name.as_str(), c)).collect();
    let plain = by_name["as-string__mustache__no-script"];
    let typed = by_name["as-string__mustache__instance-ts"];
    assert!(plain.expected.is_some() && typed.expected.is_none());
}

#[test]
fn matches_the_official_compiler() {
    let mut failures = Vec::new();
    for case in cases() {
        let options = CompileOptions {
            filename: Some(case.name.clone()),
            ..CompileOptions::default()
        };
        let actual = match compile(&case.source, options) {
            Ok(_) => None,
            Err(e) => Some(e.diagnostic().code.unwrap_or_else(|| "(no code)".into())),
        };
        if actual != case.expected {
            failures.push(format!(
                "{}\n  source:   {}\n  official: {:?}\n  rsvelte:  {:?}",
                case.name,
                case.source.replace('\n', " "),
                case.expected,
                actual,
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{} of the cases diverge from the official compiler:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
