/* props.svelte.js generated by Svelte v5.57.1 */
import * as $ from 'svelte/internal/client';
import { noop } from '../utils/functions.js';

export class Props {
	#form;

	get form() {
		return $.get(this.#form);
	}

	set form(value) {
		$.set(this.#form, value);
	}

	#error;

	get error() {
		return $.get(this.#error);
	}

	set error(value) {
		$.set(this.#error, value);
	}

	page;
	components = [];
	tree;
	onerror;

	constructor({ page, tree, form, error, onerror = noop }) {
		this.page = page;
		this.tree = tree;
		this.onerror = onerror;
		this.#form = $.state(form);
		this.#error = $.state(error);
	}
}

export class RenderNode {
	/** @type {Component} */
	component;

	/** @type {Component | undefined} */
	error;

	#data = /** @type {Record<string, any>} */ (
	$.state)({});

	get data() {
		return $.get(this.#data);
	}

	set data(value) {
		$.set(this.#data, value);
	}

	#child = $.state();

	get child() {
		return $.get(this.#child);
	}

	set child(value) {
		$.set(this.#child, value);
	}

	constructor(component, error) {
		this.component = component;
		this.error = error;
	}
}