/* stack-item.svelte.js generated by Svelte v5.57.1 */
import * as $ from 'svelte/internal/client';
import { tick } from 'svelte';

export class StackItem {
	#state = /** @type {import('./types.package').StackItemState} */ (
	// eslint-disable-next-line no-undef
	$.state)('idle');

	get state() {
		return $.get(this.#state);
	}

	set state(value) {
		$.set(this.#state, value, true);
	}

	config;

	#internals = {
		msToTimeout: 0,
		timeoutId: undefined,
		lastStartedTime: new Date().getTime(),
		resolveListeners: new Set(),
		resolve: () => {}
	};

	/** @type {Promise<Resolved | undefined>} */
	resolution;

	/**
	 * @param {import('./types.package').StackItemInstanceConfig<string, UserComponent>} config
	 */
	constructor(config) {
		this.config = config;
		this.#internals.msToTimeout = config.timeout;

		this.resolution = new Promise((resolve) => {
			this.#internals.resolve = resolve;
		});
	}

	/**
	 * @returns {number | null}
	 */
	get progress() {
		if (this.config.timeout === 0) return null;

		if (this.state === 'elapsing') {
			const elapsedMs = Date.now() - this.#internals.lastStartedTime;
			const actualMsToTimeout = this.#internals.msToTimeout - elapsedMs;

			return (this.config.timeout - actualMsToTimeout) / this.config.timeout;
		}

		return (this.config.timeout - this.#internals.msToTimeout) / this.config.timeout;
	}

	resume = () => {
		if (this.#internals.msToTimeout <= 0 || this.state === 'elapsing') return;

		clearTimeout(this.#internals.timeoutId);
		this.#internals.lastStartedTime = new Date().getTime();

		this.#internals.timeoutId = setTimeout(
			async () => {
				this.#internals.msToTimeout = 0;
				await this.resolve();
				this.state = 'timeout';
			},
			this.#internals.msToTimeout
		);

		this.state = 'elapsing';
	};

	pause = () => {
		if (this.state === 'paused' || this.state === 'idle') return;

		clearTimeout(this.#internals.timeoutId);
		this.#internals.msToTimeout -= new Date().getTime() - this.#internals.lastStartedTime;
		this.state = 'paused';
	};

	/**
	 * @param {Resolved} [resolved]
	 * @returns {Promise<Resolved | undefined>}
	 */
	resolve = async (resolved) => {
		await tick(); // make sure DOM updates are applied before resolving

		if (this.state === 'resolved' || this.state === 'timeout') return this.resolution;

		let cancelled = false;

		function cancel() {
			cancelled = true;
		}

		await Promise.all(Array.from(this.#internals.resolveListeners).map((callback) => callback({ resolved, cancel })));

		if (cancelled) return;

		this.#internals.resolve(resolved);
		this.state = 'resolved';

		return this.resolution;
	};

	/**
	 * @param {import('./types.public').StackItemResolveListener<Resolved>} callback
	 * @returns {() => void}
	 */
	onResolve = (callback) => {
		this.#internals.resolveListeners.add(callback);

		return () => {
			this.#internals.resolveListeners.delete(callback);
		};
	};
}