import * as $ from 'svelte/internal/server';
import { tooltip } from '$lib/actions/tooltip';
import Icon from '$lib/components/global/Icon.svelte';

export default function DNSAAAAABulk($$renderer, $$props) {
	$$renderer.component(($$renderer) => {
		let hostnameInput = '';
		let ipInput = '';
		let ttl = 3600;
		let generateZoneFile = false;
		let zoneName = 'example.com';
		let results = [];
		let zoneFileContent = '';
		let showExamples = false;

		const examples = [
			{
				label: 'Web Servers',
				hostnames: 'www\napi\ncdn\nstatic',
				ips: '192.168.1.10\n192.168.1.11\n192.168.1.12\n192.168.1.13'
			},

			{
				label: 'Mail Servers',
				hostnames: 'mail\nimap\nsmtp\npop3',
				ips: '10.0.1.20\n10.0.1.21\n10.0.1.22\n10.0.1.23'
			},

			{
				label: 'IPv6 Services',
				hostnames: 'web6\napi6\nmail6',
				ips: '2001:db8::1\n2001:db8::2\n2001:db8::3'
			}
		];

		function isIPv4(ip) {
			const parts = ip.split('.');

			return parts.length === 4 && parts.every((part) => {
				const num = parseInt(part, 10);

				return !isNaN(num) && num >= 0 && num <= 255 && part === num.toString();
			});
		}

		function isIPv6(ip) {
			const ipv6Regex = /^([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}$|^([0-9a-fA-F]{1,4}:){1,7}:$|^([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}$|^([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}$|^([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}$|^([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}$|^([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}$|^[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})$|^:((:[0-9a-fA-F]{1,4}){1,7}|:)$|^::$/;

			return ipv6Regex.test(ip) || (/^::$/).test(ip) || (/^::1$/).test(ip);
		}

		function generateRecords() {
			const hostnames = hostnameInput.split('\n').map((h) => h.trim()).filter((h) => h);
			const ips = ipInput.split('\n').map((i) => i.trim()).filter((i) => i);

			if (hostnames.length === 0 || ips.length === 0) {
				results = [];

				return;
			}

			const newResults = [];
			const maxLength = Math.max(hostnames.length, ips.length);

			for (let i = 0; i < maxLength; i++) {
				const hostname = hostnames[i % hostnames.length];
				const ip = ips[i % ips.length];

				if (hostname && ip) {
					const recordType = isIPv4(ip) ? 'A' : isIPv6(ip) ? 'AAAA' : 'INVALID';

					newResults.push({ type: recordType, name: hostname, ttl, value: ip });
				}
			}

			results = newResults;
		}

		function generateZoneFileContent() {
			if (results.length === 0) return;

			// Generate serial number from current date
			const today = new Date();

			const serial = today.getFullYear().toString() + (today.getMonth() + 1).toString().padStart(2, '0') + today.getDate().toString().padStart(2, '0') + '01';

			const zoneHeader = `; Zone file for ${zoneName}
; Generated by ${window.location.host}
$TTL ${ttl}
$ORIGIN ${zoneName}.

@ IN SOA ns1.${zoneName}. admin.${zoneName}. (
    ${serial}        ; Serial
    3600              ; Refresh
    1800              ; Retry
    604800            ; Expire
    86400             ; Minimum TTL
)

; Name servers
@ IN NS ns1.${zoneName}.
@ IN NS ns2.${zoneName}.

; A and AAAA Records
`;

			const records = results.map((record) => {
				const name = record.name === '@' ? '@' : record.name;

				return `${name.padEnd(20)} IN ${record.type.padEnd(6)} ${record.value}`;
			}).join('\n');

			zoneFileContent = zoneHeader + records;
		}

		function loadExample(example) {
			hostnameInput = example.hostnames;
			ipInput = example.ips;
			generateRecords();
		}

		function downloadZoneFile() {
			const blob = new Blob([zoneFileContent], { type: 'text/plain' });
			const url = URL.createObjectURL(blob);
			const a = document.createElement('a');

			a.href = url;
			a.download = `${zoneName}.zone`;
			a.click();
			URL.revokeObjectURL(url);
		}

		function copyToClipboard(text) {
			navigator.clipboard.writeText(text);
		}

		$$renderer.push(`<div class="card"><div class="card-header svelte-vodz6u"><h1>A/AAAA Bulk Generator</h1> <p class="card-subtitle svelte-vodz6u">Bulk create A and AAAA record sets from hostname and IP lists with TTL controls and zone file generation.</p></div> <div class="grid-layout svelte-vodz6u"><div class="input-section svelte-vodz6u"><div class="input-group"><label for="hostnames">`);
		Icon($$renderer, { name: 'server', size: 'sm' });

		$$renderer.push(`<!----> Hostnames</label> <textarea id="hostnames" placeholder="www
api
mail
ftp" rows="8" class="svelte-vodz6u">`);

		const $$body = $.escape(
			// Generate records when input changes
			// Generate zone file when flag changes and records exist
			hostnameInput
		);

		if ($$body) {
			$$renderer.push(`${$$body}`);
		} else {}

		$$renderer.push(`</textarea></div> <div class="input-group"><label for="ips">`);
		Icon($$renderer, { name: 'networking', size: 'sm' });

		$$renderer.push(`<!----> IP Addresses</label> <textarea id="ips" placeholder="192.168.1.10
192.168.1.11
2001:db8::1
2001:db8::2" rows="8" class="svelte-vodz6u">`);

		const $$body_1 = $.escape(ipInput);

		if ($$body_1) {
			$$renderer.push(`${$$body_1}`);
		} else {}

		$$renderer.push(`</textarea></div> <div class="controls-row svelte-vodz6u"><div class="input-group"><label for="ttl">`);
		Icon($$renderer, { name: 'clock', size: 'sm' });
		$$renderer.push(`<!----> TTL (seconds)</label> <input type="number" id="ttl"${$.attr('value', ttl)} min="60" max="86400"/></div> <label class="checkbox-option svelte-vodz6u"><input type="checkbox"${$.attr('checked', generateZoneFile, true)} class="svelte-vodz6u"/> <span class="checkmark svelte-vodz6u"></span> Generate zone file</label></div> `);

		if (generateZoneFile) {
			$$renderer.push(`<!--[0--><div class="input-group"><label for="zoneName">`);
			Icon($$renderer, { name: 'globe', size: 'sm' });
			$$renderer.push(`<!----> Zone Name</label> <input type="text" id="zoneName"${$.attr('value', zoneName)} placeholder="example.com"/></div>`);
		} else {
			$$renderer.push('<!--[-1-->');
		}

		$$renderer.push(`<!--]--></div> <div class="examples-section svelte-vodz6u"><details class="examples-toggle svelte-vodz6u"${$.attr('open', showExamples, true)}><summary class="svelte-vodz6u">`);
		Icon($$renderer, { name: 'lightbulb', size: 'sm' });
		$$renderer.push(`<!----> Quick Examples</summary> <div class="examples-grid svelte-vodz6u"><!--[-->`);

		const each_array = $.ensure_array_like(examples);

		for (let $$index = 0, $$length = each_array.length; $$index < $$length; $$index++) {
			let example = each_array[$$index];

			$$renderer.push(`<button class="example-card svelte-vodz6u"><h4 class="svelte-vodz6u">${$.escape(example.label)}</h4> <p class="svelte-vodz6u">${$.escape(example.hostnames.split('\n').length)} hosts</p></button>`);
		}

		$$renderer.push(`<!--]--></div></details></div></div> `);

		if (results.length > 0) {
			$$renderer.push(`<!--[0--><div class="results-section svelte-vodz6u"><div class="results-header svelte-vodz6u"><h2 class="svelte-vodz6u">Generated Records</h2> <div class="export-buttons svelte-vodz6u"><button class="svelte-vodz6u">`);
			Icon($$renderer, { name: 'copy', size: 'sm' });
			$$renderer.push(`<!----> Copy Records</button> `);

			if (generateZoneFile && zoneFileContent) {
				$$renderer.push(`<!--[0--><button class="svelte-vodz6u">`);
				Icon($$renderer, { name: 'download', size: 'sm' });
				$$renderer.push(`<!----> Download Zone</button>`);
			} else {
				$$renderer.push('<!--[-1-->');
			}

			$$renderer.push(`<!--]--></div></div> <div class="records-table svelte-vodz6u"><div class="table-header svelte-vodz6u"><div class="svelte-vodz6u">Name</div> <div class="svelte-vodz6u">TTL</div> <div class="svelte-vodz6u">Type</div> <div class="svelte-vodz6u">Value</div></div> <!--[-->`);

			const each_array_1 = $.ensure_array_like(results);

			for (let index = 0, $$length = each_array_1.length; index < $$length; index++) {
				let record = each_array_1[index];

				$$renderer.push(`<div${$.attr_class('table-row svelte-vodz6u', void 0, { 'invalid': record.type === 'INVALID' })}><div class="name svelte-vodz6u">${$.escape(record.name)}</div> <div class="ttl svelte-vodz6u">${$.escape(record.ttl)}</div> <div class="type svelte-vodz6u"><span${$.attr_class('record-type svelte-vodz6u', void 0, {
					'a': record.type === 'A',
					'aaaa': record.type === 'AAAA',
					'error': record.type === 'INVALID'
				})}>${$.escape(record.type)}</span></div> <div class="value svelte-vodz6u">${$.escape(record.value)}</div></div>`);
			}

			$$renderer.push(`<!--]--></div> `);

			if (generateZoneFile && zoneFileContent) {
				$$renderer.push(`<!--[0--><div class="zone-file-section svelte-vodz6u"><div class="zone-file-header svelte-vodz6u"><h3 class="svelte-vodz6u">Zone File Preview</h3> <button class="svelte-vodz6u">`);
				Icon($$renderer, { name: 'copy', size: 'sm' });
				$$renderer.push(`<!----> Copy Zone File</button></div> <pre class="zone-file-content svelte-vodz6u">${$.escape(zoneFileContent)}</pre></div>`);
			} else {
				$$renderer.push('<!--[-1-->');
			}

			$$renderer.push(`<!--]--></div>`);
		} else {
			$$renderer.push('<!--[-1-->');
		}

		$$renderer.push(`<!--]--></div>`);
	});
}